raysan5/raylib

src/core.c
src/raylib.h

Hide and show mouse cursor at runtime :) With this PR and [this one](https://github.com/raysan5/raylib/pull/21) it's possible to create real first person camera!

Functions to show and hide mouse cursor at runtime

---

src/raylib.h

GLFW mappings. Sorry about the last goof up. I Didn't look in your branches when I posted it originally.

Added Alpha Numeric Mapping For Develop Branch

---

src/camera.c

It needs to be confirmed if commented lines doesn't affect camera behaviour... I think that it doesn't...

Fixed small glitch on zoom-in

---

src/makefile

`raymath.c` is no longer there, but `glad.c` was recently added :)

Fix raylib compiling on Linux

---

src/Makefile
templates/advance_game/Makefile
templates/basic_game/Makefile
templates/basic_test/Makefile
templates/simple_game/Makefile
templates/standard_game/Makefile

I've added .PHONY targets and fixed "clean" recipe.

Fix Makefile files

---

src/audio.c
src/jar_xm.h

This is an early draft, needs lots of work. Still need to figure out way
to calculate total length of song. This is hard because xm tracks stream
out zeros when done, only position in track can be found. Position does
not give any direct value of how much more time is left. I think that by
setting the loop count to 1 and seeking until the end I can total up the
number of samples and come up with a length.

Added proto version of jar_xm

---

src/audio.c
src/audio.h
src/raylib.h

Look over changes and give feedback please.

First stage of audio API update

---

src/audio.c
src/audio.h
src/raylib.h

It's a basic rework of the Music module to be more user-friendly like in the [issue #144 ](https://github.com/raysan5/raylib/issues/144)

Code refractoring of music module to be more user-friendly (issue #144)

---

games/drturtle/makefile
games/just_do/makefile
games/raylib_demo/makefile
games/skully_escape/makefile

Also fix the conditional for Linux on the makefiles. On Ubuntu I have to uncomment the line bellow.
(hopefully right this time 😕)

[games] Fix building the games on Linux by adding missing libs

---

src/core.c

Added GestureEvent processing to TouchThread for PLATFORM_RPI

	modified:   core.c

---

games/drturtle/04_drturtle_gui.c
games/drturtle/05_drturtle_audio.c
games/drturtle/06_drturtle_final.c
games/drturtle/drturtle_final_web.c
games/drturtle/makefile
games/just_do/makefile
games/light_my_ritual/makefile
games/light_my_ritual/screens/screen_gameplay.c
games/light_my_ritual/screens/screen_title.c
games/raylib_demo/makefile
games/raylib_demo/raylib_demo.c
games/skully_escape/makefile
games/skully_escape/screens/screen_aisle01.c
games/skully_escape/screens/screen_aisle02.c
games/skully_escape/screens/screen_armory.c
games/skully_escape/screens/screen_attic.c
games/skully_escape/screens/screen_bathroom.c
games/skully_escape/screens/screen_ending.c
games/skully_escape/screens/screen_kitchen.c
games/skully_escape/screens/screen_livingroom.c
src/audio.c

Maybe these are exercises for your students?

Fixed some games. Replaced font.size with font.baseSize. Uncommented linux libs.

---

examples/Makefile
src/Makefile

I think this is good. The comments should explain the usage well enough.

Added _DEFAULT_SOURCE to CFLAGS for C99 compatibility

---

src/meson.build

Closes https://github.com/raysan5/raylib/issues/293

Add library versioning

---

examples/textures/textures_image_generation.c
src/raylib.h
src/textures.c

Namely:
- `GenImageHorizontalV`
- `GenImageHorizontalH`
- `GenImageChecked`
- `GenImageWhiteNoise`
- `GenImageCellular`
The gradient implementation may be a bit naive, for example it doesn't do any gamma correction.
I'll look into implementing `ImageGenSpot` and `ImageGenPerlin` but I don't know if I'll succeed.
Also I think I could implement an `ImageSaveAs` function so that the users can save their procedurally generated images (looking at the `TakeScreenshot` implementation this shouldn't be too hard)

Add some image generation functions

---

docs/cheatsheet/raylib_models.c
examples/others/standard_lighting.c
src/raymath.h
src/textures.c

Not much to say here, just some typos :smile:

Fix some typos (lenght -> length)

---

examples/Makefile

We need to grab the OS name before determining what the path should be.

Update Makefile in `examples/`

---

src/raymath.h

Hi Ray! Noticed a small typo while reading the code :)

Fix typo in raymath.h

---

.gitignore
CMakeLists.txt
examples/CMakeLists.txt
examples/Makefile
games/CMakeLists.txt
games/drturtle/CMakeLists.txt
games/just_do/CMakeLists.txt
games/koala_seasons/CMakeLists.txt
games/light_my_ritual/CMakeLists.txt
games/skully_escape/CMakeLists.txt
games/wave_collector/CMakeLists.txt
src/CMakeLists.txt
src/Makefile
utils.cmake

Some people might find this handy.
Not all OSes and platforms are ready, but a good chunk of it is good to go.

CMake based build system.

---

meson.build
src/meson.build

Increment raylib version and so lib version number.
Actually since this is develop branch I guess incrementing already (so we dont forget) cannot hurt.

Increment version in meson build file

---

examples/Makefile

Hello , i added clean for FreeBSD to example Makefile

Added  clean to Makefile for FreeBSD

---

project/vs2015.UWP/raylib.App.UWP/App.cpp

Add a basic UWP gamepad poll function with zero changes to code outside of App.cpp

Add UWP gamepad input polling

---

examples/CMakeLists.txt

small bugfix for cmakefile in examples-folder

fixed cmakefile

---

src/external/mini_al.h
utils.cmake

Fixes this build failure:
http://www.cpantesters.org/cpan/report/a069fade-0e1f-11e8-a1cf-bb670eaac09d

mini_al: Support {Net,Open}BSD OSS

---

project/Builder/README.md
project/Builder/examples/README.md
project/Builder/examples/meson.build
project/Builder/meson.build

Takes care of Builder for https://github.com/raysan5/raylib/issues/466

Add Builder project files

---

src/raylib.h

My assumption is that these are the same as the GLFW definitions so that's what I mirrored.

Add more key definitions

---

src/shapes.c

This is a bug waiting to happen, so let's fix it before it does. :)

Patch implicit type

---

src/CMakeLists.txt
src/Makefile

Please do this whenever necessary. And adapt it before releasing a new
RC. The RC should already have the correct one.

Increase API version

---

README.md
cmake/utils.cmake
examples/Makefile
games/Makefile
games/drturtle/Makefile
games/just_do/Makefile
games/koala_seasons/Makefile
games/light_my_ritual/Makefile
games/skully_escape/Makefile
games/transmission/Makefile
games/wave_collector/Makefile
release/include/raylib.h
src/Makefile
src/core.c
src/raylib.h
src/rglfw.c
templates/advance_game/Makefile
templates/simple_game/Makefile
templates/standard_game/Makefile

Hello i bring support OpenBSD, NetBSD, DragonFly operating systems.
M.

Added support OpenBSD, NetBSD, DragonFly OS

---

src/external/mini_al.h

This fixes a bug with the Core Audio backend that is sometimes preventing audio from being played.

Update mini_al with a fix for macOS.

---

README.md

Simply removes the period after exclamation mark per [this comment on Reddit 💬](https://www.reddit.com/r/gamedev/comments/90z6fy/raylib_20_released/e2v5qpl/)  
😄

Remove period after exclamation

---

src/audio.c

It would be good to have a way to continue execution even when loading a stream didn't work.
Free music and set it to NULL in case something went wrong, so that users can check for it.

 Deal with failed LoadMusicStream

---

src/audio.c

Fix bug in LoadMusicStream

---

src/external/mini_al.h

I just thought I would do a quick update to mini_al because I've just fixed a bad bug in the ALSA backend which should significantly improve things on Raspberry Pi. This should resolve the random crackling issues and significantly improve latency.
It does not fix that glitch at the start of streaming - that's happening because the time it takes to render the first frame is longer than the time it takes to play the audio buffer which results in a situation where the audio buffer is unable to get fed with data quickly enough.
This should also fix the audio_raw_stream example.
You should probably also give this a quick test on the other backends before merging.

Update mini_al to 0.8.5.

---

src/shapes.c

By comparing the edges of the rectangles relative to each other we can
determine if they intersect or not.

Shapes: Simplifies CheckCollisionRecs

---

src/raylib.h

For #627. :smile:
Actually... thinking about it more, should this be updated to include all of the keypad keys as well?

Add the plus and minus keys on both the main keyboard and keypad

---

src/raylib.h

Add the remaining numeric keypad keys, and a few other missing ones

---

src/core.c

core: Support slashes as well in GetFileName & GetDirectoryPath

---

src/raymath.h

- Added Vector2MultiplyV
- Added Vector2DivideV
- Added Vector3Divide
- Added Vector3DivideV

Added a few missing functions to raymath

---

games/just_do/screens/screen_level06.c
games/koala_seasons/screens/screen_gameplay.c
games/transmission/screens/screen_ending.c

* changed bitwise & to logical &&
* removed redundant state check
* moved a strcpy inside a NULL check to prevent a crash.
NOTE: nothing sensible will happen as a result, but no crash at least.

3 minor sample game cleanups:

---

src/core.c

Please read individual commit messages for each commit for explanation of why.

Improve OpenURL()

---

src/core.c

See https://github.com/raysan5/raylib/issues/686

Add warning to OpenURL()

---

examples/CMakeLists.txt
examples/Makefile
examples/shaders/resources/shaders/glsl100/palette-switch.fs
examples/shaders/resources/shaders/glsl120/palette-switch.fs
examples/shaders/resources/shaders/glsl330/palette-switch.fs
examples/shaders/shaders_palette_switch.c
projects/Notepad++/raylib_npp_parser/raylib_to_parse.h
src/raylib.h
src/rlgl.h

Hi @raysan5!
Here's the pull request for the simple change we've been discussing yesterday.
Let me know it suits you well!
Bye,
Marco

Shaders uniforms array

---

src/raudio.c
src/raylib.h
src/rlgl.h
src/utils.c

Hello Raysan!
Here's my proposal for the logging facility "rework", in order to be more similar to the standard ones.
I also added an API to enable/disable the "exit-on-error" feature.
Hope this suits you fine!
Marco

Reorganizing logging

---

src/text.c

- There is about 3-6KB to find somewhere else, unsure where. However this should fix the bulk of it.
- Tabs to spaces

 #764 - Quick fix that clears alot of memory.

---

src/text.c

Removed unnecessary if

---

src/models.c
src/raylib.h

Adding DrawCubeWiresV for convenience as the library has DrawCubeV.

Adding DrawCubeWiresV for convenience

---

src/core.c

Based on pull request from user "DarkElvenAngel", better integrated with the current event system and enhanced with buffer to help with fast typing at low framerates.

RaspberryPi Keyboard input with evdev

---

src/raylib.h
src/shapes.c

Proposed implementation for issue #738 ... it's mostly just code modified from `DrawCircleSector()` unfortunately sometimes (very very rarely) i still get the glitches mentioned in #783 .Don't think it's because of my code but i might be wrong.
Here's the code for the application shown in the screenshot
```c
#define RAYGUI_IMPLEMENTATION
#include <raygui.h>
float innerRadius = 80.0f, outerRadius = 190.0f;
int startAngle = 0, endAngle = 360, segments = 0;
bool drawRingLines = false, drawRing = true, drawCircleLines = false;
Vector2 center = {0};
Color color={0}, lineColor={0};
void DrawGui()
{
startAngle = GuiSliderBar((Rectangle){645,40,105,20}, "StartAngle", startAngle, -450, 450, true );
endAngle = GuiSliderBar((Rectangle){645,70,105,20}, …
```

Added DrawRing(), DrawRingLines() and DrawCircleSectorLines()

---

src/raylib.h
src/shapes.c

Hey @raysan5 , made this today since i need it for a project, ~~will add a `Lines` version later~~ (added). BTW i didn't know how to handle the texture coordinates so i didn't add any, is that bad?
As always here's the code for quick testing!
```c
#define RAYGUI_IMPLEMENTATION
#include <raygui.h>
float roundness = 0.2f;
int width = 200, height = 100, segments = 0, lineThick = 1;
bool drawRoundedRect = true, drawRoundedLines = false, drawRect = false;
const int SCREEN_WIDTH = 800, SCREEN_HEIGHT = 450;
void DrawGui()
{
width = GuiSliderBar((Rectangle){645,40,105,20}, "Width", width, 0, SCREEN_WIDTH-250, true );
height = GuiSliderBar((Rectangle){645,70,105,20}, "Height", height, 0, SCREEN_HEIGHT-50, true);
roundness = …
```

Added `DrawRoundedRect()` and `DrawRoundedRectLines()`

---

src/Makefile

[build] fixed GLFW compiler flag for OSX

---

src/external/jar_xm.h
src/raudio.c

Disclaimer: I don't know the XM format (at all) and I don't know jar_xm.h at all
But hey, this seems to work on all the files I have tested on.
Fixes #843

Add rewind for the XM music format

---

CONTRIBUTING.md

For changing easings.h to work without the inclusion of raylib.h

Added Narice to the CONTRIBUTING.md

---

projects/scripts/build-linux.sh
projects/scripts/build-rpi.sh
projects/scripts/build-windows.bat

Multiple small fixes I've written since first sending these scripts, as well as a Raspberry Pi one, thanks to Discord user gururamen for the flags for that one :) I tested the scripts on Linux, Windows, macOS and a RPI 3B+.

Fix and update projects/scripts

---

examples/Makefile
examples/audio/audio_multichannel_sound.c
src/Makefile
src/raudio.c
src/raudio.h
src/raylib.h

as it says on the tin, please see the example for usage...

add multi channel audio to raudio

---

examples/Makefile
examples/core/core_scissor_test.c
examples/textures/textures_mouse_painting.c

- Example gif for core_scissor_test.c
- Example gif for textures_mouse_painting.c

Added scissor test and mouse painting examples proposed in #890

---

src/rmem.h

Object Pool Changes:
-- changed 'size' member name of 'union ObjInfo' to 'index' to better name its purpose.
Memory Pool Changes:
-- Added memory node buckets to store and allocate smaller, more frequent byte sizes.
-- Replaced 'memset' call to deinitialize free list data with NULL and 0 assignments.
-- Removed some no-longer-needed commented-out code.
-- Changed insertion sort code to put the largest size at the tail rather than the head.
-- Made certain pointer variables as constant pointers.

End of July rmem Update

---

src/raylib.h
src/textures.c

Fix build failure introduced in 2a913b6587d60dab64c3b81019990e6872a9ac75

Fix build caused by GetImageAlphaBorder()

---

src/rmem.h

Replaced '__RemoveNode' as it was causing invalid memory accesses with regular doubly linked list deletion algorithm.
Replaced double pointer iterator in 'MemPoolAlloc' with single pointer iterator.
Fixed undefined variables errors in 'MemPoolFree' for the freelist bucket.

Removing '__RemoveNode'

---

src/raudio.h

It appears that you've missed renaming this function here, which makes trying to compile standalone raudio.c error out.

IsAudioBufferProcessed -> IsAudioStreamProcessed

---

examples/core/core_2d_camera_ext.c
src/core.c
src/raylib.h

Referring to comment here: https://github.com/raysan5/raylib/pull/945#issuecomment-521766590
I went ahead and made an example of handful of camera logic approaches. To do this though, I also needed world to screen and screen to world functions, which I implemented as well. Names are placeholderish, as I didn't try to guess what you'd want them to be named as.

World to screen and screen to world transformations for Camera2D; extended Camera2D example

---

src/raylib.h
src/rlgl.h

Const corectness for LoadShaderCode

---

examples/Makefile

sorry only just noticed this... (fixes some of the examples not building....)

corrected examples Makefile target

---

src/models.c

mem leak in gltf loader

---

src/core.c
src/raylib.h

Hi, I created the following APIs about https://github.com/raysan5/raylib/issues/535
```
RLAPI bool HasWaitingInputCharacter();                        // Check if input character exists at least one in the internal input character stream. The characters are produced by the operating system text input system.
RLAPI unsigned int PullNextInputCharacter();                  // Pull a input character from the the internal input character stream
```
It can handle multiple characters per frame. 
This is the example which modified from "raylib [text] example - Input Box"
```
/*******************************************************************************************
*
*   raylib [text] example - Input Box
*
*   This example has been created using raylib 1.7 (www.raylib.com)
*   raylib is licensed …
```

add api FIFO based character input.

---

CONTRIBUTING.md
SPONSORS.md

Miscellaneous fixes for typos and similar issues in text-only files.

Typo fixes

---

src/models.c

* Normal vbo not correctly updated

Normals was not correctly updated when using animated meshes

---

templates/simple_game/Makefile.Android.macos
templates/simple_game/Makefile.macos.android

This makefile can work on macos to build android app:)
maybe i'll try to update the wiki page for android building on macos latter

Create makefile for building android app on osx

---

src/raylib.h
src/textures.c

Added draw functions:
ImageClearBackground()
ImageDrawPixel()
ImageDrawLineEx()
ImageDrawCircle()

Added draw functions to ImageDraw*() #1028

---

examples/shaders/resources/shaders/glsl120/base_lighting.vs
examples/shaders/resources/shaders/glsl120/fog.fs

ended up using the 100 version shaders as off the top of my 
head can't think of any improvement I could use on the shaders for
version 120
This has been tested on Linux (Desktop) requires testing on a Rpi

fog/lighting shaders (for Rpi)

---

examples/shaders/resources/shaders/glsl100/spotlight.fs
examples/shaders/resources/shaders/glsl330/spotlight.fs
examples/shaders/shaders_spotlight.c

NB glsl100 shader needs testing on "bare metal"

spotlight example, each spot has own radius, mouse countrol

---

projects/VSCode_tcc_win/.vscode/c_cpp_properties.json
projects/VSCode_tcc_win/.vscode/settings.json
projects/VSCode_tcc_win/.vscode/tasks.json
projects/VSCode_tcc_win/main.c
projects/VSCode_tcc_win/main.code-workspace

cloned VSCode into another folder.
added TCC specific parameters to tasks.json
remove CMAKE specific parameter.
remove non windows specific configuration.

tcc-based vscode project for windows

---

projects/4coder/Makefile
templates/advance_game/Makefile
templates/simple_game/Makefile
templates/standard_game/Makefile

Currently mingw32-make is set but it should be regular make

Set the correct version of make on macos

---

src/rmem.h

Optimizations of allocators.
Renamed 'Stack' to 'Arena'.
Replaced certain define constants with an anonymous enum.
Refactored MemPool to no longer require active or deferred defragging.

Mempool and other Allocators Optimization

---

src/raymath.h

Move position to target with lerp.

Add Vector2MoveTowards function

---

templates/advance_game/screens/screen_logo.c

"Advance Game" will not compile with those four lines of code.

No need for "LOGO_RECS_SIDE" maybe an artifact?

---

src/CMakeLists.txt

Tested on a Raspberry Pi 3B+, sucessfully used together with node-raylib

Update CMakeLists.txt to fix CMake build for Raspberry Pi

---

src/raymath.h

I would like to add this two functions.
It's simple, but having a length function that doesn't use sqrt() (for comparative purposes) would be nice when you need to calculate lots of distances each frame.

Introduced Vector2 and Vector3 Square Lenght.

---

src/raymath.h

// Normalize input value within input range
// Remap input value within input range to output range

Adding Normalize and Remap functions

---

src/raylib.h
src/rlgl.h

I needed this blend mode for rendering a framebuffer containing text on transparent background to screen, otherwise it looks fuzzy and wrong.

added BLEND_SET

---

examples/models/models_skybox.c
examples/models/resources/shaders/glsl100/skybox.fs
examples/models/resources/shaders/glsl330/skybox.fs

Hi @raysan5 , 
Actually I added a parameter to the shaders in order to flip the cubemap, due to the fact that I don't know if this bug affects other OS (linux, osx, android etc.)

Fix bug #1270

---

projects/VS2017.UWP/raylib.App.UWP/App.cpp

[UWP] Fix time query precision

---

examples/others/rlgl_standalone.c

Fix format-security error in rlgl_standalone.c

---

src/raudio.c

Aside from all the possible upstream fixes, I think this is a good compromise for now.
https://github.com/raysan5/raylib/issues/1299

Chromium needs a larger audio buffer

---

src/external/miniaudio.h

emscripten compile is currently broken in master https://github.com/dr-soft/miniaudio/commit/cbe8e0b0fc39ac47c295d09faa105418849739d3

Updated miniaudio to v0.10.13, fixes emscripten compilation error

---

raylib.pc.in
src/CMakeLists.txt

Addresses some of the issues in https://github.com/raysan5/raylib/issues/1337

CMake MinGW fixes

---

projects/scripts/build-windows.bat

I got tired of waiting for the build script to do its job so i spent i little time figuring out why it was so slow. 
Turns out it the culprit was the vcvarsall.bat script that was getting called every time. 
So i modified it to only call it if it wasn't called before, so the script is only slow the first time it is called, which isn't the ideal scenario, but it is certainly better than it was before.

Making the windows script faster

---

projects/VSCode/Makefile

It seems to be the only place where the version was not updated.

Change raylib version for VSCode mingw project makefile

---

BINDINGS.md

Please add information about Never language binding in project documentation.

Added Never language to the list of bindings.

---

BINDINGS.md

- raylib-cpp
- raylib-lua-sol
- node-raylib
- raylib-js
- raylib-chaiscript
- raylib-squirrel

Add versions for various bindings

---

BINDINGS.md

Just added a link to my Gambit Scheme binding to `BINDINGS.md`.

Added Gambit Scheme to bindings

---

BINDINGS.md

Added Gforth bindings and updated the link to the Factor bindings.  I did the Factor ones too, but changed my name on Github recently.  Now it points to the correct link.

Add Gforth bindings and update Factor bindings

---

examples/Makefile
examples/shaders/resources/shaders/glsl330/base_lighting_instanced.vs
examples/shaders/shaders_rlgl_mesh_instanced.c
src/raylib.h
src/raymath.h
src/rlgl.h

Putting this here for feedback and discussion related to #1127.
`rlDrawMeshInstanced` is a low level approach to instanced mesh rendering. It loads a batch of transform matrices into a VBO, and requires a modified vertex shader using `LOC_MATRIX_MODEL` as an attribute location (not a uniform).
Todo:
- ~~Add a full code example to go with `base_lighting_instanced.vs`.~~
- Figure out if `rlDrawMeshInstanced` fits with the higher level API proposed in #1127. Might not.

[wip] rlDrawMeshInstanced

---

src/external/tinyobj_loader_c.h
src/models.c

... also fixed obj_loader hash map issues
this fixes issue #1406 and #1374 
I don't mind saying that the hash map issues were quite "interesting" (read difficult!)
I'm really happy that it now loads materials into separate sub meshes, as this opens up a whole extra world of resources (think kenney.nl) and is ideal for low poly designs :grinning:

allow for multiple materials in obj files

---

src/core.c

fixed https://github.com/raysan5/raylib/issues/1392

fixed mouse movements are bound to the screen resolution #1392

---

BINDINGS.md

Here we go!
We done it in 3 days...Thanks god and thanks raysan! ❤️

Added Boo bindings for raylib!

---

src/raylib.h

I'm not sure if any description is needed here. :p

A couple of little comment fixes

---

examples/Makefile
src/core.c

fixed https://github.com/raysan5/raylib/issues/1392 for cmake build system

Fixed keyboard stuttering but for cmake only

---

src/raymath.h

Optimized MatrixLookAt as per https://github.com/raysan5/raylib/issues/1439
Tested the changes against core_3d examples to check for any behavior differences.

Optimized MatrixLookAt

---

src/rlgl.h

This PR exposes options to get/set the open GL width and aliasing options for line drawing.

Add options to set line width and aliasing to rlGL layer.

---

examples/text/text_input_box.c

Fixed writing out of array bounds
Adjusted FPS comment to match value
Deleted unused function at the end, which has never been in use in the history of this file
For Issue: https://github.com/raysan5/raylib/issues/1455

Fixed #1455

---

examples/shapes/shapes_draw_circle_sector.c
examples/shapes/shapes_draw_ring.c

Fixed a couple of examples as they weren't compiling. Happy Christmas!

Fix use of GuiSliderBar in examples.

---

BINDINGS.md

To know why i corrected raylib-mruby version take look at previous pull request i did now...

Corrected raylib-mruby version + Updated raylua bindings!

---

examples/core/core_window_letterbox.c

Providing a comment to the original example, with the code to make the real mouse take the screen scale of the letterbox into consideration.

providing an example on how to apply the screen scale to the real mouse

---

src/core.c
src/raylib.h

Resolves #1484
I added this function regarding this issue - We have a bunch of functinos that are for querying monitor information and changing monitors but there is no way currently to know which is the current used monitor. @raysan5

Monitor utilites

---

README.md

Hi, raylib is great. I recently added it to the conan dependency manager and thought it might be nice to add a description in the readme after seeing vcpkg on there.

Add info to readme for conan dependency manager

---

.gitignore
src/CMakeLists.txt

Fix cmake build error dirent

---

.github/workflows/cmake.yml

Will expand on the file but it will be nice to know if they are some extremely breaking changes in the future. cmake.yml will run two task one for linux build and one for windows build essentially checking that both are working. We can add all platforms later.

Added a windows and linux simple compile with cmake

---

examples/models/models_gltf_animation.c
src/models.c

This is to account for GLTF info being more like instructions on how to build your animation instead of verbose description of each pose.
Fixes #1553 
PS: Also added a few comments to explain the animation loading.

Update loading of gltf animation.

---

src/rlgl.h

Sorry if this is a bit of a useless pr

Fix spelling mistake

---

src/physac.h
src/raymath.h

Now that all the samples are included in the visual studio projects, more parts of raylib are generating typecast warnings during a build.
This PR resolves the issues in physics and raymath that were found building the physics sample.

[Physics] Fix typecast warnings generated by visual studio 2019

---

examples/textures/textures_mouse_painting.c

after checking the mouse_right_button down there was an else which prevented any changes to selectedColor that was caused by arrow keys ... 
after some up and running I could fix the problem of arrow keys ...

fixed the right and left button not working

---

src/models.c

This PR fixes new typecast warnings found in the new model loading code.

[Models} Fix typecast warnings generated by Visual Studio 2019 

---

src/shapes.c

Corrected the issue https://github.com/raysan5/raylib/issues/1596

Fixed DrawLineEx

---

examples/audio/audio_module_playing.c
examples/audio/audio_multichannel_sound.c
examples/audio/audio_raw_stream.c
examples/core/core_2d_camera.c
examples/core/core_2d_camera_platformer.c
examples/core/core_3d_camera_first_person.c
examples/core/core_3d_picking.c
examples/others/easings.h
examples/others/raudio_standalone.c
examples/others/rlgl_standalone.c
examples/textures/textures_image_drawing.c
examples/textures/textures_rectangle.c
examples/textures/textures_srcrec_dstrec.c
src/raymath.h
src/rlgl.h

This PR fixes many of the typecast warnings generated by visual studio 2019 in examples.

[Examples] Fix typecast warnings in examples.

---

BINDINGS.md

hey!
Ive made a Raylib Binding for my Programming language ReCT! Its still a fairly small language (~30 users) but it would be really cool to be featured here, tho I'd completely understand if only relevant languages are allowed on the list

Added ReCT Binding (Relib) to the list

---

src/raudio.c

stb_vorbis.h also has an API for loading from memory.

LoadMusicStreamFromMemory OGG support

---

src/models.c

This PR fixes typecast warnings added with new model loading code.

[Models] Fix typecast warnings

---

examples/shaders/shaders_rlgl_mesh_instanced.c

Added a simple jump animation to the instanced mesh.
Added keyboard controls to modify all parts of the animation (speed, height, etc.)
Added text to describe controls.

Added animation and keyboard controls to rlgl mesh Instancing example

---

src/shapes.c

[shapes] CheckCollisionPointTriangle (fix), CheckCollisionPointLine (new routine)  

---

src/external/jar_xm.h

Hello RayLib, this is a long in the tooth refresh to the XM module player.
It fixes the majority of all of it's issues,
Some of the changes done were based on original specifications as well as observations made from the ModPlug Library.
It is in no means perfect, but a long overdue refresh to the capability.

Update to the xm player routine and support functionalities

---

src/raudio.c

This PR makes XM streams use audio streams in the native device format, and generate the appropriate sample data when possible. This should reduce CPU usage during streaming.

[AUDIO] XM streams use native sample sizes

---

examples/Makefile.Android

Fix of old directories that aren't in the raylib repository more ando some windows/linux portability problems.

Fix old directories used and windows/linux portability

---

src/models.c

When using the [iqm](https://github.com/lsalzman/iqm) exporter for Blender, I noticed animations were not using bone weights. 
This adds bone weight support to `UpdateModelAnimation()`.

Use bone weights for animation

---

BINDINGS.md

Bump version supported version by raylib-ocaml.

Update BINDINGS.md (version change for raylib-ocaml)

---

templates/simple_game/Makefile.Android.linux

modified  templates/simple_game/Makefile.Android.linux
switched out @echo for @printf to make it actually print newlines instead of literal \n's

Fix for newlines in Makefile

---

examples/shapes/shapes_basic_shapes.c
src/raylib.h
src/shapes.c

* Changed `DrawRectangleLinesEx` and `DrawRectangleRoundedLines` to use float for line thickness
* Added `DrawPolyLinesEx` function that allows user to specify line thickness

Add RenderPolyLinesEx routine

---

BINDINGS.md

Those bindings got updated recently.

Update raylib-lua and raylib-wren binding versions

---

BINDINGS.md

Update raylib-go bindings

---

src/raymath.h

Fixes #1765 
@raysan5 The signs were the other way around. Also, I noticed a small inconsistency if the multiplication is done before the addition/substraction.

Fix QuaternionToMatrix returning transposed result.

---

parser/README.md
parser/raylib_parser.c

This adds the option to output the parser data in JSON format by passing a `--json` option like....
```
raylib_paser --json
```
Results in [`raylib_parser.json`](https://gist.github.com/RobLoach/206bb0bda8a1633ed5fadebe12e3fdee)

parser: Add JSON support with --json

---

projects/scripts/README.md

Changed the Readme file for the build scripts.

Changed windows-build to build-windows in Readme.md (scripts)

---

parser/raylib_parser.c

Add nullptr check before passing arg

---

src/core.c
src/raylib.h

Thanks raysan for letting me know about `Mouse.previousPosition`.
This pull request adds `GetDeltaMouse()`. It is a simple function that returns the movement of the mouse for each frame.
It can be useful for interfaces, cameras, etc.

core: added `GetMouseDelta()`

---

BINDINGS.md

Added new Haxe raylib (under progress) binding to BINDINGS.md

Added hxRaylib

---

src/text.c

When :
```
Vector2 vec = MeasureTextEx(...);
Rectangle rec = {..., .width: vec.x);
DrawTextRec(...,rect,...);
```
The last letter of the text was not displayed before this fix.

Fix DrawTextRec

---

examples/textures/textures_image_loading.c

Use 60 FPS for textures_image_loading example

---

src/models.c

Fixed vertex normals not being loaded and replace by vertex positions.

Fixed normals

---

src/models.c

Fix for issue: https://github.com/raysan5/raylib/issues/1876

GenMeshTangents Fix

---

src/core.c

Legacy keyboard support was blocking the render loop, also it was keeping the last key status until the next key.

Raspberry RPI/DRM keyboard fix

---

src/textures.c

Fixes #1873
The existing code was correct for one octant, it now works for all 8
Added two internal functions, _ImageDrawLineHorizontal and _ImageDrawLineVertical, without which it would've been 4 times as much code.

Fixes #1873 Implemented remaining 7/8 of ImageDrawLine

---

src/extras/rmem.h

[rMem] Fix seg fault after a free operation

---

.gitignore

We need to revert this as its ignoring changes to Makefiles.

Revert "Ignore generated example binaries (#1884)"

---

BINDINGS.md

Not sure if worth adding..
People sometimes ask if there is a Kotlin/native binding so I tried to create one.  Turns out that Kotlin/native binds to C libraries on its own automatically, so I didn't really have to do anything, but this is an example of how to set everything up.  Maybe people looking for Kotlin/native bindings will want to copy this.

Kotlin binding (sort of)

---

src/Makefile

'# TODO: see 'install' target.' (line 655) should be a note rather than something
to do.

Modify TODO to NOTE on Makefile

---

BINDINGS.md

You can change the name to whatever you want to because the binding doesn't have a name.

added another odin binding

---

BINDINGS.md

Binding version update for https://github.com/irishgreencitrus/raylib.v

Updated the raylib.v binding to the latest version

---

src/rcore.c

MAX_DIRECTORY_FILES macro removed.
ClearDirectoryFiles() tweaked to reflect changes.

Fixed file/alloc limitation in GetDirectoryFiles()

---

parser/raylib_parser.c

Found and verified fixed with Valgrind.

Fix memory leak in parser

---

src/Makefile
src/rtextures.c

forgotten CC overriding when compiling for x86, x86_64
[relative issue](https://github.com/raysan5/raylib/issues/2145)

Fixes CC while compiling for ANDROID_ARCH x86

---

BINDINGS.md

Added [dart-raylib](https://pub.dev/packages/raylib) to BINDINGS.md

Added dart-raylib to BINDINGS.md

---

examples/text/resources/LICENSE.md

Fix typo in link for text example resources.

Update text-examples resource LICENSE.md

---

BINDINGS.md

raylib-cslo switches to MPL-2.0

---

src/raymath.h

Following the pattern in Vector3Normalize.

Fix inverse length in Vector2Normalize

---

src/Makefile

Fix RPi make install

---

parser/raylib_api.json
parser/raylib_api.lua
parser/raylib_api.txt
parser/raylib_api.xml
parser/raylib_parser.c

This PR updates the API parser to also include struct descriptions. The bulk of the work is rewriting part of the struct parser to read from lines instead of the buffer directly.

Parse struct descriptions

---

src/Makefile

Fix build results path on Linux and RPi

---

BINDINGS.md

Sorry about this, there was a small typo in the URL for the language in the original PR.

fix scopes binding URL

---

projects/VSCode/.vscode/c_cpp_properties.json

Specify root as the starting point for the linux compiler path

Added: missing /

---

src/extras/physac.h

Fix typo in comment: s/simluate/simulate/

Fix typo in comment: s/simluate/simulate/

---

src/raymath.h

Just a small mistake that caught my eye.

simplify QuaternionInvert

---

BINDINGS.md

Updated Swift version from 3.7 to 4.0

Update Swift binding version

---

BINDINGS.md

This commit adds naylib https://github.com/planetis-m/naylib

Add naylib

---

parser/raylib_parser.c

Fix parsing raygui comments and vector2 enum

---

examples/shaders/shaders_mesh_instancing.c

The allocations without free's.
https://github.com/raysan5/raylib/blob/c064eefe26ce1aaf54e665997ec746fa673e237c/examples/shaders/shaders_mesh_instancing.c#L63-L66
https://github.com/raysan5/raylib/blob/c064eefe26ce1aaf54e665997ec746fa673e237c/examples/shaders/shaders_mesh_instancing.c#L85

[Examples] Free Allocated Matrices.

---

parser/raylib_api.json
parser/raylib_api.lua
parser/raylib_api.txt
parser/raylib_api.xml
parser/raylib_parser.c

The parser was previously generating invalid XML.

Fix string defines generating invalid XML

---

src/rtextures.c

Previously, for every pixels, `ImageDrawPixel()` was called which checks for image format and performs calculations on the given pixel coordinate.
https://github.com/raysan5/raylib/blob/07240b96ad7c689119e70714f3fb39852b3657b7/src/rtextures.c#L2419-L2432
The functions optimized here just copies same data over and over, so the calculation doesn't need to be performed more than once.
This optimization is already used somewhere else.
https://github.com/raysan5/raylib/blob/07240b96ad7c689119e70714f3fb39852b3657b7/src/rtextures.c#L2797
I was thinking of a general function sth like this.
`void _repeat_pixels_in_memory(unsigned char *src, int count, int bytesPerPixel)
{
for(int i = 1; i < count; i++)
{
memcpy(src + i * bytesPerPixel, src, bytesPerPixel);
}
}
`
But not many use cases, so didn't …

Optimize Image Draw Functions.

---

BINDINGS.md

Update raylib haxe binding name

---

parser/raylib_api.json
parser/raylib_api.lua
parser/raylib_api.txt
parser/raylib_api.xml
parser/raylib_parser.c

This PR reorders the parsers output and code to be similar to raylib.h, with the following order:
* Defines
* Structs
* Aliases
* Enums
* Callbacks
* Functions
It also orders everything to be internally consistent.

Reorder parser

---

BINDINGS.md

Factor's bindings have been moved into the main repo. Additionally, they have been updated to 4.0.

Update Factor Information on BINDINGS.md

---

src/extras/easings.h

Small documentation change to add descriptions to each Easings.h function. This makes it so that the easings_api.json looks a bit cleaner:
``` json
{
"name": "EaseCircIn",
"description": "Ease: Circular In",
"returnType": "float",
"params": [
```

Easings: Add function descriptions

---

examples/audio/audio_music_stream.c

The audio effects system works great !
The issue with the delay effect was simply caused by an uninitialized variable.

Fix crash with delay demo.

---

src/extras/raygui.h
src/raudio.c

This PR accompanies Issue #2476 and aims to fix a few of the found warnings.

Fix lgtm warnings

---

src/raylib.h
src/rcore.c

Pull request corresponding to issue https://github.com/raysan5/raylib/issues/2505 .

Change WaitTime argument from milliseconds to seconds

---

cmake/GlfwImport.cmake
cmake/LibraryConfigurations.cmake
examples/CMakeLists.txt

Fixes https://github.com/raysan5/raylib/issues/2546 for CMake builds at least

Fix CMake build on Raspberry Pi OS Bullseye

---

.github/workflows/macos.yml
src/Makefile

It now builds universal macos binaries.  However I am not able to test if they work!

Fix fat universal (arm64 + x86_64) macos Github Actions build

---

BINDINGS.md

Reordered the maintained bindings into alphabetical order.
Just got a bit triggered by it being in a seemingly random order.

set the maintained bindings in alphabetical order

---

src/raudio.c
src/raymath.h
src/rcore.c

This PR fixes some simple casting and sign matching warnings.

[CORE] Fix Warnings

---

src/raymath.h

Fix Vector3ClampValue and Vector2ClampValue

---

examples/models/models_yaw_pitch_roll.c
src/raymath.h

This commit fixes matrix rotation functions.

[raymath] Rotation functions returns clockwise rotation matrix, #2595

---

src/raudio.c

This PR fixes a bug when music.looping is true, then music.looping is set to false but the music continues looping.
Also using proper functions to seek to start of an audio file.
Removed old comment.

Music doesn't stop looping fix

---

BINDINGS.md

Add R package raylibr as a new binding for the R language

Update bindings with raylibr

---

CMakeLists.txt
cmake/LibraryConfigurations.cmake
examples/CMakeLists.txt

I apologize for the whitespace changes. I can remove them. Emacs automatically removes trailing WS.
See ticket.

Fix #2621: Set CMP0054 policy to NEW and appropriately quote ${PLATFORM}

---

BINDINGS.md

https://github.com/robloach/raylib-cpp

BINDINGS: raylib-cpp has support for raylib 4.2

---

src/rcore.c

Fixes #2683
Remove elements from touch point related arrays when touch up and similar events are processed. This makes GetTouchPointCount() always report the actual count of touch points, and all positions returned by GetTouchPosition() correspond to positions of currently happening touches.

Remove touch points on touch up events on Android

---

examples/textures/textures_image_drawing.c
src/raylib.h
src/rtextures.c

To match `DrawCircle()` and `DrawCircleLines()`, this adds `ImageDrawCircleLines()` and `ImageDrawCircleLinesV()` to draw outlines of circles, and updates `ImageDrawCircle()` to draw a filled-in circle.

ADDED: `ImageDrawCircleLines()`

---

src/raylib.h

Edited the 2 comments stating that these function draw a filled circle.

Clarified working of ImageDrawCircle and ImageDrawCircleV for the cheatsheet

---

parser/output/raylib_api.json
parser/output/raylib_api.lua
parser/output/raylib_api.txt
parser/output/raylib_api.xml

build raylib_api without the 'vectex' typos

---

src/rshapes.c

This fixes the issue #2735.
I used the testing code from the issue above.

Fix bezier line breaking #2735

---

BINDINGS.md

Updated bindings support for crystal

---

examples/shapes/shapes_basic_shapes.c

fixing typo

---

cmake/LibraryConfigurations.cmake

Fix deprecation error on android api higher than 23

---

src/raymath.h

Same as [glm::angle](https://github.com/g-truc/glm/blob/fc8f4bb442b9540969f2f3f351c4960d91bca17a/glm/gtx/vector_angle.inl#L20) Alternative to https://github.com/raysan5/raylib/pull/2829 https://github.com/raysan5/raylib/pull/2831

Fix vector2angle

---

BINDINGS.md

TurboRaylib - dynamic bindings of ray lib for Delphi/Lazarus

Add new Delphi/Lazarus bindings

---

examples/core/core_loading_thread.c

core_loading_thread example join thread on completion

---

src/rlgl.h

I was using a skybox for my renderer and noticed the cubemap was bilinear-filtered, which was not desired. However, I found that the available `rlgl` function for changing texture parameters only works for normal textures. I made a `rlCubemapParameters` function to take care of this.

[rlgl] Add `rlTextureParameters` alternative for cubemaps

---

src/Makefile

Fix android sound issue #2118

---

src/rlgl.h

pilepine=>pipeline
chosing=>choosing
additioanlly=>additionally
attachmment=>attachment
initialize=>inititialize
Binded=>Bound
lattest=>latest
hi @raysan5, I ran rlgl.h into some "typo checking" program(basically a JetBrains IDE), and here are all the things that the program was able to spot and fix. as my English isn't really well I would like it if you could check that I didn't make any mistakes in the typo fixing...

fixed typo

---

src/Makefile

I have limited experience with make, please review carefully.

Add wayland support

---

BINDINGS.md

I'm the only maintainer and have been working hard recently to get my library to be as nice to use as possible. I found out about this language list, and getting a new language on it didn't seem so bad. A bonus for my efforts.

Added my BQN Library to the list

---

src/rmodels.c

Fix typo in rmodels.c

---

BINDINGS.md

New release! 🎉 
https://github.com/schveiguy/raylib-d/releases/tag/v4.5.0

Update raylib-d binding version to 4.5

---

BINDINGS.md

https://github.com/TSnake41/raylib-lua/releases/tag/v4.5a

Update BINDINGS.md (raylib-lua -> 4.5)

---

projects/VSCode/Makefile
projects/VSCode/Makefile.Android
projects/VSCode/main.c

Removes unnecessary trailing whitespace from VSCode Project template
Fixes compile issues due to SetCameraMode call and missing argument to UpdateCamera call.

Fix vs code project

---

examples/textures/textures_image_generation.c
parser/output/raylib_api.json
parser/output/raylib_api.lua
parser/output/raylib_api.txt
parser/output/raylib_api.xml
projects/Geany/raylib.c.tags
projects/Notepad++/raylib_npp_parser/raylib_npp.xml
projects/Notepad++/raylib_npp_parser/raylib_to_parse.h
src/raylib.h
src/rtextures.c

This gradient is useful for users who want to implement a falloff map for procedural generation, or potentially for users who want to create a custom vignette for their screen.

Add GenImageGradientSquare

---

BINDINGS.md

PR just got merged: https://github.com/janet-lang/jaylib/pull/48

BINDINGS.md: Janet bindings supported version update

---

examples/core/core_input_gamepad.c

Better examples/core_input_gamepad

---

src/rcore.c

I have reviewed the application shutdown behavior for Android (implemented in one of my previous PR). #3067
Additionally, I have added clearer comments.

Review `android_main()` in rcore.c

---

BINDINGS.md

Update BINDINGS.md for Crystal

---

examples/examples_template.c

Change examples_template.c to raylib 4.5

---

src/build.zig

**zig version:** `0.11.0-dev.4332+43b830415` or higher
**Reference**
- https://github.com/ziglang/zig/pull/16446

Zig build: PathSource changed

---

src/rlgl.h

Fixes #3226 
Could @ubkp try this out before mergine, please

Fix build for OpenGL 2.1, where half floats are part of an extension

---

src/rtextures.c

Fix uninitialized thread-locals in stbi #3282

---

src/Makefile

should close [#3288](https://github.com/raysan5/raylib/issues/3288)
Only tested under Linux

Update Makefile : clean `raygui.c` & `physac.c`

---

BINDINGS.md

I just made some bindings for raylib in the raku language :)

added raylib-raku to bindings

---

BINDINGS.md

Update TurboRaylib bindings  => change version in bindings.md

---

parser/output/raylib_api.json
parser/output/raylib_api.lua
parser/output/raylib_api.txt
parser/output/raylib_api.xml

Meta files in `parser/output` are outdated. I have regenerated them based on the latest commit.

[parser] Update `raylib_api.*`

---

src/build.zig

Fix raygui.c leftover from zig build

---

src/rcore_desktop_sdl.c

* Implement GetCurrentMonitor in rcore_desktop_sdl
Tested on Window 11 with SDL 2.28.4

Implement GetCurrentMonitor in rcore_desktop_sdl

---

src/build.zig

I don't know which zig version is intended to be used here,
but if it is master then this PR adjusts to the new API of Compile.addCSourceFiles()

fix build.zig

---

src/raylib.h
src/rshapes.c

Strangely, ImageDrawCircleLinesV already existed. I'm not sure why this didn't exist before, but implementing it was trivial.

Add DrawCircleLinesV for consistency

---

src/raudio.c

Fix QOA seeking

---

src/build.zig

Tested on linux, shouldn't cause any problems for other operating systems

Allow raylib to be built with zig 0.11.0 and zig 0.12.0dev (master)

---

BINDINGS.md

It got updated to 4.5 overnight, let's include latest information.

Update info about Jaylib

---

examples/core/core_2d_camera_split_screen.c
examples/core/core_drop_files.c
examples/models/models_loading_m3d.c
examples/shaders/shaders_hybrid_render.c
examples/shaders/shaders_write_depth.c
examples/shapes/raygui.h
examples/shapes/shapes_bouncing_ball.c
examples/shapes/shapes_draw_circle_sector.c
examples/shapes/shapes_lines_bezier.c
src/external/rprand.h
src/rcore.c

To get ready for Raylib 5.0, this PR fixes various type and sign warnings in visual studio.

[WARNINGS] Fix warnings in visual studio

---

src/raylib.h

Adjusting raylib.h to reflect post-5.0 changes now.  This is important for testing and verification that I am providing.

Preparing for 5.1-dev

---

examples/Makefile.Web
examples/shaders/resources/shaders/glsl100/lightmap.fs
examples/shaders/resources/shaders/glsl100/lightmap.vs
examples/shaders/resources/shaders/glsl120/lightmap.fs
examples/shaders/resources/shaders/glsl120/lightmap.vs
examples/shaders/shaders_lightmap.c

GLSL 100 and 120 shaders for lightmap example.

Added glsl 100 and 120 shaders to lightmap example.

---

src/rmodels.c

This pull request introduces support for additional glTF/GLB data formats.

Expanding Possibilities: Integrating Additional glTF / GLB Data Formats for Enhanced 3D Experiences

---

BINDINGS.md

Bumped version number and updated the link for Raylib.nelua.
Kenta (the original creator of Raylib.nelua) passed ownership of the bindings to me after deciding to leave the project.

Update BINDINGS.md for Raylib.nelua

---

BINDINGS.md

This PR updates the bindings https://github.com/janet-lang/jaylib/pull/54

Update BINDINGS.md for Janet

---

BINDINGS.md

Unsure why some are bold and some are not...

Update raylib-d binding

---

src/platforms/rcore_desktop_sdl.c

[core] Fix `SetWindowIcon()` for `PLATFORM_DESKTOP_SDL`

---

src/platforms/rcore_desktop.c
src/platforms/rcore_desktop_sdl.c
src/platforms/rcore_drm.c
src/platforms/rcore_template.c
src/platforms/rcore_web.c

Corrected spelling errors in comments.
I did this a little differently compared to my previous PRs regarding spelling fixes, so if there happens to be anything I missed, please let me know.

Fix typos in src/platforms/rcore_*.c

---

src/rmodels.c

Hello! This ensures cgltf uses the callbacks configured by the user to load and unload file data, enhancing the consistency and predictability of raylib.

[rmodels] Set cgltf callbacks to use `LoadFileData()` and `UnloadFileData()`

---

src/raylib.h
src/rtext.c

TextReplace const correctness

---

HISTORY.md

There is a typo where 'undoubtdly' appears instead of 'undoubtedly'.

Fix typo in HISTORY.md

---

src/rshapes.c

I tested this changes with the same cases shown in #3742 and goes nice 🙌.

[shapes] Fix CheckCollisionPointPoly

---

src/platforms/rcore_desktop_sdl.c

> The fingerId from SDL was used as an index into the CORE.Input.Touch arrays, but it's an opaque / arbitrary int64, way bigger than MAX_TOUCH_POINTS, so the first non-simulated touch event would segfault.
Working on Windows tablet (ARM64 :)

Fix SDL multitouch tracking

---

examples/models/models_bone_socket.c

optimisation of the "bone socket" tutorial

---

src/platforms/rcore_drm.c
src/raylib.h

Fixed the gamepad button problem as described in #3789 and also changed the way axes are enumerated and removed some trailing spaces.

Fixing gamepad buttons not working in drm backend

---

projects/VSCode/Makefile

Changed the raylib version from 4.2.0 to 5.1-dev, in the makefile from the VScode project to be just like the raylib.h file

Update Makefile RAYLIB_VERSION

---

BINDINGS.md

Been that way for a while, but I don't think I told anyone.

Update raylib-zig version

---

src/rlgl.h

Line 110 of file rlgl.h is the one in question.

Changed RLGL_VERSION from "4.5" to "5.0

---

build.zig
src/build.zig

Fix local dependency breakage caused by #3905
Tested on ubuntu x64 with zig 0.11.0 and zig 0.12.0-dev.3632+7fb5a0b18

[build.zig] Fix local dependency breakage

---

src/raudio.c

Fix for #3889
Fixes for QOA crashes.
Memory leak fix on .wav loading.

Fixes for loading Music

---

src/Makefile

Sorry, I should've done some tests for this and this should've been included in the last PR.
Found some issues with compiling using the shared method for PLATFORM_DESKTOP_RGFW.

(PLATFORM_DESKTOP_RGFW) Fix Makefile issues (RGFW) (linux) (macOS)

---

BINDINGS.md

Update Raylib-CSharp to `5.1-dev`.

  Update Raylib-CSharp to `5.1-dev`.

---

src/rmodels.c

stepping (mostly noticeable with semi-transparent cylinders)

Fix #4024, cylinder drawing was incorrect due to imprecise angle

---

BINDINGS.md

Removed Raylib.NET (Project closed)

---

BINDINGS.md

Update Julia Bindings

---

parser/raylib_parser.c

Fix mistakes in example usages in raylib_parser help text

---

src/raymath.h
src/rmodels.c

Fix issues described in https://github.com/raysan5/raylib/issues/4055

Fix GLTF animations

---

src/platforms/rcore_android.c
src/platforms/rcore_desktop_glfw.c
src/platforms/rcore_desktop_rgfw.c
src/platforms/rcore_desktop_sdl.c
src/platforms/rcore_drm.c
src/platforms/rcore_template.c
src/platforms/rcore_web.c

Fixing this issue: https://github.com/raysan5/raylib/issues/4019

Adding GetKeyName(int key)

---

examples/Makefile

These were missing. Added in alphabetical order

update make for examples

---

examples/models/models_yaw_pitch_roll.c
examples/shaders/shaders_lightmap.c
examples/shaders/shaders_texture_drawing.c
examples/shaders/shaders_vertex_displacement.c

We want to set a good example, right? :wink:

[Examples] update examples missing unloadtexture

---

examples/text/text_writing_anim.c

"press" is not correct, since a single press will have almost no visual change
The proper behavior is to "hold"

[Examples] update text writing anim

---

examples/models/models_box_collisions.c

Renamed "cursors" to "arrow keys"

[Examples] update models box collisions

---

examples/shaders/shaders_basic_pbr.c

Scale was not correct. Maybe they model was updated at some point? Not sure. But it looks perfect at 0.25 now

[Examples] update shaders basic pbr

---

src/rtext.c

rtext: always multiply by sign in TextToFloat()

---

parser/raylib_parser.c

[raylib_parser] Fix seg fault with long comment lines

---

src/config.h
src/rmodels.c

changing any of the #defines in CONFIG.H related to vboId could cause issues when rendering.
( wanted to add more attributes for a test and ran into this issue )

fix for hardcoded index values in vboID array

---

src/build.zig

Allow Zig build script to change desktop backend using a new `platform` option, which replaces the previous `platform_drm` option. I don't have an extensive testing setup, so someone else should at least run the build once too.
fixes #4299 (closing unresolved issues is weird?)
cc @ryupold 
ref Not-Nik/raylib-zig#143

Allow Zig build script to change desktop backend

---

examples/textures/textures_image_drawing.c

Taken from https://github.com/raysan5/raylib/pull/4356

[examples] Typo fix -- taken from FluxFlu

---

src/rcore.c

"data" parameter does not exist

removed old comment

---

build.zig

Context: https://github.com/raysan5/raylib/pull/4407#pullrequestreview-2382221857
Should hopefully be the last modification to `build.zig` on my part until the next release.

build.zig: Fix a minor issue with `-Dconfig`

---

CONTRIBUTING.md

"Can you write some tutorial/example?"
changed to 
"Can you write some tutorials/examples?"
Alternatively we could do 
"Can you write a tutorial/example?"

Grammar fix in CONTRIBUTING.md

---

src/rshapes.c

Fix typo in rshapes.c

---

examples/Makefile
examples/Makefile.Web

Ref: https://github.com/raysan5/raylib/pull/4434#issuecomment-2438953574, https://github.com/raysan5/raylib/pull/4434#issuecomment-2439001173.
Note: I don't have Windows here, so please double check/test this PR.

[build] [web] Use `mingw32-make` for `PLATFORM_WEB` examples `Makefile` on Windows

---

src/rlgl.h

[RLGL] signed/unsigned mismatch

---

src/platforms/rcore_desktop_rgfw.c
src/platforms/rcore_web.c

Like #4074 I found the same defect on other platforms. 
P.S. I'm not sure if there will be an issue, but logically it should be added.
#3929

fix the issue with GetScreenWidth/GetScreenHeight that was identified on other platforms

---

BINDINGS.md

Fix typo in BINDINGS.md

---

src/raymath.h

while working on a personal project using raylib, i noticed that raymath doesnt have a function for calculating the cross product of 2D vectors, so i implemented a simple function for this purpose in my project, and i think it could be a useful addition to the raymath module.

[raymath] Add cross product function

---

src/platforms/rcore_desktop_rgfw.c

Fixes casting warnings from MSVC.
@ColleagueRiley for visibility.

[RGFW Platform] fix casting warnings

---

CMakeOptions.txt

A humble fix of a small problem

CMakeOptions.txt: Added a missing `)`

---

BINDINGS.md

DOOR, or D Object Oriented Raylib, is a work in progress wrapper + various utilities for raylib users who program with the D programming language.

Add the D Object Oriented Raylib wrapper to the list of BINDINGS.md 

---

src/rlgl.h

use unused variable. Fixes #4560

---

BINDINGS.md

Added new Jai bindings for Raylib version 5.5 and latest Jai version

Added new Jai bindings to BINDINGS.md

---

BINDINGS.md

Removed 2 repos that give 404 when accessed

[documentation] Removing 404 repos from bindings

---

BINDINGS.md

I've created bindings for Raylib 5.5 for the Fennel programming language.

Update BINDINGS.md | Fennel Bindings

---

src/rlgl.h

see: https://github.com/raysan5/raylib/issues/4604

[rlgl] Reviewed `rlActiveDrawBuffers` for OpenGL ES 3

---

src/platforms/rcore_desktop_sdl.c

Fix Typo in rcore_desktop_sdl.c

---

src/rmodels.c

resolved a few segfaults with animation system

---

src/platforms/rcore_desktop_glfw.c

[rcore] [GLFW] Fix camera initial position

---

src/rlgl.h

This optimization works in the following ways:
1. Reduces calls to malloc to 1. Instead of needing an extra array, we can just swap the top half with the bottom half of the one array.
2. Unroll the inner for loop and remove a condition. Unrolling loops buys some performance wins, but the real goal was to remove the if check to avoid branch misses and just set the alpha channel to 255.
On my hidpi arm64 laptop, I saw ~60% improvement in performance in my debug build (29 FPS vs 47 FPS). When optimized, the gains were roughly 10% (75 FPS vs 83 FPS).

[rlgl] Optimize rlReadScreenPixels

---

cmake/LibraryConfigurations.cmake

Proposed fix for: https://github.com/raysan5/raylib/issues/4484

[build][CMake] Fix cmake configuration issue for Android

---

src/platforms/rcore_web.c

Should also have the benefit of being slightly faster than obtaining the canvas element via ID.

Replacing hardcoded canvas id references with module variable usages

---

examples/Makefile.Web

Paired with https://github.com/raysan5/raylib.com/pull/95

[Examples] added missing file for Skybox

---

src/rtext.c

Fix buffer write overflow
Fix reading past the end of text

[rtext] `TextSubtext()` fixes

---

examples/text/text_codepoints_loading.c

As a beginner, it was not clear to me what the purpose of the LoadCodepoints function is. I am trying to help past me.

Amend comment to explain what LoadCodepoints is doing.

---

CMakeLists.txt

Do not check GUI libs for DRM

---

src/external/RGFW.h
src/platforms/rcore_desktop_rgfw.c

- update RGFW to 1.6
- fixes mistakes in `rcore_desktop_rgfw.c`
- loads/unloads gamepads when the `RGFW_gamepadConnected` `RGFW_gamepadDisconnected` event happens instead of when they first send input.

update RGFW to 1.6

---

cmake/raylib-config.cmake

[cmake] set correct description for verbose option

---

examples/core/core_high_dpi.c
examples/shaders/shaders_rounded_rectangle.c

Fix warnings with casting in submitted examples. 😞

[Examples] Fix cast warnings in examples.

---

src/rmodels.c

As discussed in #4888 this fixes scale-related issues during skeletal animation updates. 
Could you, please, take a look

[rmodels] Fix bones animation scale

---

src/raudio.c

This PR simply fixes the whitespace issue identified in PR #4898

[RAUDIO]Fix code formatting issue from PR #4898

---

src/platforms/rcore_desktop_glfw.c

Revert GLFW_SCALE_FRAMEBUFFER to pre GLFW 4.3 behavior

---

src/rmodels.c

In the current GLTF import code, cgltf does not assign bone weights to meshes that do not have bone weight attributes but are parented to the bone. This case in the GLTF file means that every vertex in the mesh is 100% weighted to the parent bone, but since the GLTF import code leaves the bone weight and id lists empty, raylib will never animate these mehses. This is why in some models, things like hats and weapons will not animate.
You can see an example here, notice that the bow and hood from the model are not attached to any bones.
https://github.com/user-attachments/assets/68cf4192-bb37-44ff-a8fb-e561db3099f8
But if you open the same model in a simple GLTF viewer, those meshes do animate.
https://github.com/user-attachments/assets/10fcf63d-5a71-48d6-b8b2-6395943a43bc
To fix this, we …

[rmodels] Fix GLTF bone weight assignments for meshes that are parented to armature bones.

---

build.zig

EGL was previously not being linked properly for Android targets

build.zig fixes for android targets

---

src/config.h

Update comment (gamepad axes)

---

examples/shapes/shapes_basic_shapes.c
src/raylib.h
src/rshapes.c

hi! added vectorized versions of the draw ellipse functions

[rshapes] Add DrawEllipseV and DrawEllipseLinesV

---

src/platforms/rcore_desktop_rgfw.c

RGFW: fix Escape always closing the window

---

src/external/RGFW.h
src/platforms/rcore_desktop_rgfw.c

It is a development version (not a stable release) of RGFW, but it fixes some issues present in 1.7.
Fixes #4968.

Update RGFW to 1.7.5-dev

---

parser/output/raylib_api.json
parser/output/raylib_api.lua
parser/output/raylib_api.txt
parser/output/raylib_api.xml
projects/Notepad++/raylib_npp_parser/raylib_to_parse.h
src/raylib.h
src/rtextures.c

https://github.com/raysan5/raylib/issues/4973

add const qualifier to ImageDrawTriangleFan and ImageDrawTriangleStrip arguments

---

BINDINGS.md

docs: mention another Common Lisp binding

---

src/platforms/rcore_desktop_sdl.c

there is a compile error when PLATFORM=PLATFORM_DESKTOP_SDL, this fixes it

fixed compile error for PLATFORM sdl

---

src/raudio.c

[raudio] Fix: music stopping early. Fix: GetMusicTimePlayed for short music

---

src/Makefile

Removing libraylib.web.a when using make clean.

[build] Update Makefile

---

examples/rexm.c

Added the defining of exName, exCategory, and exRename.
Also fixed something where there was more args needed than said anywhere else

Added certain variable assigment to the rename option and fixed some arugment based logs

---

BINDINGS.md

<b>Hello</b>
I have added Raylib-Ada from @Fabien-Chouteau  to BINDINGS.md
<i>Best regards Artem</i>

Add raylib-ada to BINDINGS.md

---

src/raylib.h
src/rtext.c
tools/parser/output/raylib_api.json
tools/parser/output/raylib_api.lua
tools/parser/output/raylib_api.txt
tools/parser/output/raylib_api.xml

theres no reason for it to not be const

add const qualifier to the first arg of TextJoin

---

src/external/miniaudio.h

I was asked in the discord server to do this. The version has been tested by @M374LX and I.

Update miniaudio.h to version 0.11.23
