- src/gestures.c
- src/makefile
`#include <sys/time.h>` is needed for this compile-time error:
```
gestures.c:553:21: error: storage size of ‘now’ isn’t known
struct timespec now;
^
```
`-std=gnu99` is required for `CLOCK_MONOTONIC`:
```             
gestures.c:554:19: error: ‘CLOCK_MONOTONIC’ undeclared (first use in this function)
clock_gettime(CLOCK_MONOTONIC, &now);
^
```
> Fix compiling on Linux

- src/core.c
- src/makefile
- src/raylib.h
Exposes `GLFW_CURSOR_DISABLED` flag that disables cursor so the mouse can't leave the window, essentially a better hide function for 3D cameras than `GLFW_CURSOR_HIDDEN` flag.
> Disable cursor feature

- examples/Makefile
- src/Makefile
- templates/advance_game/Makefile
- templates/basic_game/Makefile
- templates/basic_test/Makefile
- templates/simple_game/Makefile
- templates/standard_game/Makefile
I've removed some useless code (GLEW recipes and duplicated code) and fixed the command for cleaning of `/src/` after you've compiled raylib for GNU/Linux.
> Cleaning of Makefile files

- examples/Makefile
- src/core.c
- templates/advance_game/Makefile
- templates/basic_game/Makefile
- templates/basic_test/Makefile
- templates/simple_game/Makefile
- templates/standard_game/Makefile
This fixes building the examples on OSX.
If you install glfw3 with [homebrew](http://brew.sh), the library is called "glfw3" and so the linker command needed to change. Ideally, there should be a way to work with the library being called glfw as well, but I don't know the correct linker command for this.
`core_input_gamepad` does not compile, but this is because `GetGamepadMovement` does not seem to exist anymore in develop. I have just removed it from my own makefile for now, and will file a separate issue later.
> Fix building examples on OSX

- examples/core_input_gamepad.c
Replaces usage of removed `GetGamepadMovement()` function in core_input_gamepad.c with 2 calls to the new `GetGamepadAxisMovement()`
> fix example

- src/models.c
This fix allows GenMeshCubicmap() to create cubic maps having cells of
arbitrary sizes.
> Small fix for GenMeshCubicmap()

- src/raylib.h
Same PR as #183, but against `develop` this time :+1:
> Fix a typo in the DrawCube, DrawCubeWires and DrawCubeTexture definitions

- src/rlgl.c
Fixes vbo indices for normals in rlglUpdateMesh. Also similar fix to color, tangents and texcoord2 but I haven't tested these since I'm not currently using.
> Fix vbo indices for rlglUpdateMesh

- src/Makefile
Library for Android can now be built with make. ANDROID_NDK_HOME needs to point to whetever android-ndk is installed. Same variable is used for Android Studio so there is a chance that it will be already configured. I also added support for arm64 arch, it is common now on newer phones, and support for clang.
Currently build fails with clang:
`
audio.c:197:6: error: conflicting types for 'IsAudioDeviceReady'
bool IsAudioDeviceReady(void)
^
./raylib.h:930:12: note: previous declaration is here
RLAPI bool IsAudioDeviceReady(void);                                  // Check if audio device has been initialized successfully
^
audio.c:526:6: error: conflicting types for 'IsSoundPlaying'
bool IsSoundPlaying(Sound sound)
^
./raylib.h:944:12: note: previous declaration is here
RLAPI bool …
> Integrate Android build into Makefile

- README.md
Last character 'l' was missing on examples link.
> Fixed examples link

- examples/Makefile
According to Man Pages, timespec with std=c99 needs "_POSIX_C_SOURCE 199309L". Due a some kind of bug, "#define _POSIX_C_SOURCE 199309L" doesn't work, so we must use "-D_POSIX_C_SOURCE=199309L" in compiler options.
> Examples Linux Physics Fix

- src/audio.c
Fix for audio.c(607): error C2036: 'void *': unknown size in Visual Studio 2015.
> fix for audio.c(607): error C2036 in Visual Studio.

- examples/Makefile
- src/Makefile
Restore /usr/local/include/raylib to INCLUDES in examples/Makefile. Is in use by at least one user.
Modify CFLAGS for PLATFORM_WEB in examples/Makefile and src/Makefile to reflect emscripten recommended optimizations.
> Restore inadvertant changes to Makefiles

- templates/basic_game/Makefile
Removed glew from basic_game makefile as glew is not part of the raylib package (no glew in mingw).
> basic_game - update makefile

- src/Makefile
Some distributions build the programs with a specific set of CFLAGS.
Lets allow that by adding raylibs flags.
> Accept external CFLAGS

- .gitignore
- README.md
- meson.build
- src/meson.build
I would like to add this initial meson support, so far working for Linux, along the Makefile.
Once the meson support is also done for Windows, Android and Web one might drop the Makefile.
I rebased my commits since in the first one I had a mistake, because of this 1adc0313015b30cf061a3bc9d47292f82dc649f8 has the 'with jubalh'. Sorry for that one.
This commit also regards https://github.com/raysan5/raylib/issues/176
I suggest to close that issue since the initial request was to support CMake to have easier building on Linux, which is now solved through meson.
> Initial meson support

- src/core.c
- src/gestures.h
- src/physac.h
If we compile with c99 without gnu extensions (gnu99) we need this
define, to have CLOCK_MONOTONIC and similar macros available
> Add define to have CLOCK_MONOTONIC work in c99

- meson.build
We use variable init in for loops, so need c99.
> Meson: use gnu99

- meson.build
glfwSetWindowMonitor and some other functions are only available from 3.2
onwards.
> Add version info to glfw dependency

- src/raylib.h
- src/textures.c
Signature: `SaveImageAs(Image image, const char *filename);`
I think this would be useful for the users who generate procedural textures, it allows them to save them (for example to upload or share them)
Right now the workaround is to display the image on the entire window and to take a screenshot, but I think a dedicated function makes sense
> Add the SaveImageAs function

- examples/textures/textures_image_generation.c
- src/raylib.h
- src/textures.c
And here are some results:
- Density = 0.0
- Density = 0.3
- Density = 0.5
- Density = 0.8
- Density = 1.0
I don't know if this is really what you expected, tell me 😄
> Add a density parameter to GenImageRadialGradient

- src/models.c
When there is a newline at the end of an .OBJ file, this can cause a bogus triangle to be added to the mesh. In LoadOBJ(), the "dataType" does not get reset, and the result from fscanf is not checked, so at the end of the file the last triangle is sometime counted twice, but since there isn't a corresponding entry in the vertex data it can create a bogus triangle. Usually the verts are all zero and you don't see it, but this has been causing occasional glitchy rendering for me.
Simply resetting the dataType for each line fixes this, as it won't process the last entry twice.
> Fix for OBJ loading

- src/Makefile
This should make the proper `.dylib` file, and set it so that whatever program is trying to be run, the .dylib can be in the same folder.
1. There should be a note of that `same folder` thing somewhere in the docs.
2. I haven't tested how this effects of building the examples.
Discussion should go back to ticket #328 to resolves those two things
> Able to make a .dylib for OS X

- src/physac.h
Physac wasn't working on OS X.  It looks like the necessary timing code wasn't being compiled in by the preprocessor.
fixes #340
> Make physac work on OS X

- src/shapes.c
Variable t was read and modified without interleaving sequence points,
technically undefined behavior. Report by Clang's -Wunsequenced.
Reported by Travis CI. I want to test Automatic build on pull request too.
> Fix warning about unsequenced modification of variable

- src/raylib.h
- src/rlgl.c
Just a tiny little change: the `glUniform*` functions take const pointers, so I don't think there is any reason to disallow const pointers from being used in `SetShaderValue` :)
> Have SetShaderValue(i) take a const pointer

- examples/shaders/shaders_postprocessing.c
- src/rlgl.c
I did as you suggested: I added a `LoadShaderPartial` function and changed the `LoadShaderProgram` function to take already compiled shaders. Which means we only have to compile the default shaders once now !
Fix #381
> Store the default shaders

- .travis.yml
- src/CMakeLists.txt
- src/core.c
- src/gestures.h
- src/physac.h
- src/rglfw.c
- utils.cmake
There have been two problems:
* GLFW itself was compiled with the definitions for compiling
_against_ GLFW (Fixed by removing requirement for external glfw)
* rglfw.c was being compiled as C code, although it includes
Objective C files.
This _might_ break the Windows build, needs to be checked.
Fixes #391, but as noted I'd prefer though a separate source directory
and build script for GLFW.
The prior commit fixes a Travis CI compile error when compiling for Linux.
>  Fix macOS build of new rglfw.c approach

- .travis.yml
- appveyor.yml
- raylib.pc.in
- src/CMakeLists.txt
- utils.cmake
After installation, compiling new user programs is possible with
$ cc game.c `pkg-config --static --libs --cflags raylib`
or
$ cc game.c `pkg-config --libs --cflags raylib`
depending on configuration
Also adds following configuration options:
- `WITH_PIC` "Compile static library as position-independent code"
- `STATIC_RAYLIB` "Build raylib as a static library"
- `MACOS_FATLIB`  "Build fat library for both i386 and x86_64 on macOS"
> Generate and install pkg-config pc file and allow static/shared builds in one go

- README.md
`brew install raylib` now install the 1.9.1-dev release, unless `--build-from-source` is supplied, it downloads a prebuilt raylib from Homebrew's servers. `brew install --HEAD` builds the latest commit available on the `develop` branch.
> Note that raylib can now be installed via Homebrew

- .travis.yml
- CMakeLists.txt
Otherwise using a compiler that defaults to -std=c89 or -std=gnu89 will
fail. Example:
http://www.cpantesters.org/cpan/report/abb85066-d283-11e7-9926-b2f4efb9c382
> CMake: Explicitly ask for C99 support

- src/audio.c
- src/external/mini_al.c
- src/external/mini_al.h
- src/raylib.h
This adds mini_al as a backend for audio. I've left the OpenAL implementation in place, and it can be toggled with USE_MINI_AL:
```
#define USE_MINI_AL 1 // Set to 1 to use mini_al; 0 to use OpenAL.
```
A few notes about this:
- I've tried to use a consistent coding style, but I know I have used my own personal style in places, so you may want to clean that up.
- The implementation of mini_al is defined in `external/mini_al.c`. It needs to a separate transaction unit due to naming conflicts with the Win32 API.
- In my testing, I found the first call to `EndFrame()` is slow, and thus causes a pause in the audio at the beginning of playback. Moving `UpdateMusicStream()`, etc to after the drawing section should fix this, I think.
- With OpenAL, the maximum volume for sounds is clamped to 1, …
> mini_al integration

- .travis.yml
- appveyor.yml
Now with external OpenAL and GLFW dependencies removed, we don't have to worry about installing them in CI.
Shared libraries are now always built along with static libs. Games and examples are built everwhere except for Visual Studio, because Physac needs pthreads, which VS doesn't provide.
> Build shared libs, games and examples on CI

- project/vs2015.UWP/raylib.App.UWP/App.cpp
- project/vs2015.UWP/raylib.App.UWP/App.h
Mouse input is implemented, with all bells-and-whistles. This includes cursor locking and scroll wheel support.
Keyboard input is reverted to a callback model to better reflect the existing architecture in "core.c"
> Add mouse input and revert keyboard to callback model

- CMakeLists.txt
- src/Makefile
As an extension, GNU C treats `sizeof(void)` as `1`. MSVC doesn't.
Make it an error on GCC/Clang to avoid accidental MSVC breakage.
> GCC/Clang: Treat void pointer arithmetic as error

- .travis.yml
- src/CMakeLists.txt
- utils.cmake
`-DWITH_SYSTEM_GLFW=ON`: Link against system glfw and fail otherwise
`-DWITH_SYSTEM_GLFW=OFF`: Use embedded `rglfw.c`
`-DWITH_SYSTEM_GLFW=IF_POSSIBLE`: Probe for system glfw but fallback to
rglfw if unavailable
Also change Linux 64-bit CI build to install system glfw and use it,
so this doesn't bitrot.
> CMake: Add tristate option for using system GLFW

- src/core.c
- src/raylib.h
You can't do much with raylib if glfwInit or glfwCreateWindow fails,
currently it just exits by means of TraceLog(LOG_ERROR.
User code, however, might want to fall back to a text-only UI
or display a warning if raylib can't be used.
> Return false from InitWindow if glfwInit or glfwCreateWindow fails

- src/core.c
Otherwise we run into an assertion failure inside GLFW's `glfwGetVideoMode`.
Example:
http://www.cpantesters.org/cpan/report/b4ba5894-0bdb-11e8-841e-2c60b04e1d2d
This is related to #456.
> InitWindow: return false if no monitor found

- examples/Makefile
- src/Makefile
Quite a few additions to the makefiles here, mostly limited to LINUX and RAYLIB_LIBTYPE=SHARED, to avoid the dreaded `./core_basic_window: error while loading shared libraries: libraylib.so.1: cannot open shared object file: No such file or directory`  by formally installing libraylib (to the location of your choice) or by customizing RAYLIB_RUNTIME_PATH. This adds control, portability, and a running choice of shared libraries to the developer experience. Now distro-agnostic! 
That is to say, one can have multiple builds of libraylib to choose from at compile and run time, without sudo, using only make, on any ELF-aware system with binutils. FreeBSD and MacOS users might extend these changes if desired. I'm curious if this plays on WSL.
The default `make; make install; cd ../examples; …
> Linux make install improvements

- examples/Makefile
- src/Makefile
The default setting of `EXAMPLE_RUNTIME_PATH ?= $(RAYLIB_RELEASE_PATH)` in ../examples/Makefile makes it so that the examples run automatically against a freshly built, but not yet installed, libraylib.so in ../release/libs/linux. This is like an implicit USER mode. It does not require root permissions or any special input beyond `RAYLIB_LIBTYPE=SHARED` but is easily customizable if desired. The value of `EXAMPLE_RUNTIME_PATH` will override that of `RAYLIB_INSTALL_PATH` at an example's run time, if libraries exist at both locations. It is recommended to set `EXAMPLE_RUNTIME_PATH = $(RAYLIB_INSTALL_PATH)` if you don't want to pick up fresh versions of libraylib in ../release/libs/linux. If no libraylib exists at `EXAMPLE_RUNTIME_PATH`, ld.so moves on to check the location set by `ldconfig` …
> Update Makefiles. Automate example usage of staged libraylib.so.

- CMakeLists.txt
- src/Makefile
- src/external/jar_xm.h
jar_xm.h does some shady pointer casts leading to unaligned accesses
and breaking strict aliasing. x86 has special circuitry for doing
unaligned accesses, but on other architectures, it may trap and require
kernel fix-up or crash outright. With this patch, one obstacle in
porting raylib to the GameBoy Advance has been removed. Go for it ;-)
To avoid having to rewrite that `mempool' code, insert padding before
structs and instruct the compiler (GCC, most importantly), to be gentle
when optimizing.
This fixes #490 (Unless we got ourselves 256-bit pointers, if so,
hello future!)
> jar_xm: Workaround for unaligned pointer accesses

- examples/models/models_skybox.c
- src/core.c
- src/raylib.h
- src/raymath.h
RAYMATH_EXTERN_INLINE was renamed to RAYMATH_HEADER_ONLY, which user code
may define if they want to use it as header-only library. If multiple
files in the same project define RAYMATH_HEADER_ONLY, they might each
have duplicate out-of-line definitions of the same functions.
By default, raymath.h exposes inline definitions, which instructs the
compiler _not_ to generate out-of-line definitons, if out-of-line
definitions are required, those of the file defined with
RAYLIB_IMPLEMENTATION are used instead. There may be only one such file.
In C++ mode, the compiler will select only one out-of-line definition
automatically, so no need to define a RAYLIB_IMPLEMENTATION.
Unfortunately, we have to remove raymath function declaration from
raylib.h as those declarations would lead to duplicate …
> raymath.h: Use C99 inline semantics

- src/external/mini_al.h
Related to issue #506.
This should fix a crash on OSS/BSD resulting from a buffer overflow.
> Fix a buffer overflow in the OSS/BSD backend of mini_al.

- examples/models/models_orthographic_projection.c
- src/core.c
- src/raylib.h
I needed orthographic rendering for my own things. This solution doesn't modify the existing Camera struct but instead uses a new one called CameraOrtho and a new Begin3dModeOrtho() call. This means that the input systems and picking functions are not compatible, but for that to be possible they would need a lot of internal reimplementation. Some of the semantics might not be compatible either, suggesting that only a partial reimplementation would be necessary, further suggesting that a separate set of functionality is warranted.
This is a (at least partial) solution of issue #439
> Add orthographic 3d rendering mode

- games/arkanoid.c
- games/asteroids.c
- games/asteroids_survival.c
- games/floppy.c
- games/gold_fever.c
- games/gorilas.c
- games/just_do/just_do.c
- games/koala_seasons/koala_seasons.c
- games/light_my_ritual/light_my_ritual.c
- games/missile_commander.c
- games/pang.c
- games/skully_escape/skully_escape.c
- games/snake.c
- games/space_invaders.c
- games/tetris.c
- games/transmission/transmission.c
- games/wave_collector/wave_collector.c
- src/core.c
- templates/advance_game/advance_game.c
- templates/simple_game/simple_game.c
- templates/standard_game/standard_game.c
Inspired by #504.
Instead of requiring the user to do `PLATFORM_ANDROID` `#ifdef`ery,
have the `android_main` entry point exported by raylib and call
the user-defined `main`. This way many games could (in theory)
run unmodified on Android.
**This is untested!**
> Allow use of main instead of android_main

- src/CMakeLists.txt
- utils.cmake
- include GNUInstallDirs so it can be used for multilib builds (i.e. ABI_X86 64, 32, x32) , so lib/ dir is not hardcoded
- add USE_AUDIO option so raylib can be built without alsa on Linux, as supported in Makefile
- adds USE_WAYLAND option so raylib can be built with Wayland support
> Add GNUInstallDirs and USE_AUDIO/USE_WAYLAND options to CMake

- src/CMakeLists.txt
- src/CMakeOptions.txt
- src/audio.c
- src/config.h
- src/config.h.in
- src/core.c
- src/models.c
- src/rlgl.c
- src/rlgl.h
- src/shapes.c
- src/text.c
- src/textures.c
- src/utils.c
- src/utils.h
- utils.cmake
Instead of requiring users to manually edit or add `#define SUPPORT_*`s to the appropriate source file, centralize all library configuration to an internal `config.h` file.
This file is generated at configuration time from CMake options and hardcoded for the Makefile and other build systems.
> Refactor all #define SUPPORT_* into a config.h

- .gitignore
- CMakeLists.txt
- src/CMakeLists.txt
Panders to the idiosyncrasies of my work flow:
I have my raylib build directory mounted as a VirtualBox vboxfs for use
with my Linux VM, but vboxfs doesn't support symlinks, while raylib shared
library versioning on Unix expects symlinks to work.
If this happens, library versioning is now disabled on Unix with
an error message instead of just failing the build.
> CMake: Don't create symlinks on unsupporting file systems

- examples/Makefile
- games/Makefile
- games/drturtle/Makefile
- games/just_do/Makefile
- games/koala_seasons/Makefile
- games/light_my_ritual/Makefile
- games/skully_escape/Makefile
- games/transmission/Makefile
- games/wave_collector/Makefile
- templates/advance_game/Makefile
- templates/simple_game/Makefile
- templates/standard_game/Makefile
Currently, if:
* GCC doesn't supports `-no-pie`: Build error
* GCC supports `-no-pie`
* GCC is not configured with `--enable-default-pie`: No-op
* GCC is configured with `--enable-default-pie`:
Slightly worse performance because we still generate `-fpie` code
(`-pie` affects linker, `-fpie` affects compiler)
So instead of probing for existence of `-fno-pie -no-pie`, remove it altogether.
Fixes #540: Build breakage on Debian 8 with gcc 4.9.
> Makefile: Remove unnecessary -no-pie for older GCC support

- cmake/utils.cmake
Fixed bug in utill.cmake on FreeBSD (cannot find -X11 libraries) for issue https://github.com/raysan5/raylib/issues/551
> Fix cannot find -lX11

- .travis.yml
- CMakeLists.txt
- cmake/test-pkgconfig.sh
- cmake/utils.cmake
- raylib.pc.in
- src/CMakeLists.txt
- src/external/glfw/CMakeLists.txt
```
if (${PLATFORM} MATCHES "Desktop")
target_link_libraries(${RAYLIB}_shared glfw ${GLFW_LIBRARIES})
```
was never true because `PLATFORM STREQUAL "PLATFORM_DESKTOP"`...
This fixes #551 and makes the changes suggested in #552 (commited as 965cc8a)
unnecessary.
Also adds a simple CTest test case as a sanity check that the resulting raylib.pc file can be used to compile a simple application.
>  CMake: Reuse libraries found by glfw CMake config

- release/include/raylib.h
- src/Makefile
- src/core.c
- src/raylib.h
#567 
This is my first ever significant pull request! I love that that raylib is so easy to comprehend.
Note that in getting the gamepad feature to work, I had to abort before the gestures system could be handled. I tried some methods for ignoring gestures only when gamepad input was detected, however the system seems really glitchy (pointerCount seems to go all over the place), and I had to give up. Perhaps someone who is doing gesture stuff can step in here and try to re-enable it. 
The gamepad feature is really simple, all I had to do was capture the keycode when motion was detected, no axis needed for this one. 
I've tested this with Android, wasn't able to test elsewhere right now. Won't be offended if this is rejected for that reason! Was a great experience solving this myself, I'm …
> SNES-like GAMEPAD Support added for Android, Makefile has optional support for 32bit

- examples/CMakeLists.txt
- games/CMakeLists.txt
I found that examples and games using CMake were not compiled correctly. The output was LLVM IR bitcode instead of html + js. I introduced the changes needed for their `CMakeLists.txt` mimicking what's done in the Makefiles.
> Fix HTML5 examples and games using CMake

- src/rlgl.h
Even though we are not compiling `rlgl_standalone` in Travis CI, users should be able to compile it separately. I tried to do so manually running
```
gcc -o rlgl_standalone -Isrc examples/others/rlgl_standalone.c build/release/external/glfw/src/libglfw3.a -framework Cocoa -framework IOKit -framework CoreFoundation -framework
CoreVideo -framework OpenGL
```
and got:
```
Undefined symbols for architecture x86_64:                                                                                                                                                                                       [183/36228]
"_MatrixFrustum", referenced from:
_rlFrustum in rlgl_standalone-e6fe05.o
"_MatrixIdentity", referenced from:
_rlLoadIdentity in rlgl_standalone-e6fe05.o
_rlRotatef in …
```
> Fix rlgl.h to be used as a standalone

- projects/Builder/README.md
- projects/Builder/examples/meson.build
- projects/Builder/meson.build
Update Builder example for raylib 2.0.0.
External OpenAL and GLFW are not required anymore.
> Update Builder example

- src/core.c
- src/rglfw.c
GLFW was changing the working directory to `Resources` by default. We should prevent this in order to run successfully the games examples that load stuff from `resources/[whatever]`.
> [games] Prevent GLFW changing working dir to 'Resources'

- examples/models/models_mesh_picking.c
(I'm not sure if the built-in CMake makes any difference)
The old FLT_MAX constant seems to be too big for MSVC, resulting in error C2177. I could have just used as defined in float.h that comes with MSVC. But I thought why not just go all the way and use the bit-by-bit correct constant as defined here: https://stackoverflow.com/questions/16350955/interpreting-the-bit-pattern-of-flt-max
> fix problem when compiling with MSVC 2017, error C2177

- examples/physac/physics_demo.c
- examples/physac/physics_friction.c
- examples/physac/physics_movement.c
- examples/physac/physics_restitution.c
- examples/physac/physics_shatter.c
- src/physac.h
This PR addresses https://github.com/raysan5/raylib/issues/592
To start with, both `physics_demo` and `physics_shatter` had a bug because they were never setting `needsReset` back to `false`.
Then, as discussed in https://github.com/raysan5/raylib/issues/592, I thought it would be much simpler to avoid `physac` creating any threads rather than making the library thread-safe. I feel it's much simpler for beginners and newcomers to simply call `RunPhysicsStep` themselves within their main loop rather than learning concurrency all of the sudden. For this reason, I believe `PHYSAC_NO_THREADS` should be the default. I would actually rename it to do the opposite: `PHYSAC_CREATE_THREAD` or similar.
I had to fix refactor `PhysicsLoop` slightly and created `PhysicsRunStep` to be able to run …
> [physac] Fix Physac examples to be run without creating new thread

- examples/textures/textures_image_processing.c
- examples/textures/textures_image_text.c
- examples/textures/textures_particles_blending.c
- examples/textures/textures_srcrec_dstrec.c
- src/camera.h
- src/core.c
- src/models.c
- src/raymath.h
- src/rlgl.h
- src/shapes.c
- src/text.c
- src/textures.c
Thanks a lot for the great library. I just fixed some compiler warnings which are caused by forat to int, int to float or double to float casts, which are not explicitely marked as explicit casts.
> Fix compiler warnings

- games/snake.c
This PR fixes two bugs in the game Snake. The fruit spawn position when initially colliding with the snake was causes it to be rendered off-grid and the collision detection of the snake's head and the fruit.
Changes were tested on Linux 4.17.12-arch1-1-ARCH
> Games: Fixes bugs in Snake

- src/raymath.h
- Added __declspec(dllexport) to RMDEF in raymath.h. This allows them to be accessed when importing from raylib.dll.
> Raymath dllexport fix

- README.md
The link to rlgl in the README was broken, it previously pointed to a .c file which doesn't exist (anymore).
> Fixes path to rlgl.h in README.md

- projects/README.md
- projects/VSCode/.vscode/c_cpp_properties.json
- projects/VSCode/.vscode/launch.json
- projects/VSCode/.vscode/tasks.json
- projects/VSCode/Makefile
Previously the project was insufficient for running raylib on OSX. This will be the first official project that actually supports building, running, and debugging on the platform.
There are some things to keep in mind:
- This project requires that the user specify the path to their installation of raylib in a few places. It might be a good course of action to work towards having a similar situation to the Windows side of things, where we can be more certain of the direct path to raylib on OSX.
- The wiki needs to be updated to explain better how to run raylib on OSX. Perhaps directing people to use VSCode and linking that project is the best course of action?
> Updated VSCode project to support OSX building / debugging.

- src/raylib.h
The prototype of GenImageFontAtlas() in the main raylib.h header has a set of swapped parameter names.
Going through the usage of the function within raylib itself, it appears as if the correct order is:
1) charsCount
2) fontSize
However, it's exposed to the world as the other way around, which may cause some major confusion.
> GenImageFontAtlas prototype in raylib.h is incorrect.

- src/physac.h
Generating the projects using CMake, targeting VS2017, results in an error when compiling.
This is due to physac.h trying to make a 'vertices' array of size 'int count', making it const does not work, either.
This changes the static declaration to a malloc/free combo.
Tested using the physics-demo.
> Physac.h fix for variable array size declaration.

- src/text.c
GenImageFontAtlas() allocates an array of stbrp_rect for the packing functions, but it never frees them.
> Fixes memory leak in text.c

- src/core.c
- src/raylib.h
Added a function to get the last write time of a file. I used this so I can reload files or resources if the time since they were last loaded changes.
```
char *path1 = "test1.txt";
char *path2 = "test2.txt";
long mod1 = GetLastWriteTime(path1);
long mod2 = GetLastWriteTime(path2);
TraceLog(LOG_INFO, "last write time %ld %ld", mod1, mod2);
```
> Added GetLastWriteTime to allow for file reloading

- src/Makefile
Removed -Iexternal from the base include path, added it back conditionally for Windows only. This allows non-Windows platforms to compile raylib as discussed in https://github.com/raysan5/raylib/issues/667.
> Remove non-Windows includes from Makefile

- src/core.c
- src/raylib.h
1) Now all '/dev/input/event*' devices are used for input(Mouse no longer used). They are scanned trough on startup, devices that are mice or touchscreens are given reading threads. This allows for an unlimited number of simultaneously working mice. Keyboard and gamepad continue to use existing methods.
2) Multitouch is now supported on RPi with 10 point multitouch
3 Touchscreens now get scaling factors from '/dev/input/event*' by ioctl 
4) Fixed bugs with IsMouseButtonPressed(Used to constantly fire when holding button) and GetMouseWheelMove(Did not work)
5) Fixed exesive CPU usage of GamepadThread
Relates to issue: https://github.com/raysan5/raylib/issues/666
> RaspberryPi Mouse and touch overhaul

- src/core.c
When doing a8dffc63fbe3926498ecb905428f454d0afbe526 I was not aware that
printing a warning and not executing the code would be an option. I only
learned that through 618f220851570f2bb9ea0bb354a65e92c6d06968.
So I propose that we allow all URLs except if the string contains a `'`.
Which could end the URL and call another command via `system()`.
Related to https://github.com/raysan5/raylib/issues/686
> Check for single apostrophe in OpenURL()

- src/utils.c
funopen is only needed on Android, so declare it
only there. This fixes following MinGW build failure:
```
utils.c:50:7: error: conflicting types for ‘funopen’
FILE *funopen(const void *cookie, int (*readfn)(void *, char *, int),
^~~~~~~
In file included from utils.c:45:0:
/usr/include/stdio.h:586:7: note: previous declaration of ‘funopen’ was here
FILE *funopen (const void *__cookie,
^~~~~~~
```
> utils: declare funopen only on Android

- src/core.c
- src/raylib.h
Needed mouseScale to be seperate for x and y so it works when the width and height are different.
For example works with a size of 500x500 but not when using 1024x600.
Solved by addding `SetMouseOffset` to set the scale with a Vector2.
Default scale is 1.0f for both x and y and `SetMouseScale` sets both aswell.
```c
Vector2 size = { GetScreenWidth(), GetScreenHeight() };
Vector2 offset = { 1920.0f / size.x, 1080 / size.y };
SetMouseOffset(offset);
```
> Added SetMouseOffset

- projects/scripts/README.md
- projects/scripts/core_basic_window.c
- projects/scripts/linux-build.sh
- projects/scripts/osx-build.sh
- projects/scripts/windows-build.bat
Some people might want to build projects without make systems or such, so here's three build scripts I wrote to build raylib applications without those. Only the three main desktop platforms sadly, but they were the easiest to write and test. I've ran them all successfully on Windows 8.1, Arch Linux (gcc) and a pretty up-to-date macOS, but additional testing would probably be nice if possible.
> Add project/scripts

- src/core.c
- src/raylib.h
Implemented from https://en.wikipedia.org/wiki/HSL_and_HSV#Alternative_HSV_conversion. 
When converting back and forth from **Color** to **HSV** some precision will be lost and the initial color won't be exactly the same but this cannot be avoided. I put a note in the source!
> Added ColorFromHSV()

- src/utils.c
Here it is, a small fix that issue the `LOG_OTHER` log-type not properly handled.
> Trace log failing on other

- CONTRIBUTING.md
I've deprecated [raylib-rust](https://github.com/dtcristo/raylib-rust) in favour of [raylib-rs](https://github.com/deltaphc/raylib-rs) which is more feature complete. Therefore feel free to remove this link as I'm not maintaining the bindings anymore.
> Remove `raylib-rust`

- raylib.pc.in
$prefix/lib isn't in pc_path on Fedora 28:
[root@fedora-28 ~]# pkg-config --variable=pc_path pkg-config
/usr/lib64/pkgconfig:/usr/share/pkgconfig
This has the effect that the raylib.pc file is written to the
correct location but `pkg-config --libs raylib` doesn't output
the correct library path. This fixes this problem by substituting
the directory names into raylib.pc, same as we do with the CMakeLists.txt
since #518.
This issue popped up during the automated test of the Perl bindings:
athreef/Alien-raylib#3
> CMake: pkg-config: fix usage for RedHat-like systems

- src/text.c
Getting the following strict error....
```
src/text.c:117:105: error: constant expression evaluates to 2398692640 which
cannot be narrowed to type 'int' [-Wc++11-narrowing]
...0x00000000, 0x00000000, 0x00200020, 0x0001b000, 0x00000000, 0x00000000, 0x8ef92520, 0x00020a00...
^~~~~~~~~~
```
Switching it to an unsigned int fixes it.
> Fix font cannot be narrowed to type 'int'

- src/core.c
clang was complaining about the type conversions. For example...
```
src/core.c:1888:15: error: cannot initialize a variable of type 'char *' with an
rvalue of type 'void *'
char *cmd = calloc(strlen(url) + 10, sizeof(char));
^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> Fix clang++ compilation errors

- src/raylib.h
- src/text.c
Improved the code for `DrawTextRec()` and added the ability for selecting text renaming it `DrawTextRecEx()`. `DrawTextRec()` now directly calls `DrawTextRecEx()`. 
You can drop the *Ex* if you don't think it's necessary.
> Added DrawTextRecEx()

- src/text.c
Fixed as issue where `strrchr` in `LoadBMFont` would only look for forward slashes, instead of backslashes causing `strlen` to fail on a null string formatted like so:
> R"(..\Resources\fonts\example.fnt)"
> LoadBMFont filepath fix

- src/models.c
- src/raudio.c
- src/shapes.c
- src/text.c
- src/textures.c
Related to issue #752.
This PR currently contains fixes to most of the configuration flags. I'm making this PR now since I need some advice on how to continue.
Issues when `SUPPORT_IMAGE_MANIPULATION` is disabled:
- `LoadTextureCubemap` calls `ImageDraw`, which is now undefined. `ImageDraw` then seems to depend on `ImageCrop` and `ImageResize`, and `ImageResize` depends on `stbir_resize_uint8`. Should `LoadTextureCubemap` depend on `SUPPORT_IMAGE_MANIPULATION`, or should something more sophisticated be done?
- `ImageFormat` calls `ImageMipmaps`, which is now undefined. Is it safe to just not call `ImageMipmaps` if this flag is not enabled?
- `ImageAlphaCrop` calls `ImageCrop`, I'm guessing it should be under this flag as well.
A few notes on the changes I made already:
- If I understood …
> Fix config.h flags

- src/text.c
Small error that prevented rendering the text inside a rectangle with sufficient height.
Sorry i didn't catch this earlier!
> Fixed height bug in DrawTextRecEx()

- src/raudio.c
When calling:
```
SetSoundPitch(sound, 0.8);
// ...
SetSoundPitch(sound, 0.9);
```
expected pitch of 90% of the original sound, but instead got 0.8*0.9=72%
This PR changes the behavior to set pitch relative to the base sound.
> Fix audio pitch

- src/text.c
My quick fix introduced errors when unloading fonts not using the data field, Do´h.
This should fix that error.
> Fixed segmentation fult created by quick fix

- src/text.c
Since the unicode patch, text selection didn't work as expected (see below), so i fixed it(easy fix :D).
Working on raygui textbox now so i'll probably find all the bugs related to drawing unicode text, if there are any... Lucky me!
> Fixed text selection in DrawTextRecEx()

- src/easings.h
PI is not always defined in math.h, thus it must be defined in this header
> Defined PI (#822)

- src/CMakeOptions.txt
- src/config.h.in
Hi! ^ ^
This change allows the recently-added option to be toggled in CMake. The wiki page "CMake Build Options" needs to be updated as well.
On a side note, is it desirable that such options default to different values depending on the platform, e.g. `SUPPORT_HIGH_DPI=ON` on macOS (as almost all recent models have a Retina display), and `SUPPORT_BUSY_WAIT_LOOP=OFF` on systems with `nanosleep()`? Because with current master 0b2bad4 and default value `SUPPORT_HIGH_DPI=OFF`, the macOS build draws on only 1/4 of the window.
> Add SUPPORT_HIGH_DPI to CMakeOptions.txt

- src/models.c
Square root calls are computationally expensive.  In this function, it can be avoided.  Instead of checking whether distance<(radiusA+radiusB), we can check whether distance squared < (radiusA+radiusB) squared.
I used the existing Vector functions, but perhaps the code is less readable that way.  The Vector3DotProduct of centerB-centerA with itself gives the distance squared.
> Remove sqrt() from CheckCollisionSpheres()

- src/text.c
My earlier patch https://github.com/raysan5/raylib/pull/817 failed to account for wordwrap.
> Fixed DrawTextRecEx() selection when wordwrap is ON

- examples/shaders/resources/shaders/glsl330/julia_shader.fs
- examples/shaders/shaders_julia_set.c
Zoom increase/decrease should now scale depending on the current zoom, and the zoom should also now behave as expected (increased zoom = closer image).
> Update julia set example.

- src/models.c
In the `LoadIQM` function, the `vaoId` of the meshes is never initialized to 0. So when `LoadModel` calls `rlLoadMesh`, if `vaoId` is positive then the mesh is never uploaded to the GPU ([see here](https://github.com/raysan5/raylib/blob/master/src/rlgl.h#L2349)).
The fix is simply to initialize all the struct members to 0.
Fixes #848
> Fix unitialized struct member bug (#848)

- src/external/jar_xm.h
See #850 
The function didn't work for some .xm files ([one](https://modarchive.org/index.php?request=view_by_moduleid&query=59963) [two](https://modarchive.org/index.php?request=view_by_moduleid&query=43516)) so I fixed it.
> Fix jar_xm_reset

- src/config.h.in
config.h.in is missing an MP3 flag which stops MP3 audio from working on cmake projects unless this is overcome/overriden.
> Add MP3 config to config.h.in

- src/CMakeLists.txt
- src/Makefile
With v2.5.0 out, increment API_VERSION, so binaries dynamically linked against
the released raylib aren't accidentally paired with a development or later
released raylib that may be incompatible.
---
Issues was discussed multiple time in the past (see #613 for an example).
The intention here is not to change raylib's versioning scheme, just the compatibility/API version evaluated by the dynamic loader.
> build: increment API_VERSION after release

- src/rlgl.h
I've tested this with the example in #891 and my own application which used to break, both work fine now.
Hope it helps!
> Fix vertex padding not zeroed for quads

- src/rmem.h
L235 - Increased the memory threshold size so that we can further reduce fragmentation by allocating memory blocks that is close to the requested size by 16 bytes.
> Increasing threshold size for traversing memory blocks

- examples/Makefile
- games/Makefile
- games/cat_vs_roomba/Makefile
- games/drturtle/Makefile
- games/just_do/Makefile
- games/koala_seasons/Makefile
- games/light_my_ritual/Makefile
- games/skully_escape/Makefile
- games/transmission/Makefile
- games/wave_collector/Makefile
- projects/4coder/Makefile
- projects/VSCode/Makefile
- templates/advance_game/Makefile
- templates/simple_game/Makefile
- templates/standard_game/Makefile
This fixes the a bug while building for HTML5 by changing the mentioned backslashes to forward-slashes.
https://github.com/raysan5/raylib/issues/917
> #917 This commit changes the path to 'shell.html' in all Makefiles

- src/rlgl.h
* This is the clean version, without CLion's junk *
This should fix a logic error which would mean that, even if it was supported, texture wrapping mode RL_WRAP_MIRROR_CLAMP would never be applied. Below is an image of where the issue occurred.
This PR assumes that OpenGl 1.1 is incapable of using this extension regardless of whether or not the supported flag is true. If this is wrong, please correct me.
> [Clean] Should fix RL_WRAP_MIRROR_CLAMP issue

- src/rmem.h
Patched a potential bug concerning the '__RemoveNode' function as, when removing certain nodes that are either at the head or tail, it can yield a free list node of size 0 bug as the previous node was removed and its size was set to 0 but not fully removed from the other nodes.
> Patched potential bug when defragging.

- src/Makefile
Added in a check for x86 and x86_64 branches of android
Added in $(OS) checks to see if we're running on windows or *nix
Added a default location for android ndks and sdks at /usr/lib/android
> Improved Android Building

- src/models.c
Free texturePath in LoadGLTF()
> Fix memory leak in LoadGLTF()

- src/core.c
This is a single small fix to an apparent copy-paste error in the `GetMouseY()` function present when building for the Android platform.
> Small fix in GetMouseY()

- examples/core/core_2d_camera.c
- src/core.c
Currently when working with Camera2D, you have to constantly change both offset and target when following the player. This isn't intuitive; when following player with camera, generally only one vector - player's position - changes every frame, and thus to update camera one would expect to also only change one field.
This pull request removes camera transformation by target at the end of camera world-space transformation, which means user doesn't have to add this value himself to the offset anymore. In effect, this makes offset to be not relative to world coordinates, but to screen, and thus the value doesn't have to be updated when the position of the followed object changes.
Illustration of new camera behavior
> A more intuitive Camera2D behavior

- src/models.c
`mesh.vboId` is  not uninitialized in `GenMeshHeightmap`, which cause segfault in the models_heightmap example.
> Fix uninitialized vboId in GenMeshHeightmap

- src/shapes.c
By removing the equal sign, if the 2 rects are right next to each other and are not overlapping, there will be no collision detection. This is what a majority of other game libraries do and would make it easier to implement collisions for tile based games.
> Update shapes.c for smoother collision detection

- examples/Makefile
I'm not sure why the clean command is so complex (especially given that find -type f -executable | xargs rm -fv works!)
but I fixed the version as is, to support x-pie-executable which was preventing it deleting anything on my system...
> examples makefile not deleting examples in Linux

- examples/models/models_material_pbr.c
as LoadModel now expects user to unload shaders and textures (as they could be used elsewhere) the example now does this...
just before loading the PBR material the default material (from loadOBJ/ LoadModel) must be unloaded, to avoid a leak....
phew... finally got there!
> fixed leak with PBR example

- src/shapes.c
Hi, I think I have fixed a bug.
In the moudle: _shapes_, the function: _void DrawPoly(Vector2 center, int sides, float radius, float rotation, Color color);_ Its implementation is wrong.
There are problems with rendering polygons, with number of sides not divisible by 360.
The 360/sides is integer division, and as a result a  non divisible by 360 number will render sides+x sides. Sub-cases:
- If the lower bound of (360/sides) is not divisible by 360 there will be an overlap and it will create an artifact (more visible when rendering transparent). (Example sides: 7, 11, 13, 14...)
- If the lower bound of (360/sides) is divisible by 360 there will be no overlap but there are still going to be rendered more edges. For example if you request a polygon with 23 sides, there will be rendered one …
> Fixed regular polygon shape rendering

- src/shapes.c
Thanks ray for accepting my bug fix! ([#972](https://github.com/raysan5/raylib/pull/972))
I would like to make some minor changes, mostly to improve code legibility.
In the src/shapes.c the DrawPoly() function:
- Change the variable name from internalAngle to centralAngle, since technically, the geometric definition of internal angle is [this](https://en.wikipedia.org/wiki/Internal_and_external_angles), and of central angle is [this](https://en.wikipedia.org/wiki/Central_angle).
- The centralAngle can be initialized with the value of zero. Although the functionality remains the same (as long as it is initialized with a 360/sides multiple), it makes more sense this way, and it also minimizes unnecessary computations.
> Improve code readability

- src/raudio.c
The result of `success` is actually never used. Either we should check
for it and return or remove it. I assume just checking the last one is
okay.
> Remove dead assignments

- examples/shaders/resources/shaders/glsl100/raymarching.fs
- examples/shaders/resources/shaders/glsl330/raymarching.fs
- examples/shaders/shaders_raymarching.c
Added   - #define PLATFORM_DESKTOP line for desktop users.
This now will correctly find the proper glsl version for the raymarching.fs file.
Removed - Uniforms --> deltaTime and viewUp. Including the code that was setting them.
They were never used and they were triggering a log warning.
Removed - The const from both screenWidth and screenHeight.
Now they can be used to update the shader resolution when screen is resized.
NOTE : This is a quick fix and probably not the best idea.
Added   - IsWindowResized() to check if screen is resized.
If window is resized then width, height and shader resolution are updated.
Changed - MIT tag at bottom right color value to BLACK. Now it's easier to see.
> updated RayMarching Demo

- src/raylib.h
- src/rlgl.h
also fixed issue with GL11 where model matrix was only returning identity
> added GetMatrixProjection 

- BINDINGS.md
I have added my Raylib Binding for Pascal to the bindings.md file.
> Update Bindings list include raylib-pas info

- examples/CMakeLists.txt
- games/CMakeLists.txt
At least on Linux, CMake seems to add automatically
the '-rdynamic' flag. As a result, Emscripten
generates a fat HTML file that does not work.
Removing it allows HTML+JS+WASM generation.
> Fix generation of web examples

- src/core.c
- src/raylib.h
I based the name from `ColorFromHSV`. Not sure if it is the best name for it. 
Example usage
```c
Color color = ColorFromNormalized((Vector4){0.5f, 0.1f, 0.1f, 1.0f});
```
I am not sure if a cast should be added for converting the float to unsigned char.
> [Core] Added ColorFromNormalized which is the reverse of ColorNormalize.

- src/rlgl.h
`rlUpdateMeshAt` allows the user to update a subset of a buffer, starting at the nth (`index`th) element.
I find myself frequently updating only certain regions of a buffer at a time, and having this function available helps performance tremendously.
> [rlgl] Create function `rlUpdateMeshAt`

- src/camera.h
Hi, about https://github.com/raysan5/raylib/issues/924
I fix the camera behavior. I noticed additional camera issues.
I think that there are 3 problems.
1. z-direction camera at initialization is not working. it is caused by SetCameraMode(camera, CAMERA_FREE); Because "cameraAngle.y" was nan after this function.
```
Camera camera = { 0 };
camera.position = Vector3 { 0.0f, 0.0f, 0.0f };
camera.target = Vector3 { 0.0f, 0.0f, 10.0f };
camera.up = Vector3 { 0.0f, 1.0f, 0.0f };
camera.fovy = 45.0f;
camera.type = CAMERA_PERSPECTIVE;
```
2. Camera rotation by mouse.y movement has a non-linear behavior when a camera angle close to align xz plane.
3. camera.position at start is not zero. it was flip 180 degrees unexpectedly.
```
Camera camera = { 0 };
camera.position = Vector3 { 0.0f, 0.0f, 0.0f …
```
> Fix camera not working problem at align z direction. #924

- src/text.c
I was playing around with `shaders_model_shader.c`:
```C
// Load shader for model
// NOTE: Defining 0 (NULL) for vertex shader forces usage of internal default vertex shader
Shader shader = LoadShader(0, TextFormat("resources/shaders/glsl%i/grayscale.fs", GLSL_VERSION));
```
The original code above suggests we can do this:
```C
// Load shader for model
Shader shader =
LoadShader(
TextFormat("resources/shaders/glsl%i/base.vs", GLSL_VERSION)
, TextFormat("resources/shaders/glsl%i/grayscale.fs", GLSL_VERSION)
);
```
Unfortunately, we cannot. This was causing the runtime error `gl_Position: undeclared identifier`, the kind of error we get when attempting to compile a vertex shader as a fragment shader. What was going on?
Adding some basic output to `LoadShader()` revealed the following:
``` …
```
> [text] `TextFormat()` caching

- src/core.c
If press/release events for a mouse button come too fast, then using
`IsMouseButtonReleased()` does not work. This has been noticed when
using a touchpad on Linux when tapping with two fingers two emulate
right mouse button click.
The situation looks like this:
```
BeginDrawing           <-- current==released, previous==released
Pressed                <-- current=pressed
Released               <-- current=released
IsMouseButtonReleased  <-- returns false because current==previous
EndDrawing             <-- previous=released
```
The fix is to update the previous mouse button state in addition to
current mouse button state when `MouseButtonCallback()` is called by
glfw. Now the situation is as follows:
```
BeginDrawing           <-- current==released, previous==released
Pressed …
```
> Fix `IsMouseButtonReleased()` when press/release events come too fast

- src/core.c
* We get the video mode from the target monitor and use that to set, therefore
keeping windowed-fullscreen
* Added a GLFW_AUTO_ICONIFY 0 hint so that glfw does not minimize the window
when changing focus from a windowed fullscreen window. This is more expected
behavior for windowed full screen, when a user alt-tabs or clicks on a window in
the other monitor, they expect their windowed-fullscreen window to remaining up.
This would fix Issue #1035 
Points worth thinking about for the future:
* If the monitors are of different resolutions, can the user manage the framebuffer in a sensible way? E.g letterboxing/scaling
> SetWindowMonitor made functioning again.

- src/camera.h
pitch rotation was only being done on one axis
this allows you to look straight up and down, other camera modes will need this method implementing...
> fixed free camera pitch rotation

- src/raudio.c
Short non-looping sounds can sometimes think they need to keep playing and will output their first few frames again. This helps to break out of all the loops instead of just this one.
> Fix for short non-looping sounds

- src/models.c
The loadModel function used the GenMeshCube to generate a default cube mesh, if no model could be load.
Now, if the SUPPORT_MESH_GENERATION feature is not supported, we don't load a default cube mesh, but we simply warn the user that no meshes can be loaded, and we can't create a default mesh because the feature is not enabled.
>  Fix compilation when SUPPORT_MESH_GENERATION not supported

- .gitignore
- src/textures.c
Pretty simple changes, usually involved just adding a call to `RL_FREE`.
For `ImageToPOT` I put the allocation of the `pixels` buffer in the body of the if-statement because if the condition was false the array was allocated for nothing and it would also leak.
> Fixed memory leaks in textures.c and added jetbrains/clion project-files to gitignore.

- src/rlgl.h
This fix guarantees the string loaded from a file is zero-terminated. The old code:
```C
// WARNING: \r\n is converted to \n on reading, so,
// read bytes count gets reduced by the number of lines
if (count < size)
{
text = RL_REALLOC(text, count + 1);
text[count] = '\0';
}
```
does not zero-terminate the string if `count == size`, which can very well be the case if the text file was written in an editor that uses `\n` instead of `\r\n` (basically every text editor on Linux).
> [rlgl] `LoadText()` fix

- src/textures.c
I think that the `if` statement on line `3121` should be `else if` because it would cause a memory leak if both branches could be hit in the same call because they both do an allocation stored in `image.data`.
> Changed `if` to `else if`.

- examples/CMakeLists.txt
- games/CMakeLists.txt
- games/drturtle/CMakeLists.txt
- games/just_do/CMakeLists.txt
- games/koala_seasons/CMakeLists.txt
- games/light_my_ritual/CMakeLists.txt
- games/skully_escape/CMakeLists.txt
- games/wave_collector/CMakeLists.txt
- projects/CMake/CMakeLists.txt
Before all CMakeLists.txt in examples and tests used a specific version of raylib, which would have been needed to be upgraded. This is fixed in this PR. Also sorry for three commits instead of one
> Always use latest raylib version for cmake

- examples/CMakeLists.txt
- games/CMakeLists.txt
- games/drturtle/CMakeLists.txt
- games/just_do/CMakeLists.txt
- games/koala_seasons/CMakeLists.txt
- games/light_my_ritual/CMakeLists.txt
- games/skully_escape/CMakeLists.txt
- games/wave_collector/CMakeLists.txt
- projects/CMake/CMakeLists.txt
We didn't use the latest version, but a compatible version, which is established by  [`raylib-config-version.cmake`](https://github.com/raysan5/raylib/blob/master/cmake/raylib-config-version.cmake).
It's ok to have a minimal version, so revert the raysan5/raylib#1123.
> Revert "Always use latest raylib version for cmake"

- src/core.c
In `InitGraphicsDevice(...)`, the Android section has a screen security check
like other platforms- but CORE.display.width, CORE.display.height are
not set yet, so the security check sets it to 0. So ensure we query the
device's screen width and height before the screen size security check.
This also gives you the ability to run a proper full-screen application
on Android without any scaling and guess work on the target device by
setting screen width and height to 0 in `InitWindow(...)` and using
`GetScreen[Width|Height]()` to get the actual values.
> Android: Set CORE.display.[width, height] before screen size check

- projects/scripts/build-windows.bat
- Adding the option to change the target platform(x86/x64)
- Generating the .pdb file on debug builds
- Correcting comments that called the script 'windows-build.bat' instead of 'build-windows.bat'
> build-windows.bat fixes

- src/core.c
This was working in 2.6 but no longer does in current git tree.
It appears touch position is only tracked on
AMOTION_EVENT_ACTION_[DOWN|UP], which only registers the initial touch
on the screen. Subsequent movement is not tracked into CORE.
Touch position and the Gesture System appears to be updated twice in
AndroidInputCallback in what looks like perhaps a copy paste error (code
is identical) with the exception of tracking AMOTION_EVENT_ACTION_UP in
the 2nd copy of the code (but this is not necessary to track).
If you need to track the first touch or release touch position, you can
do so with checking IsMouseButton[Pressed|Released] on the same frame.
This patch makes it so the touch position is always updated, and merges the
duplicated code into 1 singular code path.
> Android: Track touch motion across screen

- appveyor.yml
- src/CMakeLists.txt
We build the library as debug with AppVeyor and package it this way,
which is unfortunate, because on Windows it's linked against debug
variants of the C runtime. Fix this by build RelWithDebInfo instead
Fixes #1128.
> appveyor: configure for Release with Debug Info

- src/core.c
Switch to actually tracking touch input to use for "mouse" input rather
than the gestures system. The gesture system as an abstraction ontop of
raw touch input loses some information needed to map to "mouse"
input.
Before,
- IsMouseButtonReleased() triggers immediately after the initial touch
(because GESTURE_TAP activates immediately on touch) instead of waiting for the
touch to be released.
- IsMouseButtonUp() returns false, when it should just be the opposite
of IsMouseButtonDown().
- IsMouseButtonDown() returns true only after GESTURE_HOLD (which
activates after some period of time after GESTURE_TAP), when instead it
should just be true whenever there is touch input i.e. gesture !=
GESTURE_NONE or alternatively when any input is received on the screen.
After this PR, touches map …
> Android: Better track touch input returned from IsMouse*()

- src/text.c
Selection index didn't account for change in k value after a word wrap, causes misaligned selection post-wrap.
related: https://github.com/raysan5/raylib/pull/833
> Fixed DrawTextRecEx() selection when wordwrap is ON (again)

- examples/Makefile
- src/Makefile
Hi all. My first PR here!!
I have been reviewing many compilation flags for warnings  and testing them (the complete list is 
`gcc --help=warning`). So far I tested the next ones:
```
-Wbad-function-cast -Wbool-compare  -Wbool-operation -Wbuiltin-declaration-mismatch -Wcast-align -Wcast-qual -Wchar-subscripts -Wcharacter-truncation -Wchkp -Wconversion-extra  -Wdeprecated -Wformat-overflow -Wfree-nonheap-object -Wimplicit -Wint-in-bool-context -Wint-to-pointer-cast -Winteger-division -Wmissing-parameter-type -Wmissing-prototypes -Woverlength-strings -Wpointer-sign -Wpointer-to-int-cast -Wunused
-Wunused-but-set-parameter -Wunused-but-set-variable -Wunused-const-variable -Wunused-const-variable -Wunused-dummy-argument -Wunused-function -Wunused-label -Wunused-local-typedefs -Wunused-macros …
```
> Update compilation warning flags

- src/raymath.h
Running cppcheck on my project which include raymath.h showed me these two warnings:
```
[raylib/src/raymath.h:557] -> [raylib/src/raymath.h:565]: (style) Variable 'result' is reassigned a value before the old one has been used.
[raylib/src/raymath.h:1326] -> [raylib/src/raymath.h:1328]: (style) Variable 'resAngle' is reassigned a value before the old one has been used.
```
This is mostly a style fix, but since the first value is never used might as well not assign it.
> Fix "variable is reassigned before use" linter warning on raymath.h

- src/core.c
- src/raylib.h
- src/utils.c
in file core.c cppcheck shows errors only in function `SaveStorageValue()`:
* `Common realloc mistake: 'fileData' nulled but not freed upon failure`
* `Memory pointed to by 'fileData' is freed twice.`
Validation:
* Tested examples/core/core_storage_values.c
* Launched Unit Test for this function: 
* Rerun CPPCHECK afer fix
**Important**: The unit test and the cppcheck results can be fond in a new repository:
https://github.com/danimartin82/raylib_test
**Important**: Still pending to decide what to do with negative positions in functions `SaveStorageValue(int position, int value)` and `LoadStorageValue(int position)`. My proposal will be to change the header so `position` is `unsigned int`.
> [cppcheck] Improvements in SaveStorageValue() in core.c

- src/models.c
- src/raudio.c
Errores fixes:
- models.c,2843 Either the condition 'fileData!=NULL' is redundant or there is possible null pointer dereference: fileData.
- raudio.c,805, 806, 807, 808, %d in format string (no. 2) requires 'int' but the argument type is 'unsigned int'.
> [cppcheck] Fix minor warnings in models.c and raudio.c

- src/text.c
A small fix to a subtle bug in `GenImageFontAtlas` that we previously discussed in this thread: https://github.com/raysan5/raylib/pull/1170
> Fixed offset check in GenImageFontAtlas

- src/text.c
- Added NULL return if the replacement string (by) is empty
- Reordered sanity checks since there's no need to initialize variables if the strings are invalid.
> TextReplace changes

- src/raudio.c
related to this issue [#1175](https://github.com/raysan5/raylib/issues/1175) I added a warning if the file extension isn't supported
> added log warning for unsupported file extension for music stream

- projects/VSCode/.vscode/launch.json
- projects/VSCode/Makefile
- Fixes the built executable not launching when debugging from VSCode because of misconfiguration
- Fixes the build error on macOS due to calling the wrong make version
> Fix VSCode

- examples/Makefile.Android
- templates/advance_game/Makefile.Android
- templates/simple_game/Makefile.Android
- templates/standard_game/Makefile.Android
For uploading a apk to Google Play a minimun of 25 years (9125 days) is needed for the validity of the key.
More info:
https://developer.android.com/studio/publish/app-signing
Pending to improve the makefiles: the actual makefiles for android in raylib generate a new key in a new keystore each time it is compiled. This is not valid for Google Play, they request to use always the same keysotre.
> [android] Extend validity of the certificate

- examples/CMakeLists.txt
I was trying to compile raylib+examples by emcc 
I followed this [instruction](https://github.com/raysan5/raylib/wiki/Working-for-Web-(HTML5))
```
emsdk install latest
emsdk activate latest
```
However, emcc failed with messages about ```LLVM not supporting EMTERPRETIFY```
This PR fixes this issue on my machine:
Ubuntu 19.10
emcc (Emscripten gcc/clang-like replacement) 1.39.12
> Fix for building examples with latest emsdk (LLVM)

- src/models.c
I have problem when loading IQM models with more than one mesh because I can't assign different textures for other meshes, for example I want do like code bellow and without materials is very uncomfortable.
```
// Load mrfixit model
Model mrfixitModel = LoadModel("../resources/mrfixit.iqm");               // Load the animated model mesh and basic data
Texture2D mrfixitBody = LoadTexture("../resources/mrfixit_body.png");    // Load model texture and set material
Texture2D mrfixitHead = LoadTexture("../resources/mrfixit_head.png");    // Load model texture and set material
mrfixitModel.materials[0].maps[MAP_DIFFUSE].texture = mrfixitBody;             // Set map diffuse texture
mrfixitModel.materials[1].maps[MAP_DIFFUSE].texture = mrfixitHead;             // Set map diffuse texture …
```
> Fix materials loading for IQM models

- examples/core/core_input_gamepad.c
- src/core.c
- src/raylib.h
**Fixes GetGamepadAxisCount:**
**GLFW** defines the number of axis from 0 to 5 which means that **GLFW_GAMEPAD_AXIS_LAST** is equal to **count - 1** and not **count**.
**Fixes core_input_gamepad example:**
For an Xbox gamepad, the axes are not correctly drawn (inverted axes).
**Fixes inaccurate axis values:**
Joysticks axis are really inaccurate between -0.2 and 0.2.
I suggest to return 0.0 for this slice.
> Gamepad axis bug fixes and improvement

- src/models.c
Just flipped the signs of `n5` and `n6` at lines `2021` and `2022`.
> Fixed Generated Normals for GenMeshCubicmap

- src/core.c
How to reproduce a bug:
1. on Unix-like machine call GetPrevDirectoryPath("/home")
2. result is empty string 
3. expected result "/"
> fix bug in GetPrevDirectoryPath on Unix-like systems

- src/core.c
- src/raylib.h
The camera in my game can move when the cursor is at the edges of the screen. However it will still move when it is outside the screen. I could try to find a workaround but I saw cursorOnScreen is stored in core.c. It is called IsCursorOnScreen instead of IsMouseOnScreen to match other cursor functions like IsCursorHidden.
Example usage:
```c
if (IsCursorOnScreen())
{
TraceLog(LOG_INFO, "Cursor on screen!");
}
else
{
TraceLog(LOG_INFO, "Cursor off screen!");
}
```
To check if the mouse entered or exited the window you have to store the previous state of IsCursorOnScreen. This seems to be how similar functions in core work.
```c
// Load
bool cursorOnScreen = false;
bool lastCursorOnScreen = false;
// Update
cursorOnScreen = IsCursorOnScreen();
if (cursorOnScreen && !lastCursorOnScreen)
{ …
```
> Added bool IsCursorOnScreen(void).

- src/raymath.h
Things were pointing the wrong way.
Classic XYY copy-paste error.
> fix bug in QuaternionFromVector3ToVector3

- src/Makefile
Letting ANDROID_NDK to be modified at compile time.
Default path to the ANDROID_TOOLCHAIN have changed in the latest Android command-line tools release.
> Fixing Android build from Linux.

- src/models.c
Found and fixed a buffer overflow on the vertices array in GenMeshPoly when using certain numbers of sides - 11 or 50 are good examples.
Changed degree stepping to floats in order to close the poly accurately.
Added check on sides to prevent divide by zero and invalid numbers.
Thanks. :)
> Fixed buffer overflow in GenMeshPoly

- src/rlgl.h
Updating the whole color buffer of a mesh would allocate and copy memory for `vertexCount * 4` `float`s instead of `unsigned char`, leading to extra memory allocation as well as data being copied beyond the color buffer.
> Fix extra memory allocated when updating color buffer in mesh

- src/core.c
Scissor mode implementation uses global window height instead of the current framebuffer height when calculating scissor mode coordinates, leading to inconsistent scissor mode when drawing to smaller framebuffers.
> Fix wrong height used when using scissor mode with render texture of different height from window

- src/core.c
- src/raylib.h
Note: only gets the monitor's current video settings. e.g. a 165 Hz monitor set to 60 Hz will return 60.
> [add] GetMonitorRefreshRate(int monitor);

- src/textures.c
Reproducing case
```cpp
#include <assert.h>
int main(int argc, char **argv)
{
Color color = {};
color.r     = 255;
color.b     = 255;
uint16_t pixel = {};
SetPixelColor(&pixel, color, UNCOMPRESSED_R5G6B5);
Color color_after = GetPixelColor(&pixel, UNCOMPRESSED_R5G6B5);
assert(color.r == color_after.r);
assert(color.g == color_after.g);
assert(color.b == color_after.b);
return 0;
}
```
Previously, for RGB565 the color component is stored with a range of [0, 31] in the uncompressed format. Before this patch, suppose a pixel that's completely red in RGB565 := (R31, G0, B0), GetPixelColor will convert to 255 space and do
```
R = (31 * 31)  / 255
R = 961 / 255
R = 3.7
```
Where as we expect a completely red pixel in RGB565 to return 255 for red. Patch fixes the conversion
```
R = 31 / 31 * 255 …
```
> GetPixelColor: Fix incorrect color transform to 255 space

- src/rlgl.h
This may be related to #1301, but this PR addresses problems found in 3.1, unlike the issue, which appears to be centered around 3.0.
Two leaks come from any `RenderBatch` objects and default `Shader` resources that are created.
The allocations occur here:
https://github.com/raysan5/raylib/blob/00fda3be650ade80f1492105c2107a4ace6bc575/src/rlgl.h#L4088-L4094
The default RenderBatch created by `rlglInit()` (and seemingly any other RenderBatch) does not record the number of buffers that it has created, which prevents its buffers (and the memory allocated for them) from getting cleaned up when it's passed to `UnloadRenderBatch`.
This is resolved by adding the assignment to the `buffersCount` which is evaluated by the `UnloadRenderBatch` function during clean-up.
The allocation occurs here on …
> Free leaked allocations from render objects when using rlgl with OpenGL 3.3

- src/core.c
I was adjusting `RL_CULL_DISTANCE_NEAR` and found the remaining hard coded `0.01` scaling value used for perspective top/right frustum calculations needed adjustment too. I suggest this change gives more intuitive results from `BeginMode3D` when people first try changing `RL_CULL_DISTANCE_NEAR` and expect only the near plane to move.
> scale perspective top calc for near culling plane

- src/models.c
When intersecting from a `Ray` to a `Y` ground plane, error can accumulate in resulting `RayHitInfo.position.y`, and it may be negative (beneath the supplied positive Y-normal plane).
Example: It's possible to call `GetCollisionRayGround(<mouse ray>, 0.0f)` and intermittently get results that flip flop between `(Vector3){..., 0.0, ...}` and `(Vector3){..., -0.000001, ...}`.
I suggest this should be cleanly clamped to `groundHeight` since we know the hit position must occur on the supplied plane, or not at all.
> clamp ray hit y position to ground plane height

- src/models.c
- src/raylib.h
Probably still [wip] and [rfc] but this is working for me and perhaps is generally useful.
`MeshSmoothNormals` sums and averages vertex normals. I use it for visually smoothing terrain generated by `GenMeshHeightmap`.
> [wip] MeshNormalsSmooth()

- src/core.c
- src/rlgl.h
Useful to see some log noise when I break rlgl :)
Actually I am surprised not to see `glGetError` anywhere. Are OpenGL errors meant to be caught in some other way? I think at least `GL_OUT_OF_MEMORY` is possible for any raylib user to hit even if they do not touch rlgl directly.
> rlCheckErrors

- examples/shaders/resources/shaders/glsl330/lighting.fs
The shader as it is right now renders it like this:
But with the change, it looks like this:
The problem is that the shader currently is not multiplying the ambient color by the texture diffuse color, so it's just using a white texture multiplied by the `ambient` vector as the diffuse layer. We can simply resolve this by just multiplying by the diffuse color.
> Fix color of ambient light

- src/Makefile
When you install emsdk out of the box, the directory is no longer `$(EMSDK_PATH)/python/3.7.4_64bit` but rather `$(EMSDK_PATH)/python/3.7.4-pywin32_64bit` noting the `3.7.4-pywin32_64bit` change on the last file.
Thus, without adjusting this in the raylib Makefile it will throw an error:
```
PS C:\raylib\raylib\src> make PLATFORM=PLATFORM_WEB -B                                                                  emcc -c core.c -Wall -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing -std=gnu99 -Os -s USE_GLFW=3 -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mingw -DPLATFORM_WEB -DGRAPHICS_API_OPENGL_ES2              '"python"' is not recognized as an internal or external command,                                                        operable program or batch …
```
> Update Makefile for web

- src/core.c
- src/raylib.h
Hi, I've added the following windows related functions.
**New functions, desktop only** 
```c
// Decorate the window (only PLATFORM_DESKTOP)
void DecorateWindow(void);
// Undecorate the window (only PLATFORM_DESKTOP)
void UndecorateWindow(void);
// Maximize the window, if resizable (only PLATFORM_DESKTOP)
void MaximizeWindow(void);
// Restore the window, if resizable (only PLATFORM_DESKTOP)
void RestoreWindow(void);
// Check if window has been maximized (only PLATFORM_DESKTOP) 
bool IsWindowMaximized(void);
```
**Usage**
For example with the new functions, for set full-screen windowed borderless mode you could do:
```c
SetConfigFlags(FLAG_WINDOW_RESIZABLE);
InitWindow(screenWidth, screenHeight, "some game");    
MaximizeWindow();
UndecorateWindow();
```
To restore to the normal windowed …
> new windows functions allows borderless mode

- src/raylib.h
- src/rlgl.h
Adds a new function BeginBlendModeEx that permits the use of any blend factors and blend equation. I have used this in a project (Windows) so think it works as intended. Also adds a default Subtract blend mode for use with the normal BeginBlendMode.
> Multiple blendmodes

- src/core.c
error message missed device name and printed file descriptor (which should be always -1 at this line) instead of error number
> fixed wrong error message for input device on RPI

- BINDINGS.md
The repository is not a mirror anymore.
> update raylib-nelua repository url

- cmake/JoinPaths.cmake
- raylib.pc.in
- src/CMakeLists.txt
Fixes incorrect usage of CMake paths which cause issues
on some more complicated environments (NixOS especially).
> Fix #1380: Add join_paths and join prefix with include/lib dirs

- BINDINGS.md
Raylib-forever: 3.1-dev
It generates the c-to-nim bindings straight from the source.
nim-raylib: 3.1-dev
It uses Raylib-forever.
raylib-php: 3.0
Tested it using the provided binaries.
raylib-java: 2.0
Tested it using the provided binaries.
> Add some bindings' versions

- src/raymath.h
Vector3Reflect exists but not Vector2Reflect. The code is pretty much the same.
I'm not sure what RMDEF does, but I added it to match other function definitions (haven't done much C programming, maybe I'm missing something). Can someone explain to me what it does?
> Add Vector2Reflect to raymath.h

- projects/Geany/raylib.c.tags
- projects/Notepad++/c_raylib.xml
- projects/Notepad++/raylib_npp_parser/raylib_npp.xml
- projects/Notepad++/raylib_npp_parser/raylib_to_parse.h
- projects/VS2017.UWP/raylib.App.UWP/App.cpp
- src/camera.h
- src/core.c
- src/raylib.h
Making mouse wheel return a float means the threshold between not scrolling and scrolling is more sensitive and allows for finer grained response.
Right now, especially on desktop through GLFW, we truncate the scroll movement from double to int and so we lose quite a bit of data. Implementing for example a window that can be scrolled by the mouse is very choppy because we lose that precision.
> mouse: Return float movement for precise scrolling where possible

- BINDINGS.md
It's 2.5
@raysan5 Oh...There are 4 bindings has license date of 2016, But unsure if 1.6.0 or 1.5.0 or 1.4.0 :(
> Added version of raylib-cppsharp via used raylib license date!

- src/core.c
There is no zero-check, so window upscales to nothing.
SetupFramebuffer() is kinda wrong, it uses not its params, but global variables. I won't touch it, maybe it has purpose
> Fixed zero-window upscaling

- examples/others/rlgl_standalone.c
Stumbled on this example and I love this! Adding instructions that work for me on MacOS.. Note that glfw3 will need to be statically built locally and copied to this external/libs directory on mac. I can upload my static version, but it probably makes sense to do this only if there's some general naming convention for adding platform specific folders. Like "external_osx/lib" or "external/lib_osx". Then I'll drop my static libs in there.
> Added Apple Compilation Instructions

- examples/others/rlgl_standalone.c
Without GLFW_OPENGL_FORWARD_COMPAT, running this as a standalone will yield the error:
```
NSGL: The targeted version of macOS only supports forward-compatible core profile contexts for OpenGL 3.2 and above
```
> Added GLFW_OPENGL_FORWARD_COMPAT for Apple Support

- src/core.c
- src/models.c
- src/raudio.c
- src/textures.c
Fix typecast warnings in raylib code as reported by visual studio 2019.
This PR just does some basic casting to prevent warnings when building the code in visual studio 2019.
The PR focuses just on raylib code, not any external library header files (par_shapes.h, and jar_xm.h still have warnings).
> Fix typecast warnings

- projects/VS2017/examples/core_basic_window.vcxproj
- projects/VS2017/examples/core_basic_window_cpp.vcxproj
- projects/VS2017/raylib/raylib.vcxproj
Two small quality of life changes to projects.
1) Use the latest windows SDK not a specific one.
2) Use the project dir as the root for the include dir for raylib, to help if the project is ever included in some other solution that may not be at the expected path. This helps for cases where the user wants to build raylib as part of a different game solution.
> Small quality of life changes to VC projects.

- src/core.c
- src/raylib.h
This PR adds a function to the API that returns information about multiple displays on desktop platforms that tells you where a monitor is relative to the primary monitor, so you can move a window onto it. This PR also changes some comments that refer to the primary monitor but are attached to functions that deal with selected monitors.
> Add function to get the position of a monitor (and fix some comments)

- src/rlgl.h
Add functions to enable/disable depth writes to go with functions for depth tests. Since depth test enable/disable is exposed via rlgl, depth writes (mask) should be exposed as well.
> Add enable/disable for depth mask

- projects/VS2019/examples/core_basic_window.vcxproj
- projects/VS2019/examples/core_basic_window_cpp.vcxproj
- projects/VS2019/raylib/raylib.vcxproj
This PR moves the 'obj' temp dir for the 3 projects that are part of the visual studio solution. Previously all 3 projects were attempting to share the same temp dir in the solution folder. This causes conflicts in visual studio when multiple projects attempt to write and use the same debug files (such as the runtime PDBs). These conflicts cause warnings that are very confusing to users.
This does not change the bin folder, so the end result is the same build as before, there just is not a conflict when visual studio tries to thread the build process.
> Fix obj/pdb conflicts in Visual Studio Projects

- CMakeLists.txt
This change only modifies the default value. In cmake you can have raylib as a subdirectory (dependency) and when you have it as dependency you wouldn't probably want to use the example by default. You can still use the option to enable them though.
> Building examples by default only if raylib is standalone.

- src/CMakeLists.txt
I did this to support vcpkg expectation. When using the library from vcpkg for web you would install it using vcpkg install raylib:wasm32-emscripten but also vcpkg expects the output lib to be with .a extension instead of .bc
Doesn't make a difference for standalone builds or when raylib is used as a subdirectory dependency.
> Changed extension for web from .bc to .a

- src/models.c
- src/raylib.h
This PR breaks the current model ray collision code into two parts, one for meshes and one for models. This allows applications to detect collisions when they are drawing meshes directly using rlDrawMesh.
This PR also changes the model ray collision code to call the mesh version for each mesh, so there is no new code to maintain, just exposing what was already in raylib with a little more granularity.
> Expose mesh collision code

- src/textures.c
Since I don't think the purpose of raylib is to save space compressing image, I think it could be a good idea to keep quality from 90 to 100.
> Changing JPG compression

- src/CMakeLists.txt
@raysan5 Another small improvement. I really want to get this to work for vcpkg and currently vcpkg only has one of these critical headers.
> Add headers to install cmake

- src/raymath.h
This PR adds two function in the [raymath.h](https://github.com/raysan5/raylib/blob/master/src/raymath.h) header:
```c
bool Vector2LineIntersect(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, Vector2* pointIntersection)
```
```c
bool Vector2SegmentIntersect(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, Vector2* pointIntersection)
```
If the second one is true, the first one is always true.
The first one check if two lines A and B defined by their points, so that A is defined by (p1, p2) and B is defined by (p3, p4) intersect. If it's true, it put the intersection point in the *Vector2\* pointIntersection* parameter, if it's not NULL.
Which corresponds to this image for example:
<kbd>
</kbd>
</br>
The second one check if two segments A and B defined by their points, so that A is defined …
> [Math Feature]: Add two functions for Vector2 to know if two lines intersect and two segments intersect

- src/raylib.h
- src/shapes.c
Beziers in most graphics environments take 3 points for a finer control of the direction of the curve.
> Add Quadratic Bezier drawing

- BINDINGS.md
As i said, There are functions from raylib 2.5, I assume it's better to rename it to 2.4-dev instead of 2.4
> Edited version of raylib-mruby to comply with 2.5 (Renamed to 2.4-dev)

- BINDINGS.md
Sorry for that, At least i'm correct now ;)
I found similarity with functions of raylib-cr so i guess it's 2.5-dev now!
Thanks ray!
> Again, Renamed version of raylib-mruby to 2.5-dev

- BINDINGS.md
[raylib-cpp](https://github.com/robloach/raylib-cpp) now targets raylib 3.5.0 as of [raylib-cpp 3.5.0-alpha1](https://github.com/RobLoach/raylib-cpp/releases/tag/v3.5.0-alpha1).
> Update raylib-cpp to state that it targets 3.5

- BINDINGS.md
[raylua v3.5a](https://github.com/TSnake41/raylib-lua/releases/tag/v3.5a) has been released
> TSnake41/raylib-lua updated to 3.5

- src/textures.c
The use of ImageDrawRectangle to clear an image is very slow. It makes a new image, draws it, and then destroys the image. This is not fast.
This PR changes ImageClearBackground and ImageDrawRectangleRec to fill in the raw image data one pixel at a time (still doing data conversions per pixel), and is an order of magnitude faster.
> Faster version of ImageClearBackground and ImageDrawRectangleRec

- src/core.c
GetCurrentMonitor calls a function that returns the current monitor handle, not the index. This PR looks up that monitor in the monitor list to get the index so it can be used by other functions.
> fix GetCurrentMonitor to correctly lookup the monitor index

- src/core.c
This PR adds logic to compute the current monitor for non-full screen windows. The monitor that contains the upper left origin is returned.
> Add a current monitor function for window mode windows.

- src/raudio.c
This PR:
- Avoid dereferencing the *audioBuffer* pointer if it's NULL (which will crash the app), by returning earlier in the **LoadSoundFromWave** function.
> [Fix]: Avoid dereferencing a null pointer in the LoadSoundFromWave function

- src/models.c
This PR:
- Fix a dereferencing of a null pointer in the *LoadMaterials* function inside the *models* module.
(the **materials** pointer array is initialized to NULL, then used in a for loop to access it at *i* index).
> [Fix]: Avoid dereferencing a null pointer in LoadMaterials function

- src/core.c
This PR:
- Modify the check condition for the screen window height and width in this function for the *PLATFORM_DESKTOP* macro:
```c
static bool InitGraphicsDevice(int width, int height)
```
These values can't be less than zero because they are unsigned int. So we only need to check if they are equal to 0, not less than 0.
> [Cleanup]: Modify check condition less than zero for unsigned integers

- src/models.c
Resolves #1495
This line allocated some memory that was already allocated in the beginning of the function and was essentially creating a leak.
> Removed a repeating allocation of memory

- src/rlgl.h
This PR:
- Remove an unused condition in in *GenerateMipmaps* function if macro *GRAPHICS_API_OPENGL_11* is defined.
We don't need to check if the width or height are different to 1 in the while loop because it's actually the condition of the while loop.
> [Cleanup]: Remove unused condition 

- src/CMakeOptions.txt
- src/config.h.in
A few changes to include the SUPPORT_DATA_STORAGE flag option to make the `SaveStorageValue()` and `LoadStorageValue()` functions usable when building raylib with CMake.
> Include SUPPORT_DATA_STORAGE flag for building with CMake

- src/core.c
On Raspberry Pi DRM builds, keyboard state changes are rarely detected (if at all) by `IsKeyPressed(`) / `IsKeyReleased()`.
When a key is pressed or released, the input worker thread in `EventThread()` reads the event, maps the scan code to a keycode, then registers the keycode in `CORE.Input.Keyboard.currentKeyState[]`, setting it to 1 for pressed and 0 for released.
When the user’s application calls `EndDrawing()`, that in turn calls `PollInputEvents()`. One of the first things that `PollInputEvents()` does is copy `CORE.Input.Keyboard.currentKeyState[]` to `CORE.Input.Keyboard.previousKeyState[]`.
The input functions `IsKeyPressed()` and `IsKeyReleased()` are supposed to detect key state changes from frame to frame. They do this by comparing `currentKeyState[key]` with …
> Fix keyboard state change detection on RPI

- src/physac.h
Just reorder the code, no changes.
Why:
- It is logical to include typedefs in API part, they are directly used in examples
- It is in line with how raylib.h is
- It makes it easier to parse this file and separate only "header" part (relevant at least for wrappers)
> Reorder typedefs in physac.h to be in header part

- templates/simple_game/Makefile
- templates/simple_game/Makefile.Android.linux
Description
----------------
This PR corrects some build issues on Linux environments for building Android applications in templates/simple_game.
Fixes/improves:
- Automatically detects if host OS is Windows or Linux in the root Makefile, which avoids manual editing of the file to include 'Makefile.Android.linux' instead of Makefile.Android.
- Leave `ANDROID_HOME` and `ANDROID_TOOLCHAIN` with default values only if they do not already exist, which allows the user to add them as environment variables, and thus, Makefile-independent.
- Fixes `lib$(PROJECT_LIBRARY_NAME).so` builds: the generated library was configured to use the path of the NDK libraries instead of the native Android libraries.
> Fixes Android builds on Linux environments

- src/core.c
This PR fixes #1534 , handling both Unix and Windows paths starting with a slash/backslash.
> Fix absolute path handling in GetFileName and GetDirectoryPath (#1534)

- BINDINGS.md
[`node-raylib`](https://github.com/robloach/node-raylib) is now on raylib 3.5.0
> BINDINGS: Update node-raylib to 3.5

- cmake/GlfwImport.cmake
This PR fixes an issue where raylib would build as a shared library regardless of the value in `BUILD_SHARED_LIBS`. This was due to a simple syntax mistake in `cmake/GlfwImport.cmake`.
> Fix issue when trying to build raylib statically

- src/core.c
GLFW was included using #include <GLFW. This tells the compiler to check the system library paths for the header. Raylib includes it's own GLFW so it should be using #include "GLFW.
This PR makes this change, and helps some platforms produce fewer errors/warnings.
> Use local includes for GLFW 

- examples/shaders/resources/shaders/glsl330/color_mix.fs
out is a keyword in shaders and can't be used as a variable name.
This PR changes it to outVal so it compiles.
> [Shaders] Fix compiler error in GSSL 3 version of color_mix_shader

- src/core.c
This PR forces Joystick initialization before the window is created and shown on Desktop platforms, to avoid long first frames as in #1554.
> Fix initialize GLFW's Joystick before window is created on Desktop platforms (#1554)

- src/core.c
#1294 fixed the issue that toggle fullscreen changes the screen size because of the WindowSizeCallback. The proposed edit by @raysan5 was to comment out WindowSizeCallback which I essentially simplified to disable the callback around the set window monitor functions.
The developers using the ToggleFullscreen function should be aware that they need to size the screen correctly on that same frame. Otherwise they should check if fullscreen and size properly using the GetMonitorWidth and GetMonitorHeight functions.
> Disabling WindowSizeCallback around fullscreen toggle.

- BINDINGS.md
It looks like the Harbour bindings disappeared? Did they exist at one point?
> BINDINGS: Remove Harbour

- src/core.c
This should hopefully slightly reduce input latency when raylib is manually limiting the frame rate of the application. I don't have any concrete numbers, but using the slow mo mode on my camera and running the `core_input_mouse` example it does look like the ball stays slightly closer to my mouse cursor.
> Poll inputs after frame sleep

- src/core.c
The current implementation of the EventThread for the Raspberry Pi doesn't resolve isMouseButtonPressed/Up/Down() neither does it updates the position if using GetTouchPosition(int) if using a touchscreen 
This PR attempts to solve this shortcomings by adding some extra logic: 
-It checks the absolute pressure in the screen in an absolute event to simulate a touch action or a left mouse click.
-Updates the touch position at index 0 on absolute events.
This fixes #1585
> Fix support of touchscreens for RPI

- src/external/jar_xm.h
- src/raudio.c
Made changes to raudio to fix issues with `LoadMusicStream` and `UnloadMusicStream`.
Issues fixed:
- If a format is not valid or fails to load it is no longer assumed to be wav. This makes sure the correct unload call is made and makes the format clear to the user.
- Fixed crashing with invalid wav files when unloading. It was trying to use a callback where it shouldn't because it was not initialized to a zero value.
- Fixed crash in jar_xm when unloading a NULL ctxData.
> [raudio] Fix load and unload issues with Music

- examples/shapes/shapes_logo_raylib_anim.c
There was problem with using `IsKeyPressed`, In example code it uses `char` while `IsKeyPressed` takes an `int`.
However, This fixed!
> Fixed problem related to `IsKeyPressed` function!

- BINDINGS.md
While it is JavaScript, I'd rather this be named raylib-duktape since there are different implementations of javascript available. Like QuickJS, V7, or Node.js.
> Rename raylib-js to raylib-duktape

- src/models.c
The current glFT code assumes that the parent bone is always non null and that it can always compute an offset from it to the root bone. This is not always the case, some bones don't have a parent. If the parent bone node is null, this will compute a very bad offset and cause a segfault later in the code, because the offset is not checked against the bone list bounds.
This change only computes an offset for the parent if the bone is non-null, attaching all null parent bones to the root node.
> [models] make sure glTF parent bones are not null before trying to compute the offset from the root

- examples/network/network_tcp_client.c
- examples/network/network_tcp_server.c
- examples/network/network_udp_client.c
- examples/network/network_udp_server.c
- projects/VS2019/examples/network_ping_pong.vcxproj
- projects/VS2019/examples/network_resolve_host.vcxproj
- projects/VS2019/examples/network_tcp_client.vcxproj
- projects/VS2019/examples/network_tcp_server.vcxproj
- projects/VS2019/examples/network_test.vcxproj
- projects/VS2019/examples/network_udp_client.vcxproj
- projects/VS2019/examples/network_udp_server.vcxproj
- src/rnet.h
This PR includes fixes to make rnet and it's examples build on Windows in visual studio 2019.
Mostly typecasts, and some int to unsigned short changes, and including the windsock 2 library in the examples.
There are still some warnings in rnet.h but they may be due to the fact that Winsock2 and Berkley sockets are slightly different. I did not want to make any changes that would break Linux/MacOS builds.
> [rnet] fixes for VisualStuido 2019 builds

- src/models.c
Few fixes here:
- Add support for u8 bone indicies when loading glTF animations
- Fix a potential segfault when interpolating glTF animations when a given channel has it's first keyframe timed not at 0s.
- Ensure we respect the parent hierarchy for nodes when loading glTF animations, regardless of the order as provided in the nodes list.
I've tested this in a personal project on windows, but no other platforms as yet, using some kenney.nl assets that were exported as glTF from the source blend files. I suspect that there's more that could be done here, but this should help patch up a couple of common issues, glTF seems to support cameras, multiple scenes each with multiple models in, and at the moment we're just reading the raw nodes list which would contain everything. This is probably …
> Patch up GLTF Skeleton loading

- src/raudio.c
Fixing compiler warning for passing (unsigned char*) to (const char*)
> jar_xm_create_context_safe requesting const char*

- src/raymath.h
This commit add a check to `QuaternionSlerp()` which inverts one of the quaternions if they are inverted to each other (same rotation, just all components are negative)
The check is outlined here in the other issues section on this page.
https://www.euclideanspace.com/maths/algebra/realNormedAlgebra/quaternions/slerp
Three.js has this exact same check in their slerp function, so I'm guessing this is the standard way to do this in graphics focused stuff.
> Add check to flip quaternion

- BINDINGS.md
the vraylib binding from  MajorHard doesn't seem to be getting any updates, so maybe replace it with the working fork?
> replace vraylib link

- src/core.c
This PR makes some small fixes to ToggleFullscreen to make it work in a more understandable manner.
- Always try to restore vsync
- Use the internal  GetCurrentMonitor instead of glfw so it picks up the current monitor corner.
Note that this does not change how ToggleFullscreen handles resolution. It will still attempts to change the display resolution to match the window size.
Users that want to toggle fullscren to the monitor size should use code similar to this.
> [core] minor fixes to Toggle Fullscreen

- src/core.c
- src/raylib.h
Fixes #1294
Uses not yet submitted pull request of @JeffM2501 - #1636 
Modified how fullscreen gets toggled.
- Removed the unsetting and setting of the resize callback function. Instead of that I moved the fullscreen flag setting into a more correct place before setting the fullscreen so that this flag can be used in the callback.
- In the resize callback now window size is only set when it is not fullscreen resulting in preserving the window size.
- When going fullscreen the larges resolution is used so that there are no problems of the type when you minimize the window you cannot use anything else in your desktop because the resolution might be too low. If a low res effect is desired one should use render texture (this is the approach all game engines use).
@raysan5 This should yield …
> Fix fullscreen resolution

- src/models.c
- src/raylib.h
@raysan5 Is this what you meant by UnloadModelAnimations for #1523 . 
We don't have a structure that you can pass in with the count of animations so it must go with a count parameter. Else we would need a breaking change to return a structure with ModelAnimations array and count.
> Implement UnloadModelAnimations

- BINDINGS.md
I just updated dray to bind to the raylib 3.5 api.
https://github.com/xdrie/dray
> Update dray bindings version to 3.5

- BINDINGS.md
Both PHP extensions support RayLib 3.5
> raylib-php && raylib-phpcpp support 3.5

- examples/shapes/shapes_draw_circle_sector.c
- examples/shapes/shapes_draw_ring.c
- src/raylib.h
- src/shapes.c
Here's a nice simple one. The angle params for DrawRing and DrawCircleSector were ints so precise fitting wasn't possible. I've changed them to floats which solves the problem - they get converted to float in the functions anyway. Related examples updated and checked. Good to go.
> Improved accuracy for DrawRing and DrawCircleSector angles

- src/shapes.c
- src/textures.c
- Add check so rotation is only applied if rotation != 0.0f.
- Replace matrix usage by calculating the vertex data directly.
> Optimize DrawTexturePro and DrawRectanglePro transformations

- src/core.c
This appears to fix the issue with macOS windows opening with the wrong viewport size/scale by ensuring that the open gl viewport is set in the coordinate space of the underlying window which may have a different scale factor. I do not know if this works on any other platforms, but it seems like it should.
> Possible fix for macOS windows opening with the wrong viewport size

- src/config.h
- src/raudio.c
Currently the audio device is forced to init at 44.1k and is only configuratable by a compile time config flag. This will not work well as not all devices support the same sample rates.
This PR forces MinAudio to init with a sample rate of 0 and then reads the effective sample rate from the device after it has been started.  Then this sample rate is used as the target for all sounds to minimize resampling during playback.
This PR changes no APIs, removes a config define and enhances playback quality.
> [AUDIO] Use device native sample rates

- src/raudio.c
- src/raylib.h
This PR makes some small changes to music looping to make it more consistent across sound types.
It adds functions to get/set the loop state music files, and for XM module files, correctly tells the tracker to loop the sample generator.
XM files are then no longer tracked by sample count, but allowed to loop infinitely using data provided by the tracker.
Because of this the GetMusicTimePlayed function now has special logic for XM files that will use the modulo of the samples played to track the relative time from start regardless of how many loops the tracker has generated.
With this change XM files are no longer brute force restarted for loops, allowing the music file to process the loop as it was written (using a jump table)
> [AUDIO] Music Looping enhancements

- examples/core/core_input_gamepad.c
- examples/core/core_input_gestures.c
- examples/core/core_input_multitouch.c
- examples/core/core_scissor_test.c
- examples/core/core_vr_simulator.c
- examples/core/core_window_flags.c
- examples/core/core_window_letterbox.c
- examples/core/core_world_screen.c
- examples/models/models_cubicmap.c
- examples/models/models_first_person_maze.c
- examples/models/models_material_pbr.c
- examples/models/models_mesh_picking.c
- examples/models/models_skybox.c
- examples/shaders/shaders_postprocessing.c
- examples/shaders/shaders_rlgl_mesh_instanced.c
- examples/shaders/shaders_simple_mask.c
- examples/shaders/shaders_texture_drawing.c
- examples/text/text_font_loading.c
- examples/text/text_font_sdf.c
- examples/text/text_font_spritefont.c
- examples/text/text_raylib_fonts.c
- examples/text/text_rectangle_bounds.c
- examples/text/text_unicode.c
- examples/textures/textures_bunnymark.c
- examples/textures/textures_draw_tiled.c
- examples/textures/textures_mouse_painting.c
- examples/textures/textures_sprite_button.c
- examples/textures/textures_sprite_explosion.c
- projects/VS2019/examples/core_custom_logging.vcxproj
- projects/VS2019/examples/core_input_gestures.vcxproj
This PR fixes warnings in several examples in visual studio 2019
> [Examples] Warning fixes (pt 1)

- src/Makefile
Description
----------------
The Raylib root Makefile for `PLATFORM=PLATFORM_WEB` is assumed to run in Windows environments, which makes it incorrectly set the PATH variable, so Linux (and possibly other) environments are not able to find binaries from EMSDK_PATH.
Fix this by checking which PLATFORM_OS and configure PATH accordingly.
> Makefile: Fix PATH for other PLATFORM_OS's

- src/raymath.h
Optimization to avoid unnecessary `sqrt` calls in `MatrixRotate` when `axis` vector is already unit length or the zero vector.
> Don't call sqrtf when axis already normalized

- src/shapes.c
- src/textures.c
- The vertices did not map to where I expected causing rotation to be
off by 90 degrees. I reorganized the vertices making it easier to
reason about which fixes this.
- The order for drawing is now topLeft, bottomLeft, bottomRight,
topRight.
> Fix 90 degree bug with DrawTexturePro and DrawRectanglePro

- src/rlgl.h
Thanks for this nice project!
`RLGL.State.activeTextureId` is used in for-loop like that:
```C
for (int i = 0; i < MAX_BATCH_ACTIVE_TEXTURES; i++)
{
if (RLGL.State.activeTextureId[i] > 0)
{
glActiveTexture(GL_TEXTURE0 + 1 + i);
glBindTexture(GL_TEXTURE_2D, RLGL.State.activeTextureId[i]);
}
}
```
So the size of `RLGL.State.activeTextureId` should be MAX_BATCH_ACTIVE_TEXTURES.
I'm using raylib to run a Neural Network on the Raspberry Pi GPU using GLSL shaders. So I needed to increase MAX_BATCH_ACTIVE_TEXTURES.
> Fix activeTextureId to have MAX_BATCH_ACTIVE_TEXTURES elements instead of the hardcoded 4

- src/text.c
This PR makes the default FPS display change colors based on the actual FPS values.
FPS >= 30 = Green (good FPS)
FPS < 30 and FPS >= 15  = Orange (not great FPS)
FPS < 15 = Red (Bad FPS)
> [Text] Have FPS colors change based on good/bad FPS values

- src/shapes.c
The `Rectangle` version of `DrawRectangle` is `DrawRectangleRec`, and it preserves non-integral floating point values that are passed to it without truncating them.
The `Rectangle` version of `DrawRectangleLines` is `DrawRectangleLinesEx`, and it casts all of the floating point values passed to it  to integers before forwarding them to `DrawRectangleRec` (which is perfectly capable of handling floats, as noted above).
This causes a bug in the public API where it's impossible to outline a rectangle drawn with `DrawRectangleRec` with lines drawn by `DrawRectangleLinesEx` due to the truncation. For example, the outline will jitter around when drawn on top of a smoothly animated rectangle.
The fix is to simply preserve the floating point precision. I've left the intentional truncation in the …
> Preserve floating point values in DrawRectangleLinesEx

- src/rlgl.h
When building with cmake I get:
```
raylib/src/core.c:136:
raylib/src/rlgl.h: In function ‘rlDrawVertexArrayElements’:
raylib/src/rlgl.h:3121:67: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
3121 |     glDrawElements(GL_TRIANGLES, count, GL_UNSIGNED_SHORT, buffer + offset);
|                                                                   ^
raylib/src/rlgl.h: In function ‘rlDrawVertexArrayElementsInstanced’:
raylib/src/rlgl.h:3134:76: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
3134 |     glDrawElementsInstanced(GL_TRIANGLES, count, GL_UNSIGNED_SHORT, buffer + offset, instances);
```
So I'm fixing up pointer arithmetics in those functions. Note that they were previously used always with offset 0.
```
raylib/src$ grep -R …
```
> Fixing pointer arithmetic to avoid error [-Werror=pointer-arith]

- src/models.c
###Reason for the change
The current code is wrong and will cause bugged ray-mesh detections in meshes with shared vertices. 
###Example
If we make use of the GetMeshCube function (where we have 12 triangles but 24 vertices)  there's going to be 4 triangles (2 faces) which are not going to be taken into account for the collision check.
###Comments
I'm not sure on which case the mesh will be intialized without a triangle number but that (in my opinion) should be a problem of the code initializing that mesh and it should not be remedied in the collision check function.
> GetCollisionRayMesh makes use of triangle count

- src/raylib.h
- src/utils.c
The `SaveFileText` and `SaveFileData` callbacks returned `void`, which loses out on whether or not the save was successful. If a save failed, the callback would still return `true`. This change makes it so that those callbacks report the output directly so that you correctly know when a save failed.
> Make SaveFile* callbacks return a boolean

- examples/shapes/shapes_draw_circle_sector.c
- examples/shapes/shapes_draw_ring.c
- src/shapes.c
There's a hard-coded restriction on the minimum number of segments in DrawRing, DrawCircleSector etc. It's a problem when you need to draw small sectors, e.g. 10 or 20 degrees. These only require 1, 2 or 3 segments (depending on radius) but they're forced to use 4 which is significantly more resource-hungry than necessary.
This change sets the minimum number of segments based on the degree range. I have also updated related examples.
I present this solution but actually prefer having no logic other than the check for zero to trigger the auto calculation. What do you prefer? I'm happy to rework it.
> Circle sector minimum segments

- src/external/stb_vorbis.h
without this modification, I couldn't get raylib running on macos catalina due to alloca being undefined
> added import in order for alloca to work on macos

- src/textures.c
The `ImageClearBackground` implementation in current master skips over some pixels in the image.
The fix is simple - the y-coordinate of each cleared pixel was calculated in the loop as `i/dst->height`, but needs to be `i/dst->width`.
```c
int main(void)
{
InitWindow(640, 480, "Example");
Image image = GenImageColor(320, 160, BLUE);
ImageClearBackground(&image, RED);
Texture texture = LoadTextureFromImage(image);
while (!WindowShouldClose())
{
DrawTexture(texture, 0, 0, WHITE);
EndDrawing();
}
UnloadTexture(texture);
CloseWindow();
}
```
Current master:
With fix:
> Fix ImageClearBackground

- src/core.c
Found testing `core_input_gamepad`. The last axis was not drawn.
I found that `GLFW_GAMEPAD_AXIS_LAST` is defined to the last axis which is 5
not the total number of axes which is 6.
See GLFW docs for reference:
https://www.glfw.org/docs/latest/group__gamepad__axes.html
> Fix off by one bug with GetGamepadAxisCount on PLATFORM_DESKTOP

- cmake/LibraryConfigurations.cmake
- src/models.c
A couple minor changes I needed to enable cross compiling     
raylib DRM platform in a Yocto/BitBake environment.           
First issue I encountered was dealing with unused result from `chdir()` in `LoadOBJ()`.
>  warning: ignoring return value of 'chdir', declared with attribute warn_unused_result [-Wunused-result]
I just tossed in a `LOG_WARNING` if something went wrong.     
Also noticed that it was using `chdir()` directly, which seemed to conflict
with the `#define CHDIR _chdir` setup happening here:
https://github.com/raysan5/raylib/blob/d17c519f88ff33084772263f4585a96051c45cfa/src/models.c#L53-L59         
So I also converted it to use `CHDIR()` instead.              
The next issue was related to CMake.                          
The DRM platform was using …
> Enable DRM platform cross compilation support

- templates/simple_game/Makefile.Android.linux
This PR attempts to update the Android-Linux makefile on the template project so it runs with the latest state of tooling and version.
- added Android NDK reference in order to use their binaries at a few points.
It seems some linked bins and sources were using local or other folders that either do not contain those binaries or moved in recent updates.
- corrected a few architecture related binary file references to the correct files
- added CC/AR definitions to x86 / x86_86
- swapped the order of zipaligning and signing
With the original order I was getting a lot of aligning errors and digging on error reports it seems zipaligning has to be done on the unsigned apk just before signing
- changed signing from jarsigner to apksigner as the former one is not supported anymore
- minor shell …
> Update and fix Android Linux makefile sample for template project

- examples/text/resources/shaders/glsl330/sdf.fs
The signed distance field text rendering example uses a fixed "smoothing" value in the shader. This only works well for one specific zoom level and becomes blurry for others. This PR replaces that with a calculation to always get a sharp text outline regardless of the zoom level. This is based on how much the distance to the outline changes from fragment to fragment (aka local derivatives, dFdx, dFdy).
Unfortunately dFdx and dFdy are optional for GLSL 1.00 and I can't test the GLSL 1.00 shader. Without local derivatives a zoom independent "smoothing" value could be calculated as `FONT_SDF_PIXEL_DIST_SCALE / 255.0f * drawScale` (I think). Where `drawScale` would be 1.0 if the font is drawn 1:1 and 2.0 when the font is drawn twice as large as the distance field. `drawScale` could be …
> [examples] Added zoom independent sharp edges to the SDF text example

- examples/models/models_mesh_generation.c
This PR adds a custom mesh to the mesh generation example to show users how to define allocate, define, and upload a mesh from pure code.
> [Examples] Add a custom mesh to mesh generation example

- BINDINGS.md
https://github.com/RobLoach/raylib-cpp/releases/tag/v3.7.0
> BINDINGS: raylib-cpp targets raylib 3.7.0

- src/core.c
Window shouldn't be considered ready when CloseWindow has been called.
> Unset CORE.Window.ready on CloseWindow

- src/config.h
- src/core.c
This PR changes the default "HALF BUSY WAIT" loop to be a "PARTIAL BUSY WAIT" loop. In cases where there is a target FPS set, it will sleep for some fraction of the target frame time before doing a busy loop at the end. By default it will sleep for 95% of the frame time and spin wait for the last 5% for accuracy.
This helps reduce CPU spin load in the default build but still allows for the accuracy of a spin wait.
In cases where there is no target FPS, the code works exactly like it used to, sleeping for 4ms max.
The user can configure the sleep percentage with a #define as needed.
> [CORE] Better default sleep/busy loop ratio

- src/rlgl.h
I was updating raylib for vita and i found a little problem. 
Raylib had in older versions a check for vao extension in rlUploadMesh now the code is refactorized in uploadMesh at model.c using calls to rlLoadVertexArray and rlEnableVertexArray.
rlEnableVertexArray has the vao extensin check, but rlLoadVertexArray doesn't so to avoid the crash check for vao extension must be added.
Regards
> check for vao extension

- .gitignore
- examples/audio/audio_raw_stream.c
- examples/core/core_3d_picking.c
- examples/core/core_input_mouse.c
- examples/core/core_input_multitouch.c
- examples/models/models_loading.c
- examples/models/models_mesh_generation.c
- examples/physics/physics_demo.c
- examples/physics/physics_shatter.c
- examples/shaders/shaders_hot_reloading.c
- examples/shaders/shaders_julia_set.c
- examples/shapes/shapes_lines_bezier.c
- examples/shapes/shapes_rectangle_scaling.c
- examples/text/text_draw_3d.c
- examples/text/text_rectangle_bounds.c
- examples/text/text_unicode.c
- examples/textures/textures_bunnymark.c
- examples/textures/textures_draw_tiled.c
- examples/textures/textures_image_generation.c
- examples/textures/textures_image_processing.c
- examples/textures/textures_mouse_painting.c
- examples/textures/textures_sprite_button.c
- examples/textures/textures_sprite_explosion.c
- projects/VS2017.UWP/raylib.App.UWP/App.cpp
- src/camera.h
- src/core.c
- src/raylib.h
Changes Tested on Windows 10 using the `core_input_mouse example`.
On my mouse:
MOUSE_SIDE_BUTTON is Mouse 4
MOUSE_EXTRA_BUTTON is Mouse 5
I could not test the MOUSE_FORWARD_BUTTON and MOUSE_BACK_BUTTON keys as my mouse doesn't have them, but I added support for it anyways. 
Build tools: 
mingw32-make --version
GNU Make 4.2.1
gcc --version
gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
> Added support for additional mouse buttons

- src/CMakeLists.txt
Updated to fix versioning and linking issues.
Old version would cause examples to not be linked on fresh raylib install or linked with an old library version on updated raylib install.
> Updated raylib CMake project version to 3.7.0

- projects/VS2017.UWP/raylib.App.UWP/raylib.App.UWP.vcxproj
- projects/VS2017.UWP/raylib.UWP/raylib.UWP.vcxproj
- projects/VS2017/raylib/raylib.vcxproj
- projects/VS2019/raylib/raylib.vcxproj
This PR was prompted by trying to link the x64 Windows release with LLVM's linker.
Using whole program optimization generates lib files with a different file format that is not compatible with any other linker than the one included with the MSVC version used to create them. This means that the library is incompatible even with different MSVC versions. See (specifically the third point): https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-160#restrictions
I removed whole program optimization from all Visual Studio projects, please tell me if I missed any.
I am not sure how the releases are made, if they get their configuration from elsewhere this has to be changed there as well.
Note that this change will result in an ~15% larger library.
> Removes Whole Program Optimization

- src/models.c
boneWeights uint32 were loaded in normals instead of boneWeights.
> Fixed GLTF boneWeights uint32 loading

- examples/core/core_2d_camera_smooth_pixelperfect.c
Fixed an if-statement which caused lag while moving the camera. Should be perfect now.
> Hotfix for smooth pixel-perfect camera example [core_2d_camera_smooth_pixelperfect.c]

- src/models.c
output->framePoses[frame] is over-allocated.
framePoses is a 2D array:
- first dimension: frames (allocated l. 4717)
- second dimension: nodes (allocated l. 4731)
Second dimension should be allocated of nodes_count transformations only.
> Fixed over-allocation of buffer

- projects/VS2017/raylib/raylib.vcxproj
- projects/VS2019/raylib/raylib.vcxproj
This halves the size of the distributed binary in addition to removing some linker warnings when the debug symbol database is not distributed with the binary.
> Removes debug information from release builds

- projects/CMake/CMakeLists.txt
The CMake project template didn't link to the required libraries for macOS, causing the build to fail. I added calls to include the IOKit, Cocoa, and OpenGL libraries in the CMake template for those who are building on macOS.
> Fixed CMake project template for MacOS

- cmake/GlfwImport.cmake
GLFW versions under 3.3.3 do not support MacOS 11, so I've bumped it in the CMake file
See issue #1787
> Bumped minimum GLFW version in cmake

- parser/raylib_parser.c
Fixed a bug that was causing struct 27: AudioStream to be malformed. Before the fix it looked like this:
```
Struct 27:  (6 fields)
Fields 1: ypedef struct rAudioBuffer rAudioBuffer 
Fields 2:   
Fields 3: rAudioBuffer * buffer // Pointer to internal data used by the audio system
Fields 4: unsigned int sampleRate // Frequency (samples per second)
Fields 5: unsigned int sampleSize // Bit depth (bits per sample): 8, 16, 32 (24 not supported)
Fields 6: unsigned int channels // Number of channels (1-mono, 2-stereo)
```
After the fix it is properly parsed:
```
Struct 27: AudioStream (4 fields)
Fields 1: rAudioBuffer * buffer // Pointer to internal data used by the audio system
Fields 2: unsigned int sampleRate // Frequency (samples per second)
Fields 3: unsigned int sampleSize // Bit depth …
```
> Small parser bugfix

- parser/raylib_parser.c
Fixed a bug that was causing the Matrix fields to be of type `float m0, m4, m8,`. Now the type is parsed correctly and the field name is `m0, m4, m8, m12`.
> Fix parsing multiple struct fields defined in one line (Matrix struct)

- cmake/GlfwImport.cmake
In the new upgrade glfw no longer has a target glfw_objlib to take the sources from and build them in raylib. We directly take the sources from glfw now (which should bring the same meaning).
> Fix build issue with cmake after glfw upgrade

- projects/Geany/raylib.c.tags
- projects/Notepad++/c_raylib.xml
- projects/Notepad++/raylib_npp_parser/raylib_npp.xml
- projects/Notepad++/raylib_npp_parser/raylib_to_parse.h
The MeshBoundingBox function does not exist, so I've renamed some of the occurences of the function to GetMeshBoundingBox.
> Rename relevant occurences of MeshBoundingBox to GetMeshBoundingBox

- src/external/tinyobj_loader_c.h
Missing fclose in tinyobj loader.
> Fix missing fclose in tinyobj loader

- src/core.c
Hi, 
I was trying to use raylib in an application where I wanted the canvas to be able to be dynamically resized (so that it could cover the entire web page), and I noticed that the support for this was only partially implemented in raylib (and commented out). 
So, I went and finished the rest of it and got it working. I hope this is helpful. 
Thanks, for making a great library.
> Add support for resizing Emscripten canvas

- src/core.c
This is a simple change to allow calling `SetWindowSize()` on web. The recent change https://github.com/raysan5/raylib/commit/9095dd9e82b6be2b4ab477deaea6fe4634d1583c was a good step forward but in my testing I found that on macOS there were some issues with high-dpi due to not multiplying by `devicePixelRatio`. If `SetWindowSize()` is exposed the user can still directly set the desired canvas size multiplied by `devicePixelRatio`. Here is a comparison (first doesn't use `devicePixelRatio`, second does, and last is a comparison of the two screenshots side-by-side at the same zoom level):
Regardless of the dpi issues just providing access to `SetWindowSize()` lets the user manage this themselves and also apply other custom size behavior so it seems useful.
This would solve …
> Allow SetWindowSize() on web

- src/core.c
Just a simple fix - the LoadShaderFromMemory function almost matches LoadShader, except that the "matNormal" uniform location isn't fetched.
This breaks the lighting in the simple lighting sample (if we switch out the use of LoadShader for LoadShaderFromMemory).
> fix to LoadShaderFromMemory

- src/core.c
#1854 This issue also exists in the `DecompressData()` function.
> Fix DecompressData() pointer issue

- src/models.c
This is a better fix for issue #1876 and the GenMeshTangents function in general. 
The function was assuming that the mesh had already been uploaded to the GPU and was attempting to access the vboId field without ever verifying that it had actually been allocated.
Additionally if the vboId has been allocated, and the tangents already have a vertex buffer, instead of releasing the old one and creating a new one, this now simply updates the existing buffer.
> [Models] Better Fix for GenMeshTangents issue #1876

- BINDINGS.md
This PR modifies the bindings file to be less confusing for C++ users.
Raylib is noted as working with C and C++ directly, because it does.
Raylib-cpp has been moved into a Utility Wrapper section since it is not a traditional language binding (it is not required in order to use raylib with C++) but simply an optional conversive wrapper.
> Clarify raylib and raylib-cpp in bindings file

- src/config.h
- src/utils.c
**UWP** is not available on `master` branch anymore so these definitions don't do anything. 
I'm curious if stating *Raylib* supports **UWP** on `raylib.h` is still ok since a branch does exist with the platform supported?
> Remove unused UWP defines

- src/raymath.h
This PR prevents Vector2Normalize from dividing by zero like Vector3Normalize does.
> Don't normalize zero length vectors.

- src/core.c
Just a small fix that may be a hack, haven't tested on more than just my machine yet, but it seems harmless enough
> fixed DisableCursor() on web by registering an empty mouse click event

- .gitignore
- examples/Makefile
- Add --preload-file flag before specifying the resource dir
- Add empty resource dir to `shapes/` (otherwise wasm-ld will fail)
- Add wasm outputs to .gitigore
> Fix Makefile to build WASM examples.

- src/raylib.h
I think it is useful to know what the empty behavior is in cases where
you are enumerating key presses (e.g. implementing "press any key to
continue").
> Document Get{Key,Char}Pressed return value.

- .gitignore
When building a shared Raylib library on Linux, the build process
produces 3 files: libraylib.so (symlink), libraylib.so.381 (symlink)
and libraylib.so.3.8.1 (the library).
Only the first one of these (.so) is currently ignored by Git.
Adding \*.so.\* to .gitinore makes Git ignore the rest of them as
well.
> Add *.so.* to .gitignore to ignore build artifacts

- src/external/stb_image.h
- src/textures.c
This allows to compile raylib with tcc with no errors.
> Fix tcc not finding emmintrin.h

- src/models.c
This part of the code from [LoadOBJ](https://github.com/raysan5/raylib/blob/68bcfa119243e716eaf00ffe521d0358c084b74f/src/models.c#L3494) seemed to be out of date with how tinyobj handles meshes.
https://github.com/raysan5/raylib/blob/68bcfa119243e716eaf00ffe521d0358c084b74f/src/models.c#L3545-L3553
Now the correct count of faces for each material is calculated. I tested this on different models, and it seems to work for different amount of objects and materials.
The new version simply iterates over the faces and gathers information that way.
```c
for(int fi = 0; fi< attrib.num_faces; fi++){
tinyobj_vertex_index_t face = attrib.faces[fi];
int idx = attrib.material_ids[fi];
matFaces[idx]++;
}
```
This is fixing  #1966
And I also added a comment above the function, which will maybe help …
> [models] Fixed counting loop for face amount per material in `LoadOBJ`

- src/models.c
I found the issue with the transforms. `LoadGLTFNode` assumed that every single transformation would automatically be saved in to the matrix, but this wasn't the case. I added the missing transforms with checks if they exist to ensure that all the transforms are applied on Load.
Heres a file that I used for testing which has all things that
[all_test.zip](https://github.com/raysan5/raylib/files/7071277/all_test.zip)
Currently a problem remains with the bones that the vertex data is already transformed on meshes that are a child of a bone structure, which results in the transformation being applied twice.
There is some further information on this transform in the glTF file because sites like https://www.gltfviewer.com/ load the file perfectly fine.
But I really don't know where to find …
> [models] LoadGLTF fixed missing transformations and nonroot skinning problem

- src/Makefile
On my system, when linking against the 3.7.0 binary downloaded library, the name recorded inside the library is `libraylib..dylib` instead of `libraylib.370.dylib` as the installed symlink is named.
This is due to the use of `$VERSION` which is not set inside the Makefile. I think this was a typo, because there is no symlink built that uses that name.
The binary download for 3.0.0 works fine, but when I build locally 3.0.0, the same problem occurs. I feel the person who generated the raylib binary release must have hand-fixed the issue for the 3.0.0 version, but not the 3.7.0 version.
In addition, adding the `@rpath/` prefix allows you to use DYLIB_LIBRARY_PATH or LD_LIBRARY_PATH to refer to the dynamic library. If you look at the 3.0.0 binary release, it has this prefix in it.
For sure …
> Fix dynamic library issues on Macos

- src/models.c
Just quick fix to update `matFace` to the correct value when no materials are present on the mesh.
> [models] Fixed loading OBJ models with no materials.

- src/camera.h
Previous mouse position was initialized to (0, 0) and caused camera direction vector to move first time scene initializes.
Watch the difference on a core_3d_camera_first_person example.
> Fixes camera direction for first person camera mode.

- src/core.c
When building for HTML the GetGamepadName() function currently returns null:
This implements that function by capturing it when the device is detected from the gamepadEvent object. Now the name will return correctly:
> Implemented GetGamepadName() for emscripten

- src/extras/rnet.h
i got an error because of this
so pls
> Prevent INVALID_SOCKET to be defined twice on linux

- src/core.c
- src/raylib.h
This is a proposal for a new public API function `SetRandomSeed(unsigned int seed)`.
**Rationale:**
Specifying a fixed seed for the random number generator is often used in games for various reasons, for example when replaying the same randomly generated world or when competing in games that are random by nature (and the random element is undesired).
By adding an API function for seeding the random number generator we solve two different problems regarding the use case:
**1.** The underlying RNG implementation does not leak to client code (as would be the case if we called `srand` directly from the client code). This prevents client code from breaking in the case where the implementation would change.
**2.** Seeding the RNG would be possible and simple from other programming languages …
> Add SetRandomSeed(unsigned int seed) function

- src/raylib.h
- src/rmodels.c
LoadModelAnimations takes an `int` for the animation count parameter.
The animation count should never be negative, so it makes sense to
specify it as unsigned in the API. This matches the API for
UnloadModelAnimations, which expects an unsigned int. Both GLTF and IQMM
also store the animation count internally as unsigned, and we were
casting to a signed int for no reason.
GLTF actually uses `size_t` internally, so we're technically risking
overflow, but having 2^32 animations seems unlikely.
> Use unsigned int for animation count.

- src/raudio.c
- src/raudio.h
- src/raylib.h
This function allows you to seek into a position in seconds on a music stream, something commonly used for music player programs to allow you to get to a certain point of your tune.
Unfortunately it does not support *module-based* formats **(.XM, .MOD)** as they work pretty differently than most others and did not have functions for seeking anyways. (Even the functions for going back to the start are an addition from **Ray** too anyways)
Any _feedback_ (heh!) would be greatly appreciated, specially as this function could prove quite useful to many.
> `SeekMusicStream` function

- src/raudio.c
`SeekMusicStream` did not update the frames being processed, resulting in looping malfunctioning. This PR fixes this + adding a line to return from the function if the format trying to be seeked is a Module one, as they do not have support for seeking.
> Fix + Module format return for `SeekMusicStream`

- .gitignore
- src/build.zig
@raysan5 as discussed on Discord:
This commit adds a `build.zig` file in `src/` which can be used by the Zig build system to build Raylib. In it's current form it's able to build Raylib into a static library for Windows and Linux.
This has been tested with Zig 0.8.1 in WSL2 on a Windows machine.
How to use:
`cd src/`
`zig build`
This produces a debug build in `src/`. Add one of the following switches to `zig build` command to specify release build type:
`-Drelease-small=true`
`-Drelease-safe=true`
`-Drelease-fast=true`
The Zig compiler has first class support for cross-compilation. Here are some cross-compilation
Cross-compilation examples:
To windows target:
`zig build -Dtarget=native-windows-gnu`
To linux target:
`zig build -Dtarget=native-linux-gnu`
> Add Zig build file

- src/rlgl.h
The intention behind rlCheckRenderBatchLimit is to occasionally call it to ensure buffer space is available for the next set of vertices to be sent, however if that threshold is reached and rlDrawRenderBatch called to draw existing buffers, the state of all draw batches is reset to default (RL_QUADS and default texture).
This means calling code needs to call rlBegin / rlSetTexture after each rlCheckRenderBatchLimit which returned true; proposed fix automatically restores mode and texture of the active batch so calling code won't need to care if batch did overflow or not.
> [rlgl] restore draw batch state after limit check

- src/rcore.c
With new emscripten callbacks, resizedLastFrame is now set on web platform but is never cleared. The fix resets the flag in PollInputEvents.
> [web] fix: reset resizedLastFrame

- src/external/vox_loader.h
- src/rmodels.c
`NOTE`: unused symbols have been deleted and the following report will show in what location they were previously.
Unused symbols:
- ArrayInt - vox_loader.h: line 84
- initArrayInt - vox_loader.h: line 168
- insertArrayInt - vox_loader.h: line 175
- freeArrayInt - vox_loader.h: line 186
- offsetX, offsetY, offsetZ - vox_loader.h: line 610
- chunkTotalChildSize - vox_loader.h: line 623
Other warnings:
- initialization discards 'const' qualifier - vox_loader.h: line 572
- incompatible types for VoxVector3 and Vector3 - rmodels.c: line 5748
- incompatible types for VoxColor and Color - rmodels: line 5749
> Supress most warnings on rmodels.c

- src/rcore.c
card1 is not always the the correct card to use on rpi4
rpi os finds the correct card and links it to /dev/dri/by-path/platform-gpu-card during boot.
this fix makes sure that we always point to the correct card on RPI4/CM4
> [rcore] fix rpi4 Failed to get DRM resources 

- src/rcore.c
Apologies @raysan5 , it looks like my fix for web resize has broken desktop resize, the flag needs to be cleared before polling events as it looks like those events actually set it.
Please kindly revert my fix and I will PR a proper one once I had a chance to test properly.
> Revert "reset resizedLastFrame on web platform (#2020)"

- BINDINGS.md
removed raylib-nelua because it's the same as nelua-raylib but with some significant improvements :smile_cat:
not to mention, nelua-raylib was added by me in the past #1890
> added nelua-raylib and removed raylib-nelua

- examples/models/models_loading.c
When trying to test some of my models, I noticed that .glb was missing from the extensions that it checks for upon dropping a file on the window. This PR also checks for the missing extensions.
> Add missing file extensions for drag-and-drop support

- BINDINGS.md
Because the repository and the author's GitHub profile doesn't exist anymore
> removed raylib-d

- BINDINGS.md
https://github.com/RobLoach/raylib-cpp/releases/tag/v4.0.0
> BINDINGS: raylib-cpp now targets raylib 4.0.0

- src/rtext.c
I was running the [core_input_gamepad](https://github.com/raysan5/raylib/blob/master/examples/core/core_input_gamepad.c) example program with a PS4 Controller and disconnected and reconnected the USB cable. The program crashed with a EXC_BAD_ACCESS (SIGSEGV). The SIGSEGV happens in [core_input_gamepad.c](https://github.com/raysan5/raylib/blob/3f595fda2613cf2620c1d8ed31506a72905ff170/examples/core/core_input_gamepad.c#L65) when [GetGamepadName](https://github.com/raysan5/raylib/blob/3f595fda2613cf2620c1d8ed31506a72905ff170/src/rcore.c#L3378) returns a NULL (when the gamepad is disconnected) and [TextIsEqual](https://github.com/raysan5/raylib/blob/3f595fda2613cf2620c1d8ed31506a72905ff170/src/rtext.c#L1141) attempts to compare two strings with one of them a NULL. TextIsEqual uses …
> Protect TextIsEqual from NULLs

- src/rlgl.h
Since 4.3 was added the commented out capabilities can be shown.
> [rlgl] Allow GL4.3 capabilities to be shown

- BINDINGS.md
I just updated it to 4.0. :) New version is looking spiffy!
> Add sol-vin/raylib-cr to bindings page. 

- .gitignore
- parser/Makefile
- parser/raylib_api.lua
- parser/raylib_parser.c
This PR adds LUA output format for parser. It's almost identical to JSON, only notable deviation is different function parameters format, for example in Lua:
```lua
params = {
{name = "rec", type = "Rectangle"},
{name = "color", type = "Color"}
}
```
while in JSON:
```json
"params": {
"rec": "Rectangle",
"color": "Color"
}
```
The motivation is quite simple: we cannot assume the order of object/table traversing which is crucial for things like function parameters. 
To speed up things a bit I also added Makefile which by default compiles parser and parses raylib.h in all 4 formats. Also you can call
```
make all
```
which parses raylib, raymath, all extras.
> Lua output format for parser

- BINDINGS.md
Sadly, [raylib-v7](https://github.com/Rabios/raylib-v7) is no longer being maintained as per their [README](https://github.com/Rabios/raylib-v7/blob/master/README.md).
> Move raylib-v7 to list of unmaintained bindings

- src/extras/physac.h
if `BUILD_LIBTYPE_SHARED` is defined allow build as a shared dll
This is as per a discussion on discord yesterday, on how to get physac working with C# bindings.
> allow physac to be built as a shared library

- src/raylib.h
- src/rcore.c
@raysan5 @lukekras 
This fixes https://github.com/raysan5/raylib/issues/2142
I've tested on a macbook with a 4k screen, but maybe a better solution would be to use the `GetRenderHeight` function here:
```c
if ((CORE.Window.flags & FLAG_WINDOW_HIGHDPI) > 0)
{
Vector2 scale = GetWindowScaleDPI();
rlScissor((int)(x*scale.x), (int)(CORE.Window.currentFbo.height - (y + height)*scale.y), (int)(width*scale.x), (int)(height*scale.y));
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
}
```
but we would need to change the implementation of GetRenderHeight to something like this:
```c
#if defined(__APPLE__)
Vector2 scale = GetWindowScaleDPI();
return CORE.Window.render.height * scale.y;
#elif
return CORE.Window.render.height;
#endif
```
I'm not entirely sure because I don't have everything in mind and I don't have …
> Fix scissor on macos

- src/raymath.h
functions use radians, making this awkward to use.
Per discussion on discord, raymath should always use radians. I found this one was left out by searching for `180` and `360`.
> Vector2Angle returns degrees instead of radians, but all other raymath

- src/raymath.h
This pull request fixes `Vector2Angle()` not working as expected. (https://github.com/raysan5/raylib/issues/2172, https://github.com/raysan5/raylib/pull/2193) 
Here's the animation of a simple example I made with the fixed version of `Vector2Angle()`: 
```c
float angle = Vector2Angle((Vector2) { .x = 1 }, Vector2Subtract(GetMousePosition(), SCREEN_CENTER)) * RAD2DEG;
```
> Fix Vector2Angle() not working as expected

- BINDINGS.md
I wrote a little auto-generated raylib bindings package for [GNU Guile](https://www.gnu.org/software/guile/)!
https://github.com/petelliott/raylib-guile
> Add raylib-guile to BINDINGS.md

- parser/raylib_api.json
- parser/raylib_api.lua
- parser/raylib_api.txt
- parser/raylib_api.xml
- parser/raylib_parser.c
This PR updates the API parser to parse the descriptions of enums and enum values. These were marked with TODOs before. Enum value descriptions especially have quite a lot of content that was missing from the parses.
> Parse enum descriptions and value descriptions

- src/external/jar_xm.h
Default was off, with no way to turn it on.
> Turn on interpolation for XM playback

- src/raylib.h
This PR adds a comment to LoadFontEx to specify how to get the default character set.
This is a common question on discord.
> Extend comment for LoadFontEx 

- src/Makefile
Justification: original comment said the following
"TODO: Add other platforms. Remove sudo requirement, i.e. add USER mode."
For the other platforms part, installing is included on unix-like systems, so for example Windows doesn't have a path where to install libraries.
Removing the requirement for sudo is also quite contradictory since we're writing files to directories which require root. Not sure what the original commiter meant by USER mode.
> Remove TODO on Makefile

- examples/Makefile
tested compiling from x86-64 (debian buster) to Raspberry Pi (raspbian buster).
```
make PLATFORM=PLATFORM_RPI USE_RPI_CROSS_COMPILER=TRUE RPI_TOOLCHAIN=/opt/cross-pi-gcc-8.3.0-0 RPI_TOOLCHAIN_SYSROOT=
```
> fixed cross-compilation of examples

- src/raylib.h
- src/rcore.c
- src/rtext.c
`SetWindowOpacity()` takes `opacity`(`float`) as a parameter. Value of `opacity` must fall under 0 and 1. If it exceeds 1; it will be equal 1, similarly if it's smaller than 0; opacity is equal to 0.
Random Screenshots (*READ THE VALUE INSIDE SetWindowOpacity()*):
`SetWindowOpacity(99999999.0)` goes same as `SetWindowOpacity(1.0)`.
Thank you
> [Feature] Added SetWindowOpacity(float opacity)

- src/rlgl.h
Changed a reference to a now non-existent function in rlgl.h to the one that should be used to set custom blend modes. Also fixed the typo.
> Change comment about custom blend modes in rlgl.h

- parser/raylib_api.json
- parser/raylib_api.lua
- parser/raylib_api.txt
- parser/raylib_api.xml
- parser/raylib_parser.c
Related issue: https://github.com/raysan5/raylib/issues/2255
Uses arrays with objects containing name and type instead of objects with name as key and type as value for function parameters in the JSON raylib parser.
> JSON parser: Use array for function params (#2255)

- src/raylib.h
- src/rcore.c
This PR adds `GetApplicationDirectory `as a function. It uses platform specific code to find the folder that the executable is running in. This is a good path to pass to `ChangeDirectory `so that you ensure you have a good starting working directory.
While this does call platform specific code, it does not include `windows.h`
This is a feature that GLFW should provide, but does not, so we need to provide to to users ourselves.
> [CORE] Add a function to return the application directory.

- src/build.zig
This change enables Zig programs to link raylib by adding the following to its build script:
```zig
const rl = @import("raylib/src/lib.zig").Pkg("raylib/src");
// ...
const exe = b.addExecutable(name, path);
// Add more settings
exe.linkLibrary(rl.addRaylib(exe.builder, exe.target));
```
> Split build.zig

- projects/CMake/CMakeLists.txt
- projects/CMake/README.md
- projects/CMake/core_basic_window.c
- projects/README.md
I found the CMake documentation for building for web was lacking (as mentioned in https://github.com/raysan5/raylib/issues/2273), so I've updated the project template to help improve it. This does two things...
1. Adds a Web build to the CMake project template
2. Adds a README.md with documentation on how to use the CMake project template
> cmake: Add Web and Docs to CMake project template

- src/rlgl.h
This would close #2280 by setting vertexShaderId to RLGL.State.defaultVShaderID if vsCode is null, same for the fragment shader.
> Restore rlLoadShaderCode behavour

- src/rcore.c
My initial PR was not set to the correct formatting standards for raylib and there were cases that would not return a valid path. This Update fixes the formatting and should always return a valid path, even if the functions fail to find the exe dir.
> [CORE] Bug and formating fixes for GetApplicatonDir

- src/rcore.c
This PR fixes an issue with the function signatures of the windows calls used by GetApplicationDirectory so that they work on 32 bit builds. No functionality has changed.
> [CORE] Fixes for GetApplicationDirectory on 32 bit windows builds

- src/rcore.c
Unless these imports require to have this format, the code has been adjusted to the conventions
> Review code conventions for specific defines

- projects/VSCode/Makefile
- projects/VSCode/main.c
- projects/VSCode/resources/LICENSE
When compiling for PLATFORM_WEB, the `./projects/VSCode` sample relied on `libraylib.bc`, which is [no longer generated](https://github.com/raysan5/raylib/commit/789c5fbdf92df93ade774c2d3132e5ae2a207713) by the latest raylib makefile.
I also updated the EMSDK path formatting to match [raylib-game-template](https://github.com/raysan5/raylib-game-template), and updated the versions to those in the latest EMSDK.
I refactored the VSCode example's `main.c` to use emscripten_set_main_loop() on PLATFORM_WEB, and added the resources/LICENSE file to match the game template.
This PR should allow those following the [Working For Web guide](https://github.com/raysan5/raylib/wiki/Working-for-Web-%28HTML5%29) to make use of the VSCode project sample.
> updated VSCode project to match latest WASM practices

- src/rmodels.c
When loading a gltf file, if there's no texture setting for a material, it's material won't be loaded(become WHITE by default).
This pr fixes that.
> fix: glTF: material color won't be loaded if there's no texture for that material 

- src/rcore.c
Previously failed to build with an implicit declaration of `_NSGetExecutablePath`.
> Fix GetApplicationDirectory on macOS

- src/external/cgltf.h
Fix undefined symbol `_ftelli64` when trying to compile with Raylib's Notepad++ & TCC on Windows.
> Fix Undefined Symbol `_ftelli64`

- cmake/LibraryConfigurations.cmake
- src/CMakeLists.txt
raudio needs `dlclose`, which is in `libdl` on Linux. Before this commit the audio examples won't compile with `USE_EXTERNAL_GLFW:STRING=ON` in CMake.
> Make audio examples compile with external glfw

- src/build.zig
- Adds a new OS clause to build.zig for the BSDs
- Tested on my FreeBSD box using https://github.com/Not-Nik/raylib-zig
- All demos build and render just fine.  Nice !
> Add BSD support for zig builds

- src/Makefile
GNU make on Windows first tries to find sh.exe on the path,
and will execute build rules using it if it is present.
The make clean target uses the builtin cmd.exe command del, which
won't work under sh.exe, it fails likeso:
```
del *.o /s
sh: del: not found
make: *** [Makefile:739: clean] Error 127
```
Setting the shell to cmd before attempting to run cmd builtin commands fixes the issue 
The reason this is not done for the entire Makefile is because it would
break cross-compilation of raylib.
> Fix make clean target failing when shell is not cmd

- src/raylib.h
- src/rlgl.h
This adds a new blendmode `BLEND_ALPHA_PREMUL`, which is required for correct alpha blending of `RenderTexture`s. 
The same can be achieved in a more complicated way with `BLEND_CUSTOM` and `rlSetBlendFactors`, but that requires a bunch of OpenGL constants which are not readily available in every binding (e. g., Lua).
Fixes #2227, #1121.
> add premultiplied alpha blend mode

- src/raymath.h
Since `sinf()` and `cosf()` are rather expensive functions compared to basic math operations, we try to avoid them as much as possible.
> Optimize `Vector2Rotate()` function

- src/rcamera.h
I noticed the free camera acting unexpectedly and its seems some values needed to be negated. I've attached two video clips to showcasing the issue and the fix. I thought it was a platform issue but it seems the free camera example on raylib.com also has the same issue.
Only tested on arch linux.
Here you can see the panning action "zooming" in and out when panning while viewing at an angle, and the panning moving in the opposite direction when viewing straight down:
https://user-images.githubusercontent.com/30801498/154765282-c4a1dc58-3421-4511-a0de-13820e5565f9.mp4
And here it is with this PR applied, it now pans correctly:
https://user-images.githubusercontent.com/30801498/154765284-b180d8a0-3da4-4f08-9212-8c669c36b4c9.mp4
> Fix free camera panning in the wrong direction

- src/rtext.c
Increase atlas size guesstimate, print warnings if atlas size is too small, and make sure all rectangles are properly initialized.
Fixes #2356.
> Increase font atlas dimensions guesstimate

- src/raymath.h
Needed to sort polygons with distance to camera. In such cases, where we just do comparisons, squared distance seems good.
Might be useful as a general API.
Not sure if this is considered bloat, but as we can see vector2/3 has length and squared length functions.
https://github.com/raysan5/raylib/blob/43dbe67431dac3e44c514cf1839f49cae69777b6/src/raymath.h#L249-L263
> Vector2/Vector3: Add squared distance.

- src/Makefile
Hash "#" is single-line comment character in bash so echo ignores all of line if #include and #define written and make gives an error because it cannot find raygui.c and physac.c
> Fixed an issue in Makefile when using raygui and physac on unix systems

- examples/core/core_input_gamepad.c
Sorry for the spam, you were too fast! I wanted to force-push this into my previous PR, but you beat me to it.
As prior commit, but complete fix for XBox controller and trigger
buttons too.
> The joystick range is a float from -1 through +1. Casting this to int
> yields only three possible values: -1, 0, and 1. This gives a
> misleading joystick placement in the demo.
>
> By casting to int after the multiplication to get pixel values, the
> demo reveals the analog feel of the joystick.
> Improve joystick visualisation in gamepad example again

- src/rcore.c
This PR implements the OpenURL() function for Android Platform.
It will call an Intent to open the given url with the default browser app.
> OpenURL() for Android Platform

- src/rtextures.c
This is a tiny change that makes code in src/rtextures.c "fold"
correctly in editors/IDE's by matching the number of opening
parenthesis to closing parenthesis.  One of those editors is Emacs ;-)
> Fix too many opening parens in src/rtextures.c

- src/rtextures.c
This PR adds a check to the render batch to verify there is enough room for the geometry that may be created. Without this the batch can overflow.
> [Textures] Make DrawTextureNPatch check the batch limits

- src/raymath.h
This PR fixes calculation of `QuaternionScale` function in `raymath.h`.
I found the previous implementation of `QuaternionScale` was calculating `(w+ix+jy+kz)(s+is+js+ks)`, rather than usual quaternion-scalar multiplication `(w+ix+jy+kz)s`.
Changed the function to calculate `(w+ix+jy+kz)s = ws+i(xs)+j(ys)+k(zs)`.
(Sorry for hard-to-read math, because GitHub does not allow LaTeX equations)
> Fix QuaternionScale

- src/raymath.h
I use these functions heavily during gamedev so I thought they could be useful for others too:
- FloatEquals:  Check whether two given floats are almost equal
- Vector{n}Invert: Invert the given vector
- Vector{n}Clamp: Clamp the components of the vector between min and max values specified by the given vectors
- Vector{n}ClampMagnitude: Clamp the magnitude of the vector between two given min and max values
- Vector{n}Equals:  Check whether two given vectors are almost equal
Additionally Vector3{Up,Down,Left,Right,Forward,Backward} are added for convenience.
Vector3Refract refracts a vector given a normal and a refractive index.
QuaternionEquals checks whether two given quaternions are almost equal.
Furthermore, a macro named "EPSILON" with a value 1e-6 is added (used in floating-point …
> Augment raymath.h with useful functions

- examples/core/core_vr_simulator.c
- src/rcore.c
- src/rlgl.h
I tried to find a way to fix the issue without breaking an existing API. I think the current solution fits that criteria.
I needed to comment in the `distortionScale`, to keep the example's "vignette" effect. To my eyes the final image looks the same as the previous version.
> Fix for vr rendering not taking render target size into account. fixes #2420

- src/rcore.c
In MouseScrollCallback priority was given to the horizontal movement, I have changed it to return the largest movement (in absolute value) between the X and Y axis.
Perhaps it would be more interesting to have different functions for the X and Y axis.
> Fix issue #2371

- parser/raylib_api.json
- parser/raylib_api.lua
- parser/raylib_api.txt
- parser/raylib_api.xml
- parser/raylib_parser.c
This PR fixes some small inconsistencies in the parser and adds support for aliases.
JSON example output:
```json
"aliases": [
{
"type": "Vector4",
"name": "Quaternion",
"description": "Quaternion, 4 components (Vector4 alias)"
},
{
"type": "Texture",
"name": "Texture2D",
"description": "Texture2D, same as Texture"
},
{
"type": "Texture",
"name": "TextureCubemap",
"description": "TextureCubemap, same as Texture"
},
{
"type": "RenderTexture",
"name": "RenderTexture2D",
"description": "RenderTexture2D, same as RenderTexture"
},
{
"type": "Camera3D",
"name": "Camera",
"description": "Camera type fallback, defaults to Camera3D"
}
],
```
> Add aliases to parser

- BINDINGS.md
This PR adds my own [Racket Raylib bindings](https://github.com/eutro/racket-raylib) to `BINDINGS.md`.
> Add racket-raylib to BINDINGS.md

- parser/raylib_api.json
- parser/raylib_api.lua
- parser/raylib_api.txt
- parser/raylib_api.xml
- parser/raylib_parser.c
- Fix parser function description detection
- Some functions in easings.h are defined on a single line and include a division which was mistaken for the start of the description.
- Fix parser detection of macros with names that contain spaces
- Add support for self-referencing structs to parser (like MemNode)
- Fix parser code style
- Fix parser handling of multiple fields on one line
- For types this time, pointer types are detected by the last `*` and may contain multiple fields
- `MemNode *next, *prev` used to be parsed into one field with type `MemNode *next, *` and name `prev` 
- Increase parser MAX_STRUCT_FIELDS
- For internal rlglData State struct (internal structs are still not supported but this makes it less wrong).
- Add description helper to parser
- Makes sure a description …
> Parser improvements

- src/utils.c
This immediately shows log messages when stdout is not connected to a
tty.
> Flush stdout after trace messages

- parser/Makefile
- parser/raylib_parser.c
- src/rlgl.h
This PR adds support for truncating parser input lines with a command line arg. This can be used to not parse implementations in headers that contain them.
I noticed the implementations being parsed because two function implementations in rlgl.h had the RLAPI specifier which caused them to be duplicated in the parser output.
> Add support for truncating parser input

- parser/raylib_api.json
- parser/raylib_api.lua
- parser/raylib_api.txt
- parser/raylib_api.xml
- parser/raylib_parser.c
This small PR adds support for calculated defines to the parser. The new define types with the `_MATH` suffix mean that a define is a mathematical expression that would have the preceding type when calculated.
raylib.h examples:
```json
{
"name": "DEG2RAD",
"type": "FLOAT_MATH",
"value": "(PI/180.0f)",
"description": ""
},
{
"name": "RAD2DEG",
"type": "FLOAT_MATH",
"value": "(180.0f/PI)",
"description": ""
},
```
> Add support for calculated defines to parser

- src/rcore.c
When selecting a display connector in drm mode raylib tries to find an exact match with `FindExactConnectorMode(..)`
and if none is found resorts to `FindNearestConnectorMode(..)`.
This PR relaxes the drm connector selection by removing the fps requirement in `FindNearestConnectorMode(..)`.
It is still uses the fps to find the most suitable display!
This change should fix #2259.
It also fixes the problem with `SetTargetFPS(..)` and `InitWindow(..)` ordering.
`SetTargetFPS(..)` is used in order to reach a certain internal fps target and less for display selection.
Resolution is more defining here.
> Fix #2259 by relaxing drm connector selection on RPI4 native mode

- src/raudio.c
- src/raylib.h
- src/rgestures.h
- src/rlgl.h
I've had [a bit of a trip](https://stackoverflow.com/questions/72300728/returning-a-struct-from-a-function-in-windows-corrupts-its-data/) tracking down a completely bamboozling bug, where certain member offsets in my structs were inconsistent throughout my program when compiling on Windows. It turns out this was caused by the fact that `raylib.h` defines its own `bool` data type if it deduces that `stdbool.h` cannot be used, and the size of this type is not necessarily the same as the size of `bool` as `stdbool.h` defines it. Consequently, depending on whether the compiler had seen `stdbool.h` or `raylib.h` when it came across the definition of my structs, it would generate different member layouts in different compilation units for those structs which had `bool` members. If I passed one …
> Improved boolean definitions

- src/rcore.c
On macOS when running on a display with retina resolution or on an external 4k screen, the `TakeScreenshot` function triggered by F12 and the gif recording triggered by Ctrl-F12 ignore the scaling so they only grab the lower left quarter of the window.
This change uses the factors from `GetWindowScaleDPI()` to scale width and height to allow the full window content to be grabbed even if scaling is active.
Not sure if there would be need for a check of `FLAG_WINDOW_HIGHDPI`, from my understanding, the scaling would be needed there to, for other cases if should be a scaling by 1, and the overhead of `GetWindowScaleDPI()` seems small compared to the gif or png encoding that happens afterwards.
> use GetWindowScaleDPI to calculate size for rlReadScreenPixels in sceenshot/recording

- .github/workflows/android.yml
- .github/workflows/cmake.yml
- .github/workflows/linux.yml
- .github/workflows/linux_examples.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
- .github/workflows/windows_examples.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- src/rcore.c
Hello,
This PR fixes the regression described in this issue (https://github.com/raysan5/raylib/issues/2434), in which video stuttering or high amount of tearing was found when running Raylib programs compiled with SUPPORT_PARTIALBUSY_WAIT_LOOP.
The regression was introduced in commit 4e9afac2a55cd3d7b347d9e3706e0dd370386ff7 (https://github.com/raysan5/raylib/commit/4e9afac2a55cd3d7b347d9e3706e0dd370386ff7), and is caused by the way the the busy wait time limit is checked before returning. In the previous version, a target time was calculated by adding the desired time to wait to the current time, and, after sleeping, the remaining busy waiting was done by continously checking the current time until it passed the target time. The stated commit changed this behavior, making it calculate the …
> Fix regression that was causing video stuttering

- BINDINGS.md
[Commit d57c8136426b7cc8a39e77f05097c8585d4bb1eb](https://github.com/longlene/cl-raylib/commit/d57c8136426b7cc8a39e77f05097c8585d4bb1eb) from [longlene/cl-raylib](https://github.com/longlene/cl-raylib) now puts the binding on track with raylib version 4.0.  This PR moves cl-raylib back to the actively maintained language bindings table.
> Update `cl-raylib` binding

- src/raylib.h
- src/rcore.c
This substitutes the internal representation of the single scroll value with a `Vector2`. When the original `GetMouseScrollWheel` function is called, it performs the same task that was previously done for the x/y callback function (take the component with the largest magnitude). Callbacks that just provide one value are put into the Y component.
~~I also modified the scroll wheel example as appropriate, but I can modify it to get the original functionality back if needed.~~ EDIT: reverted back to the original.
BIG NOTE: this is only tested on MacOS by me (and only with a modified scroll wheel example), I don't have experience building any of the other platforms (Android, web, etc).
I tried to update what I think is some playback system, but I'm not sure if I did that right, please pay …
> Add function to read both X and Y mouse scrolling from a trackpad

- src/raymath.h
Implementation of a wrap function, mainly to avoid overflow.
> add wrap function

- src/rtextures.c
This PR fixes the problem described in https://github.com/raysan5/raylib/issues/2523
> fix: round off error in ColorAlphaBlend

- src/rtext.c
When using ExportFontAsCode(...), the exported .h file sets the font padding to the value of the constant FONT_TTF_DEFAULT_CHARS_PADDING. This results in incorrect rendering of certain AngelCode fonts, so this pull request instead uses the glyphPadding of the Font given as an argument.
> Changed ExportFontAsCode to use given font's padding.

- src/raudio.c
Assuming `UpdateMusicStream()` is not meant to be called from multiple threads at the same time, this drastically reduces the number of dynamic allocations that Raylib's Audio API does at runtime when playing music.
However, if thread safety is required, you might consider doing a similar optimization by maintaining a PCM sample buffer per thread. I tried to use `thread_local`, but it didn't compile in the default MSVC C compiler as it requires C11. When I tried compiling Raylib using the C11 switch, I got other, unrelated errors about `stdalign.h`.
I did compile this and my music played properly, but that's about all the testing I've done. Just figured I'd share in case you find the general idea useful. You may consider any code in this contribution public domain or Zlib licensed, at …
> Share PCM streaming buffer to reduce dynamic allocations

- src/rlgl.h
rlGetGlTextureFormats was expecting unsigned int, corrected variables according to that.
> Fix signedness in rlBindImageTexture

- src/external/stb_vorbis.h
- src/rglfw.c
I tried multiple methods to fix the build for cygwin
_WIN32 can be defined when using cygwin, this however causes other errors, because some headers are not present on cygwin and other problems.
I find this to be the cleanest solution, maybe some comments should be added for explanation?
> fixed build for cygwin

- src/raymath.h
Test code:    
```
float theta = GetRandomValue(0, 360) * DEG2RAD;
Vector3 n = Vector3Normalize((Vector3) { GetRandomValue(0, 100) / 100.0f, GetRandomValue(0, 100) / 100.0f, GetRandomValue(0, 100) / 100.0f });
Quaternion q0 = { .w = cos(theta / 2), .x = n.x * sin(theta / 2), .y = n.y * sin(theta / 2), .z = n.z * sin(theta / 2) };
Quaternion q = QuaternionFromMatrix(QuaternionToMatrix(q0));
assert(QuaternionEquals(q, q0));
```
algorithm form: Ken Shoemake. "Quaternions and 4 x 4 Matrices."
> [raymath] `QuaternionFromMatrix()` not returning expected result

- src/raymath.h
While working on the rcamera redesign I noticed that there was no function in `raymath.h` to rotate a vector around an axis in 3D.
This PR adds the function `Vector3RotateByAxisAngle(Vector3 v, Vector3 axis, float angle)` to do just this.
Maybe this can be useful in other applications as well.
I tried to follow the `raymath.h` conventions and general code style.
> [raymath] add Vector3RotateByAxisAngle

- cmake/raylib-config.cmake
raylib does not currently guard against multiple inclusion in cmake projects.
This causes issues when you want to first check for existence of a raylib install and actually add it later.
For example, in my case, I first check for a local install of all my dependencies using find_package('dependency here' QUIET). If not found, I then use FetchContent to automatically grab the missing dependency. Works fine when I DON'T have a local install of raylib. But this causes issues when a local install exists and I attempt the find_package(raylib REQUIRED) call because raylib's config will attempt to add an already existing library ("raylib") when calling find_package on it multiple times.
This change will only run the cmake configuration logic if the raylib target does not already exist.
> add: cmake config include guard

- src/rtextures.c
Height of the rectangle can be float, which may lead to doing extra iteration of loop and writing out of bounds.
This only fixes problem reported in https://github.com/raysan5/raylib/issues/2577, but there may be another usages of using rect dimensions without casting in other pieces of code.
> rtextures: Fix ImageFromImage crash

- src/rtextures.c
Dimensions of Rectangle should be casted to int before multiplication,
otherwise there is a risk for underallocation/overallocation of memory.
In case of overallocation its just a waste of memory. In case of underacllocation its a crash in best case.
Example: https://godbolt.org/z/zjhKh7xr8
> rtextures: Improve numerical stability of float multiplication

- examples/audio/audio_raw_stream.c
Fix issue where old sine waves are still rendered if you decrease the wavelength on the audio_raw_stream example.
> Fix rendering issue in audio_raw_stream.c example

- src/raudio.c
GetMusicTimePlayed() was calculated using buffered frames, not played frames.
For example: calling LoadMusicStream->UpdateMusicStream->GetMusicTimePlayed would return non-zero value, even though no music was playing.
> GetMusicTimePlayed bug fix

- BINDINGS.md
I added new bindings for Free Pascal based on the most up to date 4.0 version of Raylib. This pull request adds a line to the BINDINGS.md markdown document.
> Added new Free Pascal bindings

- src/rcore.c
This prevented alt-tabbing out of fullscreen window with fullscreen resolution. I moved the code to the else clause because of the comment "If we are windowed fullscreen". It also says "ensures that window does not minimize when focus is lost" but it doesn't happen even without this code ( at least on Win10 ). Maybe it's needed on other OS, not sure.
> Can't alt-tab out of fullscreen window fix

- examples/build.zig
Specifically, std.fs.OpenDirOptions struct no longer has the iterable flag, now it's a standalone function call std.fs.openIterableDir.
This was added to zig with https://github.com/ziglang/zig/pull/12060
> Updated examples to work with zig master branch

- src/rtext.c
This truncation causes text that spans the zero coord boundary to round differently left of zero vs. right of zero, in turn causing letters to appear squished together. If you actually need the position to be an integer, you should instead `floorf()` the float, rather than doing an integer truncation, but I don't see any reason to convert it to an integer in the first place. Everything else in the equation is a float.
Here's an example of the visual "squishing" artifact that occurs before this fix:
https://i.imgur.com/mxpq0rS.mp4
> Fix Codepoint position truncation

- src/rcore.c
When file extension is longer or equal length compared to buffer holding lowercased string, strncpy does not null terminate the string.
Increased buffer size by 1 to ensure it will always be null-terminated, so that following strcmp does not read out of buffer bounds.
> Fix string lacking null termination in IsFileExtension

- examples/others/reasings.h
- examples/shapes/reasings.h
The header comments for the function `EaseSineInOut` were mislabeled as `EaseSineOut`. This has been fixed. Not much else to say... weather's nice, huh?
> Tiny documentation fix in reasings.h

- src/external/glfw/include/GLFW/glfw3native.h
- src/rcore.c
This reflects GLFW's fix: https://github.com/glfw/glfw/issues/1348
Currently, we can't build raylib with an external GLFW in Win32
since some symbol re-definition errors occur.
The internal GLFW in raylib seems to avoid this problem by customizing `glfw3native.h`: https://github.com/raysan5/raylib/commit/2feea87b616292b5bce4454a42c2d048f1cce7d8
This fix enables building with an external GLFW in Win32 without any customization,
if it contains the fix of https://github.com/glfw/glfw/issues/1348.
This fix is compatible with the current internal GLFW too.
If we update the internal GLFW to the latest before we merge this branch,
we don't need the commit: 6609c689248bf7931d30a468dd4631edc1a75a0a.
In that case, I will remove that commit from this branch.
> Win32: resolve some symbols re-definition of windows.h in glfw3native.h

- src/Makefile
The current Makefile ignores the system PATH variable when appending the emsdk paths. This PR corrects this for both Windows and Linux
> Fix PATH for Web target

- examples/CMakeLists.txt
The build is fine with this change:
```
emmake make
make: make
[  0%] Building C object raylib/CMakeFiles/raylib.dir/rcore.c.o
emcc: warning: linker setting ignored during compilation: 'USE_GLFW' [-Wunused-command-line-argument]
emcc: warning: linker setting ignored during compilation: 'ASSERTIONS' [-Wunused-command-line-argument]
[  0%] Building C object raylib/CMakeFiles/raylib.dir/rmodels.c.o
...
[ 99%] Building C object examples/CMakeFiles/textures_to_image.dir/textures/textures_to_image.c.o
emcc: warning: linker setting ignored during compilation: 'USE_GLFW' [-Wunused-command-line-argument]
emcc: warning: linker setting ignored during compilation: 'ASSERTIONS' [-Wunused-command-line-argument]
emcc: warning: linker setting ignored during compilation: 'WASM' …
```
> Removed raylib_opengl_interop.c from PLATFORM=Web build

- src/raylib.h
- src/rshapes.c
Adding a function to _Basic shapes collision detection functions_. Detects if point is inside of polygon described as series of vertices.
> Check collision point polygon

- examples/core/core_2d_camera_platformer.c
`canJump` used to alternate between `true` and `false` when on the ground.
When using `IsKeyPressed` instead of `IsKeyDown` for jumping, the player might not jump due to that behavior. This behavior got fixed by adjusting the condition for checking if an obstacle is being hit. With this change, `canJump` doesn't alternate between `true` and `false` when the player is on the ground and instead stays on `true`.
> Fixed a bug in the 2d camera platformer example

- examples/core/core_custom_logging.c
> examples/core/core_custom_logging.c: Fix typo

- src/rlgl.h
Uses a macro defined in `<OpenGL/gl3ext.h>`.
Also some general syntax cleanup, removing a few conditionals for unoptimized builds. Should save a few CPU cycles ;)
Tested on macOS Monterey 12.5.1 only, but since Apple's OGL hasn't been updated in ages this should work on older systems too.
> Enable DXT compression on __APPLE__ targets

- projects/CMake/CMakeLists.txt
This updates the cmake project template to make it easier to target different raylib versions.
> CMake: Project template fix to easily target raylib version

- src/rcore.c
Fix display -> screen coordinate conversion for android platform and move it to the platform event handling code, simplifying GetTouchPosition() function implementation.
Fixes previous behavior on Android which is reporting touchscreen input coordinates as a number in range from 0 to 1 to reporting values in screen coordinates.
Tested with native resolution and upscaling. Downscaling currently seems to have another bug somewhere deeper in rendering setup.
> Fix touchscreen input related functions on Android

- src/rcore.c
On android after rebinding context (which happens when you minimize and navigate back to an app, or when you turn a screen off and back on) there's a bug that viewport has a wrong scale and part of it is off screen.
The change fixes it on devices I tried, but the solution feels hacky to me. However when I attempted instead to call SetupViewport() again which feels like a more proper solution, it didn't fix it.
> Fix viewport scaling bug on android after context rebind

- src/rcore.c
Currently assumes a single gamepad, has no code specific to gamepad detection (gamepad is "detected" when an event related to gamepad arrives). Also assumes that all gamepads look roughly like an xbox/ps controller. Both assumptions are not strictly true, but an implementation like that probably covers 85% of usecases.
Also it doesn't update previousButtonState so functions IsGamepadButtonPressed() and IsGamepadButtonReleased() don't work, but they didn't work previously on Android anyway, and they are flaky on desktop as they are now, so the mechanism for these two functions probably should be reworked anyway.
It's certainly an improvement compared to the previous android gamepad handling code, which put gamepad events into touch related structs.
> Basic gamepad support for Android

- src/rgestures.h
Related to https://github.com/raysan5/raylib/issues/2729 , makes gestures.h use `GetTime()` if it's available.
> Update Gestures to use GetTime() if it's available

- src/raudio.c
Fix for #2714
Code used for testing:
```
int main(void)
{
bool restarting = true;
while (restarting) {
// Initialization
//--------------------------------------------------------------------------------------
const int screenWidth = 800;
const int screenHeight = 450;
InitWindow(screenWidth, screenHeight, "raylib [audio] example - music playing (streaming)");
InitAudioDevice();              // Initialize audio device
Music music = LoadMusicStream("resources/country.mp3");
PlayMusicStream(music);
SetTargetFPS(60);               // Set our game to run at 60 frames-per-second
//--------------------------------------------------------------------------------------
// Main game loop
while (restarting && (!WindowShouldClose()))    // Detect window close button or ESC key
{ …
```
> Clear PCM buffer state when closing audio device

- src/build.zig
The recent GLFW update([9e0e08c](https://github.com/raysan5/raylib/commit/9e0e08cba495cb8799171c113b55591b46827459)) made build.zig no longer work. It would fail compilation by saying that `ppoll()` was undeclared. Adding the `-D_GNU_SOURCE` flag to compilation fixes this issue(same fix as this one done on the Makefile: [be2328f](https://github.com/raysan5/raylib/commit/be2328f848d96a788f9f40f1ed302c64335d47df)).
This change was tested and works on Linux(Artix), I have not tested on Windows or MacOS as I do not have either of those platforms.
> Update build.zig to work with last GLFW update

- src/rlgl.h
> Coincidentally it seems like #2717 found some similar problems mentioned in this PR... I have made these changed a long time ago, sorry for that.
There are several problems.
1. In some cases rlSetBlendMode is not enough for all situations (like some 3rd party libraries like Live2D, actually I have written a raylib renderer for Live2D for fun, with changes in this PR)
2. If custom blend factors or equations is changed, some functions, like glBlendFunc, should be called. No function call is made now if RLGL.State.currentBlendMode is not changed
For problem 1, I used a more modest approach. I think glBlendFuncSeparate will not be used in most cases, so I add one more blend mode for this case. I don't know if it is appropriate to force developers to use glBlendFuncSeparate...
And I add …
> Add rlSetBlendFactorsSeparate and checks for custom blend mode modifications

- BINDINGS.md
Raylib-CsLo and Raylib-cs now support raylib 4.2
https://github.com/NotNotTech/Raylib-CsLo/tags
https://github.com/ChrisDill/Raylib-cs/releases
> Update BINDINGS.md 

- examples/text/text_rectangle_bounds.c
Hello! I copied the `DrawTextBoxed()` code into my project and noticed this glitch. Wrapped spaces are currently moved into the start of the next line. Hence this PR. Cheers!
> avoid leading spaces in `text_rectangle_bounds`

- src/rshapes.c
Addresses problem mentioned in https://github.com/raysan5/raylib/issues/2744#issuecomment-1273568263 (in short: when drawing pixels using `DrawPixel`/`DrawPixelV` in camera mode, upscaled pixel becomes a line instead of bigger pixel).
> Use RL_QUADS/RL_TRIANGLES for single-pixel drawing

- src/external/vox_loader.h
and make version check be only 150 not over 150
because everytime a version changes, the way to load the file gets different, we would first have to add support, then allow
the old version check was big and didnt work(it just checked for the first letter, and if the first letter was not "V" and "O" and "x" AND " " THEN it would fail, not good, so i made this!
> Fix & Simplify .vox signature check

- src/rshapes.c
- src/rtextures.c
Already explained in #2755, should close it.
Also it would be nice to specify a scaling method 'cause not all fonts look great when using cubic interpolation, but that can be easily done manually by drawing text with "native" font size first and then using `ImageResizeNN` if desired
> Fix ImageTextEx and ImageDrawTextEx scaling

- BINDINGS.md
[raylib-umka](https://github.com/robloach/raylib-umka) provides [Umka scripting language](https://github.com/vtereshkov/umka-lang) bindings to raylib.
> BINDINGS: Add Umka bindings to BINDINGS.md

- parser/Makefile
- parser/raylib_parser.c
Currently, the `make all` target will segfault if it is run without all the necessary files present, now make instead puts an error. Also, the path to the old "easings.h" has been updated to "reasings.h" 
The parser itself has been reviewed to print a more helpful error message instead of segfaulting, if a nonexistent file is passed on the command line.
> Review parser Makefile

- src/build.zig
This should delegate the responsibility of calling `standardReleaseOptions` and setting the build mode of the `*LibExeObjStep` step to the caller, especially since this might not be the process by which one wants to determine the build mode.
Also changes hides `getSrcDir` to enforce usage of `srcdir`, and asserts that the file is in fact inside a directory.
Also fixes a linker error, by passing `null` to the `root_src` param of `addStaticLibrary` instead of the header file.
> build.zig: let user decide how to set build mode + fix linker warning

- examples/textures/textures_image_processing.c
- src/rtextures.c
Sorry for the second pull request on this, there was a problem on opaque pictures.
Also added blur on an example.
> Fixed blur issue on opaque pictures & added example

- BINDINGS.md
I've just write a binding generator for raylib in Chez Scheme 9.5.8, and rewrite some of the examples in scheme✅. This idea is inspired by  Petelliott's [raylib-guile](https://github.com/petelliott/raylib-guile).
> Add ChezScheme support

- examples/Makefile.Android
When using the Android.Makefile that is inside examples for building a project, if chosen Android architecture is **x86** then the makefile will create a folder inside **_lib_** called **i686**. However, in order to install, Android actually expects this folder to be called **x86**.
Basically, the **_lib\i686\\_** folder should actually be named **_lib\x86\\_** in order to be able to install the app on a x86 Android.
In order to fix this, I just changed the _ANDROID_ARCH_NAME_ variable from **i686** to **x86**.
- The problem also exists in the _Android.Makefile_ on the [raylib-game-template](https://github.com/raysan5/raylib-game-template) repo, so you probably should take a look on that.
- The Makefile for the raylib library itself doesn't appear to have this issue.
> Fix Android x86 Architecture name

- examples/build.zig
#2720 fixed the build.zig in src/, but not the one in examples/.
> Fix examples/build.zig for the latest Zig version

- src/raylib.h
- src/utils.c
When I tried using negative numbers, or numbers over 128, the hexadecimal value returned would have 8 digits instead of only having 2. 
ExportDataAsCode() uses the 'x' format specifier to convert decimal to hexadecimal, which is only usable with unsigned data.
> Fix ExportDataAsCode() data types

- src/build.zig
I just built the project on mac os, and needed to add several frameworks to resolve missing symbol linker errors.
> Add frameworks needed on macos

- src/Makefile
I fixed the edeting of the PATH in the makefile. Before it would completely destroy it.
The editing of the path is kind of flawed in it self, so maybe a way to disable this edeting of the path should be added, or it should be removed entirely.
> Fix Makefile emscripten path

- BINDINGS.md
Now [Raylib-py](https://github.com/overdev/raylib-py) is a releases-only project.
For now on, code maintenance will happen in a parallel project created to automate the binding generation: [RaylibpyCtbg](https://github.com/overdev/raylibpyctbg)
> Raylib-py updated to 4.2, plus parallel project

- src/rcore.c
Added a comment explaining the range limitations of GetRandomValue. Added a run-time warning TRACELOG when GetRandomValue is called with an invalid range.
> Warning on GetRandomValue range limit

- src/rlgl.h
Currently, rlgl does not expose glCullFace. Changing the face culling mode is useful for shadow mapping. rlCullFace sets the face culling mode to RL_FRONT or RL_BACK, corresponding to GL_FRONT and GL_BACK respectively.
> Added rlCullFace

- src/rlgl.h
format is passed to rlGetGlTextureFormats which has a signed int parameter.
> Correct types for rlBindImageTexture

- src/rcore.c
Simply, the last indexes of the arrays are wrong.
Generating 16 characters or more of input at one time will destroy the other values of the structure.
> Fix array out of range

- cmake/CompileDefinitions.cmake
`MAX_KEY_PRESSED_QUEUE` is duplicated, and there is no `MAX_CHAR_PRESSED_QUEUE`.
Maybe this should be `MAX_CHAR_PRESSED_QUEUE`.
> Fix wrong compile definition

- src/rcore.c
When PLATFORM_ANDROID, PLATFORM_RPI or PLATFORM_DRM are defined, there is a compilation error due to redefinition of the variable 'time' in the function GetTime. So the second instance of 'time' was changed to 'time_nsec'. This both resolves the name collision and more accurately describes what that variable represents.
Verified working on Raspberry Pi 3B+ with Raspbian Buster.
> Updated rcore.c, renamed 'time' to 'nanoSeconds'

- src/CMakeLists.txt
It would try to use the glfw on the system but we're cross-compiling for web where the implementation is provided by emscripten's team
> Fix an issue when compiling for web

- cmake/LibraryConfigurations.cmake
Use GLVND also when legacy implementations exist for old cmake versions <= 3.10. This is a breaking change for old cmake versions (prior to around 2017-10-05) which will now use GLVND rather than defaulting to libGL.
This fixes the following warning when building:
CMake Warning (dev) at /gnu/store/qv13zgbmyx0vjav8iiqp772kp6rxvwnd-cmake-3.24.2/share/cmake-3.24/Modules/FindOpenGL.cmake:315 (message):
Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
FindOpenGL found both a legacy GL library:
OPENGL_gl_LIBRARY: /home/simendsjo/.guix-profile/lib/libGL.so
and GLVND libraries for OpenGL and GLX:
OPENGL_opengl_LIBRARY: …
> Use GLVND also for old cmake versions

- src/raymath.h
This fix ensures that the angle can be computed for all normalized vectors. But we still return negative values, which is not correct, but is required to maintain backwards compatibility.
Fixes #2828
> Fix Vector2Angle()

- examples/Makefile
- examples/shaders/resources/shaders/glsl100/write_depth.fs
- examples/shaders/resources/shaders/glsl330/write_depth.fs
- examples/shaders/shaders_write_depth.c
An example to demonstrate how to write into the depth buffer so people don't have to search like I have in the future.
This example replaces the depth values by `1 - depth` to essentially invert the depth and make the farthest pixel appear on top.
Also I only tested the build on PLATFORM_WEB and PLATFORM_DESKTOP on a Linux machine. I don't know if it works on windows but I don't see why it shouldn't.
> [example] Writing into the depth buffer

- examples/core/core_loading_thread.c
makes dataProgress atomic as well.
> Use explicit atomics

- src/rcore.c
Environment
* Ubuntu 20.04 LTS
* X11 window system
We can create a display-sized fullscreen as follows:
```c
SetConfigFlags(FLAG_FULLSCREEN_MODE);
InitWindow(0, 0, "title");
```
However, at this time, `window.position.x` and `window.position.y` are set to `0`.
There is no way to set that value for `ToggleFullscreen`.
This causes problems on X11 when `ToggleFullscreen`.
When toggling a display-sized fullscreen to windowed screen by `ToggleFullscreen`, the window is at (0, 0) as follows:
```c
ToggleFullscreen();
SetWindowSize(800, 450);
```
However, sometimes (about 50%) it goes wrong as follows:
* The side-bar and top-bar disappear.
* The header of the window doesn't appear.
The initial windowed position should be near the center, not just on this issue.
> Set initial window position for display-sized fullscreen

- examples/core/core_input_multitouch.c
Touches became sticky and didn't disappear after using more than 2 fingers, fixed by getting the touch count of how many fingers are on the screen, and only looping through the available/pressed down touch points instead of looping through the maximum touch points. Tested with more than 10 touch points, and with different MAX points value, working perfectly.
> Fixed bug : touches become sticky

- src/rmodels.c
When a buffer is read using cgltf_load_buffer_base64, the data is a raw void*, so we can't call `cgltf_free`. `cgltf_free `assumes the data is a `cgltf_data `structure and will try to free the various buffers in that structure. 
This causes a crash with some files (attached)
[house.zip](https://github.com/raysan5/raylib/files/10453346/house.zip)
This PR calls a normal free for the data, so it's properly deallocated so it won't crash.
I could not find a pure free method in cgltf, so I just called raylib's free since it looks like that is what is installed for cgltf's allocators anyway.
> [MODELS] Fix crash with some GLTF models

- src/rmodels.c
The function `LoadMaterials `did not do anything with the materials parsed from the MTL file. This PR moves the code that the OBJ reader uses for materials into a function that can be used by both `LoadObj `and `LoadMaterials`.
I'm not sure if you want to keep `LoadMaterials `as a function because nobody has used it, but if you do, this PR makes it work. 
I can see justification for removing `LoadMaterials `too.
This should resolve issue #2869
> [Models] Fix LoadMaterials

- src/rlgl.h
`ARB_texture_cube_map` only became core in OpenGL 1.3. A friend experimenting with porting my image viewer to GL 1.1 found that the function I recently added threw a error. Now it should only be usable if GL1.1 isn't the version being used.
> [rlgl] Stub `rlCubemapParameters` if under GL 1.1

- src/rcore.c
- src/rmodels.c
- src/rtext.c
There were a few raylib modules that continued to use `TraceLog()` instead of the `TRACELOG()` macro. This change ensures that all the internal raylib modules use the `TRACELOG()` pattern consistently.
> Fix to use TRACELOG() instead of TraceLog() for internal modules

- src/raylib.h
Ran into an issue in raylib-cpp where a user was using raylib 4.5-dev, even though the library currently only targets 4.2. With having RAYLIB_VERSION_MAJOR and RAYLIB_VERSION_MINOR, we will be able to target different versions of raylib in different ways with the same code, using C preprocessor conditionals.
For example:
``` c
#if RAYLIB_VERSION_MAJOR >= 4 && RAYLIB_VERSION_MINOR >= 5
newColor = ColorTint(BLUE, RED);
#else
TraceLog(LOG_INFO, "The color should be tinted, but this isn't supported in raylib <= 4.2");
#endif
```
> Add RAYLIB_VERSION numbers to raylib.h

- src/rmodels.c
Simply checks if joints were loaded in with animations file, and copies string data to name.
One issue is that maybe we should be using `strcpy_s` instead of raw memcpy?
Fixes #2863
> [models] Load bone names from IQM file if available

- src/config.h
The file config.h doesn't have any kind of include guards. This means that if some external library (like raylib extras) needs to check options in in raylib, it will get warning/errors if it tries to include config.h.
This PR simply adds a guard to the file to prevent that.
> [CORE] Add include guard to config.h

- examples/audio/audio_raw_stream.c
- examples/core/core_custom_frame_control.c
- examples/core/core_drop_files.c
- examples/shaders/shaders_hot_reloading.c
- examples/shapes/raygui.h
- examples/text/text_draw_3d.c
- examples/textures/textures_fog_of_war.c
- examples/textures/textures_polygon.c
- projects/VS2022/examples/rlgl_compute_shaders.vcxproj
- projects/VS2022/examples/rlgl_standalone.vcxproj
- projects/VS2022/examples/shaders_hot_reloading.vcxproj
- projects/VS2022/examples/shapes_draw_circle_sector.vcxproj
- projects/VS2022/examples/shapes_draw_rectangle_rounded.vcxproj
- projects/VS2022/examples/shapes_draw_ring.vcxproj
- projects/VS2022/examples/text_draw_3d.vcxproj
- projects/VS2022/examples/textures_fog_of_war.vcxproj
- projects/VS2022/examples/textures_polygon.vcxproj
- src/rmodels.c
This PR fixes up warnings in the main raylib project when used in Visual Studio 2022.
Changes are
* Typical float/int/unsigned casting issues
* Had to use time_t for the time type in the shader hotload example, a long won't work, the platform may be using a 64 bit time structures
* Disabled CRT warnings in some new examples
* Fixed compute shader project (it was not building anything at all)
> [BUILD] Fix MSVC warnings and bad project settings for 4.5 release

- src/raudio.c
- src/raylib.h
- src/rcore.c
- src/rtext.c
- src/rtextures.c
I found I kept on re-checking what data within the structs to check in order to make sure assets were loaded successfully. Is it `.data != NULL`? `.buffer`? Having consistent helper methods will make it easier to check if the assets are ready for use. These match the `IsWindowReady()` pattern...
```
IsAudioStreamReady()
IsShaderReady()
IsImageReady()
IsFontReady()
IsWaveReady()
IsSoundReady()
IsMusicReady()
```
These arn't really needed, but they do clean up the code, and make it easier to read. I was unsure how to verify `IsModelReady()` as on failure, it loads default data. Should we just check if it's the default model?
> Add IsReady() methods to ensure assets loaded successfully

- parser/raylib_parser.c
Without that increase I get:
Number of text lines in buffer: 1589
malloc(): corrupted top size
core dumped
> Raylib.h has exceeded 512 functions!

- src/raylib.h
- src/rmodels.c
- src/rtextures.c
Following #2892, this adds the following functions to check if the objects are ready for use...
``` c
IsModelReady()
IsMaterialReady()
IsTextureReady()
IsRenderTextureReady()
```
> Add IsReady() for Model, Material, Texture, RenderTexture

- examples/Makefile
- examples/build.zig
- src/build.zig
Addresses #2884
This does create a `libraylib.a` using `zig build -Dtarget=wasm32-emscripten --sysroot /usr/local/opt/emscripten/libexec/` in `src` on macOS 13.2, but I couldn't yet get any programs to work with it.
> Add WASM support for Zig build

- src/rcamera.h
I believe this addresses #2660 and maybe #2661 though I'm not sure. Maybe I was just misusing the library.
Moving the assignment of the camera's y value to ``playerEyesPosition`` before the projection matrix was applied a.) made more sense to me and b.) fixed a weird issue I was having with v4.2.0 where mouse movement would move the player in a very small range *if* the playerEyesPosition ever changed from what it was initialized at.
I am on linux and have only tested the build on linux. Works well, though, and resolved my issues.
> [core]  rcamera bugfix - messed up orientation

- src/rmodels.c
Fixes #2908 by using `MATERIAL_MAP_SPECULAR` as the map index, instead of using the incorrect map index `SHADER_LOC_COLOR_SPECULAR`.
> fix DrawMesh using SHADER_LOC_COLOR_SPECULAR as a material map (#2908)

- build.zig
- examples/build.zig
- src/build.zig
Version: approximately usable at `zig 0.11.0-dev.1571+c1f71963a`.
Also, adds package manager support (early MVP).
We need to add root build zig file to support Zig Package Manager. Once package manager gets support for overidding build root directory - we can move this logic in `src/build.zig` and remove root `build.zig`.
Also, now every build artifacts must accept target and optimize arguments, so it is also adjusted.
For now, there is not much info about how to use package manager in Zig, so I will leave it here:
Create `build.zig.zon`:
```zig
.{
.name = "raylib_usage",
.version = "0.0.0",
.dependencies = .{
.raylib = .{
.url = "https://github.com/raysan5/raylib/archive/543333cae47c397f9bce93fe654aeba7cbe7e33d.tar.gz",
.hash = "1220a2bf5e5a53060256428b107b7a86077581861e9cb7b42c5083f44357 …
```
> Update zig build to latest master

- examples/build.zig
- src/build.zig
this is follow up of #2910.
i renamed deprecated functions/structs std.build.Builder and related stuff.
> zig build: do not use deprecated functions

- src/config.h
- src/minshell.html
- src/raudio.c
- src/raylib.h
- src/rcamera.h
- src/rcore.c
- src/rgestures.h
- src/rlgl.h
- src/rmodels.c
- src/rshapes.c
- src/rtext.c
- src/rtextures.c
- src/shell.html
- src/utils.c
As asked, I made fewer commits in this pull request. I will keep reviewing the project... And adding what I found in time. Let me know about your revision.
> Fixed some grammar mistakes and typos.

- src/rcamera.h
Moving camera after rotation is set, to avoid 1 frame delay in movement direction
> Move camera after rotation

- examples/models/models_billboard.c
- examples/models/models_cubicmap.c
- examples/models/models_heightmap.c
- examples/models/models_loading_vox.c
- examples/models/models_mesh_generation.c
- examples/models/models_rlgl_solar_system.c
- examples/shaders/shaders_basic_lighting.c
- examples/shaders/shaders_fog.c
- examples/shaders/shaders_hybrid_render.c
- examples/shaders/shaders_mesh_instancing.c
- examples/shaders/shaders_postprocessing.c
- examples/shaders/shaders_write_depth.c
- src/rcamera.h
This PR makes the orbital camera mode work like it used to before the change to the new camera system.
I think there was some confusion that the author of the camera system had about what the orbital camera did and they just made it a copy of the third person camera. It is not that. It is a always turning camera that has no other input. You move the camera by moving the camera manually.
This PR restores that functionality using the new camera logic.
Also during the camera update the cursor was disabled in all examples that used an orbit camera, possibly because they thought it was a third person camera. This PR restores the cursor because the mouse is not used with orbital camera.
With this PR all the demos should be back to working like they used to, with the new camera logic.
> [CAMEARA] Fix Orbital Camera Mode

- src/CMakeLists.txt
Changes the DLL export condition to apply to platform WIN32 instead of compiler MSVC.
Tested with:
Ninja with Clang 15.0.7
Ninja with MSVC 19.35
Visual Studio solution with MSVC 19.35
> fix(build): Fix DLL build on Windows

- src/Makefile
I have been able to build and run raylib applications on a [Pinebook Pro](https://www.pine64.org/pinebook-pro/), which uses a set of ARM64 processors. Currently, the Makefile and wiki indicate that the x86 and x86-64 platforms are the only supported platforms, but ARM64 *does* seem to be working.
Pong made with raylib running on a Pinebook Pro:
The one caveat is that I needed to set `LIBGL_ALWAYS_SOFTWARE=true` to force software rendering, as otherwise the application was unable to initialize the OpenGL context, producing a `GLXBadFBConfig` error:
However, I suspect this is a hardware issue with the Pinebook Pro, which is closer to a system-on-a-chip than a traditional desktop platform. I tested building raylib with OpenGL 1.1 support and still received the same error, which indicates to …
> Update Makefile comment to indicate arm64 as a supported Linux desktop platform

- src/rglfw.c
Building raylib 4.5 (with rglfw.c) on BSD platforms fails with missing symbol `_glfwPollPOSIX`.
The root cause seems to be that rglfw.c does not include `src/posix_poll.c` on BSD systems.
This commit adds the missing include and allows Raylib to successfully build on OpenBSD and FreeBSD atr least (I haven't tested on NetBSD).
> Fix missing include in rglfw.c on BSD platforms

- src/raudio.c
The `qoaplay_open()` function expects a `char *`, but we are passing in a `const char *`. While this works just fine, it does issue a compiler warning when strict:
```
src/raudio.c: In function ‘LoadMusicStream’:
src/raudio.c:1290:45: warning: passing argument 1 of ‘qoaplay_open’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
1290 |         qoaplay_desc *ctxQoa = qoaplay_open(fileName);
|                                             ^~~~~~~~
In file included from src/raudio.c:233:
src/external/qoaplay.c:86:34: note: expected ‘char *’ but argument is of type ‘const char *’
86 | qoaplay_desc *qoaplay_open(char *path)
|                            ~~~~~~^~~~
```
This change casts the argument to a `char *` to fix the warning.
> [raudio] Fix warning on discarded const qualifier

- src/external/qoaplay.c
- src/raudio.c
Function `qoaplay_open(char * path)` doesn't change the path it is given.
Therefore, it should be safe to add the const qualifier.
Avoids a compiler warning in rauido.c.
Tested on Win10+mingw-gcc 12.2 and Ubuntu-20.04 (on WSL2).
> Add const qualifier to char * path argument in qoaplay_open()

- BINDINGS.md
This updates a few different raylib bindings to 4.5.
- raylib
- node-raylib
- raylib-cpp
- raylib-umka
> BINDINGS: Update various versions to 4.5

- src/rtext.c
Calculate exact image size with a method based on total glyph width and glyph row count.
Current method seemed a little bit overkill with square root, log and power functions and only approximates image size which can be wonky with some weird fonts like cursive fonts.
Proposed method calculates image size directly with a simpler (and probably faster) method and results exact image size needed.
> Calculate exact image size in GenImageFontAtlas

- src/rtext.c
Basic packing algorithm currently follows this order: 
Copy pixel data -> Move offsetX for current glyph -> Check remaining space for current glyph... 
Since X offset already moved according current glyph, remaining space should be checked for the next glyph. Because of this, current logic causes glyphs wrapping around texture. 
Proposed change fixes that by moving offsetX check to the beginning of the loop.
> Fix packing logic error in ```GenImageFontAtlas```

- src/rtext.c
- src/rtextures.c
Fixes #2996 
- Fixed GetCodepointNext in the minimal way possible, when the first byte of an encoding is invalid '?' is now returned with size=0. Not all invalid input is replaced with '?' but the vast majority is
- Checked all usage of GetCodepointNext in rtext.c and rtextures.c, there are two places size==0 were not properly handled, LoadCodepoints() and GetCodepointPrev()
- LoadCodepoints() now handles size==0 the same as everywhere else in the code, without the fix there would have been a buffer overflow on invalid input
- Left GetCodepointPrev as-is
- Internally raylib should be fixed, but external code may break when encountering invalid input if they never properly handled size==0, for either GetCodepointNext or GetCodepointPrev
There's a few remaining issues to become bulletproof …
> [rtext] Fix GetCodepointNext() to return default value on invalid input with size=0

- src/raudio.c
- src/utils.c
This is another warning fixup for the raylib library.
one size_t casting issue, and disable some warnings on the qoi headers
> Build : Fix warnings in raylib for MSVC

- src/rshapes.c
When `i` starts with `0`, `t` is also `0`, which results in `previous == startPos == current`, this segment is not only redundant, but it also causes division-by-zero since `sqrtf(dx*dx + dy*dy)` is zero.
> Minor fix in DrawLineBezier*

- projects/CMake/core_basic_window.c
Hello, thanks for making this lib :)
> CMake project example: fix a couple of typos

- src/raudio.c
The current `ExportWaveAsCode()` has some various bugs/inconsistencies:
The data array name will list the **_entire_** path to the file. I don't know if ':', '/', and '\\' are valid symbols in C var names but I made it so only the file name without its path and extension are listed. Also, note the missing file names before the wave data information preprocessor defines, and the unusual data array var name casing.
Before:
After:
> [raudio] Rewritten `ExportWaveAsCode()` file saving to be more like rtextures `ExportImageAsCode()`

- examples/shapes/raygui.h
This use of offset 'i' should follow the range check.
> Fix offset used before range check

- src/rshapes.c
Checking `<= x + w` causes off-by-one error where `CheckCollisionPointRec` will return true at the same time for two rectangles rendered right next to each, but which don't overlap (e.g. when making a 2D tile editor). This is clearly not what was intended.
The convention for collision checks of this nature should always be lower bound inclusive and upper bound exclusive.
> Fix off-by-one error in CheckCollisionPointRec

- src/rcamera.h
Hello! This fixes the distance check in `CameraMoveToTarget` to avoid a 0 value. Thank you!
> Ensure distance is greater than 0 in CameraMoveToTarget

- src/rmodels.c
I had just noticed that the mapWidth and mapHeight values ​​were only used as a limit in the for loop while they could be used throughout the function.
> Correction of values ​​used only once in GenMeshCubicmap

- HISTORY.md
It's just a simple issue.
The old link led to an unregistered site (http://www.codecutter.net/tools/winbgim/). The actual domain has changed to (https://winbgim.codecutter.org/).  I checked the wayback machine, it's the same site, take a look: https://web.archive.org/web/20190421035959/http://www.codecutter.net/tools/winbgim/.
> WingBGI link in "HISTORY.md" now leads to the correct website!

- build.zig
- examples/build.zig
- src/build.zig
update for `zig 0.11.0-dev.2868+1a455b2dd` and upper
main changes:
- `lib.install()` or `exe.install()` replaced with `b.installArtifact`
- `lib.setOutputDir()` and `exe.setOutputDir()` are removed
- root `build.zig` just calls `src/build.zig`
All examples are working. But output path is set to default `zig-out`. There are some workarounds, but it requires to set CLI paramater `--prefix`, so it's kinda complicated.
> [zig build] update to latest zig master

- build.zig
- src/build.zig
I noticed the build.zig file wasn't working with the latest zig compiler. So I went ahead and fixed it. It went ahead and built fine on my linux machine, and I used the resulting library to compile the basic example, so I don't think there were any hidden errors.
(Small side note, is the zig build script community maintained? I'd want to add a notice to the build file itself if that was the case.)
> Fixed broken build.zig files.

- examples/models/models_loading_gltf.c
- src/raylib.h
- src/rmodels.c
- Added ModelAnimation.name in order to keep GLTF animation names.
- Updated models_loading_gltf, showing the name of the animation currently playing at the bottom
Why?
- In the creation of tools, it allows picking animations by name
- In the creation of a game, it allows choosing an animation to run by name instead of only by array position (currently by being based only by index position it's either error prone or confusing/hard).
> Store GLTF model animation names

- BINDINGS.md
Hey,
raylib-go released its 4.5 version  today: https://github.com/gen2brain/raylib-go/releases/tag/v4.5.0
> Update BINDINGS.md - raylib-go is 4.5 now

- src/rmodels.c
fileData wasn't freed for LoadModelAnimationsGLTF causing a memory leak. Added UnloadFileData line, freeing it.
With a test of just loading and unloading animations from a glb file; this change clears up the following memory leak reported via valgrind.
```
==7704== 
==7704== HEAP SUMMARY:
==7704==     in use at exit: 62,960 bytes in 1 blocks
==7704==   total heap usage: 193 allocs, 192 frees, 388,008 bytes allocated
==7704== 
==7704== 62,960 bytes in 1 blocks are definitely lost in loss record 1 of 1
==7704==    at 0x4842794: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==7704==    by 0x493EA95: LoadFileData (in /raylib/libraylib.so.450)
==7704==    by 0x48E0A1B: LoadModelAnimations (in /raylib/libraylib.so.450)
==7704==    by 0x10967E: main (animtest.c:22)
==7704== …
```
> Update rmodels.c; free fileData for LoadModelAnimationsGLTF

- src/rcore.c
Fixed that the Android application was not closed properly after calling `CloseWindow()` and continued to run.
**Edit**: I want to clarify the call to `exit(0)` in `android_main`. This will not be a problem in normal use of Raylib on Android, only if there are other processes in progress from Java/Kotlin this may in some cases not complete them, hence the precision in the comments, I hope it's pretty clear.
Otherwise, you have to handle closing the application through Java, which can complicate/messy things for the user. So I thought to myself that if a person would be able to tweak the Java code of his Raylib game, he would be able to do the right things to properly close his application.
> Fix Android app freeze after calling CloseWindow()

- examples/textures/textures_image_generation.c
- parser/output/raylib_api.json
- parser/output/raylib_api.lua
- parser/output/raylib_api.txt
- parser/output/raylib_api.xml
- projects/Geany/raylib.c.tags
- projects/Notepad++/raylib_npp_parser/raylib_npp.xml
- projects/Notepad++/raylib_npp_parser/raylib_to_parse.h
- src/raylib.h
- src/rtextures.c
This allows the user to create linear gradients with a single function. In addition to horizontal and vertical gradients this function also allows the user to create diagonal gradients and gradients in any direction in 360 degrees.
> Replaced GenImageGradientH and GenImageGradientV with GenImageLinearGradient

- FAQ.md
I noticed some file formats from the new release of raylib were missing so I decided to help out and update it!
added M3D model format and QOA file format to the list
> Add new file formats to FAQ

- src/build.zig
I've been using raylib for a game written in Zig, and the current build.zig works fine for me when building for my host, but when cross-compiling, the compile-raylib step fails with errors about not being able to find Xlib headers. This fixes it for me. (I am on Alpine Linux.)
> build.zig: Fix cross-compiling from Linux

- src/raylib.h
The color macros don't work properly in C++98, because they require
aggregate initialzation, which is a C++11 feature. So, explicitly state
how to fix this issue, instead of letting the compiler give a more vague
error message like:
main.cpp:8:23: error: expected '(' for function-style cast or type construction
ClearBackground(BLACK);
^~~~~
/opt/homebrew/Cellar/raylib/4.5.0/include/raylib.h:179:35: note: expanded from macro 'BLACK'
#define BLACK      CLITERAL(Color){ 0, 0, 0, 255 }         // Black
NOTE: Don't use this check with MSVC because by default, it reports
199711L  regardless of any C++ version passed on command line
Only passing `/Zc:__cplusplus` will make MSVC set this correctly
see: https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus
> Add error if raylib.h is included in a C++98 program

- src/rcamera.h
I Added Analog Stick Support to the rcamera module a Week or Two Ago, However looking back this code only allowed for 4 Directions of Movement, This Change adds the full range of Movement to the Right Analog Stick.
> Simple Analog Stick 8 Direction Fix

- src/external/vox_loader.h
I propose this small change to allow loading MagicaVox files in version 200. The Vox files saved by the MagicaVox editor have been in version 200 since version 0.99.7, although no specification for this new version can be found on the internet.
At the end of the message, I am including two links to support my statement, which seem to confirm that loading can still be done in the same way as with version 150 Vox files.
The only noticeable issue is that when exporting the file via the editor instead of saving it, it appears to have been compressed or minified, and therefore the first line containing "VOX " is not present. Even when removing this check, no voxel loads properly, so a solution to this problem would need to be found in the future. However, the strings "SIZE," "XYZI," and "RGBA" …
> Addition of support for vox files in version 200.

- src/rmodels.c
I ran across a GLTF file with animation data but no normals which caused raylib to segfault on a memcpy since normals were expected to be defined. This PR fixes it.
> GLTF: fix segfault in animNormals memcpy when mesh.normals == NULL

- src/build.zig
Support for compiling with `raygui`, `raymath`, and `physac`.
Also outputs the required headers.
`addRaylib` gains an additional positional argument that takes an Options struct.
Raygui should be located `../raygui` relative to the repo root
Physac should be located `../physac` relative to the repo root
These locations match the options in the Makefile
One step generates `src/raygui.c`, `src/raymath.c`, or `src/physac.c` with the `[lib]_IMPLEMENTATION` macro defined depending on which are enabled
> Add options to zig compile

- src/rtextures.c
Just a warning cleanup for MSVC2022
> Fix casting warnings in rtextures.c

- examples/Makefile
- examples/others/raymath_vector_angle.c
also expanded the makefile to add "others" as an option and to compile those examples by default. requires libglfw3, of course.
> fix vector angle example mode 0 circle segment drawing

- src/rcore.c
Adds normalization to `gestureEvent.position[i]` that was missing for `PLATFORM_WEB`.
Fixes https://github.com/raysan5/raylib/issues/3141.
> Fix swipe gestures for web

- src/rgestures.h
Adds `previousPositionA` and `previousPositionB` to the `rgestures.h`'s `Touch` struct to keep track of the previous Pinch positions. Didn't want to try to reuse `downPositionA` and `downPositionB` for this case to not break the other gestures that use them and are working properly.
Assign the values of `previousPositionA` and `previousPositionB` during the `event.touchAction == TOUCH_ACTION_DOWN` instead, so they can exist before the `event.touchAction == TOUCH_ACTION_MOVE`.
Removes the now no longer used `GESTURES.Touch.downPositionA` and `GESTURES.Touch.downPositionB` assigns inside the `event.touchAction == TOUCH_ACTION_MOVE`.
Changes the `MINIMUM_PINCH` check to now use the `previousPositionA` and `previousPositionB`.
Changes the criteria to define if it's `GESTURE_PINCH_IN` or …
> Fix pinch gestures for web

- src/rgestures.h
Changes `300` to `330` on `GESTURE_SWIPE_DOWN` to complete the 360° arc.
Changes `120` to `150` on `GESTURE_SWIPE_UP` and `GESTURE_SWIPE_LEFT` so they align with `330` and both have a 60° range.
Changes `>` to `>=` on `GESTURE_SWIPE_UP` and `GESTURE_SWIPE_DOWN` to catch the exact `30.0f`, `150.0f`, `210.0f` and `330.0f` degrees if they happen.
Fixes https://github.com/raysan5/raylib/issues/3154.
> Fix degrees of swipe gestures for web

- BINDINGS.md
I have a super lightweight Rust binding for raylib. Forgot to add it to the list, so here it is.
> Add raylib-ffi to bindings list

- src/rcore.c
Adds a reset for the `CORE.Input.Touch.pointCount` for web, if it was the last `EMSCRIPTEN_EVENT_TOUCHEND` event.
Fixes https://github.com/raysan5/raylib/issues/3100.
> Fix Touch pointCount for web

- .github/ISSUE_TEMPLATE/new-issue-template.md
Would like to suggest adding a new task to the issue template reminding users to check the documentation on the wiki. The information there is excellent and is possibly being overlooked.
> Add a new task the issue template about checking the wiki

- src/Makefile
Working from wsl and compiling for windows this change makes it much easier to compile a static library for windows on arm. To compile a static library for windows on arm:
```
make PLATFORM=PLATFORM_DESKTOP TARGET_OS=WINDOWS CROSS_CC=/llvm/bin/aarch64-w64-mingw32-gcc CROSS_AR=/llvm/bin/aarch64-w64-mingw32-ar
```
This does not work to compile a shared library yet, only static.
> Makefile change for cross compiling.

- src/rgestures.h
Adds a different check to detect `GESTURE_DRAG` for `PLATFORM_WEB`.
Adds a `DRAG_TIMEOUT` define for the previous check.
Adds `GESTURE_HOLD` to the check to update the `GESTURES.Touch.upPosition`.
Changes the default value of `FORCE_TO_SWIPE` to make it less twitchy for high sensitivity web browsers like Chrome for Android.
Fix https://github.com/raysan5/raylib/issues/3182.
> Fix GESTURE_DRAG and GESTURE_SWIPE_* issues (mostly) for web

- src/rshapes.c
Changes for fixing https://github.com/raysan5/raylib/issues/3180
Besides swapping sinf() and cosf(), the vertex order for quads and triangles was updated, so they would be visible.
Here is an example that I used to test if my changes were good, this includes all functions that were updated:
<details>
```c
// example.cpp
// Compiling:  g++ example.cpp -lraylib
#include <raymath.h>
int main() {
InitWindow(800, 800, "Reproduction");
while (!WindowShouldClose())
{
float angle = (int)(GetTime()*100) % 360;
DrawCircleSector({ 150, 100 }, 50, 0, angle, 5, BLACK);
DrawCircleLines(150, 100, 50, BLACK);
DrawCircleSectorLines({ 300, 100 }, 50, 0, angle, 5, BLACK);
DrawCircleLines(300, 100, 50, BLACK);
DrawRing({ 450, …
```
> Update usage of 'sinf()' and 'cosf()' to be correct

- src/raylib.h
There is a comment in the example https://github.com/raysan5/raylib/blob/d6f16b76649944f65491633a75ad648a6ddfdacf/examples/audio/audio_mixed_processor.c#L26 about this, but it is more discoverable in the API docs.
> Document buffer format for audio processors.

- src/raylib.h
Please excuse the noise, I should have included this in the previous PR https://github.com/raysan5/raylib/pull/3186 instead of asking there whether I should do it. I wasn’t sure whether the buffer passed to `AttachAudioStreamProcessor()` always used the same type as `AttachAudioMixedProcessor()` although it looked like that in the example.
I’ve been reading carefully the example for `AttachAutdioStreamProcessor()` and the source code, and it is now clear to me that this function too uses `float` for the samples in `buffer`.
> Add note about sample format to AttachAudioStreamProcessor()

- src/rtextures.c
A significant performance increase can be had by copying the first row to all other rows.
> Optimization of ImageDrawRectangleRec()

- src/rgestures.h
**Optimize and simplify the gesture system** does:
1. Stops `GESTURE_DRAG` from triggering `GESTURE_HOLD` on `UpdateGestures()` ([L439-L445](https://github.com/raysan5/raylib/pull/3190/files#diff-ce52e9b8602ff61fde52fcdd30064097c84ee6583a4f08bd155922349424a5c1L439-L445)). "hold" is not needed for "drag". Simplifies "drag" handling while keeping its funcionality.
2. Removes `GESTURES.Touch.eventTime` update for `GESTURE_DRAG` ([L336](https://github.com/raysan5/raylib/pull/3190/files#diff-ce52e9b8602ff61fde52fcdd30064097c84ee6583a4f08bd155922349424a5c1L336)) since it no longer needs to trigger `GESTURE_HOLD` on `UpdateGestures()`.
3. Removes `GESTURES.Touch.firstId` updating from `TOUCH_ACTION_DOWN` ([L295](https://github.com/raysan5/raylib/pull/3190/files#diff-ce52e9b8602ff61fde52fcdd300640 …
> Optimize and simplify the gesture system

- src/rcore.c
In the meantime (just to not leave the mouse wheel broken) I think the problem was sharing the same variable for holding both "the event" and "the current" value since they run independently.
`GetMouseWheelMove()` returns the `CORE.Input.currentWheelMove` ([L3949-L3959](https://github.com/raysan5/raylib/blob/master/src/rcore.c#L3949-L3959)). But that is always zeroed by `PollInputEvents()` ([L5065](https://github.com/raysan5/raylib/blob/master/src/rcore.c#L5065)) when it runs on `EndDrawing()`. So the `event.value` ([L6680](https://github.com/raysan5/raylib/blob/master/src/rcore.c#L6680)) never ends up staying on `CORE.Input.currentWheelMove` long enough before it gets zeroed. This could be solved by storing the `event.value` in a new `CORE.Input.eventWheelMove` …
> Fix mouse wheel not working in PLATFORM_RPI or PLATFORM_DRM

- src/rmodels.c
The root cause of issue #3197 seems to be that having only one dimension with a negative value in `source` or `size` causes the vertex order of the billboard to become clockwise, which cannot be rendered correctly when backface culling is enabled. This PR should allow `source` and `size` with any negative dimensions to be rendered correctly, and flipped as expected.
> Re-fix `DrawBillboardPro` to allow `source` of negative size (#3197)

- src/rtextures.c
Passing any other layout than `CUBEMAP_LAYOUT_AUTO_DETECT` to `LoadTextureCubemap` loads an empty texture with 0 by 0 dimensions. This is because the size of each face is caculated like so
```c
int size = cubemap.width;
```
but `cubemap` is zero initialized and only set when auto detecting the layout.
This PR fixes this issue, by manually setting the width for each layout.
> [textures] Fix LoadTextureCubemap for manual layouts

- src/raylib.h
- src/rcore.c
Since invoking `glfwSetWindowMonitor()` ([L1676](https://github.com/raysan5/raylib/pull/3209/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339L1676)) forces fullscreen, changes `SetWindowMonitor()` to instead move the window to the defined monitor.
To move the window it checks if the screen size is larger than the monitor [workarea](https://www.glfw.org/docs/3.3/group__monitor.html#ga7387a3bdb64bfe8ebf2b9e54f5b6c9d0) ([R1684-R1693](https://github.com/raysan5/raylib/pull/3209/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R1684-R1693)). If it is larger, then anchors it on the top left corner ([R1693](https://github.com/raysan5/raylib/pull/3209/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R1693)), otherwise, …
> Changes SetWindowMonitor() to no longer force fullscreen

- src/Makefile
Since **API_VERSION** not exist   libraylib.$(**API_VERSION**).so  is equal to  libraylib..so
> Fix android soname in src/Makefile

- BINDINGS.md
Hi everyone, I made a standalone Javascript interpreter based on [QuickJS](https://bellard.org/quickjs/) with bindings for [Raylib](https://www.raylib.com/) and would like to add it to the list.
> Update BINDINGS.md to include rayjs

- src/rcore.c
Changes the `GetCurrentMonitor()` to use `glfwGetMonitorPos()` ([R1839](https://github.com/raysan5/raylib/pull/3215/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R1839)) and `glfwGetVideoMode()` ([R1840-R1844](https://github.com/raysan5/raylib/pull/3215/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R1840-R1844)) instead of `glfwGetMonitorWorkarea()` ([L1842](https://github.com/raysan5/raylib/pull/3215/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339L1842)) for non-fullscreen monitor detection on `PLATFORM_DESKTOP`.
Fixes https://github.com/raysan5/raylib/issues/3213.
**Edit:** added line marks.
> Fixes GetCurrentMonitor() detection inconsistency issue

- src/rcore.c
This PR fixes two float to int casting warnings in rcore. All the arguments are ints, so the divide should be ints too.
> integer to float warnings in rcore

- src/raylib.h
- src/rcore.c
Adds the `FLAG_BORDERLESS_WINDOWED_MODE` flag to the `ConfigFlags` enum ([R529](https://github.com/raysan5/raylib/pull/3216/files#diff-008ec254b9e10087d979356eaa799f93f24b3173a6a0c44445c24fee791a1e90R529)).
Adds `CORE.Window.previousPosition` and `CORE.Window.previousScreen` to the `CoreData.Window` struct ([R415-R416](https://github.com/raysan5/raylib/pull/3216/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R415-R416)).
Adds `ToggleBorderlessWindowed()` ([R951](https://github.com/raysan5/raylib/pull/3216/files#diff-008ec254b9e10087d979356eaa799f93f24b3173a6a0c44445c24fee791a1e90R951), [R1329-R1403](https://github.com/raysan5/raylib/pull/3216/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R1329-R1403)) to handle the …
> Adds BORDERLESS_WINDOWED_MODE for PLATFORM_DESKTOP

- CMakeOptions.txt
- cmake/CompileDefinitions.cmake
Adds `SUPPORT_CUSTOM_FRAME_CONTROL` CMake option to `CMakeOptions.txt` and `cmake/CompileDefinitions.cmake`.
@jestarray @raysan5 I tested it and I think this is correct, but I don't use CMake much, could you please check if I didn't miss anything?
Minimal reproduction code to test the change:
```
cd raylib/
mkdir build
cd build
cmake -DCUSTOMIZE_BUILD:BOOL=ON -DSUPPORT_CUSTOM_FRAME_CONTROL:BOOL=ON ..
cmake --build .
./examples/core_custom_frame_control
```
Fixes https://github.com/raysan5/raylib/issues/3201.
> Adds CMake option for SUPPORT_CUSTOM_FRAME_CONTROL

- src/raylib.h
- src/rcore.c
`SetWindowTitle` and `InitWindow` will now change the current tab name of the browser, if compiled for the web platform.
They use the emscripten function `emscripten_set_window_title`.
As stated in the header file, the `SetWindowTitle` function works only for desktop.
But this feature can be useful also on the web, for example by setting the tab title to the one of your game/app to make it more recognizable without having to change the title manually in the HTML file or interacting directly with emscripten.
Tested on Windows 11 with the latest version of emscripten on chrome with raylib's basic window example with no errors nor code changes.
> [CORE] Support for SetWindowTitle and InitWindow for web

- src/raudio.c
- src/raylib.h
This PR adds a function that makes an alias from an existing sound. The new sound has a pointer to the sound buffer used by the donor sound and does not own the sample buffer memory.
Since PlaySoundMulti was removed, this feature makes it easy to make shallow copies of sounds that can be played multiple times with out the need to load multiple copies of the sample data. Since each sound is still it's own audio buffer, the sound instances are controllable with the existing sound API.
> [AUDIO] Add a function to make an alias of a sound and share it's sample data

- src/build.zig
I made a similar change a while ago (#3090), but the same failure mode has reappeared for me when cross-compiling. I suspect the recent Zig updates have changed requirements. In particular, I see:
```
zig build-lib raylib Debug x86_64-linux-musl: error: error: unable to find Dynamic system library 'GL' using strategy 'paths_first'. searched paths: none
error: unable to find Dynamic system library 'X11' using strategy 'paths_first'. searched paths: none
```
This patch fixes it for me. I suspect similar changes are necessary for the other targets, but I only added this one because I haven't tested building from other targets.
> Tweak build.zig to work with cross-compiling

- src/rcore.c
**The problem mentioned in issue #3127 has been fixed.**
1. The fact that the application remains in the background despite the end of `android_main` and activities. *(it seems that this is a normal behavior of android to reload resources faster and that this is not managed from the same way depending on the system. I would have to try on a second device to see how it handles it)*.
2. When we called `CloseWindow()` at the end of our program `APP_CMD_TERM_WINDOW` was also "called" *(like when we quit the application without closing it)* but given that the context was already destroyed, the second calls surface destruction, etc. led to a first `EGL_BAD_DISPLAY` error.
3. Again in `APP_CMD_TERM_WINDOW`, after destroying the surface, we set `contextRebindRequired` to true, the application …
> Fixed Android app black screen issue when reopening after incomplete closing

- src/rcore.c
- current behavior is to check if only the ctrl modifier is active, the result is that gif recording will not work if num or caps lock are active, which seems like a bug to me.
- note: this fix allows other modifiers to be set at the same time (ctrl+shift+f12 will also trigger gif recording).
I don't consider this as a problem, but if you want I can explicitly remove the caps/num lock bits and _after_ that check if `mods` is _equal_ to `GLFW_MOD_CONTROL`
> fix: gif recordering doesn't work if num/caps lock is active.

- src/rcore.c
corrects all instances of:
'acording' > according
'usualy' > usually
'aprtially' > partially
'dettach' > detach
> Fix typos in rcore.c comments

- src/rtext.c
- src/rtextures.c
Removes existing unused function warnings generated when compiling functions declared with `static` linkage in external headers. This changeset suppresses warnings with a set of pragmas around external header includes using the pattern:
```c
#if defined(__GNUC__) // GCC and Clang
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-function"
#endif
// include the libraries here
#if defined(__GNUC__) // GCC and Clang
#pragma GCC diagnostic pop
#endif
```
This significantly reduces the warning noise when compiling on Linux, and has been tested with `CC=gcc` and `CC=clang`. I do not have a machine with MSVC set up, so I cannot test or confirm the behavior on Windows, but the `#if defined(__GNUC__)` guard *should* only have an effect with GCC and Clang and not produce any …
> Ignore unused function warnings from external headers when compiling with GCC and Clang
