raysan5/raylib

- src/rmodels.c
- src/rshapes.c
- src/rtext.c
Found around 6 comment typos in rmodels, rshapes, and rtext modules.
I accidentally undid these changes (and more I believe) at one point so there may be something I missed. If thats the case then let me know.
rmodels:
-  'dyamond' > diamond
- 'verted' > vertex
- 'attibute' > attribute
- (_not a typo but im lengthening it just in case, so it doesnt get confused with quad_) 'quat' > quaternion
rshapes:
- 'missused' > misused
rtext:
- 'fo' > to
> fix typos in rmodels, rshapes, rtext modules

- src/rcamera.h
This PR address part of _"REVIEW: Example: core_3d_camera_free. Displayed controls do not match and camera behaves strangely."_ from https://github.com/raysan5/raylib/discussions/2952.
1. Fixes `CAMERA_FREE` behaving strangely (unintended rolling while yawing and pitching) by setting `rotateUp` to `false` ([R439](https://github.com/raysan5/raylib/pull/3240/files#diff-cb37d550d2b398139f0ed2cebf04598776b16fa58107b4b4b7b7099280a67db5R439)). This change does not impact the other cameras, because `rotateUp` is already `false` for them.
2. Fixes `CAMERA_FREE` mouse wheel zoom by adding it to the zoom mode check ([R503](https://github.com/raysan5/raylib/pull/3240/files#diff-cb37d550d2b398139f0ed2cebf04598776b16fa58107b4b4b7b7099280a67db5R503)).
3. Adds pan to `CAMERA_FREE` by adding handling for …
> Fix rcamera.h issues

- examples/Makefile
After seeing the lastest revision on the wiki's [Working-on-GNU-Linux](https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux), tried compiling all examples and indeed encountered an error:
```
~$ cd test/
~/test$ ls
raylib-master.zip
~/test$ unzip raylib-master.zip
[...]
~/test$ cd raylib-master/src/
~/test/raylib-master/src$ make PLATFORM=PLATFORM_DESKTOP
[...]
ar rcs ../src/libraylib.a rcore.o rshapes.o rtextures.o rtext.o utils.o rglfw.o rmodels.o raudio.o
raylib static library generated (libraylib.a) in ../src!
~/test/raylib-master/src$ cd ../examples/
~/test/raylib-master/examples$ make PLATFORM=PLATFORM_DESKTOP
[...]
others/rlgl_standalone.c:70:10: fatal error: GLFW/glfw3.h: No such file or directory
70 | #include "GLFW/glfw3.h"         // Windows/Context and inputs management …
```
> Fix examples/others/rlgl_standalone.c compilation issue

- src/rtext.c
Removes the last warning from non-external libraries when compiling with the default build configuration on x64 Linux.
> Ignore unused return value of GetCodepointNext in GetCodepointCount

- examples/text/text_unicode.c
The issue causing the `examples/text/text_unicode.c` to crash on `PLATFORM_WEB` was the `Line Feed (LF)` char `\x0A` on some entries of `messages[]` ([L71](https://github.com/raysan5/raylib/blob/master/examples/text/text_unicode.c#L71), [L77](https://github.com/raysan5/raylib/blob/master/examples/text/text_unicode.c#L77), [L78](https://github.com/raysan5/raylib/blob/master/examples/text/text_unicode.c#L78), [L79](https://github.com/raysan5/raylib/blob/master/examples/text/text_unicode.c#L79), [L80](https://github.com/raysan5/raylib/blob/master/examples/text/text_unicode.c#L80), [L81](https://github.com/raysan5/raylib/blob/master/examples/text/text_unicode.c#L81), [L119](https://github.com/raysan5/raylib/blob/master/examples/text/text_unicode.c#L119), …
> Fix text_unicode.c example crashing

- src/build.zig
This adds the ability to select only some of the modules of raylib.
The motivation is that I had an issue with using miniaudio myself & I was missing all the decoding functionality (since `MA_NO_WAV`, `MA_NO_FLAC`) etc are defined in `raudio.c`
> add build.zig options for individual modules

- src/raylib.h
- src/rcore.c
Hi Ray!
Currently `IsKeyPressed` ignores key repeats. This PR keeps the current behavior the same while adding the additional `IsKeyPressedRepeat`.
Another approach could be changing the existing `IsKeyPressed` functionality to take into account key repeats as well, and add `IsKeyPressedExt`, expecting an extra `bool repeat` flag for taking into account key repeats or not.
Personally I would be in favor of the second approach (changing existing behavior), but it's up for discussion.
> Add `IsKeyPressedRepeat` (desktop only)

- src/rcore.c
When setting the flag `FLAG_VSYNC_HINT` with `SetConfigFlags` the warning
> emscripten_set_main_loop_timing: Cannot set timing mode for main loop since a main loop does not exist! Call emscripten_set_main_loop first to set one up.
caused by `glfwSwapInterval(1)` won't appear anymore.
This fix was [already added](https://github.com/raysan5/raylib/commit/0bacc978c39a234da4a2b73ce3cb5b43e072a103) into the source code of raylib but it was since then removed.
I think it was accidental since adding this fix to my up-to-date local build of raylib fixed the problem and didn't seem to cause any problems on platforms that do "support" VSync like desktop.
> [CORE] Fix the emscripten_set_main_loop_timing warning when enabling VSync on web

- src/rcore.c
So, to the best of my knowledge and as deep as I could dig, the cause of the issue is as following:
1. `text` ([L2145](https://github.com/raysan5/raylib/blob/master/src/rcore.c#L2145)) has the correct string;
2. If `text` contains a `\n`, it will be passed exactly as `\n` to `emscripten_run_script()` ([L2153](https://github.com/raysan5/raylib/blob/master/src/rcore.c#L2153));
3. So, instead of this:
```
str = "This is\na test."
```
4. It will end up like this (on the JS string):
```
str = "This is
a test."
```
5. And that will cause a `SyntaxError: unterminated string literal` ([excellent example/demo here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unterminated_string_literal#multiple_lines)).
6. And, incidentally, confirms why using `backticks` `template …
> Fix SetClipboardText for web

- src/raymath.h
Add two useful vector operations, Projection and Rejection to Raymath.
> Add Vector3 Projecting and Rejection to Raymath

- src/rlgl.h
I've tested this on every browser that I tested in issue #3260 and default example works on all of them.
> Fix bug where default shaders was not linking.

- cmake/InstallConfigurations.cmake
Closes #3265.
The problem: LIBS_PRIVATE is a list of library names (used by pkg-config), but the shared library of the same name doesn't always exist. In this case, `pkg-config glfw` is valid, while `-lglfw` is not. Therefore, `library_path_to_linker_flags` can't be used, since `LIBS_PRIVATE` are not executable library names.
I'm not sure if this doesn't break other platforms (other than Linux). @raysan5, can you find someone good at CMake to look at this?
> Fix CMake extraneous -lglfw

- examples/models/models_loading_gltf.c
Hello,
The ["UP/DOWN arrow keys to switch animation"](https://github.com/raysan5/raylib/blob/master/examples/models/models_loading_gltf.c#L66-L67) binds on [models_loading_gltf.c](https://github.com/raysan5/raylib/blob/master/examples/models/models_loading_gltf.c) conflict (overlap) with the [camera controls](https://github.com/raysan5/raylib/blob/master/src/rcamera.h#L452-L453).
This pull request rebinds them to _"LEFT/RIGHT mouse buttons to switch animation"_.
Best regards.
> Fix example/models/models_loading_gltf.c controls

- examples/models/models_loading_m3d.c
Hello,
Some binds on [models_loading_m3d.c](https://github.com/raysan5/raylib/blob/master/examples/models/models_loading_m3d.c) conflict (overlap) with the [camera controls](https://github.com/raysan5/raylib/blob/master/src/rcamera.h#L480-L481).
This pull request rebinds them to:
| From                              | To                                |
| --------------------------------- | --------------------------------- |
| ["A to CYCLE THROUGH ANIMATIONS"](https://github.com/raysan5/raylib/blob/master/examples/models/models_loading_m3d.c#L83) | "C to CYCLE THROUGH ANIMATIONS" |
| ["S to toggle SKELETON DRAWING"](https://github.com/raysan5/raylib/blob/master/examples/models/models_loading_m3d.c#L95)  | "B to toggle SKELETON DRAWING" |
Also adds the missing "PRESS N to STEP ONE …
> Fix example/models/models_loading_m3d.c controls

- examples/shaders/resources/shaders/glsl100/wave.fs
- examples/shaders/resources/shaders/glsl330/wave.fs
- examples/shaders/shaders_texture_waves.c
- src/rcore.c
Found these while working on my binding
> Remove e from secondes

- examples/Makefile
- examples/Makefile.Web
Hello,
This pull request includes [examples/shaders/shaders_lightmap.c](https://github.com/raysan5/raylib/blob/master/examples/shaders/shaders_lightmap.c) to the Makefiles ([Makefile](https://github.com/raysan5/raylib/blob/master/examples/Makefile), [Makefile.Web](https://github.com/raysan5/raylib/blob/master/examples/Makefile.Web)), since it was missing.
Best regards.
> Add examples/shaders/shaders_lightmap.c to Makefiles

- src/build.zig
Zig debug builds automatically enable ubsan.
As the fix for #1891 had to be reverted, debug builds using zig will crash like so:
```
Illegal instruction at address 0x3237d2
raylib/src/rlgl.h:3690:91: 0x3237d2 in rlDrawVertexArrayElements (/home/rcorre/src/raylib-zig-template/raylib/src/rcore.c)
glDrawElements(GL_TRIANGLES, count, GL_UNSIGNED_SHORT, (const unsigned short *)buffer + offset);
```
This disables UBSAN when using zig to build raylib.
> Disable UBSAN in zig builds.

- CMakeOptions.txt
Hello,
This pull request updates the `SUPPORT_FILEFORMAT_SVG` default value on [CMakeOptions.txt](https://github.com/raysan5/raylib/blob/master/CMakeOptions.txt) to match https://github.com/raysan5/raylib/commit/c104a975904f23d011cb6072f98945b8d38eff17.
Best regards.
> Update cmake SUPPORT_FILEFORMAT_SVG default value

- src/build.zig
This reverts commit a316f9e7fc7f8e06852a40544e57f89018672ee4.
Issue #1891 was fixed again, so this is no longer needed.
> Revert "Disable UBSAN in zig builds. (#3292)"

- src/rtextures.c
Rather than the source becoming the inverse of the destination, we should instead minus it from the source coordinates. This is usually not a problem when rendering entire images or when there is scaling. However, it is an issue when your source rectangle starts at a coordinate away from `0,0`, and you're not scaling it.
This change fixes the source rectangle mapping to have it change bassed on the destination coordinate, rather than just becoming inverse of the destination.
Fixes #3259
> Fix ImageDraw() source clipping when drawing beyond top left

- src/rcore.c
Fixes #3231
Previously, this callback was unused, and also had no effect upon being uncommented.
> Implement FLAG_WINDOW_RESIZABLE for web

- BINDINGS.md
`claw-raylib` is a fully automated Raylib/Raygui binding that I recently developed for Common Lisp.
> Add claw-raylib to BINDINGS.md

- src/raylib.h
- src/rcore.c
- Adds `SetWindowMaxSize()` for both `PLATFORM_DESKTOP` and `PLATFORM_WEB`.
- Changes `SetWindowMinSize()` so it can work alongside `SetWindowMaxSize()` keeping current compatibility.
- Finishes fixing https://github.com/raysan5/raylib/issues/3231.
1. Adds a `windowMin` and `windowMax` member to `CORE.Window` ([R399-R400](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R399-R400)). This was necessary because although `GLFW` has a `glfwSetWindowSizeLimits()`, it doesn't have a `glfw*GET*WindowSizeLimits()` yet. And also because both `PLATFORM_DESKTOP` and `PLATFORM_WEB` needed a common dataset to be able to share the same functions.
<br>
2. Adds  `SetWindowMaxSize()` …
> Add SetWindowMaxSize for desktop and web

- src/rcore.c
Renames `windowMin` to `screenMin` and `windowMax` to `screenMax` as per https://github.com/raysan5/raylib/pull/3309#issuecomment-1717766328.
> Rename windowM* to screenM*

- BINDINGS.md
I learned about this repository [by absolute chance](https://github.com/a0/raylib-ruby/issues/4). While https://github.com/a0/raylib-ruby has the most idiomatic Ruby bindings, it targets an older version of Raylib and Ruby.
https://github.com/vaiorabbit/raylib-bindings seems quite active. I tried a few examples and they worked with no issues!
> Update BINDINGS.md with vaiorabbit/raylib-bindings

- BINDINGS.md
Long overdue, but better late than never
> Update raylib-ocaml bindings to 4.5 version

- src/raudio.c
This is the solution proposed by @mackron in response to the crash issue on Android after reopening the application, which was discussed on Discord and here: https://github.com/mackron/miniaudio/issues/733
The solution was to move the mutex initialization before `ma_device_start`.
I have tested it on my end, and it has successfully resolved the issue for me.
> Move mutex initialization before `ma_device_start()`

- src/rlgl.h
I managed to trigger the ubsan by simply calling `LoadRenderTexture(1280, 720);` from zig. Looking at recent PR's and issues it seems like this issue has already been mitigated elsewhere, but still exists in the codepath for LoadRenderTexture.
All I did was apply a similar fix (as seen in 30a9a24db9d2561335a2a42d423cf9cfeab6e769) for #1891 to the rLoadTextures function. This seems to fix the issue.
> Added UBSAN complaint fix to rLoadTexture #1891

- examples/Makefile
- examples/core/core_input_gestures_web.c
- src/rcore.c
- src/rcore.h
1. Fixes compilation for `PLATFORM_WEB` ([R12](https://github.com/raysan5/raylib/pull/3329/files#diff-7341b65fe444443a67b5c67d194f97dd0c919b63c579f15ce018de206cf84864R12)). `#include "GLFW/glfw3.h"` ([R15)](https://github.com/raysan5/raylib/pull/3329/files#diff-7341b65fe444443a67b5c67d194f97dd0c919b63c579f15ce018de206cf84864R15) is necessary for `CoreData`'s `GLFWwindow *handle;` ([R109](https://github.com/raysan5/raylib/pull/3329/files#diff-7341b65fe444443a67b5c67d194f97dd0c919b63c579f15ce018de206cf84864R109)) on `PLATFORM_WEB`.
2. Removes `EM_ASM_INT` from `core_input_gestures_web` example ([L311-L317](https://github.com/raysan5/raylib/pull/3329/files#diff-6bb5ee6018759da67168502ea865172f16f99f175c871a405024c1a219b85d87L311-L317)) as per …
> [split] Fix compilation for web (and desktop)

- src/rcore.c
- src/rcore.h
- src/rcore_desktop.c
- src/rcore_web.c
1. Fixes formatting on `rcore_web.c` so it's easier to compare with current master branch `rcore.c`.
On `rcore_web.c`: [R86](https://github.com/raysan5/raylib/pull/3334/files#diff-5204360a69ae27d12753764f60a1cd59e3a11ef10b86fce7691c74de0becc8cdR86), [R107](https://github.com/raysan5/raylib/pull/3334/files#diff-5204360a69ae27d12753764f60a1cd59e3a11ef10b86fce7691c74de0becc8cdR107), [R212](https://github.com/raysan5/raylib/pull/3334/files#diff-5204360a69ae27d12753764f60a1cd59e3a11ef10b86fce7691c74de0becc8cdR212), [R226](https://github.com/raysan5/raylib/pull/3334/files#diff-5204360a69ae27d12753764f60a1cd59e3a11ef10b86fce7691c74de0becc8cdR226), [R262](https://github.com/raysan5/raylib/pull/3334/files#diff-5204360a69ae27d12753764f60a1cd59e3a11ef10b86fce7691c74de0becc8cdR262), …
> [split] `rcore`, `rcore_web` and `rcore_desktop` changes (batch 2)

- src/raymath.h
This is so the functions can be easily copied and used. This was discussed in a separate pull:
https://github.com/raysan5/raylib/pull/3319#issuecomment-1722461911
> [raymath] Added macros for EPSILON on each function it's used in

- src/rcore.c
- src/rcore_android.c
- src/rcore_desktop.c
- src/rcore_web.c
1. First pass to remove unneeded platform macros for `PLATFORM_WEB`.
On `rcore_web.c`: [R353](https://github.com/raysan5/raylib/pull/3338/commits/b36a838e287dec2d3fe616d2150798b8f51e1ed5#diff-5204360a69ae27d12753764f60a1cd59e3a11ef10b86fce7691c74de0becc8cdR353), [R366-R368](https://github.com/raysan5/raylib/pull/3338/commits/b36a838e287dec2d3fe616d2150798b8f51e1ed5#diff-5204360a69ae27d12753764f60a1cd59e3a11ef10b86fce7691c74de0becc8cdR366-R368), [R411-R430](https://github.com/raysan5/raylib/pull/3338/commits/b36a838e287dec2d3fe616d2150798b8f51e1ed5#diff-5204360a69ae27d12753764f60a1cd59e3a11ef10b86fce7691c74de0becc8cdR411-R430), [R455-R457](https://github.com/raysan5/raylib/pull/3338/commits/b36a838e287dec2d3fe616d2150798b8f51e1ed5#diff-5204360a69ae27d12753764f60a1cd59e3a11ef10b86fce7691c74d …
> [split] `rcore`, `web`, `desktop`, `android` changes (batch 3)

- src/rcore_android.c
- src/rcore_desktop.c
- src/rcore_web.c
1. Fixes `ToggleBorderlessWindowed` duplicated `glfwSetWindowSize` calls as per https://github.com/raysan5/raylib/pull/3216#discussion_r1334832946.
On `rcore_desktop.c`: [L714](https://github.com/raysan5/raylib/pull/3343/files#diff-10e13300b4588e538a0c2c603707242b63d716e3ab2b80b81db9a54c308ca3acL714).
2. First and second passes to remove unneeded platform macros for `PLATFORM_ANDROID`.
On `rcore_android.c`: [L148-L477](https://github.com/raysan5/raylib/pull/3343/files#diff-df7f2529f920b22e7f3b28d8c53b9042fe9ba3e0c4be0a421ac8d9e0c3bde72dL148-L477), [L479](https://github.com/raysan5/raylib/pull/3343/files#diff-df7f2529f920b22e7f3b28d8c53b9042fe9ba3e0c4be0a421ac8d9e0c3bde72dL479), [L483-L642](https://github.com/raysan5/raylib/pull/3343/files#diff-df7f2529f920b22e7f3b28d8c53b9042fe9ba3e0c4be0a …
> [split] `rcore`, `web`, `desktop`, `android` changes (batch 4)

- src/rcore.c
- src/rcore_android.c
- src/rcore_desktop.c
- src/rcore_web.c
1. Moves `SetExitKey` from `rcore.c` ([R1940-R1947](https://github.com/raysan5/raylib/pull/3345/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R1940-R1947)) to `rcore_android.c` ([R1052-R1057](https://github.com/raysan5/raylib/pull/3345/files#diff-df7f2529f920b22e7f3b28d8c53b9042fe9ba3e0c4be0a421ac8d9e0c3bde72dR1052-R1057)), `rcore_desktop.c` ([R1515-R1520](https://github.com/raysan5/raylib/pull/3345/files#diff-10e13300b4588e538a0c2c603707242b63d716e3ab2b80b81db9a54c308ca3acR1515-R1520)), `rcore_web.c` ([R1044-R1049](https://github.com/raysan5/raylib/pull/3345/files#diff-5204360a69ae27d12753764f60a1cd59e3a11ef10b86fce7691c74de0becc8cdR1044-R1049)). **Note:** instead of deleting it from `rcore.c` just commented it to keep as reference. Will clean up later.
2. …
> [split] `rcore`, `web`, `desktop`, `android` changes (batch 5)

- BINDINGS.md
I looked at the linked Factor binding page for Raylib and found that the file [summary.txt](https://github.com/factor/factor/blob/master/extra/raylib/summary.txt) has the following text in it:
```
Bindings for Raylib 4.5
```
The bindings have also been updated within the last week.
This implies that Factor's Raylib bindings are either already up to date with v4.5 or will be soon.
Thus, I have submitted this likely correction to Raylib's bindings table.
(PS: There are other Factor Raylib bindings on the internet that are less up-to-date, so don't confuse those with this.)
> Factor's Raylib bindings mention being at v4.5 now.

- src/rcamera.h
The rcamera functions were not exported to the dll, and thus are not available to users of the DLL or bindings that must link dynamically.
This PR exports them the same as other raylib modules.
> [rcamera] DLL Exports

- BINDINGS.md
I am going to use raylib to make my games with [pocketpy](https://github.com/blueloveth/pocketpy).
So I wrote a binding generator for it. See https://github.com/blueloveTH/pkpy-bindings.
It uses raylib's JSON format for describing the API.
The output files are based on `v4.6-dev` that located in:
+ [output/raylibw.cpp](https://github.com/blueloveTH/pkpy-bindings/blob/main/output/raylibw.cpp)
+ [output/typings/raylib.pyi](https://github.com/blueloveTH/pkpy-bindings/blob/main/output/typings/raylib.pyi)
There is also an [online version](https://pkpy-bindings.streamlit.app/).
> Update BINDINGS.md with raylib-pkpy-bindings

- src/rcore.c
I finished a commented TODO, which was to use Vector3Transform instead of quaternions.
I also realized during review that it was using CORE.Window.screen.width in one place instead of the inputted width. The input width is definitely the intended value to be placed there since the convenience function GetWorldToScreen gives screen width as input.
I have tested this with a few different examples and the outputs of both old and new versions are very consistent.
> [rcore] reveiwed GetWorldToScreenEx

- examples/shaders/resources/shaders/glsl330/tiling.fs
- examples/shaders/shader_texture_tiling.c
This is an example of texture tiling with 3d models!
> Texture Tiling Example - luis605

- src/rcore.h
- src/rcore_android.c
1. Fixes the `android` compilation by moving `#include <EGL/egl.h>` from `rcore_android.c` ([L10-L11](https://github.com/raysan5/raylib/pull/3360/files#diff-df7f2529f920b22e7f3b28d8c53b9042fe9ba3e0c4be0a421ac8d9e0c3bde72dL10-L11)) to `rcore.h` ([R19-R22](https://github.com/raysan5/raylib/pull/3360/files#diff-7341b65fe444443a67b5c67d194f97dd0c919b63c579f15ce018de206cf84864R19-R22)). This was necessary because the `CORE.Window` EGL members ([R164-R167](https://github.com/raysan5/raylib/pull/3360/files#diff-7341b65fe444443a67b5c67d194f97dd0c919b63c579f15ce018de206cf84864R164-R167)) need it.
- Compiled following [these wiki instructions](https://github.com/raysan5/raylib/wiki/Working-for-Android-(on-Linux)) (for `android-29`) on Linux Mint (21.1 64-bit).
> [split] `rcore`, `android` changes

- src/rcore.c
1. Fixes the `PLATFORM_ANDROID` build by fixing the typo on the `rcore.c` preprocessor define ([R335](https://github.com/raysan5/raylib/pull/3364/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R335)).
- #3371
- Compiled following [these wiki instructions](https://github.com/raysan5/raylib/wiki/Working-for-Android-(on-Linux)) (for `android-29`) on Linux Mint (21.1 64-bit).
> [split] `rcore`, `android` changes (batch 2)

- src/rmodels.c
Hello, I've changed the m3d loader to sort faces by material. The old code assumes the faces are already grouped together by material, which may not be the case for every model. 
This will reduce the number of meshes being created and uploaded to the gpu for those cases
> Optimize m3d mesh creation

- src/rtextures.c
the `NSVGrasterizer *rast` needs to be passed to nsvgDeleteRasterizer() when we are done with it.
> Call nsvgDeleteRasterizer() on created rasterizer by nsvgCreateRasterizer().

- src/rmodels.c
This modification replaces the expensive qsort protection with an insertion sort that is near-instantaneous in the expected ordered case.
The changes desk-check and they compile.  It is not confirmed in a running application and I am guessing that I have satisfied raylib coding style.
PS: This is modeled on Donald Knuth's Algorithm 5.2.1S (Straight insertion sort) and is a refinement of that and the code @DaveH355 provided earlier in order to handle mostly-ordered faces as quickly as possible.
> Ensure m3d faces in non-decreasing materialid sequence

- src/rcore.c
I think there was a confusion about whether `rlGetVersion()` returns `RL_OPENGL_33` or `GRAPHICS_OPENGL_33` in the code of `LoadVrStereoConfig()` which was thus rejecting OpenGL4.3 and OpenGL2.1 with a `WARNING: RLGL: VR Simulator not supported on OpenGL 1.1` ... 
This patch solves it, and the `core_vr_simulator` example works with all version of OpenGL (other than 1.1 indeed)
> [core] debug `LoadVrStereoConfig()` so it accepts `RL_OPENGL_43` and `RL_OPENGL_21`

- build.zig
- examples/build.zig
- src/build.zig
Discard `build.zig` and use `src/build.zig` only, bc by default these two output in different directories.
build command: cd to `src` then `zig build`.
Close #3386
> Update zig build system to zig version 0.11.0

- src/rcore.h
- src/rcore_android.c
- src/rcore_drm.c
- src/rcore_template.c
Fixes some `windowMin` and `windowMax` that should be `screenMin` and `screenMax` for `PLATFORM_ANDROID`, `PLATFORM_DRM` and `PLATFORM_TEMPLATE`:
- `rcore.h`: [L130-L131](https://github.com/raysan5/raylib/pull/3400/files#diff-7341b65fe444443a67b5c67d194f97dd0c919b63c579f15ce018de206cf84864L130-L131).
- `rcore_android.c`: [R419-R420](https://github.com/raysan5/raylib/pull/3400/files#diff-df7f2529f920b22e7f3b28d8c53b9042fe9ba3e0c4be0a421ac8d9e0c3bde72dR419-R420), [R426-R427](https://github.com/raysan5/raylib/pull/3400/files#diff-df7f2529f920b22e7f3b28d8c53b9042fe9ba3e0c4be0a421ac8d9e0c3bde72dR426-R427).
- `rcore_drm.c`: [R520-R521](https://github.com/raysan5/raylib/pull/3400/files#diff-ae04a2ff3974ba8bcfeb7ddfde3038688d4c2aac31d22c745f52680dcdaf1ddaR520-R521), …
> Fix `windowMin/Max` to `screenMin/Max` for `android`, `drm`, `template`

- src/rcore_android.c
As mentioned in the [discussion](https://github.com/raysan5/raylib/issues/3313#issuecomment-1760386046) regarding the split of rcore.c by platform, here is the fix for the issue with `Vector2 GetMouseDelta(void)` on Android.
This now allows obtaining the delta for the first touch on Android. Tests were conducted with multitouch, and there were no problems or interference reported.
> Fix `GetMouseDelta()` issue for Android

- src/rcore_android.c
- src/rcore_drm.c
Removes leftover `)`s on `InitWindow` that were stopping `PLATFORM_DRM` and `PLATFORM_ANDROID` compilation.
- `rcore_drm.c`: [R231-R233](https://github.com/raysan5/raylib/pull/3407/files#diff-ae04a2ff3974ba8bcfeb7ddfde3038688d4c2aac31d22c745f52680dcdaf1ddaR231-R233).
- `rcore_android.c`: [R234-R236](https://github.com/raysan5/raylib/pull/3407/files#diff-df7f2529f920b22e7f3b28d8c53b9042fe9ba3e0c4be0a421ac8d9e0c3bde72dR234-R236).
**Edit 1:** added line marks.
**Edit 2:** added android fix.
> Fix `android`, `drm` compilation issue on `InitWindow`

- src/rcore_android.c
Fixed the fact that coordinates were not normalized on Android, preventing detection of `GESTURE_DOUBLE_TAP`.
Issue mentioned in the [discussion](https://github.com/raysan5/raylib/issues/3313#issuecomment-1760344608) about splitting `rcore.c` for each platform.
> Normalize `gestureEvent.position` coordinates

- src/raudio.c
The parameter `sampleCount` is multiplied by `ma_get_bytes_per_frame` meaning it is actually the number of frames, not samples. `ma_get_bytes_per_frame(format, channels)` is `ma_get_bytes_per_sample(format) * channels`.
> Fix `UpdateSound` parameter name

- build.zig
- examples/build.zig
- src/build.zig
Related: #3386 #3393
Much appreciated @Not-Nik @star-tek-mb !
> fix zig syntax errors (0.11.0) in examples, and make it install executables correctly

- src/rcore_android.c
Fixes a comparison error between two undefined variables (width, height) and also the definition of `CORE.Window.currentFbo.height`
> Fix screen size check in `InitPlatform()`

- src/rcore_web.c
Correction to the merge #3414  
Restrict function to only set the cursor inside the canvas.
Done by getting the canvas element via its id and setting its cursor.
Build tested on Linux Mint 21.2 x64.  
Tested on Firefox 118.0.2 x64 and Brave Browser Version 1.59.117 Chromium: 118.0.5993.70 x64.  
The cursor return back to the default cursor outside of the canvas as expected.
Test program:
```c
//-------------------- PROTOTYPE CURSOR FUNCTION ------------------
#if defined(PLATFORM_WEB)
#include <emscripten/emscripten.h>
#endif
//-------------------------------------------------------------------
// Window size
static const int width = 800;
static const int height = 600;
// Grid sizes
const float grid_width = 200.0f;
const float grid_height = 200.0f; …
```
> Fix SetMouseCursor implementation for PLATFORM_WEB

- src/rcore_android.c
Small correction following the mention in the issue: [[core] Splitting rcore by platform into submodules](https://github.com/raysan5/raylib/issues/3313#issuecomment-1762960531)
Changes the return type of `InitGraphicsDevice()` from `bool` to `int`.
Adds a `return 0` at the end of `InitPlatform()`.
> Fix some omissions

- src/rcore_drm.c
- src/rcore_template.c
- src/rcore_web.c
1. While reviewing the current changes, noticed `rcore_desktop.c` no longer includes `rcore.h`.
2. Since the library and examples on `PLATFORM_DESKTOP` are compiling and running fine, I think that include is no longer needed on the modules after the previous updates.
3. So also removed it from `rcore_drm.c` ([L50](https://github.com/raysan5/raylib/pull/3420/files#diff-ae04a2ff3974ba8bcfeb7ddfde3038688d4c2aac31d22c745f52680dcdaf1ddaL50)), `rcore_web.c` ([L48](https://github.com/raysan5/raylib/pull/3420/files#diff-5204360a69ae27d12753764f60a1cd59e3a11ef10b86fce7691c74de0becc8cdL48)) and `rcore_template.c` ([L49](https://github.com/raysan5/raylib/pull/3420/files#diff-8b082901dd641b3d10f6444023946081d7a3d3d84e8ed1c89b119499a82f33d1L49)). Compiled and tested here and everything appears to be …
> Remove the `rcore.h` include from `drm`, `web`, `template`

- BINDINGS.md
Following what was mentioned in BINDINGS.md for new listings, I'm putting in a PR for the inclusion of [Matte bindings](https://github.com/jcorks/raylib-matte/) for raylib 4.6-dev to the main listing.
> Inclusion of Matte to BINDINGS.md

- src/rcore_desktop_sdl.c
1. Fixes the mouse wheel getting stucked scrolling up or down by adding the missing reset ([R534-R536](https://github.com/raysan5/raylib/pull/3428/files#diff-b7c2628cbe74c1722110bdc42bc4239493b1be7ff2836f8892e3e942a42e9aefR534-R536)).
2. Fixes the mouse sensitivity being really high on 3D by adding the missing previous mouse position registry ([R538-R539](https://github.com/raysan5/raylib/pull/3428/files#diff-b7c2628cbe74c1722110bdc42bc4239493b1be7ff2836f8892e3e942a42e9aefR538-R539)).
3. Fixes the mouse button presses not working properly by adding the missing previous mouse button registry ([R561-R562](https://github.com/raysan5/raylib/pull/3428/files#diff-b7c2628cbe74c1722110bdc42bc4239493b1be7ff2836f8892e3e942a42e9aefR561-R562)) and by adding handling for `SDL_MOUSEBUTTONUP` …
> [core] Fix some mouse issues on `SDL`

- src/Makefile
Currently doing the following:
```bash
make
touch rcore_desktop.c
make
```
Will not result in rcore.o getting compiled again, despite that rcore_desktop.c has changed
This commit resolves that
The one downside this has is that for example, when building for desktop, if rcore_web.c is modified, rcore.c will get compiled again, despite that its changes are not used in this situation - I think this is unimportant, though, as make clean would be required to switch between platforms anyway
>  Make sure rcore.o gets compiled in more situations

- src/rcore_android.c
Very short fix to remove the `rcore.h` include from `PLATFORM_ANDROID` ([L49](https://github.com/raysan5/raylib/pull/3429/files#diff-df7f2529f920b22e7f3b28d8c53b9042fe9ba3e0c4be0a421ac8d9e0c3bde72dL49)) so it matches the other submodules.
References: #3420, https://github.com/raysan5/raylib/issues/3313#issuecomment-1764276021.
**Edit:** added line marks.
> [core] Remove `rcore.h` include from `Android`

- src/rcore_desktop_sdl.c
As originally mentioned by @ubkp in the issue [\[core\] Splitting rcore by platform into submodules](https://github.com/raysan5/raylib/issues/3313#issuecomment-1763623854), here is the fix for the keyboard handling issue with SDL.
This modification includes a mapping table between SDL scancodes and raylib keys, along with a function to safely retrieve them.
I've also revised the state change of `CORE.Window.shouldClose` by using `CORE.Input.Keyboard.exitKey` instead of `SDLK_ESCAPE` directly, but as indicated in the comment, I believe this part would be better placed outside of the switch statement.
> Fix SDL keyboard issue

- src/raudio.c
- src/raylib.h
It feels a little unfinished when you can SetMasterVolume but can't really Get it. So to finish the symmetry here is the GetMasterVolume implementation.
> [raudio] Implement GetMasterVolume()

- src/rcore_desktop_sdl.c
1. Adds `ShowCursor` implementation ([R469-R471](https://github.com/raysan5/raylib/pull/3436/files#diff-b7c2628cbe74c1722110bdc42bc4239493b1be7ff2836f8892e3e942a42e9aefR469-R471)).
2. Adds `HideCursor` implementation ([R477-R479](https://github.com/raysan5/raylib/pull/3436/files#diff-b7c2628cbe74c1722110bdc42bc4239493b1be7ff2836f8892e3e942a42e9aefR477-R479)).
3. Adds `EnableCursor` implementation ([R485-R486](https://github.com/raysan5/raylib/pull/3436/files#diff-b7c2628cbe74c1722110bdc42bc4239493b1be7ff2836f8892e3e942a42e9aefR485-R486)).
4. Adds `DisableCursor` implementation ([R494](https://github.com/raysan5/raylib/pull/3436/files#diff-b7c2628cbe74c1722110bdc42bc4239493b1be7ff2836f8892e3e942a42e9aefR494)).
5. Adds `SetClipboardText` implementation …
> [core] Add more missing implementations to `SDL`

- src/rcore_desktop_sdl.c
As requested in https://github.com/raysan5/raylib/issues/3313 here is the implementation of the `SetWindowState`, `ClearWindowState`, and `SetWindowIcon` functions for `rcore_desktop_sdl.c`.
The functions `SetWindowState` and `ClearWindowState` don't handle all flags, but it seems that some things can't be managed directly through SDL. Please take a look at the notes in the comments.
Otherwise, `SetWindowIcon` seems to work fine on my end on Cinnamon (Linux Mint). I don't have access to Windows to test it right now.
I'm sharing this work now so that if you have any feedback, I can make corrections, or you can merge it directly if everything looks good.
> [core] Add more missing implementations to SDL

- src/rcore_desktop_sdl.c
1. Hopefully fixes `GetMonitorPhysicalWidth` ([R728-R729](https://github.com/raysan5/raylib/pull/3442/files#diff-b7c2628cbe74c1722110bdc42bc4239493b1be7ff2836f8892e3e942a42e9aefR728-R729), [R733](https://github.com/raysan5/raylib/pull/3442/files#diff-b7c2628cbe74c1722110bdc42bc4239493b1be7ff2836f8892e3e942a42e9aefR733)) and `GetMonitorPhysicalHeight` ([R750-R751](https://github.com/raysan5/raylib/pull/3442/files#diff-b7c2628cbe74c1722110bdc42bc4239493b1be7ff2836f8892e3e942a42e9aefR750-R751), [R755](https://github.com/raysan5/raylib/pull/3442/files#diff-b7c2628cbe74c1722110bdc42bc4239493b1be7ff2836f8892e3e942a42e9aefR755)) to use `ddpi`. Tested the 3 `dpi` values (`ddpi`, `hdpi`, `vdpi`) and their values are almost the same here:
| Size | Resolution | ddpi | hdpi | vdpi |
| :---: | :---: | …
> [core] Fix some implementations for `SDL`

- src/platforms/rcore_desktop_sdl.c
1. Complement `SetWindowMonitor` to match `rcore_desktop.c`'s more closely ([L586-R630](https://github.com/raysan5/raylib/pull/3444/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12L586-R630)).
**Note 1:** `SDL` started supporting moving exclusive fullscreen windows between displays on `SDL3` (see https://github.com/libsdl-org/SDL/commit/3f5ef7dd422057edbcf3e736107e34be4b75d9ba). A workround for `SDL2` is leaving fullscreen, moving the window, then entering full screen again.
**Note 2:** There's a known issue where if the window larger than the target display bounds, when moving the windows to that display, the window could be clipped back ending up positioned partly outside the target display. The workaround for that is, previously to moving the window, setting …
> [core] Complement implementations for `SDL`

- src/platforms/rcore_desktop_sdl.c
1. Adds a note ([R832-R833](https://github.com/raysan5/raylib/pull/3447/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R832-R833)), todo ([R834](https://github.com/raysan5/raylib/pull/3447/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R834)) and small tweaks ([R830](https://github.com/raysan5/raylib/pull/3447/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R830), [R837](https://github.com/raysan5/raylib/pull/3447/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R837)) to `GetWindowScaleDPI`.
**Note:** `SDL_GetWindowDisplayScale` was only added on `SDL3` (see [doc](https://wiki.libsdl.org/SDL3/SDL_GetWindowDisplayScale)).
**Todo:** It will be necessary to implement the window scale …
> [core] Complement implementations for `SDL` (2)

- src/platforms/rcore_desktop_sdl.c
1. Fixes `SetWindowMinSize` missing the equivalent `SDL` call ([R621](https://github.com/raysan5/raylib/pull/3450/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R621)).
2. Fixes `SetWindowMaxSize` missing the equivalent `SDL` call ([R630](https://github.com/raysan5/raylib/pull/3450/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R630)).
3. Fixes the window resizes not updating the viewport by adding updating on the `SDL_WINDOWEVENT` on `PollInputEvents` ([R986](https://github.com/raysan5/raylib/pull/3450/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R986), [R1001-R1012](https://github.com/raysan5/raylib/pull/3450/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R1001-R1012)) …
> [core] Complement implementations for `SDL` (3)

- src/Makefile
I noticed rcore_desktop_sdl.c was missing from the prerequisites list
Now that the platforms are split to their own directory, it is simple to just use a "wildcard" to match them all in the makefile
> Review prerequisites of rcore.c

- examples/Makefile.Web
1. Since the web examples compilation now uses the `Makefile.Web`, the compilation is broken due to missing several examples:
```
~/raylib-master/examples$ make PLATFORM=PLATFORM_WEB
[...]
audio/audio_sound_multi.c:14:10: fatal error: 'raylib.h' file not found
core/core_input_gamepad_info.c:17:10: fatal error: 'raylib.h' file not found
shaders/shaders_lightmap.c:22:10: fatal error: 'raylib.h' file not found
textures/textures_image_rotate.c:14:10: fatal error: 'raylib.h' file not found
textures/textures_svg_loading.c:16:10: fatal error: 'raylib.h' file not found
others/easings_testbed.c:16:10: fatal error: 'raylib.h' file not found
others/embedded_files_loading.c:16:10: fatal error: 'raylib.h' file not found
others/raylib_opengl_interop.c:27:10: fatal error: 'raylib.h' file not found …
```
> [build] Fix compilation for `PLATFORM_WEB` examples

- src/raudio.c
Fixes a memory leak as a result of creating an AudioBuffer* with the old source.frameCount. This internally allocates memory to the structs data pointer which is then later overridden by the correct sound data of the source sound.
Additionally added a volume assignment from old to new as currently there is no way to get the volume of a sound and the AudioBuffer struct is not reachable from user code due to opaque definition. Also it makes sense as an Alias is a new name for the same thing.
> Fixed LoadSoundAlias() memory leak

- src/platforms/rcore_desktop_sdl.c
1. Complements `OpenURL` missing the `avoid [\'] character` check ([L1018](https://github.com/raysan5/raylib/blob/master/src/platforms/rcore_desktop.c#L1018)) on `rcore_desktop_sdl.c` ([R902-R904](https://github.com/raysan5/raylib/pull/3460/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R902-R904)). And also the security warning ([R896-R899](https://github.com/raysan5/raylib/pull/3460/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R896-R899)).
Changes tested on Linux (Mint 21.1 64-bit).
**1:** added line marks.
> [core] Complement `OpenURL` implementation for `SDL`

- src/platforms/rcore_desktop.c
1. Adds a loop to retrieve the gamepads' names near the end of `InitPlatform()` on `rcore_desktop.c` for `GLFW` ([R1540-R1544](https://github.com/raysan5/raylib/pull/3462/files#diff-769a8a9fb419056857448648271703ed813ed161157a25ace24ce449ae18643aR1540-R1544)). This handles gamepads already connected when the application starts not triggering the `glfwSetJoystickCallback`/`JoystickCallback` that sets the gamepads' names.
Fixes #3461
Compiled on Linux (Ubuntu 22.04 64-bit).
**1:** add line marks, editing.
**2:** typo.
**3:** formatting.
> [core] Fix gamepad names for `PLATFORM_DESKTOP`/`GLFW`

- src/rlgl.h
There are two missing `PLATFORM_DESKTOP_SDL` checks in `rlgl.h`, so that OpenGL ES support in `PLATFORM_DESKTOP_SDL` is broken.
Add missing PLATFORM* checks can fix that, but a bit dirty.
BTW, consider that more platforms will be supported here, so maybe `rlgl.h` should be more independent.
> Fix missing `PLATFORM_DESKTOP_SDL` checks.

- src/platforms/rcore_desktop.c
Partial fix for #3456.
At present, in case the center of the window is out of any monitor, it detects the first one as current on the GLFW implementation, while ``SDL_GetWindowDisplayIndex()`` apparently detects the monitor that is the closest to the center of the window (https://github.com/libsdl-org/SDL/blob/b29128994e87d82eae4751d65ff38b935ce7d6a2/src/video/SDL_video.c#L1114).
Maybe we can merge this PR as is and leave the issue of the center of the window being out of any monitor to another one.
> GetCurrentMonitor() - check window center instead of top-left corner

- src/raylib.h
closes https://github.com/raysan5/raylib/issues/3463
> Fix IsGestureDetected parameter inconsistency in raylib.h with rgextures.h

- src/platforms/rcore_desktop.c
This PR complements #3468 by using the closest monitor when the center of the window is not within any of them (instead of the first one).
It is essentially adapted from https://github.com/libsdl-org/SDL/blob/b29128994e87d82eae4751d65ff38b935ce7d6a2/src/video/SDL_video.c#L1114.
Closes #3456.
> GetCurrentMonitor() - use closest monitor

- src/platforms/rcore_desktop_sdl.c
1. Very short fix to remove the `rcore.h` include from `rcore_desktop_sdl.c` ([L52](https://github.com/raysan5/raylib/pull/3475/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12L52)) so it matches the other submodules.
**References:** [#3420](https://github.com/raysan5/raylib/pull/3420), [#3429](https://github.com/raysan5/raylib/pull/3429).
Changes successfully tested on Linux (Ubuntu 22.04 64-bit, gcc 11.2.0) with SDL2 (2.28.4).
1: added line marks.
> [core] Remove `rcore.h` include from `SDL`

- src/external/rl_gputex.h
This code fixes the black/crashing compressed DDS textures loading issue but instead forces only 1 mipmap to be loaded. This should still be reviewed though ig as this PR is not a final solution tothe problem.
> Fix compressed DDS texture loading issues

- src/platforms/rcore_drm.c
Moves `InitTimer()` to before the input events system initializations (from [L916-L919](https://github.com/raysan5/raylib/pull/3484/files#diff-757f4c9c5f0be7473e385fa72b35d509c5af4ee2dc8204d2dbe2418bb9b98922L916-L919) to [R909-R913](https://github.com/raysan5/raylib/pull/3484/files#diff-757f4c9c5f0be7473e385fa72b35d509c5af4ee2dc8204d2dbe2418bb9b98922R909-R913)) on `rcore_drm.c`.
Fixes #3482
Tested on Raspberry Pi 3 Model B 1.2 with Linux (Raspberry Pi OS 11 Bullseye 32-bit armhf).
**1:** added line marks; editing.
> [core] Fix `PLATFORM_DRM` hang up on exit and mouse input issues

- examples/Makefile
Fixes the examples compilation for `PLATFORM_DESKTOP_SDL` by adding the missing `RAYLIB_SRC_PATH ?= ../src` to the `examples/Makefile` ([R55-R56](https://github.com/raysan5/raylib/pull/3486/files#diff-ae8bb09b4bbb919309d4c8bb8ffc46e031bf63b7274502171a183a4dc1138f53R55-R56)) so the `*_PATHS` ([R74-R75](https://github.com/raysan5/raylib/pull/3486/files#diff-ae8bb09b4bbb919309d4c8bb8ffc46e031bf63b7274502171a183a4dc1138f53R74-R75)) could reach its files.
Tested on Linux (Ubuntu 22.04 64-bit) with SDL2 (2.28.4).
**1:** added line marks.
> [build] Fix `examples/Makefile` for `PLATFORM_DESKTOP_SDL`

- src/rlgl.h
rlDisableWireMode and rlDisablePointMode would be identical, so I didn't submit that.
> adding rlEnablePointMode to mirror rlEnableWireMode

- src/platforms/rcore_drm.c
1. Fixes the issue causing the `PLATFORM_DRM` examples with 3D cameras (e.g.: `models_first_person_maze`, `core_3d_camera_free`, etc) moving uncontrollably, by adding more handling for the relative mouse mode ([R124](https://github.com/raysan5/raylib/pull/3492/files#diff-757f4c9c5f0be7473e385fa72b35d509c5af4ee2dc8204d2dbe2418bb9b98922R124), [R404](https://github.com/raysan5/raylib/pull/3492/files#diff-757f4c9c5f0be7473e385fa72b35d509c5af4ee2dc8204d2dbe2418bb9b98922R404), [R414](https://github.com/raysan5/raylib/pull/3492/files#diff-757f4c9c5f0be7473e385fa72b35d509c5af4ee2dc8204d2dbe2418bb9b98922R414), [R528-R533](https://github.com/raysan5/raylib/pull/3492/files#diff-757f4c9c5f0be7473e385fa72b35d509c5af4ee2dc8204d2dbe2418bb9b98922R528-R533), …
> [core] Fix relative mouse mode for `PLATFORM_DRM`

- examples/shaders/resources/shaders/glsl100/lighting.fs
- examples/shaders/resources/shaders/glsl120/lighting.fs
- examples/shaders/resources/shaders/glsl330/lighting.fs
The lighting shaders had a structure that was not used, this PR removes it.
> [EXAMPLES] Remove unused structures from lighting fragment shaders

- src/platforms/rcore_drm.c
1. Moves the `keymapUS[]` LUT out of `PollKeyboardEvents` ([L1457-L1476](https://github.com/raysan5/raylib/pull/3498/files#diff-757f4c9c5f0be7473e385fa72b35d509c5af4ee2dc8204d2dbe2418bb9b98922L1457-L1476)) to `Local Variables Definition` ([R143-R162](https://github.com/raysan5/raylib/pull/3498/files#diff-757f4c9c5f0be7473e385fa72b35d509c5af4ee2dc8204d2dbe2418bb9b98922R143-R162)) so it doesn't have to be redefined every time `PollKeyboardEvents()` runs on `PLATFORM_DRM`.
2. Adds handling for `CORE.Input.Keyboard.charPressedQueue` and `CORE.Input.Keyboard.charPressedQueueCount` ([R164-R171](https://github.com/raysan5/raylib/pull/3498/files#diff-757f4c9c5f0be7473e385fa72b35d509c5af4ee2dc8204d2dbe2418bb9b98922R164-R171), [R1533-R1543](https://github.com/raysan5/raylib/pull/3498/files#diff-757f …
> [core] Moves `keymapUS[]` and fixes `GetCharPressed` for `PLATFORM_DRM`

- src/platforms/rcore_desktop_sdl.c
1. Adds the missing gestures handling for `PLATFORM_DESKTOP_SDL`.
2. Does that by adding the `ProcessGestureEvent(gestureEvent)` call ([R1169](https://github.com/raysan5/raylib/pull/3499/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R1169)) and `gestureEvent` composition ([R1149-R1166](https://github.com/raysan5/raylib/pull/3499/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R1149-R1166)) inside the `PollInputEvents()`, similar to how it's done on `PLATFORM_DESKTOP`([L1744-L1769](https://github.com/raysan5/raylib/blob/master/src/platforms/rcore_desktop.c#L1744-L1769), [L1779-L1799](https://github.com/raysan5/raylib/blob/master/src/platforms/rcore_desktop.c#L1779-L1799)) and `PLATFORM_DRM` …
> [core] Fix gestures for `PLATFORM_DESKTOP_SDL`

- build.zig
- src/build.zig
Zig 0.11.0 release slightly modifies the addCSourceFiles API. This PR gets raylib building with the 0.11.0 release.
> build.zig updates for 0.11.0 release.

- src/rcore.c
This PR implement a fix for issue #3504 where `PlayAutomationEvent()` does not add key presses to the `keyPressedQueue`.
> Fixed Issue 3504

- src/Makefile
When using `PLATFORM=PLATFORM_DESKTOP_SDL` and `RAYLIB_LIBTYPE=SHARED`, it didn't build the library (.so file).
> Update Makefile: Build shared lib when platform is SDL

- .gitignore
- CMakeLists.txt
- cmake/Uninstall.cmake
The handwritten `Makefile` in `src` [has](https://github.com/raysan5/raylib/blob/a470cdce4c3d77e543d90a5fc2aab05e8d41b51b/src/Makefile#L764) a `uninstall` target. Auto-generated `Makefile` doesn't get one as [mentioned](https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake) in the CMake's FAQs. So adding for completeness' sake.
> [build]: add uninstall cmake target

- src/platforms/rcore_drm.c
1. Fixes the gesture system for `PLATFORM_DRM`. Does that by:
1. Moving the mouse/touch/gesture handling from `EventThread()` ([R1741-R1923](https://github.com/raysan5/raylib/pull/3515/files#diff-757f4c9c5f0be7473e385fa72b35d509c5af4ee2dc8204d2dbe2418bb9b98922R1741-R1923)) to end of `PollInputEvents()` ([R608-R783](https://github.com/raysan5/raylib/pull/3515/files#diff-757f4c9c5f0be7473e385fa72b35d509c5af4ee2dc8204d2dbe2418bb9b98922R608-R783)). Similar to how it's done on `SDL` ([L1001](https://github.com/raysan5/raylib/blob/master/src/platforms/rcore_desktop_sdl.c#L1001)).
2. Changing the `ConfigureEvdevDevice()` to no longer call the `EventThread()` ([R1635-R1641](https://github.com/raysan5/raylib/pull/3515/files#diff-757f4c9c5f0be7473e385fa72b35d509c5af4ee2dc8204d2dbe2418bb9b98922R1635- …
> [core] Fix mouse/touch/gestures for `PLATFORM_DRM`

- src/platforms/rcore_drm.c
- Very quick fix to add the `platform.absRange` to the `ConfigureEvdevDevice()` ([R1552-R1553](https://github.com/raysan5/raylib/pull/3517/files#diff-757f4c9c5f0be7473e385fa72b35d509c5af4ee2dc8204d2dbe2418bb9b98922R1552-R1553), [R1558-R1559](https://github.com/raysan5/raylib/pull/3517/files#diff-757f4c9c5f0be7473e385fa72b35d509c5af4ee2dc8204d2dbe2418bb9b98922R1558-R1559), [R1571-R1572](https://github.com/raysan5/raylib/pull/3517/files#diff-757f4c9c5f0be7473e385fa72b35d509c5af4ee2dc8204d2dbe2418bb9b98922R1571-R1572), [R1577-R1578](https://github.com/raysan5/raylib/pull/3517/files#diff-757f4c9c5f0be7473e385fa72b35d509c5af4ee2dc8204d2dbe2418bb9b98922R1577-R1578)) that was missing on the #3515.
- While I was cleaning up the previous PR I forgot to add `platform.absRange` part. Really sorry, …
> [core] Fix `absRange` for `PLATFORM_DRM` (complement #3515)

- src/rcore.c
Similar issue with: https://github.com/raysan5/raylib/pull/3410
Window shouldClose flag does not reset after closing and opening another window. So for the subsequent windows `WindowShouldClose` always return true.
> WindowShouldClose(), reset shouldClose flag when window is inited

- src/rcore.c
- Moves `RecordAutomationEvent()` from [L931-L933](https://github.com/raysan5/raylib/pull/3523/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339L931-L933) to [R868-R870](https://github.com/raysan5/raylib/pull/3523/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R868-R870).
- Logic: [3521#issuecomment-1806829131](https://github.com/raysan5/raylib/issues/3521#issuecomment-1806829131)
- Fixes #3521
- Tested on `PLATFORM_WEB` and `PLATFORM_DESKTOP`.
> [core] Fix automation recording

- README.md
Exactly what it says in the title :)
> Added wiki links to README

- src/rlgl.h
The return type of `rlGetCompressedFormatName` has been corrected from `char *` to `const char *`
> [rlgl] Fixed return type of `rlGetCompressedFormatName`

- BINDINGS.md
raylib-go uses raylib 5.0: https://github.com/gen2brain/raylib-go/blob/master/raylib/raylib.h
> Update BINDINGS.md for raylib-go

- src/platforms/rcore_desktop_sdl.c
- The `SDL2` mouse button order is `LEFT, MIDDLE, RIGHT, ...` ([doc](https://wiki.libsdl.org/SDL2/SDL_MouseButtonEvent)), but `raylib.h`'s `MouseButton enum` uses `LEFT, RIGHT, MIDDLE, ...` ([L689-L690](https://github.com/raysan5/raylib/blob/master/src/raylib.h#L689-L690)) like `GLFW`.
- Fixes the `MOUSE_BUTTON_RIGHT` and `MOUSE_BUTTON_MIDDLE` order by remapping them during the input polling for `PLATFORM_DESKTOP_SDL` ([R1087-R1093](https://github.com/raysan5/raylib/pull/3534/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R1087-R1093), [R1100-R1106](https://github.com/raysan5/raylib/pull/3534/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R1100-R1106)).
- https://github.com/raysan5/raylib/pull/3428#issuecomment-1764433516
- Tested on …
> [core] Fix mouse button order for `PLATFORM_DESKTOP_SDL`

- src/platforms/rcore_desktop_sdl.c
- Adds the missing mod keys to `rcore_desktop_sdl.c`'s `ScancodeToKey` ([R76](https://github.com/raysan5/raylib/pull/3539/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R76), [R177-R198](https://github.com/raysan5/raylib/pull/3539/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R177-R198)).
- Fixes #3538
- Tested on Linux (Ubuntu 22.04 64-bit) with SDL2 (2.28.5) and Emscripten (3.1.48).
> [core] Fix missing keys on `PLATFORM_DESKTOP_SDL`

- src/platforms/rcore_desktop_sdl.c
System: Artix Linux, Desktop PC
---
When trying to compile Raylib configured with SDL and OpenGL ES2 it will fail like the following:
By editing `rcore_desktop_sdl.c` to not include `SDL_opengl.h` when compiling for OpenGL ES2 it compiles and works. See here:
However when looking through the headerfiles of SDL I see there is a `SDL_opengles2.h` which I suspect should be used in place of `SDL_opengl.h` but it fails to compile when I do that. I am not entire sure why, I tried to do some digging but havent come up with anything yet, if anyone else has any insight it would be much appreciated however I think the current fix is sufficient.
I have not tested this yet on Windows or Mac. I can test it on Windows and Mac most likely sometime later this week or next week.
> Fix for running OpenGL ES2 with SDL on desktop

- examples/Makefile
- examples/textures/textures_image_kernel.c
- projects/Notepad++/raylib_npp_parser/raylib_to_parse.h
- src/raylib.h
- src/rtextures.c
Please refer to the issue for more info: https://github.com/raysan5/raylib/issues/3527
> Image convolution function ImageKernelConvolution

- src/raudio.c
This PR just disables some high level miniaudio features that are not used by raylib.
> Disable unused miniaudio features

- BINDINGS.md
[raylib-cpp](https://github.com/RobLoach/raylib-cpp) supports raylib 5.0. Congrats on the release! :partying_face:
> BINDINGS: Update raylib-cpp support to raylib 5.0

- examples/Makefile.Web
The PLATFORM_WEB compilation failed on textures_image_kernel. I figured out that it was missing in Makefile, so I just made similar lines in Makefile.Web. There may be a need to limit RAM usage. I have no expertise to decide that.
> Added missing textures_image_kernel example in web makefile

- src/rlgl.h
Doing the binding for 5.0, I noticed this seems to not have been changed.
Most of the .h files don't follow the release versions, so I'm not 100% sure if this is correct...
> Fix version info in rlgl.h

- src/rlgl.h
Currently, if you build raylib as a DLL, and then try to build the examples, examples/other/raylib_opengl_interop.c will fail to link, because none of the opengl functions are exposed in raylib.dll
These can also help some binding users, like raylib-cs users who would like to call some opengl functions directly, bypassing rlgl.
Currently these users have to call wglGetProcAddress to get a function pointer manually.
examples/other/rlgl_standalone.c also has this issue, and it can be fixed by exposing GLFW. I don't know whether this is a good idea, though, since GLFW is not used by all platforms, while OpenGL is.
I'm happy to open a PR exposing those symbols too, if it's desired, though.
> Expose glad functions when building raylib as a shared lib

- src/Makefile
The android ndk toolchain path for OSX is toolchains/llvm/prebuilt/darwin-x86_64 and not toolchains/llvm/prebuilt/linux-x86_64
> Corrected the path of android ndk toolchains for OSX platforms

- src/platforms/rcore_desktop_sdl.c
- Fixes `SetMousePosition()` for `PLATFORM_DESKTOP_SDL` by adding the missing `SDL_WarpMouseInWindow()` call on  ([R944](https://github.com/raysan5/raylib/pull/3580/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R944)).
- Tested successfully on Linux (Mint 21.1 64-bit) with SDL2 (2.28.4).
- 1: added line marks.
> [core] Fix `SetMousePosition()` for `PLATFORM_DESKTOP_SDL`

- CMakeLists.txt
- cmake/GlfwImport.cmake
- src/CMakeLists.txt
- src/Makefile
- src/raylib.h
- src/raymath.h
- src/rlgl.h
Currently, raylib makes no attempt to hide any of its symbols when building as an so or dylib.
This means the symbols of glfw, miniaudio, stb_image, etc are all exposed to call.
This results in a bit of inconsistency compared to the windows dll, which exposes far less (just raylib+glad+raymath+rlgl).
This PR handles this by passing -fvisibility=hidden to all of raylib's source files when building as an SO, and using \_\_attribute__((visibility("default"))) to expose each symbol, much like __declspec(dllexport).
In theory, this improves the load times and size of the so, as well as providing better "api hygine"
https://gcc.gnu.org/wiki/Visibility
I updated both CMake and the Makefile to do this. I checked zig, but it does not seem to handle building shared libs at all, so I don't think it …
> Hide unneeded internal symbols when building raylib as an so or dylib

- src/platforms/rcore_drm.c
- Fixes `IsKeyPressedRepeat()` for `PLATFORM_DRM` direct input by adding the missing `CORE.Input.Keyboard.keyRepeatInFrame` to `PollKeyboardEvents()` ([R1712](https://github.com/raysan5/raylib/pull/3583/files#diff-757f4c9c5f0be7473e385fa72b35d509c5af4ee2dc8204d2dbe2418bb9b98922R1712)).
- Issue spotted by @larry104 at [#3569#issuecomment-1832811076](https://github.com/raysan5/raylib/issues/3569#issuecomment-1832811076).
```
if (IsKeyPressedRepeat(KEY_ONE)) {
DrawText("1 is repeat", 20, 20, 20, BLACK);
TraceLog(LOG_INFO, "1 is repeat");
}
if (IsKeyPressedRepeat(KEY_TWO)) {
DrawText("2 is repeat", 20, 40, 20, BLACK);
TraceLog(LOG_INFO, …
```
> [core] Fix `IsKeyPressedRepeat()` for `PLATFORM_DRM` direct input

- cmake/GlfwImport.cmake
I broke this in PR #3573 by accidentally removing too much
The examples still compiled fine so I didn't notice - my guess is that cmake was still adding a separate link to glfw manually.
> Fix cmake-built libraylib.a to properly include GLFW's object files

- src/platforms/rcore_desktop_sdl.c
1. Fixes `GetKeyPressed()` and `GetCharPressed()` for `PLATFORM_DESKTOP_SDL` by adding the missing handling for `CORE.Input.Keyboard.keyPressedQueue` ([R1115-R1121](https://github.com/raysan5/raylib/pull/3604/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R1115-R1121)) and `CORE.Input.Keyboard.charPressedQueue` ([R1123-R1129](https://github.com/raysan5/raylib/pull/3604/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R1123-R1129)).
2. Due to the way `SDL2` handles text input, it required adding the `SDL_TEXTINPUT` event case ([R1113](https://github.com/raysan5/raylib/pull/3604/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R1113)) to `PollInputEvents()` to access the `text` data field …
> [rcore] Fix `GetKeyPressed()` and `GetCharPressed()` for `PLATFORM_DESKTOP_SDL`

- src/platforms/rcore_desktop.c
Fixes #3606
CORE.Input.Touch.currentTouchState[button] was never being set, causing a the `up` value in `IsMouseButtonUp()` to be overridden as `true` constantly.
> [core] Fix IsMouseButtonUp for PLATFORM_DESKTOP

- src/CMakeLists.txt
CMakeLists.txt still shows the RayLib version to be 4.5.0.
This PR updates it to 5.0.0
> Updating CMake version to 5.0 so libraries are correctly versioned

- src/platforms/rcore_desktop_sdl.c
1. Fixes/finishes implementing real touch gestures support for `PLATFORM_DESKTOP_SDL`.
2. Does that by complementing the `SDL_FINGERMOTION` ([R1205-R1210](https://github.com/raysan5/raylib/pull/3614/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R1205-R1210)), `SDL_FINGERDOWN` ([R1185-R1191](https://github.com/raysan5/raylib/pull/3614/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R1185-R1191)) and `SDL_FINGERUP` ([R1195-R1201](https://github.com/raysan5/raylib/pull/3614/files#diff-43fa9fe6c2302f00d9c0b8bcbe58d8ca92ca52e157d5b19a612f90a81c698c12R1195-R1201)) implementations, by making them also set the `CORE.Input.Touch.position` and `CORE.Input.Touch.currentTouchState` values. 
3. Also adds a new `realTouch` bool variable on …
> [rcore] Fix real touch gestures for `PLATFORM_DESKTOP_SDL`

- src/platforms/rcore_drm.c
1. Optimizes the gesture handling for `PLATFORM_DRM` by reusing the `touchAction` var ([R754](https://github.com/raysan5/raylib/pull/3616/files#diff-757f4c9c5f0be7473e385fa72b35d509c5af4ee2dc8204d2dbe2418bb9b98922R754), [R769](https://github.com/raysan5/raylib/pull/3616/files#diff-757f4c9c5f0be7473e385fa72b35d509c5af4ee2dc8204d2dbe2418bb9b98922R769)) instead of the now redundant `gestureUpdate` ([L615](https://github.com/raysan5/raylib/pull/3616/files#diff-757f4c9c5f0be7473e385fa72b35d509c5af4ee2dc8204d2dbe2418bb9b98922L615), [L634](https://github.com/raysan5/raylib/pull/3616/files#diff-757f4c9c5f0be7473e385fa72b35d509c5af4ee2dc8204d2dbe2418bb9b98922L634), [L648](https://github.com/raysan5/raylib/pull/3616/files#diff-757f4c9c5f0be7473e385fa72b35d509c5af4ee2dc8204d2dbe2418bb9b98922L648), …
> [rcore] Optimize gesture handling for `PLATFORM_DRM`

- src/platforms/rcore_web.c
1. Complements the implementation of `SetWindowState()` ([R238-R338](https://github.com/raysan5/raylib/pull/3625/files#diff-14c6a8a6962cf65222635a523e877bbaa1f07b791028685f92bf6b44d87530d7R238-R338)) and `ClearWindowState()` ([R344-R444](https://github.com/raysan5/raylib/pull/3625/files#diff-14c6a8a6962cf65222635a523e877bbaa1f07b791028685f92bf6b44d87530d7R344-R444)) for `PLATFORM_WEB`.
2. Adds the basic structure for handling more flags on `PLATFORM_WEB` (if supported) in the future.
3. Adds handling for `FLAG_BORDERLESS_WINDOWED_MODE` ([R248-R251](https://github.com/raysan5/raylib/pull/3625/files#diff-14c6a8a6962cf65222635a523e877bbaa1f07b791028685f92bf6b44d87530d7R248-R251), [R354-R358](https://github.com/raysan5/raylib/pull/3625/files#diff-14c6a8a6962cf65222635a523e877bbaa1f07b791028685 …
> [rcore] Complement `SetWindowState()` and `ClearWindowState()` for `PLATFORM_WEB`

- .gitignore
I build Raylib as a share lib on Windows. Compiled `DLL` binaries should be Ignored.
> Ignore compiled `DLL` binaries.

- src/rtextures.c
Previous version of box blur kernel was asymmetrical, because the leftmost and topmost pixels were subtracted from the average values too early, causing the image to offset by GAUSSIAN_BLUR_ITERATIONS pixels after blurring. You can see this at the rightmost and bottommost borders of the image. This commit fixes this bug.
|Original image|Old box blur|Fixed box blur|
|-|-|-|
|![image](https://github.com/raysan5/raylib/assets/33938415/7a144a1a-7188-4591-965a-ec03dd19d594)|![image](https://github.com/raysan5/raylib/assets/33938415/7ea67fd8-71a6-4537-8f45-24573fa2a50b)|![image](https://github.com/raysan5/raylib/assets/33938415/057ea9a5-0c7e-4d39-afa5-975a82f03978)|
Image is also a bit more blurry now since the blur kernel is now 1 pixel wider.
PS. Perhaps GAUSSIAN_BLUR_ITERATIONS could be a …
> Fix box blur symmetry & simplify code

- examples/core/core_vr_simulator.c
- src/raylib.h
It looks like the `vScreenCenter` member in the `VrDeviceInfo` struct is never used in code. Thus this pull requests removes it.
> [rcore] Remove unused vScreenCenter

- src/rcore.c
The left and right screens when calling `LoadVrStereoConfig` is flipped. This pull request simply flips them back to the correct configuration.
> [rcore] Flip VR screens

- src/platforms/rcore_web.c
1. Adds implementation for `GetMonitorWidth()` and `GetMonitorHeight()` that were missing for `PLATFORM_WEB`. Does that by using `emscripten` `EM_ASM_INT` and `DOM` `screen.width` ([R575-R577](https://github.com/raysan5/raylib/pull/3636/files#diff-14c6a8a6962cf65222635a523e877bbaa1f07b791028685f92bf6b44d87530d7R575-R577)) and `screen.height` ([R583-R585](https://github.com/raysan5/raylib/pull/3636/files#diff-14c6a8a6962cf65222635a523e877bbaa1f07b791028685f92bf6b44d87530d7R583-R585)).
- Returned values are limited to the current monitor where the browser window is located.
- This change can be tested for `PLATFORM_WEB` (requires `ASYNCIFY`) with:
``` …
```
> [rcore] Add `GetMonitorWidth()` and `GetMonitorHeight()` implementations for `PLATFORM_WEB`

- BINDINGS.md
New beef bindings, auto generated and updated to work with v5.0.
> Add new raylib-beef binding

- src/platforms/rcore_web.c
1. Adds implementation for `GetWindowPosition()` that was missing for `PLATFORM_WEB`. Does that by using `emscripten` `EM_ASM_INT` and `DOM` `window.screenX` and `window.screenY` ([R621-R625](https://github.com/raysan5/raylib/pull/3637/files#diff-14c6a8a6962cf65222635a523e877bbaa1f07b791028685f92bf6b44d87530d7R621-R625)).
2. Fixes #3636 style/format to match the pattern generally used on `raylib`. Does that by changing `w` to `width` ([R576-R578](https://github.com/raysan5/raylib/pull/3637/files#diff-14c6a8a6962cf65222635a523e877bbaa1f07b791028685f92bf6b44d87530d7R576-R578)), `h` to `height` ([R585-R587](https://github.com/raysan5/raylib/pull/3637/files#diff-14c6a8a6962cf65222635a523e877bbaa1f07b791028685f92bf6b44d87530d7R585-R587)) and adding relevant notes …
> [rcore] Add `GetWindowPosition()` implementation for `PLATFORM_WEB` and fixes #3636 style/format

- src/platforms/rcore_web.c
- @raysan5 I'm sorry for the very long PR. I know this is going to be a real pain to review. Tried to simplify things as much as possible, but it's a complicated problem with a lot of background information. Please, take your time.
- Unfortunately "fullscreen" is very challenging to handle completely and reliably on web. So far I've identified 5 "types" of "fullscreen" that affects `raylib` with `emscripten`:
- Invoked by the user pressing the `F11` key.
- Will bring the entire page to fullscreen.
- There's not much we do about this. The user will always be able to press `F11`, bringing the whole page to fullscreen.
- Luckly, the `F11 fullscreen` won't break the other "types" of "fullscreen". So the user can invoke the `F11 fullscreen` and then, after, any other "type" of "fullscreen" and …
> [rcore] Add `ToggleFullscreen()` implementation for `PLATFORM_WEB`

- src/rshapes.c
Hi,
I implemented segment miters for linear splines, meaning that the lines go from this : 
to this :
This breaks when the angle between two consecutive line segments is close to 0° (works fine when it's 180° though), so I'm not sure it should stay as a replacement to DrawSplineLinear, but a DrawSplineLinearMitered could maybe be created instead ?
I feel like the usual use case is to have reasonably small angles, in order to draw arbitrary, nice-looking lines, but this is probably not worth breaking existing code. 
Let me know what you think!
> Implement miters in DrawSplineLinear

- src/platforms/rcore_web.c
- This PR implements the following behavior:
1. `SetWindowState(FLAG_FULLSCREEN_MODE)` will activate the "standard fullscreen" only when:
1. There's no "type" of "fullscreen" currently active.
2. There's "borderless windowed fullscreen" (either ours or external, aka, called by a button) active ("hot swap").
2. `SetWindowState(FLAG_BORDERLESS_WINDOWED_MODE)` will activate the "borderless windowed fullscreen" only when:
1. There's no "type" of "fullscreen" currently active.
2. There's "standard fullscreen" (either ours or external, aka, called by a button) active ("hot swap").
3. `ClearWindowState(FLAG_FULLSCREEN_MODE)` will only leave "fullscreen" if "standard fullscreen" (either ours or external, aka, called by a button) is active.
4. `ClearWindowState(FLAG_BORDERLESS_WINDOWED_MODE)` will …
> [rcore] Fix fullscreen known issue 1 for `PLATFORM_WEB`

- src/platforms/rcore_web.c
1. This is an alternative fix for the `CORE.Input.Mouse.cursorHidden` issue reported by @lesleyrs on #3643.
2. IMHO, a better way to handle that issue is through the use of `emscripten`'s `em_pointerlockchange_callback_func` and `EmscriptenPointerlockChangeEvent` ([R117](https://github.com/raysan5/raylib/pull/3644/files#diff-14c6a8a6962cf65222635a523e877bbaa1f07b791028685f92bf6b44d87530d7R117), [R1208](https://github.com/raysan5/raylib/pull/3644/files#diff-14c6a8a6962cf65222635a523e877bbaa1f07b791028685f92bf6b44d87530d7R1208)) callback functions ([doc](https://emscripten.org/docs/api_reference/html5.h.html)). That way, there's no need to change `rcore.c` and the value can be updated internally on `rcore_web.c` when such event happen …
> [rcore] Alternative fix for `CORE.Input.Mouse.cursorHidden` for `PLATFORM_WEB`

- src/platforms/rcore_web.c
1. Adds a `cursorLUT` ([R86-R101](https://github.com/raysan5/raylib/pull/3647/files#diff-14c6a8a6962cf65222635a523e877bbaa1f07b791028685f92bf6b44d87530d7R86-R101)) for `PLATFORM_WEB` that will be used by `ShowCursor()` and `SetMouseCursor()` to select the correct mouse cursor, similar to how it's done for `PLATFORM_DESKTOP_SDL` ([L207-L221](https://github.com/raysan5/raylib/blob/master/src/platforms/rcore_desktop_sdl.c#L207-L221)).
2. Fixes `ShowCursor()` implementation for `PLATFORM_WEB` by adding the `EM_ASM` `style.cursor` call that will parse the `CORE.Input.Mouse.cursor` using the `cursorLUT` ([R771](https://github.com/raysan5/raylib/pull/3647/files#diff-14c6a8a6962cf65222635a523e877bbaa1f07b791028685f92bf6b44d87530d7R771)). To optimize this call, only executes if the cursor is …
> [rcore] Fix `ShowCursor()`, `HideCursor()` and review `SetMouseCursor()` for `PLATFORM_WEB`

- examples/shaders/shaders_deferred_render.c
- src/rlgl.h
previous example didn't correctly render with depth outside of the deferred pass. the DrawSphereWires didn't work.
> fix for deferred rendering example.

- BINDINGS.md
I made a COBOL "binding" of some sort.
RL can be used in COBOL without it, but it is barely usable, and my "binding" greatly improves the usability.
Typed in public domain as I am not a lawyer and all my code is not licensed.
> Add new COBOL binding

- projects/VSCode/.vscode/c_cpp_properties.json
- projects/VSCode/Makefile
Change vscode config and makefile to add a missing IOKit framework reference and use whichever MacOSX sdk symlink is available
> VSCode sample project Mac fixup

- examples/core/core_automation_events.c
- src/raylib.h
- src/rcore.c
Currently it manipulates the object directly, and thus breaks the expectations of Unload* functions accepting a copy and only freeing dynamic memory. It would be harder for binding devs to port their work to raylib 5.0, if all the functions don't follow a common pattern.
> Review UnloadAutomationEventList

- src/raylib.h
- src/rshapes.c
In order to allow external code to do the same thing as the rshapes functions, we need to export the shape texture and texture rect so that external shape functions can use them. 
This allows people to copy code from rshapes and build extended or new shape functions in user code and still have all the same features and optimizations that internal shape functions have.
> [rshapes] Expose shapes drawing texture and rectangle

- src/build.zig
A quick fix for [3674](https://github.com/raysan5/raylib/issues/3674).
- When a `zig` raylib program links to `zig-out/lib/libraylib.a` and tries to call `ImageResize`, it crashes with the following error:
```bash
INFO: IMAGE: Data loaded successfully (848x836 | R8G8B8A8 | 1 mipmaps)
Illegal instruction at address 0x506653
src/external/stb_image_resize2.h:6806:5: 0x506653 in stbir__alloc_internal_mem_and_build_samplers (/home/wison/zig/raylib-box2d-tutorials/raylib/src/rtextures.c)
src/external/stb_image_resize2.h:7603:14: 0x483415 in stbir__perform_build (/home/wison/zig/raylib-box2d-tutorials/raylib/src/rtextures.c)
src/external/stb_image_resize2.h:7639:12: 0x482184 in stbir_build_samplers_with_splits (/home/wison/zig/raylib-box2d-tutorials/raylib/src/rtextures.c) …
```
> [ fix-crash-caused-by-zig-build ] - Fixed 'Illegal instruction' crash on 'rtextures' and 'raudio' model that caused by zig build.

- src/platforms/rcore_desktop_sdl.c
- During the Christmas holidays a visiting relative was playing a game I've made with my kernel library on his very up-to-date notebook, but there were (low) framerates issues. Upon inspection the issue was the frame sleep time being too long on Windows. The problem was solved with `SDL_HINT_TIMER_RESOLUTION` which is kind of equivalent to Windows `timeBeginPeriod()/timeEndPeriod()`.
- Since `raylib`'s `PLATFORM_DESKTOP_SDL` doesn't use `rcore.c`'s `InitTimer()` ([L3040-L3047](https://github.com/raysan5/raylib/blob/99f22a47ff09ae3bef4ee16c1910953efc46832b/src/rcore.c#L3040-L3047)), it ends up having the same issue. And since this looks relevant enough, I'm sending this PR.
- This issue is more noticeable when `vsync` is turned off and a given frame cap is enforced.
1. Adds a …
> [rcore] Fix `SUPPORT_WINMM_HIGHRES_TIMER` for `PLATFORM_DESKTOP_SDL`

- src/rtextures.c
I would like my Raylib game to be a singular executable, and not have to load any files at compile time.
#Changes 
- Adds a function that's basically LoadImageAnim but it assumes fileData is provided at compile time.
> [rgraphics] Add LoadImageAnimFromMemory.

- src/rtext.c
1. Fixes the warning below (introduced after [#3678](https://github.com/raysan5/raylib/pull/3678)):
```
rtext.c: In function ‘TextReplace’:
rtext.c:1537:17: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
1537 |     insertPoint = text;
|                 ^
```
2. Does that by adding a cast to `insertPoint = (char*)text;` ([R1537](https://github.com/raysan5/raylib/pull/3687/files#diff-6f1fe84ccc0076f84a73e0d81ebdb1804c2fd972bb78084ced6336db2f8b8363R1537)).
- **1.** added line marks.
> [rtext] Fix `TextReplace()` warning for `const`

- src/raylib.h
- src/rtextures.c
1. Fixes the warning below (introduced after [#3681](https://github.com/raysan5/raylib/pull/3681)):
```
rtextures.c: In function ‘LoadImageAnimFromMemory’:
rtextures.c:472:46: warning: pointer targets in passing argument 2 of ‘LoadImageFromMemory’ differ in signedness [-Wpointer-sign]
472 |         image = LoadImageFromMemory(fileType,fileData,dataSize);
|                                              ^~~~~~~~
|                                              |
|                                              const char *
In file included from rtextures.c:64:
raylib.h:1305:76: note: expected ‘const unsigned char *’ but argument is of type ‘const char *’
1305 | RLAPI Image LoadImageFromMemory(const char *fileType, const unsigned char *fileData, int dataSize);      // Load image from memory …
```
> [rtextures] Fix `LoadImageAnimFromMemory()` warning for `fileData`

- src/rtextures.c
1. Fixes #3707.
2. Does that by hiding the `stb_image_resize2.h` unused warnings during compilation by using `#pragma` ([R216-R219](https://github.com/raysan5/raylib/pull/3708/files#diff-dd413e2d4cd85989a953b899ac2460398a88402b5717efc95fb11e592b83a767R216-R219), [R224-R226](https://github.com/raysan5/raylib/pull/3708/files#diff-dd413e2d4cd85989a953b899ac2460398a88402b5717efc95fb11e592b83a767R224-R226)) like it was done for `stb_truetype.h` at [#3235](https://github.com/raysan5/raylib/pull/3235).
- Not sure if this is really necessary as it's just two warnings. Please close this PR if that's too much.
- `PLATFORM_DESKTOP`, `Linux` (Mint 21.1 64-bit).
```
cd raylib-master/
make PLATFORM=PLATFORM_DESKTOP
```
> [rtextures] Hide unused warnings from `stb_image_resize2.h`

- examples/shapes/shapes_following_eyes.c
I found this bug and a trivial fix in the [shapes_following_eyes](https://www.raylib.com/examples/shapes/loader.html?name=shapes_following_eyes) example.
> Fix a bug in examples/shapes/shapes_following_eyes

- src/rtextures.c
The image manipulation functions `ImageColorInvert`, `ImageColorBrightness`, `ImageColorReplace`, and `ImageColorTint` all used a nested for loop with some math to index the 1d array of pixels.
These loops could be simplified to a single loop with a counter. I think this is not only more readable, but it has also shown some *slight* speed increases for very large images. My numbers below using the diff of time.h's clock function for a 7096 x 10031 image:
before:
```
brightness 0.932933
replace 0.910925
tint 1.116619
invert 0.785766
```
after:
```
brightness 0.784316
replace 0.782897
tint 0.934186
invert 0.699755
```
> Simplified for loop for some image manipulation functions

- src/rtext.c
#3717 
The old padding*4 results in around 80px of padding area when the actual amount of padding area was 144px. Adding the padding to the width and height separately instead of only to width should give the exact amount of area after padding, and should better account for fonts with very wide glyphs. With this change I no longer lose glyphs even at impractically small font sizes in the 1-7px range. The 1.2x constant could potentially be reduced now that the area calculation is more accurate.
> [rtext] Adjust font atlas area calculation so padding area is not underestimated at small font sizes.

- src/rcore.c
in #3523 we moved `RecordAutomationEvent()` from after `PollInputEvents()` to before it, but the comment was not updated.
> Update a comment

- src/rtextures.c
There seems to be an error in `ImageDrawRectangleRec` where we should subtract the absolute values of `rec.x` and `rec.y` from `rec.width` and `rec.height` when they are negative.
Currently, we are subtracting the negative values, which is equivalent to addition. For example, in the current implementation:
If we replace `size -= position` with `size += position`, considering that the position is negative, we correctly subtract the difference as desired. This results _(the visual glitches are from my screen recorder)_:
> Fix `ImageDrawRectangleRec`

- src/rtextures.c
`ImageResizeCanvas()` accepts a fill color, that was so far unused, with a TODO to implement it.
This is a fairly simple implementation that fills in the entire canvas, with a minor optimization to copy entire rows once the first one is filled.
The implementation is similar to `ImageClearBackground()`, this could possibly be unified in the future.
I was unsure about the desired level of code commenting, so I opted for extensive comments, in line with the contributing guide.
Tested on Linux:
- build
- functionality
- with valgrind (for invalid read/writes)
> [rtextures] implemented fill color TODO in ImageResizeCanvas()

- build.zig
- examples/build.zig
- src/build.zig
The recent 0.12.0dev update caused some breakage in the build system.
This method does require the use of `anytype`, but the argument name and type checks should make it obvious what type it expects. This should not break any existing code.
Tested on linux with zig 0.12.0dev and 0.11.0
```
raylib$ zig build
raylib$ zigup run 0.11.0 build
raylib$ cd examples/
raylib/examples$ zig build
raylib/examples$ zigup run 0.11.0 build
```
Once 0.12.0 is released we can remove all of these compatibility functions
> Update to latest zig 0.12.0dev while keeping 0.11.0 compatibility

- src/rmodels.c
Hello! I am not sure why this line was commented out, but this patch seems to work fine. Thank you very much.
> Enable animation names for the m3d model format.

- build.zig
- src/build.zig
Using raylib as a shared library was helpful for hot-module reloading, allowing both the main executable and shared game library to link with raylib and then we can reload without segfaulting. I needed the no-sanitize flag to work around an illegal instruction error.
Here is the source for that example: https://github.com/candrewlee14/tetris-raylib
> Add shared library build option for build.zig and update to zig 0.12.0-dev.2139

- src/platforms/rcore_desktop.c
- src/platforms/rcore_web.c
Simplified `GetWindowScaleDPI()` so it does not fetch the wrong DPI scale some times (Windows or GLFW looks at center of window while the old raylib code looked on upper left corner of window, now it just uses the `glfwGetWindowContentScale` function to fetch the window's current scaling). The old behavior caused problems when having a system with multiple monitors where one monitor had different scaling than the other. When you moved the window back and forth between the monitors, then `WindowSizeCallback` happened since the window size changes due to the scaling. But since the upper left corner was still on the other monitor (when pulling the window to a new monitor that is to the right of the old one), then `GetWindowScaleDPI()` reported the wrong scale and used that to update the …
> High DPI bug fixes

- src/rtextures.c
I was having originally having issues with image drawing functions causing memory corruptions, I found that the condition for the bounds check in `ImageDrawRectangleRec` misses cases near the edges of the `Image`. I used code like this, running with valgrind, to verify that the memory corruption no longer occurs: (sorry for the mess)
```c++
#define IMAGE_SIZE 4
#define OVERSCAN 2
#define MAX_DRAW_SIZE (IMAGE_SIZE + OVERSCAN * 2)
int main()
{
Image image = GenImageColor(IMAGE_SIZE, IMAGE_SIZE, BLANK);
for (int y = -(MAX_DRAW_SIZE + OVERSCAN); y <= IMAGE_SIZE + OVERSCAN; y++)
{
for (int x = -(MAX_DRAW_SIZE + OVERSCAN); x <= IMAGE_SIZE + OVERSCAN; x++)
{
for (int w = -MAX_DRAW_SIZE; w <= MAX_DRAW_SIZE; w++)
{
for (int h = -MAX_DRAW_SIZE; h <= …
```
> Fix bounds check for `ImageDrawRectangleRec`

- src/platforms/rcore_web.c
Hi,
I'm trying raylib on my iPad using emscripten. I found that raylib and raygui don't work well. We need updated mouse position yet it's never updated (always 0,0). As a result, [Cubic-bezier lines](https://www.raylib.com/examples/shapes/loader.html?name=shapes_lines_bezier) doesn't work on iPad.
I don't fully understand how it works on desktop browser, but it may be reasonable to update mouse position of we are using touch screen?
This is not pretty, but after this fix, raylib and raygui work just fine.
If you have better fix, then it's great. Just kindly discard this pull request.
> Make raylib/raygui work better on touchscreen

- src/rcore.c
- src/rglfw.c
Reference to #254 
Original issue seems resolved by build step (make, cmake, zig), however looking at the source code, it seems the original intent was to include the Feature Test Macros per file. This seems logical for self-documenting purposes and outline requirements for raylib.
However, the macros are defined after includes, so they won't work.
See: [GNU Feature Test Macros](https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html)
> You should define these macros by using ‘#define’ preprocessor directives at the top of your source code files. These directives must come before any #include of a system header file. It is best to make them the very first thing in the file, preceded only by comments.
I've simply moved the rcore _POSIX_C_SOURCE feature test macro to the …
> [rcore rglfw] Feature Test Macros before include

- parser/output/raylib_api.json
- parser/output/raylib_api.lua
- parser/output/raylib_api.txt
- parser/output/raylib_api.xml
- src/platforms/rcore_android.c
- src/raylib.h
Fixes #3729
Fixes #3734
All of the keys I am able to test are correct. However, I cannot test the keypad (because I use a tenkeyless keyboard), the keyboard menu key (because my keyboard lacks it) and the Android menu key (because my phone lacks it and also because of #3734). Additionally, the Super (Windows) and Print Screen keys are grabbed by the system and apparently cannot be caught by the app.
~**Note:** there seems to be an issue (already present, not introduced by this PR) in which the app freezes on Android if a keyboard is connected after the app starts. For this reason, I recommend testers to connect a keyboard and force stop the test app before starting it~ (fixed by including ``keyboard`` in the manifest's ``android:configChanges``).
**Update:** with 1df491c54, #3734 is also …
> Fix Android keycode translation and duplicate key constants

- src/rlgl.h
Fixed the typo in the comment `We are building he library as ...` by replacing "he" with "the".
> [RLGL] fixed typo, replaced `th` with `the`

- src/raymath.h
The pull request is divided into 2 small commits, so you may don't want to merge both.
1. I identified two functions that have duplicated code, so I refactored to avoid it. You might don't want to merge this change because you might prefer the readability, but I just wanted to give it a try in case you agree with it :)
2. A ternary operator didn't have proper left space as the rest. Some divisions have both spaces also.
> [raymath.h] Small code refactor

- src/raudio.c
Changed some comments format to align comments style.
> [raudio.c] Reformated some comments

- src/rtext.c
Here is another set of minor changes to comments of rtext.c :)
> [rtext.c] fixing some comments to align comments style

- src/rlgl.h
Fix rlSetUniformSampler not setting sampler uniform if the same texture was already passed to a different sampler uniform
> Fix rlSetUniformSampler

- src/raudio.c
NOTICE: THIS IS THE SAME COMMIT AS [#17](https://github.com/raysan5/raudio/pull/17) IN RAUDIO. I PUT THIS HERE TO HAVE BOTH REPOS SYNCED.
Hey,
While I updated raudio [#16](https://github.com/raysan5/raudio/pull/16), I also found some bugs & afterthoughts with "raudio.c".
First, as GetFileNameWithoutExt, GetFileName & strprbrk were linked to Raylib itself I had to add them to "raudio.c" under the "RAUDIO_STANDALONE" define for standalone mode to work. Point at which the functions were added:
- (15-04-2023) RadsammyT: "[[raudio] Rewritten ExportWaveAsCode() file saving to be more like rtextures ExportImageAsCode() (raysan5#3013)](https://github.com/sanyokdev/raylib/commit/e2da32e2daf2cf4de86cc1128a7b3ba66a1bab1c)"
Second, I use a lot compiler flags so it found that "SaveFileData" & …
> Added missing "standalone" functions to raudio.c & fixed return bug

- src/rcamera.h
I assume these were accidentally left in. they were made in the redesign https://github.com/raysan5/raylib/pull/2563 but the macros were used in the finished pull. I guess a new redesign since then rendered the macros useless.
> [rcamera.h] cleaned away unused macros in rcamera.h

- src/rcore.c
- src/rlgl.h
There are 3 places in raylib that set the OpenGL modelview matrix scale to the screen scale (for HighDPI).
1 of these is incorrect, BeginMode2d, as the camera is going to do it's own scale.
The other two assume that when we end 2d and 3d mode that we are going back to the screen. That is not always true. BeginMode2d/3d can be used with a render texture and a render texture can be any size and doesn't have to match the screen DPI scale (it's not a screen).
This PR exposes the GL function to get the active draw FBO, and then has raylib use that to know what render target it is restoring to, and if it needs to apply the scale. 
This change should make using a render texture more consistent.
> [CORE,RLGL] Fix scale issues when ending a mode

- src/rtext.c
For multiline strings `MeasureTextEx()` is returning a much higher value than the actual text height.
Pretty much like `DrawTextEx()` this patch just increment `textLineSpacing` in the height when it sees `\n` and don't apply `scaleFactor` at the end.
Small program to simulate the issue:
```c
#include <stdlib.h>
InitWindow(200, 100, "MeasureTextEx");
Font font = GetFontDefault();
ClearBackground(WHITE);
const char *text = "Some\nMultiline\nText";
float fontSize = 20;
float spacing = 5;
SetTextLineSpacing(fontSize + 4);
DrawTextEx(font, text, (Vector2){10, 10}, fontSize, spacing, BLACK);
// draw red box around text
Vector2 m = MeasureTextEx(font, text, fontSize, spacing); …
```
> Fix MeasureTextEx() height calculation

- src/raudio.c
`char *txtData = (char *)RL_CALLOC(waveDataSize * 6 + 2000, sizeof(char));`
assumes every chunk being added to txtData is 6 bytes. This is not always true, sometimes a newline is involved and the data becomes 12 bytes instead, and this can cause a random segfault.
This commit changes `6` to `12`, and explains why in the comment.
> Fix segfault in ExportWaveAsCode

- BINDINGS.md
As of [this](https://github.com/ChrisDill/Raylib-cs/commit/5d23b5ca71d1940fa8ded9e63d71a8fe29d243b1) commit in the [Raylib-cs](https://github.com/ChrisDill/Raylib-cs) repo, it now supports raylib version 5.0.
> [docs] Correct supported raylib version of Raylib-cs to '5.0'

- src/config.h
- src/rtext.c
Added support for loading BDF fonts (spec version 2.1).
Side-note: in the future we may want to add the parameter `fileType` to `LoadFontData` so it can support more formats than just TTF. BDF font loading was implemented using `LoadBDFFontData`, so it wouldn't be difficult to make the change to support this if we wanted.
> [rtext] Add BDF font support

- src/platforms/rcore_desktop_sdl.c
Adds gamepad support to PLATFORM_DESKTOP_SDL.
Tested on FreeBSD 13
> Add gamepad support to PLATFORM_DESKTOP_SDL

- src/rcore.c
```c
puts( GetFileNameWithoutExt("dir/file.name.zip") ); 
// out : "file"
```
[with fix]
```c
puts( GetFileNameWithoutExt("dir/file.name.zip") );
// out : "file.name"
```
Use reverse search '.' for remove extension.
> [rcore] Fix `GetFileNameWithoutExt()`

- src/raylib.h
- src/rcore.c
`GetMouseRay` did not allow the user to cast a ray from the camera to the world view while in a `viewport` or `renderTexture`. To improve raylib, I added `GetMouseRayEx`, which has new arguments (width and height), making it easier to cast a ray to a specific viewport.
> Added viewport independent raycast

- src/raymath.h
Proposal to fix unnecessary promotion from float to double.
`implicit conversion increases floating-point precision: 'float' to 'double' [-Wdouble-promotion]`
> Fix implicit conversion from float to double then back to float again

- src/rmodels.c
When I was working on my 3D project I found an issue that single frame animations (like T-Pose) are not loaded. Upon investigating the reason I realised that frame count calculated based on animation length (which is 0 apparently).
Using some basic combinatorics I added 1 at the end of frame count calculations. It is easy to think of a veeeery small animation (like 0.01 second) which still has to have minimum 2 frames. Animations with 0 length should have at least 1.
Also **fmax** is preventing NaN division result when **tend** and **tstart** are both 0.
> Fixed loading GLTF animations with 1 frame

- CMakeOptions.txt
- cmake/LibraryConfigurations.cmake
Adds a PLATFORM=SDL option to CMakeLists.txt, handled in LibraryConfigurations.cmake
Tested on Win 11 ARM64 (MSVC, vcpkg)
> Add CMake PLATFORM option for SDL

- examples/build.zig
- src/Makefile
- src/build.zig
The purpose of this directory in GLFW is to provide some headers that "mingw.org" doesn't. Raylib has long been unable to build with mingw.org due to using certain symbols that aren't exposed in their headers. (_ftelli64 and _access, among others.). Mingw-w64 already has the necessary headers included, and doesn't need any of these external implementations. For some reason, this also causes the following error when building with Visual Studio's clang:
clang  -c rglfw.c -Wall -D_GNU_SOURCE -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing  -std=c99 -O1 -Werror=implicit-function-declaration -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mingw In file included from rglfw.c:61:
In file included from ./external/glfw/src/init.c:30: In …
> Remove all uses of deps/mingw

- examples/textures/textures_image_generation.c
Fixed a grammatical error by removing "are" to change `... but some are have multiple purposes ...` to `... but some have multiple purposes ...` in `textures/textures_image_generation`
> Fixed typo in a comment (#3816)

- src/config.h
- src/platforms/rcore_android.c
- src/platforms/rcore_desktop.c
- src/platforms/rcore_desktop_sdl.c
- src/platforms/rcore_drm.c
- src/platforms/rcore_web.c
- src/raylib.h
- src/rcore.c
As discussed in issue https://github.com/raysan5/raylib/issues/3815, I added a function `SetGamepadVibration(int gamepad, float leftMotor, float rightMotor)`. I also added a new define, `MAX_GAMEPAD_VIBRATION_TIME 2.0f` to control the maximum duration of the vibration. When the user sends `SetGamepadVibration(gamepad, float 0.0f, float 0.0f)`, it cancels the vibration. Otherwise it continues on for MAX_GAMEPAD_VIBRATION_TIME. 
It seems to work well on my end with an 8BitDo Pro 2 controller set both to Nintendo Switch Pro and Xbox One modes. Perhaps the max time could be changed to something else, but 2 seconds seem to be fine.
Currently the function is set as not returning a value, the SDL function returns -1 if rumble isn't supported on the controller. Should something like that be …
> Gamepad rumble support with SDL2

- src/utils.c
Hello, I decided to add this little sanitization for the '-' characater to the exported identifiers since find it quite useful for me and may help to other raylib users that use '-' in their file names.
Without this change any exported data to a file name containing the character would not compile since it's not a valid character for identifiers, I could have added more characters to be replaced ('@', '#', '%', etc) but i don't think they are really used for the use cases of `ExportDataAsCode()`.
Thanks for your time ❤️
> Add very little sanitization to indentifier names in ExportDataAsCode()

- examples/CMakeLists.txt
Currently, every example fails linking likeso:
[  3%] Linking C executable audio_mixed_processor
/usr/bin/ld: ../raylib/libraylib.a(raudio.c.o): undefined reference to symbol 'exp@@GLIBC_2.29' /usr/bin/ld: /usr/lib/libm.so.6: error adding symbols: DSO missing from command line collect2: error: ld returned 1 exit status
Apparently, linking libm explicitly is the solution.
> Fix examples linking with CMake and -DPLATFORM=SDL

- src/rtextures.c
fixes https://github.com/raysan5/raylib/issues/3665
The format of the cubemap was not being set and was defaulted to 0, causing IsTextureReady() to fail.
> Fixes IsTextureReady() returns false after successful call of LoadTextureCubemap()

- examples/others/raylib_opengl_interop.c
I tested this with CMake. I don't know if the examples makefile currently handles this case.
The resulting executable runs and produces the expected output.
NOTE: testing this PR depends on #3825, otherwise this example won't even link due to the issue that PR resolves.
Though I hope it's trivial enough that there aren't problems I missed.
> Fix building of raylib_opengl_interop on PLATFORM_DESKTOP_SDL

- src/raymath.h
Some of the Vector3 functions have no Vector2 equivalent and vice-versa, this helps increase parity a bit. Functions added for Vector2 and Vector3:
```cpp
Vector2 Vector2Min(Vector2 v1, Vector2 v2);
Vector2 Vector2Max(Vector2 v1, Vector2 v2);
Vector2 Vector2Refract(Vector2 v, Vector2 n, float r);
Vector3 Vector3MoveTowards(Vector3 v, Vector3 target, float maxDistance);
```
Also added `Vector4` math functions:
```cpp
Vector4 Vector4Zero(void);
Vector4 Vector4One(void);
Vector4 Vector4Add(Vector4 v1, Vector4 v2);
Vector4 Vector4Subtract(Vector4 v1, Vector4 v2);
Vector4 Vector4SubtractValue(Vector4 v, float add);
float Vector4Length(Vector4 v);
float Vector4LengthSqr(Vector4 v);
float Vector4DotProduct(Vector4 v1, Vector4 v2);
float Vector4Distance(Vector4 v1, Vector4 v2);
float …
```
> More Vector math functions

- src/rmodels.c
Follows the format of the previous cases.
> Add parsing for gltf u16 vec4 joints in rmodels.c

- src/build.zig
I figured out what the problem for #3834 was and found a solution to fix it as well.
The first problem was, that `srcdir` is an absolut path, but using `.{.path = ...}` is supposed to be relative only. So I instead changed it to use `.cwd_relative` which is badly named, but the appropriate field to use for absolute paths.
The next problem was, that the files added via `addCSourceFilesVersioned` needed to be relativ to the module (raylib itself) so I figured out a way to get the relative path and added that too.
~~Theres still a minor problem with getting the relative path, but that shouldn't take that long to fix.~~
> fix build paths

- cmake/LibraryConfigurations.cmake
Encountering `/usr/include/xf86drm.h:40:10: fatal error: drm.h: No such file or directory`
when doing a cross-compile I found that
```
cmake -DCMAKE_C_FLAGS=-I/usr/include/libdrm …
```
is needed. Some digging revealed that in my case #1717 spoils the libdrm includes.
The unexpected and different situation here: I'm doing a cross-compile on a multi-arch image.
I.e. I run an arm-linux-gnueabihf compiler on aarch64 and the armhf libs are installed side-by-side with the arm64 libs -- no need for a sysroot.
I propose to only drop the libdrm include path if a sysroot is actually used.
> Fix DRM cross-compile without sysroot

- src/utils.c
I opted to use `isalnum` function since it should handle most cases. It cannot however handle cases of files beginning with numbers.
> Change sanitization check for `ExportDataAsCode`

- examples/models/models_first_person_maze.c
- examples/others/raylib_opengl_interop.c
- examples/text/text_codepoints_loading.c
Fix the below warnings in examples for macos (version 14.3.1, clang 14):
others/raylib_opengl_interop.c:158:5: warning: 'glDeleteVertexArrays' is deprecated: first deprecated in macOS 10.14 - OpenGL API deprecated. (Define GL_SILENCE_DEPRECATION to silence these warnings) [-Wdeprecated-declarations]
glDeleteVertexArrays(1, &vao);
models/models_first_person_maze.c:37:13: warning: unused variable 'position' [-Wunused-variable]
Vector3 position = { 0.0f, 0.0f, 0.0f };            // Set model position
text/text_codepoints_loading.c:63:9: warning: variable 'codepoint' set but not used [-Wunused-but-set-variable]
int codepoint = 0;
> Fix examples warnings for macos

- cmake/GlfwImport.cmake
- src/platforms/rcore_desktop.c
With the ``GLFW_MOUSE_PASSTHROUGH`` constant now available in GLFW 3.4, this hack is no longer necessary.
> Remove GLFW mouse passthrough hack and increase GLFW version in CMake

- src/build.zig
#3835 Broke builds for zig versions 0.11.0 (LATEST STABLE) and  0.12.0-dev.2075+f5978181e when attempting to add support for 0.12.0-dev.2990+31763d28c. This patch supports builds for all three versions.
> [build] Fix fix-build-paths

- examples/CMakeLists.txt
The `rlgl_standalone` example depends on having glfw. On the SDL build, glfw is not embedded directly, so we'll have to link it.
> Fix CMake SDL build for rlgl_standalone

- examples/CMakeLists.txt
Follows up from #3860 to completely disable the SDL build for rlgl_standalone in CMake.
cc @Peter0x44
> [cmake] Disable SDL rlgl_standalone example

- src/platforms/rcore_desktop_sdl.c
I did some testing and this seems to work okay, but it *is* different to GLFW. GLFW seems to lose "IsCursorOnScreen" for one frame upon pressing alt+tab over the window, without a different window covering it. SDL seems to have a more reasonable behavior for this case. Either way it's an edge case and I don't know the exact way to fix, likely requires internal GLFW changes.
> Implement IsCursorOnScreen for PLATFORM_DESKTOP_SDL

- src/platforms/rcore_desktop.c
When the cursor is disabled we need to put GLFW in relative mouse motion mode. If we don't some platforms (linux) can get drift in the mouse position. 
This PR sets the GLFW mode when we disable/enable the cursor.
> [PLATFORM DESKTOP] Use relative mouse mode when cursor is disabled

- src/rmodels.c
This PR removes the call to `rlDisableVertexAttribute` for `SHADER_LOC_VERTEX_COLOR` in `DrawMesh` and `DrawMeshInstanced`, because it was being called in cases where this location is not set in the shader. This resulted in an invalid value (-1) being passed to `rlDisableVertexAttribute` which made an **OpenGL error `GL_INVALID_VALUE`**. 
Furthermore the same function is **already being called**  with correct checks (checking if location attribute is set and vboId[3]==0) few lines above (rmodels.c:1450 and rmodels.c:1671 in the original source).
This solves issue https://github.com/raysan5/raylib/issues/3841
> [rmodels] Remove redundant call for disabling vertex color attribute

- src/rtextures.c
Before this PR, LoadImageFromScreen was not applying the scale DPI to both width and height. After this PR, the behaviour of LoadImageFromScreen is the same as TakeScreenshot, but returns an image instead. Not sure if this is the appropriate fix, but this was what I was expecting when calling the function. If there needs to be adjustments such as calling ImageResize to get the current width and height instead of the scaled one, let me know.
> [rtextures] Fix LoadImageFromScreen scaling

- src/platforms/rcore_drm.c
- Sorry for the awfully long single commit, the way I developed this, that was the only way
- This PR is kind of a WIP and maybe even a XY problem
- Theses changes are theoretically breaking
---
So I'm currently using a raspberry pi and a small display plus a rotary encoder to built a little device. I'm using raylib for the software, because of the direct drm support, so I can avoid X11. Problem is: raylib doesn't support rotary encoders when selecting `PLATFORM_DRM`. This is because rotary encoders basically either have one relative or one absolute axis, but the way `rcore_drm.c` is detecting devices doesn't allow for that, it required at least two axes.
So the problem now is how one classifies the different kind of input devices into the categories raylib exposes. (This isn't …
> Organizing the drm backend to only use one api to allow for more devices

- src/build.zig
Not even sure if this should be approached this way, however it's the first step to be fixed :)
> Fixes zig build that was broken on #3863

- src/build.zig
The changes brought by #3891 uses `std.process.Child.run` which was renamed from `std.process.Child.exec` in Zig version 0.11.0, resulting in an error when trying to build raylib with Zig version 0.11.0. This commit adds a version check to use the appropriate function names.
Additionally, the `linux_display_backend` configuration option is added so users can set it when running `zig build` with the `-D` option or when using raylib as a dependency.
Tested with Zig version `0.11.0` and version `0.12.0-dev.3522+b88ae8dbd`.
Resolves #3895.
> Fix #3891 breaking builds for Zig v0.11.0

- examples/shaders/shaders_hybrid_render.c
Just adds the missing letter "t" to a comment line :p
> Fix typo in example scene: shaders_hybrid_render.c

- src/build.zig
+ `installHeader`'s signature was changed recently, so a versioned function was added for it
+ `srcdir` isn't needed, just adding "src/" before each path is sufficient
+ cabarger's hack seems to not be needed anymore
+ `process.Child.run` and `process.Child.exec` was coerced into a single function
Tested on ubuntu x64, on both 0.12.0-dev.3580+e204a6edb and 0.11.0
> Update to latest zig and simplify build.zig

- src/build.zig
I'm getting an error when attempting to build using the latest raylib and Zig master (0.12.0-dev.3635+786876c05):
```
zig build -Dtarget=wasm32-emscripten
install
└─ install raylib failure
error: unable to update file from '.../src/raylib.h' to '.../zig-out/include/raylib.h': FileNotFound
Build Summary: 15/17 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ install raylib failure
error: the following build command failed with exit code 1:
.../zig-cache/o/8c0437471634c5f3da2ba2e71966fe50/build /home/vscode/.zvm/master/zig / .../zig-cache /home/vscode/.cache/zig --seed 0xbfa3d8ae -Z33b99a15b162f409 -Dtarget=wasm32-emscripten
```
As far as I can tell this isn't resolved by #3913 so I'm submitting this request.
To resolve I updated the LazyPath that raylib …
> [build.zig] Fix FileNotFound: .../src/raylib.h

- src/raudio.c
Fixes some crashes, e.g. calling StopMusicStream after trying to load Music from a non-existant .mp3 file
> Reset music.ctxType if loading wasn't succesful

- src/raymath.h
- src/rmodels.c
I noticed that the GLTF animation loading only supported linear interpolation, so by adding support for `cgltf_interpolation_type_step` and `cgltf_interpolation_type_cubic_spline` this should cover most cases.
This was tested using `robot.gltf` by importing it into Blender, removing some keyframes, using constant and bezier interpolation, and then rerunning the `models_loading_gltf.exe` example. Step is easy to recognize, and I think the spline looks right as well, but I would love someone with discerning eyes to tell me if it looks accurate.
Here's videos of the exact same animation timeline with different interpolation applied:
- Step interpolation example:
https://github.com/raysan5/raylib/assets/64439681/f4e1d9b9-815b-412c-b62f-d503aea90955
- Bezier interpolation example: …
> Added missing interpolation types for GLTF animation channels

- src/platforms/rcore_desktop_sdl.c
The key handling in `PLATFORM_DESKTOP_SDL` was faulty in two ways, which led to `GetKeyPressed` returning incorrect data.
`CORE.Input.Keyboard.keyPressedQueue` was updated only on `SDL_TEXTINPUT`, meaning only text characters were registered as a pressed key, but not function keys (eg. tab, backspace...).
Also on such event, both `CORE.Input.Keyboard.keyPressedQueue` and `CORE.Input.Keyboard.charPressedQueue` were assigned the key's corresponding codepoint, when `CORE.Input.Keyboard.keyPressedQueue` should get the raylib keycode instead.
`CORE.Input.Keyboard.keyPressedQueue` is now updated on `SDL_KEYDOWN` event instead.
> [rcore] Fix GetKeyPressed for PLATFORM_DESKTOP_SDL

- src/raymath.h
- src/rmodels.c
This is a follow up PR on #3919.
During that PR, I went researching for a quaternion cubic spline algorithm that could be used, and landed on SQUAD. Turns out, the GLTF 2.0 very specifically [provides an algorithm](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#interpolation-cubic) that is says to use (which looks to me like Cubic Hermite Spline):
```
Let ak, vk, and bk be the in-tangent, the property value, and the out-tangent of the k-th frame respectively.
The interpolated sampler value vt at the timestamp tc is computed as follows.
vt=(2t3−3t2+1)∗vk+td(t3−2t2+t)∗bk+(−2t3+3t2)∗vk+1+td(t3−t2)∗ak+1
```
However, Cubic Hermite Spline showed flipping/spinning when I was doing tests due to quaternion double-cover. To alleviate this, I added some logic to check the dot product and …
> Replaced SQUAD interpolation with Cubic Hermite to align with GLTF 2.0 spec

- src/platforms/rcore_desktop.c
The way the current code worked was by calling `GetCurrentMonitor()`, which would always return the monitor at position (0,0). This isn't the primary monitor on all platforms, on Linux in particular it isn't the case.
This isn't the case on the SDL backend, after calling `InitWindow()` the window would always show up on the primary monitor. Even on the GLFW backend, if the full screen flag was set it would attempt to put it on the primary monitor as it would call `glfwGetPrimaryMonitor()` to do it, so for consistency's sake we should do it on windowed mode too.
> Fix window not initializing on primary monitor on GLFW backend

- src/raudio.c
This pull request fixes #3664 .
However, it fixes things slightly different than originally thought/intended.
The triggering issue with `UpdateMusicStream()` was in as much mitigated by removing the entire hack code, as it was a no-op. See [comment for details](https://github.com/raysan5/raylib/issues/3664#issuecomment-2044458367).
Included changes:
* Remove hack from `UpdateMusicStream()` and `PlayMusicStream()`
* Add mutex lock/unlock to all functions called from main thread that share buffer member access
* This required separation of some of the functions, as they are called from both threads and mutex is not re-entrant. Suffix `InLockedState` was added to indicate this.
* Fix for cleanup of order of buffer/converter; Initialisation sets up converter, then tracks buffer - deinit must …
> [raudio] Fix 3664: crash in raudio from multithreading issues

- build.zig
- examples/build.zig
- src/build.zig
With the release of zig 0.12.0, supporting 0.11.0 is no longer necessary.
Changes:
+ remove all 0.11.0 compatibility functions
+ remove most LazyPath `.path` variants
+ I didn't touch emscripten, I don't know if it's relative or absolute
+ change all absolute paths to use `.cwd_relative`
+ only use the builder's allocator
+ have local dependencies use the package manager
+ make adding raygui more flexible
+ use zig-cache for generated wayland files
`build.zig.zon`:
```diff
.dependencies = .{
+  .raylib = .{ // the dependency name "raylib" can be overridden in addRaylib's options with .raylib_dependency_name
+    .path = "path/to/raylib",
+  },
+  .raygui = .{ // the dependency name "raygui" can be overridden in addRaylib's options with .raygui_dependency_name
+    .path = …
```
> [build.zig] Drop support for 0.11.0 and use more idiomatic build script code

- examples/models/models_skybox.c
- src/rcore.c
- src/rlgl.h
**NOTE**: The PR at the moment is just a proof-of-concept to show the scale of modifications necessary to make this happen. Should it be reviewed well i will add the utils for `rlClipDistanceNear` and fix any use of `RL_CULL_DISTANCE*`, for example in the camera. Also i am not too sure about the name, when "cull" when "clip"
As discussed on discord [here](https://discord.com/channels/426912293134270465/1227696407389933649) and then mentioned [here](https://discord.com/channels/426912293134270465/426912531429457930/1227712810679799888) the current `CULL_DISTANCE`s are hardcoded and require a full recompile to change.
By adding static `rlCullDistance` globals and accessor function we can make this a runtime configurable value.
The current `RL_CULL_DISTANCE_` remain as configuration of the …
> [rlgl] Add rlCullDistance variables/getters and rlSetClipPlanes function

- src/rcamera.h
`rcamera.h` states that if `UpdateCamera()` is passed CAMERA_CUSTOM as an argument; the function  will do nothing. Source: https://github.com/raysan5/raylib/blob/master/src/rcamera.h#L120
However, the implementation of `UpdateCamera()`, has no checks to see if the mode passed is CAMERA_CUSTOM. 
https://github.com/raysan5/raylib/blob/master/src/rcamera.h#L438C6-L464
If `UpdateCamera` receives CAMERA_CUSTOM as argument; it will execute all the camera updating functions from lines 458 to 463.
This has the following effect:
https://github.com/raysan5/raylib/assets/65001595/a853549f-bb17-47af-b79b-ef2021d2ef12
After the patch is applied; this behavior changes:
https://github.com/raysan5/raylib/assets/65001595/121953c7-779c-4e41-9cbe-89f61abd9b00
Now `UpdateCamera()` won't modify the camera …
> [rcamera] Added missing CAMERA_CUSTOM check in  `UpdateCamera(Camera *camera, int mode)` function

- src/external/sinfl.h
Clang on windows defines both _MSC_VER and __clang__ for compatibility reason. The logic in sinfl.h selects the MSVC buitlin which clang only understands in clang-cl compatibility mode. If compiled with regular clang _MSC_VER is defined but the _BitScanReverse builtin is not recognised. This leads to the following warning during compilation:
```
In file included from ../raylib/src\rcore.c:141:
../raylib/src/external/sinfl.h:175:19: warning: incompatible pointer types passing 'unsigned int *' to parameter of type
'unsigned long *' [-Wincompatible-pointer-types]
175 |   _BitScanReverse(&n, n);
|                   ^~
```
This PR fixes that by selecting the __builtin_clz builtin if __clang__ is defined.
> Use builtin_clz for clang on windows

- src/raylib.h
This is a follow up to this PR: https://github.com/raysan5/raylib/pull/3938
This would make the comments in `raylib.h` match the ones present in `rcamera.h`.
Here are the `rcamera.h` comments: https://github.com/raysan5/raylib/blob/master/src/rcamera.h#L119-L125
> [raylib.h] Made comments on raylib.h match those present in rcamera.h

- src/raylib.h
Changed a comment because it didn't fit with the others.
> Changed one minor Comment

- src/platforms/rcore_desktop.c
This pull request fixes #3693 .
Tested under MS Win11, with `core_basic_window.c` sample under `raylib\projects\scripts\`, using a three-monitor setup (see linked issue for monitor layout).
This pull request causes the following regarding window initialization, when started via file-explorer without console on the three screens:
* windowed (`InitWindow(>0, >0, ...)`): window is of requested size, always centred on the monitor where file-explorer is
* fullscreen (`SetConfigFlags(FLAG_FULLSCREEN_MODE);`): Always a fullscreen window on the primary monitor
* windowed fullscreen (`InitWindow(0, 0, ...)`): window is of monitor size, filling the monitor where file-explorer is *)
* Fullscreen applications use the primary monitor, exclusively. This is as per recommendation of comment from …
> [rcore_desktop] Fix 3693 initial window geometry

- src/platforms/rcore_drm.c
Hello :)
I would like to propose an implementation for the following functions for the DRM platform : 
- int GetMonitorWidth(int monitor)
- int GetMonitorHeight(int monitor)
- int GetMonitorPhysicalWidth(int monitor)
- int GetMonitorPhysicalHeight(int monitor)
- const char *GetMonitorName(int monitor)
Although the monitor selection is not supported for the drm platform I kept the argument to avoid having multiple function prototypes.
I hope it complies to your coding rules :)
> Implementing GetMonitorWidth/Height for DRM

- src/Makefile
- src/external/RGFW.h
An issue was found the RGFW platform while a user was trying to create bindings wherein mingw did not define `nanosleep`.
It turns out I was wrong in assuming that all distros of mingw support `nanosleep`. 
This fixes the issue by never using nanosleep when compiling for windows. 
Source issue: https://github.com/ColleagueRiley/RGFW/issues/13
> Do not use "nanosleep" on windows at all (PLATFORM_DESKTOP_RGFW)

- src/build.zig
Added `opengl_version` option to `src/build.zig`.
I was manual-testing it on a Linux machine, and it works well. However, I am unsure of how correct the code is for target-specific OpenGL options. Currently, it prioritizes user-defined option and doesn't do anything linking-related so the user handles it himself (like linking GLESv2).
> feat(zig): add `opengl_version` option

- parser/raylib_parser.c
This fix allows to parse `()` like `(void)` in the function parameters.
Another way to fix is to add `void` into following lines:
https://github.com/raysan5/raylib/blob/f62202198e35161a9fe394a14bbd1a7c655107ad/src/rlgl.h#L594-L595 these lines are from the commit: https://github.com/raysan5/raylib/commit/4b0e25d3af79ce4c5cd94e8279473764d969cca3
> Fix parsing of empty parentheses

- parser/raylib_parser.c
The parser assumes all lines end in newlines, but sometimes this isn't true. Check for a null terminator along with '\n' when stripping leading spaces.
> [parser] Don't crash for files that don't end in newlines

- examples/core/core_2d_camera_mouse_zoom.c
Makes zoom increments feel more natural. Otherwise, increments can feel too small when zoomed in, or too big when zoomed out.
> [examples] Use logarithmic scaling for 2d examples with zoom functionality

- src/build.zig
This works in zig 0.12 (current stable), LazyPath.path has been removed in zig 0.13 (development)
Currently building raylib is broken in 0.13, this change fixes that while not breaking building with current stable 0.12
> Zig build script - LazyPath.path has been deprecated, using b.path()

- .gitignore
- src/platforms/rcore_web.c
Fixes #3916
These changes emulates for the Web the relative mouse mode made for the desktop. https://github.com/raysan5/raylib/pull/3874
| Before | After |
|--------|-------|
| https://github.com/raysan5/raylib/assets/45357531/ff28d2ef-b464-4fc4-ab28-054bea61ddad | https://github.com/raysan5/raylib/assets/45357531/fb80a520-e527-4b69-b767-76085f06015c |
> [rcore_web] Relative mouse mode issues.

- src/raudio.c
> [raudio] Removed drwav_uninit in LoadMusicStream to fix a crash

- src/raudio.c
- src/raylib.h
> fix WaveCrop() and use frames instead of samples

- BINDINGS.md
This PR address a few issues regarding `BINDINGS.md`.
I applied the following changes:
* The `repo` column has been removed in favor of links integrated into the binding name.
* The table layout has been fixed; it's way more readable and easier to edit.
* Added missing bold text to match 5.x raylib version and unknown licenses.
* Sorted some entries, so each programming language is followed by all their bindings.
* Added a missing binding.
> Updated BINDINGS.md

- src/rmodels.c
Found a bug in the GenMeshTangents function when calling it with a generated plane mesh. Pointers to tan1 and tan2 go out of bounds since the int i would increment up to vertexCount instead of vertexCount - 3.
> [rmodels] Fix out of bounds error in GenMeshTangents for loop.

- src/rtextures.c
If the red value is too large, the right shift operator leads to overflow in the signed int. Closes issue #3987. The cast to int afterward is not UB, only implementation-defined behaviour. See #3987.
> [rtextures] Fix Undefined behaviour in ColorToInt

- src/platforms/rcore_desktop_sdl.c
> [rcore] Call SDL_GL_SetSwapInterval() after GL context creation

- src/raudio.c
I missed this in my last PR, but the wave resulting from the cropping had the `frameCount` of the old wave.
also allow `finalFrame = wave->frameCount' as the range of frames does not include it.
> fix WaveCrop(): update wave->frameCount

- src/rmodels.c
The multiplication of colors in `DrawModelEx` can be simplified by performing 4 integer divisions rather than 8 float conversions/divisions.
> [rmodels] Multiplication of colors in `DrawModelEx` which can be simplified

- src/build.zig
This pull request fixes #4010. In Zig's master branch the path to the emsdk headers must be a relative path, as mentioned https://github.com/ziglang/zig/pull/19623. Previously, in versions >= 0.12, this path was absolute.
This fix splits the code based on the current Zig version. If the current version is greater than 0.12.0 then we use a relative path and otherwise we use an absolute path. _**If upgrading to Zig's master branch this is a breaking change and the path supplied for the `--sysroot` must be relative to Zig's build directory.**_
> [build.zig] Fix Zig emscripten build

- src/rtext.c
Adds casting to the `ExportFontAsCode()` auto-generated `LoadFont` function to fix the following compiler errors when using C++: 
`error: assigning to 'Rectangle *' from incompatible type 'const Rectangle[]' `
`error: assigning to 'GlyphInfo *' from incompatible type 'const GlyphInfo[]`
> [rtext] Added cast to ExportFontAsCode output to fix C++ compiler errors

- BINDINGS.md
- CHANGELOG
- CONTRIBUTING.md
- CONVENTIONS.md
- FAQ.md
- HISTORY.md
- ROADMAP.md
- examples/README.md
- examples/core/core_custom_frame_control.c
- projects/Notepad++/raylib_npp_parser/raylib_npp.xml
- projects/Notepad++/raylib_npp_parser/raylib_to_parse.h
- src/config.h
- src/raylib.h
* Fixed grammar and vocabulary typos in markdown files and headers
* Fixed Invalid links to files in HISTORY.md (if file path was changed)
> Fix typos in markdowns and comments, Fix invalid links in HISTORY.md

- src/raylib.h
- src/rshapes.c
Added a function to check collision between a line defined by p1, p2 and a circle defined by its position and radius. This code is tested in https://github.com/kai-z99/raylib/blob/circleLineDev/examples/shapes/shapes_collision_area.c
This function is intended to a standalone collision detection function as well as possibly a helper function for a polygon-circle collision function.
The algorithm is based on https://www.jeffreythompson.org/collision-detection/line-circle.php
It is also similar to this one: https://github.com/raysan5/raylib/pull/4000 (which is closed)
> [rshapes]Circle line collision function

- src/rmodels.c
Correctly copies animation names from IQM animation to raylib animation.
> LoadModelAnimationsIQM: fix corrupted animation names

- src/rmodels.c
> [rmodels] Send full matModel to shader in DrawMesh

- src/rmodels.c
tries to load the texture with the base path of the original IQM file, relative paths should work.
LoadIQM currently does not load textures. this change attempts to resolve this.
> LoadIQM: attempt to load texture from IQM at loadtime.

- parser/output/raylib_api.json
- parser/output/raylib_api.lua
- parser/output/raylib_api.txt
- parser/output/raylib_api.xml
- src/raylib.h
- src/rtext.c
Adds functions for converting text to camel and snake case to match the addition of a pascal case function. Both have been tested against each other's conventions.
This is a duplicate of a PR that was opened earlier. I forgot to turn my auto formatter off so the PR had 6,000 changes. I used git reset, redid the changes, and then forced pushed the commit; as a result, the old PR cannot be merged, so I have to open a new one.
And if I am wrong, then this is what I am seeing on my screen, which is of importance:
> rtext: added functions for camel case and snake case (reopened due to formatting errors)

- examples/CMakeLists.txt
Build no longer fails with `-DSUPPORT_GESTURES_SYSTEM=OFF` and `-DBUILD_EXAMPLES=ON`
> [build] Fix examples not building with gestures system disabled

- src/rlgl.h
Hi, I found a couple more instances of the `near` and `far` names being used in `rlgl.h`.
I don't really know if this could incure the same problem I found with `raymath.h`, but I tought it might be useful to also rename this one.
This relates to this old issue that mentions these names:
- https://github.com/raysan5/raylib/issues/243
I would also mention that I'm not yet using the suggested setup to select includes from `windows.h`, from here:
- https://github.com/raysan5/raylib/issues/1217
Which may fix most of this kind of issues, should anyone incur in the same warnings as [in here.](https://www.reddit.com/r/raylib/comments/1d8m52k/question_why_does_including_raymathh_make_my/)
> [rlgl] Rename near, far variables

- src/rmodels.c
Same issue described here https://github.com/raysan5/raylib/pull/4037 with this model https://github.com/KhronosGroup/glTF-Sample-Models/blob/main/2.0/BrainStem/glTF-Binary/BrainStem.glb
> [rmodels] `LoadBoneInfoGLTF()`, add check for animation name being NULL

- examples/shaders/resources/shaders/glsl330/lighting_instancing.vs
fragPosition was multiplied by mvp*instanceTransform, but it should only be multiplied by instanceTransform. Compare to lighting.vs, there we only use mvp for gl_Position, but matModel for the fragPosition.
> Fix fragPosition using wrong matrix in lighting_instancing.vs

- src/raudio.c
If you enable SUPPORT_FILEFORMAT_FLAC some FLAC files don't play correctly. Specifically with sample size 24 bits. Here is a small example to reproduce the bug [flac_bug.zip](https://github.com/user-attachments/files/15798781/flac_bug.zip). The song sounds choppy.
I looked around the source code and found that WAV hardcodes the conversion of 24 bits samples to 16 bits ones. So I applied the same approach to FLAC and it seems to fix the issue. Submitting it as a PR in case it's useful for anybody else.
Please let me know if this is not the right way to do that.
> [raudio] Add 24 bits samples support for FLAC format

- src/rlgl.h
Hello it's my first contribution to this project, i did found this error when compiling with #define RLGL_IMPLEMENTATION:
- The function rlGetMatrixProjectionStereo and rlGetMatrixViewOffsetStereo have RLAPI for the function declaration and cause error when compiling using RLGL_IMPLEMENTATION.
> Fix rlgl.h standalone/implementation

- src/raudio.c
> [raudio] fix mapping of wave data in LoadWaveSamples()

- src/rshapes.c
Avoid unnecessary square root calculation in CheckCollisionCircles
Tested in this branch:
https://github.com/kai-z99/raylib/blob/circlecollisionopt/examples/shapes/shapes_collision_area.c
> [rshapes] Optimize CheckCollisionCircles

- src/build.zig
When `addRaygui` is used from an external build, for example in a bindings project, the build of a generated `raygui.c` fails with "raylib.h not found" error from the compiler.
I've traced this down to a raylib step not adding its `src/` to the shared list of include paths using `addIncludePath` but relying on `addCSourceFiles` `.root` to provide the implicit include path for raylib proper's own files.
If raygui is later added to the step the compiler won't know where to look for `raylib.h` and friends and will fail to build.
This change simply adds raylib's `src/` to the include path list.
> [build] Fix Zig raygui build when using addRaygui externally

- examples/build.zig
This way, when we run an example using the `zig build [example_name]` command, it will be able to find the resource folder associated with that section.
> [build] zig: run examples from their directories

- examples/shapes/shapes_splines_drawing.c
- src/rshapes.c
It seems to me that these functions are wrong, if you step the index by 1 you move to a control point instead of the next segment.
> [rshapes] Fix multisegment Bezier splines.

- src/rmodels.c
reference to issue: https://github.com/raysan5/raylib/issues/3998
Fix the problem where last 3 values are uninitialized in GenMeshTangents(). Also give a warning when this function will generate uninitialized values.
> [rmodels] Read uninitialized values in GenMeshTangents() - fix bounding case

- src/platforms/rcore_desktop.c
There is a known issue that people are having where `GetScreenWidth`/`GetScreenHeight` are returning incorrect values. It only uses the one set during initialization and does not work if you change the screen size. I believe this section of code is missing, and I copied the format from `SetWindowMaxSize` directly above it
`PLATFORM_DEKSTOP_SDL` does the same thing: https://github.com/raysan5/raylib/blob/master/src/platforms/rcore_desktop_sdl.c#L661
Note: I don't know about `CORE.Window.render.width`/height or where that one should be added (definitely a separate PR) but it has the same problem and i believe same solution
https://github.com/raysan5/raylib/issues/3763
https://github.com/raysan5/raylib/discussions/3764
> [platform_desktop] fixed issue with GetScreenWidth/GetScreenHeight

- src/external/rl_gputex.h
Conversation taken from https://github.com/raysan5/raylib/issues/3962
Tried to match the LOG format from other ones in the file
Tested to make sure the issue was the correct reason
Tested to make sure the warning displays
It's a long-known issue on Unity and such https://forum.unity.com/threads/crunch-compression-width-height-multiple-of-4-issue.538306/
> add warning log multiple of 4

- src/rtext.c
When calling `int *LoadCodepoints(const char *text, int *count)`. If the value of `codepointCount` is zero, the function returns a freed pointer.
It now returns null instead.
> Fixed LoadCodepoints returning a freed pointer when codepointCount is zero

- src/rmodels.c
Having to use glTF files without node hierarchies and without transformations applied to the meshes is really a big limitation. Also, the current handling is not really correct, as it completely ignores the node hierarchy and thus might lead to meshes not getting instanced more than once. 
This patch adds using the nodes in the glTF file to drive the process of creating meshes, instead of only processing the list of meshes and ignoring the node hierarchy. Transforms defined in the nodes (including parent-child effects) are applied to the vertices/normals/tangents of the meshes in the leafs. A separate raylib Mesh is generated for each leaf node (and still generates one Mesh per primitive in a glTF mesh).
Static meshes with more complex hierarchy in terms of parenting and object transforms …
> [rmodels] Initial work to correctly handle the node hierarchy in a glTF file

- src/rmodels.c
Hello,
`LoadIQM()` did not initialize the values of `model.meshMaterial[]`.
> [rmodels] `LoadIQM()` set `model.meshMaterial[]`

- src/raylib.h
- src/rtextures.c
```c
void ImageDrawTriangle(Image *dst, Vector2 v1, Vector2 v2, Vector2 v3, Color color);
void ImageDrawTriangleEx(Image *dst, Vector2 v1, Vector2 v2, Vector2 v3, Color c1, Color c2, Color c3);
void ImageDrawTriangleLines(Image *dst, Vector2 v1, Vector2 v2, Vector2 v3, Color color);
void ImageDrawTriangleFan(Image *dst, Vector2 *points, int pointCount, Color color);
void ImageDrawTriangleStrip(Image *dst, Vector2 *points, int pointCount, Color color);
```
1. These functions enable the rendering of triangles on images, supporting any vertex order (CW/CCW).
2. The `ImageDrawTriangleEx` function allows the rendering of a triangle with vertex colors specified for interpolation. While not strictly necessary, it serves as a reference for those seeking a more comprehensive function and …
> [rtextures] Adding triangle drawing function for images

- src/raylib.h
- src/rtextures.c
I propose adding the `ImageDrawLineEx` function with the same signature as `DrawLineEx` from `rshapes.c`, enabling line rendering with specified thickness on an `Image`. This might not be the most efficient method used here, but it is the most concise, understandable, and maintainable, and it is fully functional.
In this PR, I have also revised the `ImageDrawLine` function to be shorter and more readable in my opinion, thus more maintainable as well. It avoids the use of `float` types entirely, performing all calculations using integers and utilizing a bit-shift trick for slope calculation.
Additionally, I took the liberty of modifying the `ImageDrawLineV` function to round input coordinates to the nearest integer using `(int)(xfloat + 0.5f)`, which I find preferable. However, I can …
> [rtextures] Adding `ImageDrawLineEx` function

- src/rmodels.c
```
rmodels.c: In function ‘LoadBoneInfoGLTF.isra’:
rmodels.c:4874:32: warning: ‘strncpy’ specified bound 32 equals destination size [-Wstringop-truncation]
4874 |         if (node.name != NULL) strncpy(bones[i].name, node.name, sizeof(bones[i].name));
|                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This strncpy was missing a null terminator write afterwards.
> [rmodels] Fix -Wstringop-truncation warning

- src/rtext.c
It is currently impossible to check a font loaded successfully with IsFontReady because LoadFontEx will always return a valid font.
DrawTextEx has this check:
if (font.texture.id == 0) font = GetFontDefault();  // Security check in case of not valid font
So anyone relying on the default font as a fallback for fonts failing to load should still be covered.
> [rtext] Don't return default font if LoadFontEx fails

- src/minshell.html
- src/shell.html
While testing my game, I noticed scrollbars were visible when compiling with minshell.html. First, I thought my RenderTexture was not scaling correctly on the web. After some tests, I discovered that a small change to the minshell.html file completely fixes the problem.
The issue has already been described [here](https://github.com/raysan5/raylib/issues/3231#issuecomment-1713026923).
And even the solution has already been described [here](https://github.com/raysan5/raylib/issues/3231#issuecomment-1713043728) but not merged.
I also added `background-color: black` to the body so that areas not rendered (happens when resizing the window or when not scaling the game) are black instead of white, which I assume should be the default.
Then I checked shell.html and found that it always shows a …
> [web] Fix undesired scrollbars on shell files

- src/build.zig
Also ran zig fmt.
Using dependencyFromBuildZig, the build script can now directly reference itself as a dependency in helper functions, without having to rely on the naming convention or for the user to match up the names.
> [build.zig] Leverage `dependencyFromBuildZig`

- src/build.zig
Many apologies, #4109 was not thoroughly tested enough to catch this blunder.
`@This()` was naively passed to `dependencyFromBuildZig` while inside a file that is not actually the build file, causing a panic when actually used. Passing `@import("../build.zig")` fixes this.
> [build.zig] pass the real build.zig file

- src/rmodels.c
This should fix the issue related to `.gltf` embeded textures in base64 format, by ignoring the optional `=` padding and calculating the data size in bytes correctly.
Before this patch, `cgltf_load_buffer_base64()` would fail, and the `.gltf`model would not load embedded textures.
Should not interfere with pending https://github.com/raysan5/raylib/pull/4107
> rmodels.c, `LoadImageFromCgltfImage()` : fix base64 padding support

- .gitignore
- src/build.zig
When attempting to export a project for the web with emscripten and Zig 0.13.0, I would get the following error:
```
std.debug.panic("sub_path is expected to be relative to the build root, but was this absolute path: '{s}'. It is best avoid absolute paths, but if you must, it is supported by LazyPath.cwd_relative", .{
^
raylib/src/build.zig:213:45: 0x11dd8dd in compileRaylib (build)
raylib.addIncludePath(b.path(cache_include));
``` 
The proposed change has shown to work for both Zig versions 0.12.0 and 0.13.0.
Also added `.zig-cache/` to .gitignore, as the name of the cache folder gets changed in 0.13.0
> [build.zig] Make emscripten build compatible with Zig 0.13.0

- src/rtextures.c
Some formats are not advancing k to get pixels values
> [rtextures] advance k in LoadImageColors

- src/platforms/rcore_desktop_sdl.c
With SDL_Joystick my game controller wasn't working properly. That's why I changed it to SDL_GameController. Gamepads are now mapped correctly.
> Change SDL_Joystick to SDL_GameController

- src/rshapes.c
Originally, CheckCollisionPointCircle() calls CheckCollisionCircles() with a circle radius 0. This change simplifies and gives this function its own implementation without relying on another function call.
> [rshapes] Give CheckCollisionPointCircle() its own implementation

- README.md
Currently, the Reddit badge in README displays "subreddit is private" even when it's not.
This may mislead newcomers.
Proof:
I created this static badge that could work as a replacement:
[![Reddit Static Badge](https://img.shields.io/badge/-r%2Fraylib-red?style=flat&logo=reddit&label=reddit)](https://www.reddit.com/r/raylib/)
Clicking on it takes you to the subreddit.
It does not have the live subscriber count, but atleast it does not mislead people.
> Fix Reddit badge in README

- examples/models/models_billboard.c
- parser/output/raylib_api.json
- parser/output/raylib_api.lua
- parser/output/raylib_api.txt
- parser/output/raylib_api.xml
- src/raylib.h
- src/rmodels.c
In the previous API of Raylib, `DrawBillboardPro` and `DrawTexturePro` were not consistent, which could easily lead to misunderstandings without carefully reading the documentation or source code:
1. The same `size` parameter does not guarantee the same size for the billboard because the `size` parameter in the previous `DrawBillboardPro` is actually the scale based on the assumption that the billboard's original size is `{ (float)source.width/source.height, 1.0f }`, instead of the actual billboard size.
2. The `origin` is normalized, and when it is `{ 0.0f, 0.0f }`, the origin is located at the center of the billboard. Meanwhile, `origin` solely determines the rotation center of the billboard without altering its position.
This PR aims to address the above inconsistencies, hoping to …
> [rmodels] Consistent `DrawBillboardPro` with `DrawTexturePro`

- src/platforms/rcore_desktop_glfw.c
This fix #3972 on my Linux desktop.
Awaiting confirmation on Windows platform.
MACOS not impacted.
If `FLAG_WINDOW_HIGHDPI` is set, `InitPlatform()` will ask GLFW to handle the resizing of window content area based on the monitor content scale using : ` glfwWindowHint(GLFW_SCALE_TO_MONITOR, GLFW_TRUE); `
So `WindowSizeCallback()` should not try to handle DPI rescale a second time.
> [GLFW backend] `WindowSizeCallback()` should not handle DPI scale. GLFW already do that

- src/build.zig
While tinkering with Zig and raylib, I noticed that the Zig-compiled version of raylib was running through XWayland. I determined that the build.zig file would, by default, only support X11, and could be manually switched to Wayland, but could not use both via runtime platform detection. 
I resolved this problem by adding a new value, "Both" to the LinuxDisplayBackend enum and replacing the switch statement that was responsible for including the libraries with a set of if statements. This change allows for both backends to run off of one executable compiled through Zig.  I also changed the default support mode from X11 only to both.
I tested the changes on my machine and was able to run the same binary natively in both Wayland and X11.
Apologies if anything is funky with my submission, …
> [build.zig] GLFW Platform Detection Support

- src/external/miniaudio.h
> [raudio] Fix crash when switching playback device

- src/rtextures.c
Building raylib with `rtextures=ON, rtext=OFF` currently does not work, giving a link error as it can not find `TextLength()`.
This PR fixes this by adding a tracelog warning and returning a black placeholder instead.
> Fix a dependance of rtexture to rtext

- examples/shaders/resources/shaders/glsl120/pbr.fs
- examples/shaders/resources/shaders/glsl120/shadowmap.fs
Removed presicion mediump float because it is for GLES, and not desktop GL.
also removed 'in' that are in a multitude of lines, because someone when porting it didn't remove it and didn't test it.
Tested on `Mesa Mobile Intel® GM45 Express Chipset (CTG) (0x2a42)`
it works.
> [examples] Fix PBR and Shadowmap example shaders for GLSL 1.20

- BINDINGS.md
The current link 404's. Replace it with a fork.
> Fix Carp link - BINDINGS.md

- src/rtextures.c
Added some log warnings.
LoadImage will call with NULL fileType if file extension is missing.
> Warning on invalid image data

- src/rcore.c
I am not sure why this was done in the first place. If I am missing something here and there is a good reason for doing this, please tell me.
Right now when the font texture filter is set to linear when the high dpi flag is enabled the default font looks very blurry.
The screenshots were made on a 4k monitor on Windows 11 with the `HIGH_DPI `flag enabled.
> [GLFW] No longer set the RL_TEXTURE_FILTER_LINEAR when high dpi flag is enabled

- src/rcore.c
While working with Automation Events, I recognized that my gamepad input was not recorded correctly. Negative axis movements (e.g. stick going left/up) weren't recorded at all.
Furthermore, `GetGamepadAxisMovement` seems to snap trigger axis values to 0.0 if they are in the region [-0.1, 0.1]. I think the delta/drift check was intended to ignore values in between the range [-1.0, -0.9] instead (since -1.0 is the default state for triggers).
This PR addresses both of these issues.
**Remark:**
With my changes `GetGamepadAxisMovement` always returns the default value for each axis, even if a gamepad is not attached. This makes more sense in my opinion, but it is a behavior change for triggers.
Please let me know if you don't want that, and I'll change it back to always return 0.0 if the …
> [rcore] fix gamepad axis movement and its automation event recording

- src/external/jar_xm.h
MSVC keeps giving me the warning
`jar_xm.h(1404): warning C4819: The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss`
The issue where the unicode characters. I replaced them with ascii characters to avoid the warning.
> replace unicode characters by ascii characters in jar_xml

- src/rlgl.h
Hi Ray,
When compiling raylib on Linux with `OPENGL_VERSION=4.3` the build fails because `GLint64` is defined as `long int` which is not the same type as `long long`. This will fix the issue while maintaining compatibility with Win32 where `long long` is equivalent to `GLint64`.
> [rlgl] use GLint64 for glGetBufferParameteri64v

- src/platforms/rcore_desktop_glfw.c
Previously `AUTO_ICONIFY` was only disabled if the user requested a Fullscreen window from the start. After that, changing this behavior on the user side was impossible, even when changing to a Fullscreen window.
The `AUTO_ICONIFY` causes problems on macOS. On macOS, if the window is minimized because of `AUTO_ICONIFY` then the only way to restore it is to click on the icon in the dock. In other words, when `AUTO_ICONIFY` is enabled alt/cmd-tabbing through Windows does not work correctly. On Windows, it works even when `AUTO_ICONIFY` is enabled.
Additionally, if a raylib window is in Fullscreen mode on another monitor the `AUTO_ICONIFY` behavior is a problem because the user might want the window to stay on the monitor even if it loses focus. (problem on all OS's)
`AUTO_ICONIFY` also …
> [rcore][desktop_glfw] Set AUTO_ICONIFY flag to false per default

- src/build.zig
This PR introduces a new option allowing `build.zig` to override `config.h` settings using a simple string:
```zig
pub fn build(b: *std.Build) !void {
// ...
const config: []const u8 =
"-DSUPPORT_FILEFORMAT_JPG -DSUPPORT_FILEFORMAT_PNG=0";
const raylib_dep = b.dependency("raylib", .{ .config = config });
// ...
}
```
This example enables support for the JPG format (disabled by default) and disables support for the PNG (enabled by default).
Two commits are present in the PR:
- the first allows for all definitions in `config.h` to be overriden, it has more cumbersome parsing since some definitions have different data types
- the second restricts the user to override only `SUPPORT_*` flags (which simplifies the implementation and you could possibly merge, given my assumptions are correct …
> [build.zig] Override config.h definitions

- src/build.zig
- this PR references the https://github.com/raysan5/raylib/pull/4150#issuecomment-2271084090
I added a check to find the program `wayland-scanner`, if it's not found the following error log is printed and the build fails:
```
Wayland may not be installed on the system.
You can switch to X11 in your `build.zig` by changing `Options.linux_display_backend`
```
- **NOTE:** in zig 0.14.0 it will be possible to add a failure message directly to a failed step (https://github.com/ziglang/zig/pull/20312). It is not needed, but I reference it here for the future.
> [build.zig] X11-only systems fail builds by default

- examples/audio/audio_mixed_processor.c
This fixes the display issue. The average volume is a float such as 0.03, so the cast to int was making it always 0 and having no height
> Update audio mixed processor

- examples/shaders/resources/shaders/glsl120/raymarching.fs
Raymarching example shader ported to glsl 1.20, and tested on `Intel Mobile 4 Series Chipset Integrated Graphics Controller`
> [examples][shaders_raymarching] Add `raymarching.fs` for GLSL120

- examples/shapes/shapes_draw_circle_sector.c
- examples/shapes/shapes_draw_rectangle_rounded.c
- examples/shapes/shapes_draw_ring.c
Fix issues where settings values are not displaying on shapes_draw_circle_sector, shapes_draw_rectangle_rounded, and shapes_draw_ring. The issue also notes that the PNGs are rotated 90 deg clockwise compared to the examples which is true, although I believe the samples are accurate and the PNGs are not so I did not change it.
https://github.com/raysan5/raylib/issues/4208
> [examples] Fix some examples

- src/build.zig
+ `std.mem.split` is deprecated, `splitScalar` seems like the intended choice here
+ zig files should be formatted according to `zig fmt`
> Fix build.zig and use zig fmt

- src/rlgl.h
Hi
I added warnings for the functionality related to OpenGL 4.3 features in case GRAPHICS_API_OPENGL_43 is not defined. 
Personally, been struggling to make compute shaders work, only to discover that I am not on the correct API version (as the default one is 3.3). I think it is better to add some logging to notify about incorrect OpenGL version. Currently 4.3 related functions are virtually empty if you are not using 4.3 and you can call them even if you are on 3.3. Shader compiler even says it managed to compile a compute shader when using 3.3.
> [rlgl] Adding warnings in case OpenGL 4.3 is not enabled

- examples/text/text_input_box.c
10 FPS causes input issues. 60 is rock solid and most of the other examples are also set to 60 so i think this makes sense
> [Examples] update text input box

- src/rlgl.h
Changed the conditions to avoid using GL_COMPUTE_SHADER if OpenGL ES is used. Alternatively, we can use RL_COMPUTE_SHADER instead as it is always defined, but I guess it is not recommended.
> [rlgl] Fixed compilation for OpenGL ES

- examples/core/core_input_gamepad_info.c
Hello,
This pull request fixes the `core_input_gamepad_info` example so now all possible (32) buttons are displayed within the window area.
Best regards.
> [Examples] Fix `core_input_gamepad_info` example so all buttons are displayed

- examples/core/core_vr_simulator.c
- examples/textures/textures_blend_modes.c
- examples/textures/textures_image_rotate.c
- examples/textures/textures_logo_raylib.c
- examples/textures/textures_raw_data.c
- examples/textures/textures_sprite_explosion.c
- examples/textures/textures_to_image.c
Made the examples all consistently 60fps. some didnt have any caps, some were non-60
> [Examples] set FPS to 60

- src/platforms/rcore_web.c
- src/rmodels.c
fix this warning:
```
/src/rmodels.c:5744:17: warning: missing initializer for field 'w' of 'Vector4' [-Wmissing-field-initializers]
[build]  5744 |                 Vector4 outTangent1 = {tmp[0], tmp[1], tmp[2]};
[build]       |                 ^~~~~~~
```
> Fix warnings

- src/raylib.h
- src/rshapes.c
```
void DrawCircleGradient(int centerX, int centerY, float radius, Color color1, Color color2);
void DrawRectangleGradientV(int posX, int posY, int width, int height, Color color1, Color color2);
void DrawRectangleGradientH(int posX, int posY, int width, int height, Color color1, Color color2);
void DrawRectangleGradientEx(Rectangle rec, Color col1, Color col2, Color col3, Color col4);
```
Have been changed to:
```
void DrawCircleGradient(int centerX, int centerY, float radius, Color inner, Color outer);
void DrawRectangleGradientV(int posX, int posY, int width, int height, Color top, Color bottom);
void DrawRectangleGradientH(int posX, int posY, int width, int height, Color left, Color right);
void DrawRectangleGradientEx(Rectangle rec, Color topLeft, Color bottomLeft, Color topRight, …
```
> [rshapes] Review DrawGradient color parameter names

- src/rtextures.c
I have noticed that when the width and height of GenImagePerlinNoise() are not the same, then the noise will get stretched. So I have added a compensation for it.
Now even if the sides aren´t the same length, the noise won´t get distorted, but rather extended.
Here an image to demonstrate:
On the left is my fix being applied. The noise looks normal.
On the right the current function is being used. The noise is stretched.
> Fixing GenImagePerlinNoise() being stretched, if Image is not rectangular

- projects/CMake/CMakeLists.txt
Currently, when building, the cmake example in projects/CMake gives this warning, with CMake 3.30.2
CMake Warning (dev) at /usr/share/cmake/Modules/FetchContent.cmake:1953 (message):
Calling FetchContent_Populate(raylib) is deprecated, call
FetchContent_MakeAvailable(raylib) instead.  Policy CMP0169 can be set to
OLD to allow FetchContent_Populate(raylib) to be called directly for now,
but the ability to call it with declared details will be removed completely
in a future version.
Call Stack (most recent call first):
CMakeLists.txt:20 (FetchContent_Populate)
This warning is for project developers.  Use -Wno-dev to suppress it.
Changing FetchContent_Populate to FetchContent_MakeAvailable didn't cause any issues I could observe when building. I'm not sure why it wasn't like that to begin …
> [build] CMake: Fix warnings in projects/CMake/CMakeLists.txt

- src/platforms/rcore_android.c
This MR should close #4166
This is my best effort replacement of the ALooperPollAll function that was deleted in ndk-r27.
To be clear, I have exactly zero experience with this API and the NDK,
and barely any experience with android in general.
But I'll explain my reasoning for these changes:
The [documentation](https://developer.android.com/ndk/reference/group/looper#alooper_pollall) for ALooperPollAll claims:
> Like ALooper_pollOnce(), but performs all pending callbacks until all data has been consumed or a file descriptor is available with no callback.
And then the [documentation](https://developer.android.com/ndk/reference/group/looper#alooper_pollonce) for ALooper_pollOnce claims:
> Returns ALOOPER_POLL_TIMEOUT if there was no data before the given timeout expired.
So it seems …
> Replace deprecated Android function ALooper_pollAll

- src/raudio.c
When loading FLAC files using `LoadMusicStreamFromMemory`, 24-bit files play either silence (Windows) or extreme noise (Linux, macOS), while 16-bit files work all fine.
While debugging this I stumbled on #4058, which recently fixed the same problem in `LoadMusicStream` by forcing conversion to 16-bit.
Here simply copying the same fix to `LoadMusicStreamFromMemory`, which fixes all the issues with 24-bit files for me.
> [raudio] Support 24-bit FLACs in `LoadMusicStreamFromMemory`

- src/external/RGFW.h
- src/platforms/rcore_desktop_rgfw.c
`MultiByteToWideChar` should be defined for msvc AND mingw.
`win->src.window` is now used for all platforms
> (rcore_desktop_rgfw.c) fix errors when compiling with mingw

- src/platforms/rcore_desktop_glfw.c
CORE.Window.position is now properly kept in sync with the glfw window position.
- WindowPosCallback added
- SetWindowPos now updates CORE.Window.position as well
- Fullscreen & Borderless Fullscreen now properly user CORE.Window.position for setting CORE.Window.prevposition
Those changes should not change any behavior other than fixing `ToggleFullscreen()` not restoring the window to the correct previous window position. 
---
FYI: There will be another PR for fixing the remaining problems with fullscreen & borderless fullscreen
- restoring window size correctly and using already existing CORE.Window.prevscreen for it
- BorderlessFullscreen using glfw SetWindowMonitor function as well to fix borderless fullscreen on macOS
- some small misc fixes.
> [rcore][desktop_glfw] Keeping CORE.Window.position properly in sync with glfw window position

- src/rlgl.h
Compilation breaks on rlgl.h for early OpenGL versions. 
Glint64 did not exist on those versions (< OpenGL 3.2)
> rlgl.h: glint64 did not exist before OpenGL 3.2

- examples/Makefile
- examples/Makefile.Web
In the /src Makefile, /usr/local can be overriden by the user.
Align the /example Makefile & Makefile.Web with that.
> Examples makefiles: align /usr/local with /src Makefile

- src/external/par_shapes.h
I was using raylib in one of my project which i was compiling with clang and clang showed an warning about the implicit conversion. So making a PR to get rid of the warning and to help the project in a negligible way.
> Change implicit conversion to explicit conversion to remove warning

- src/external/stb_image_resize2.h
In my project i set up the android build following [this video from youtube](https://youtu.be/UeBYWJ_3zDw?si=VsQPJQKFuoiCw8JC)
I was doing that before raylib 5 come out. Now i updated to raylib 5 and android studio complains about `vld1q_f16` is not defined in `stb_image_resize2.h`.
By updating the `stb_image_resize2.h`  from `v2.01` to `v2.10` fixed the issue.
I build the project after the update on my Debian 12.6, X11, Amd R5, IGU,. Laptop and on Android Studio 2024.1.2.12 on the same machine and both worked fine.
I ran the workflow on linux examples and android build, to make sure the update didn't break anything both worked fine.
Here is the problems i was getting before this update
```
> Task :app:buildCMakeDebug[armeabi-v7a] FAILED
C/C++: ninja: Entering directory …
```
> fix vld1q_f16 undeclared in arm on stb_image_resize2.h v2.10

- src/rcore.c
This aims to implements GetApplicationDirectory working throught sysctl.h when running raylib on FreeBSD OS.
Closes #4317
> chore: [rcore] Implement GetApplicationDirectory for FreeBSD

- src/raylib.h
- src/rtextures.c
The functions takes 2 Colors and a Float t as input. The float t is used to set what color is more dominant. 
t=0.0f - color1 is more dominant
t=0.5f - both colors are equally dominant (best choice from my testing)
t=1.0f - color2 is more dominant
> [rtextures] add MixColors. a function to mix 2 colors together

- src/raylib.h
- src/rcore.c
Right now LoadDirectoryFiles and LoadDirectoryFilesEx only return either all folders and all files (when no filter is passed) or a list of files filtered by file extension.
For use in a file browser (like raygui\examples\custom_file_dialog) it is useful to gather a list of files with a particular extension and also all folders in a location (so the user can navigate further).
This change implements this by adding a FILTER_FOLDER define.
The define can be used as a filter and will match all folders. The contents of the define are chosen as to never match a file extension on Linux and Windows.
So for example you can do
`LoadDirectoryFilesEx(%RAYLIB_SRC_DIR%, FILTER_FOLDER";.c", false);`
which results in
```
..\raylib\src\external
..\raylib\src\platforms
..\raylib\src\raudio.c …
```
> [rcore] Add filtering folders to `LoadDirectoryFilesEx()`/`ScanDirectoryFiles()`

- BINDINGS.md
rayed-bqn has had a lot of progress and I've realized it has diverged too much from raylib, and so I made raylib-bqn to be a simple binding, while rayed-bqn will be a utility wrapper.
> [BINDINGS.md] Added raylib-bqn, moved rayed-bqn

- src/rlgl.h
Ref: [src/config.h#L124](https://github.com/raysan5/raylib/blob/e5d0cc978ae933ccccd41758d50d1cd57e3474d1/src/config.h#L124)
> [rlgl] Fix rlgl standalone defaults

- projects/CMake/CMakeLists.txt
- projects/CMake/README.md
This adds missing link flags inside the CMake example without these link flags the HTML5 build will not work.
The snippet in the Cmake file was taken from the [wiki](https://github.com/raysan5/raylib/wiki/Working-for-Web-(HTML5)#23-using-cmake)
> Projects: Fix CMake example project 

- src/platforms/rcore_android.c
This commit sets the isGpuReady flag when the android platform code has initialized the GPU.
This seemingly duplicates the code that is used in `rcore.c`.
> DRAFT: Fix isGpuReady flag on android

- src/platforms/rcore_desktop_sdl.c
`SDL_GetClipboardText()` must be freed with `SDL_free()` ([doc](https://wiki.libsdl.org/SDL2/SDL_GetClipboardText#return-value)), but that can't/shouldn't be done to a returned `const`.
Fix can be tested with:
```
if (IsKeyPressed(KEY_ONE)) { TraceLog(LOG_INFO, "%s", GetClipboardText()); }
EndDrawing();
}
CloseWindow();
return 0;
}
```
> Fixes `GetClipboardText()` memory leak for `PLATFORM_DESKTOP_SDL`

- src/rcamera.h
Starting from https://github.com/raysan5/raylib/pull/4247
Did the same type of logic for the other camera speeds to factor in the `GetFrameTime()`
The other PR solved the issue when using WASD but arrow keys, E, and Q were still affected
> [rcamera] updated camera speeds with GetFrameTime

- src/build.zig
Before this change, building raylib using the `config` options field fails.
```zig
const ray = b.dependency("raylib", .{
.target = target,
.optimize = optimize,
.config = @as([]const u8, "-DSUPPORT_CUSTOM_FRAME_CONTROL"),
});
```
```
Robert@Roberts-MacBook-Pro-2 ~/z/dev (master)> zig build
thread 1133588 panic: attempt to use null value
/Users/Robert/.cache/zig/p/1220cda9f85d36e6f5be4bac65430b056c4e3d4ab3fafcf71c73ec6b1853e8a20856/src/build.zig:81:58: 0x10a8dfba5 in compileRaylib (build)
flag = flag[0..std.mem.indexOf(u8, flag, " ").?]; // Flag is only one word, so capture till space
^
/Users/Robert/.cache/zig/p/1220cda9f85d36e6f5be4bac65430b056c4e3d4ab3fafcf71c73ec6b1853e8a20856/src/build.zig:369:34: 0x10a8e5219 in build (build)
const lib = try compileRaylib(b, target, optimize, …
```
> [zig] Fix build.zig bug

- src/Makefile
GLFW has a lot of caveats and different behavior for Wayland compared to X11 on Linux systems
By disabling it as default, we can avoid these issues but still allow Wayland for those who want it explicitly and accept the caveats/changes
Idea taken from @Peter0x44
> [Makefile] updated makefile to disable wayland by default

- src/rmodels.c
Hit some small snags when importing from kenneys assets this is just a small update.
- Allows animations to be imported even if they affect more `skins` than expected, this allows users to decide if the degraded animations work for them or not 
- Allows `unsigned char` as an mesh index type 
It slightly changes the import macro to correctly cast to the expected type, the old macro is overloaded to maintain the old functionality
> Some update to gltf loading

- build.zig
- src/build.zig
Currently, the project was failing to build when trying `zig build` inside the `src/` dir instead of the root dir, due to hardcoding the path *from* the relative dir to `"src"`, such that the compiler will try to look for `$PROJECT_ROOT/src/src/<path>` instead of `$PROJECT_ROOT/src/<path>`. I tried to fix all such instances of `"src"` with the parent directory of `@src().file`.
Also, exposed the `Options` type so people can do more things with it.
> build.zig: Improve logic

- src/build.zig
Motivation and context:
https://github.com/raysan5/raylib/pull/4375#issuecomment-2408950056
https://github.com/raysan5/raylib/pull/4375#issuecomment-2408998315
@Not-Nik, I'm pretty sure this works but can you check just in case?
> build.zig: Fix `@src` logic and a few things

- src/build.zig
Fixes the options struct config optional type that is not supported from 0.13.
I simply changed it into a slice type and changed the check into a length check.
> build.zig: Fix options.config type issue

- src/platforms/rcore_desktop_sdl.c
Removes the `CHDIR` so `PLATFORM_DESKTOP_SDL` is in line with `PLATFORM_DESKTOP_GLFW` ([ref](https://github.com/raysan5/raylib/blob/d6399622a0280bc8ea458104b946f1860d928156/src/platforms/rcore_desktop_glfw.c#L1638-L1641)). Fixes #4388.
> [rcore] [SDL] Fix #4388

- src/raylib.h
- src/rcore.c
I kept it as close to the MD5 style as much as possible, using the [pseudo code](https://en.wikipedia.org/wiki/SHA-1) shared via discord for reference
> [rcore] added sha1 implementation

- src/build.zig
I am absolutely dumb and cannot make proper PRs. I'll make this a draft until someone can tell me it works.
Context:
https://github.com/raysan5/raylib/pull/4380#issuecomment-2415575757
> build.zig: Clean up my mess

- src/external/rl_gputex.h
Correctly calculate the size of all mipmaps when loading compressed and uncompressed DDS files. This properly fixes #3446 and cleans up the mess #3483 made. The root issue arose from the fact that mipmap sizes were calculated incorrectly. I'm going to write the math down here in case anyone cares.
When working with "normal" linear numbers, the following applies:
```c
(x) + (x / 2) + (x / (2 ^ 2)) + (x / (2 ^ 3)) + ... + (1)
```
is equal to
```c
(x + x) - 1
```
So, with actual numbers
```c
1024 + 512 + 256 + 128 + 64 + 32 + 16 + 8 + 4 + 2 + 1 = (1024 + 1024) - 1 = 2047
```
While mipmaps dimensions do half for every level, i.e. level0 is 1024x1024, level1 is 512x512, and so on; this actually means that the number of pixels (and thus the number of bytes) is quarted.
While, in plain notation, …
> [rl_gputex] Correctly load mipmaps from DDS files

- src/rmodels.c
The indication of locations for bone ids and bone weights did not correspond to their default values ​​in config.h
> correction of comments

- src/build.zig
Here is a PR with issues 1, 2, and 3 from https://github.com/raysan5/raylib/pull/4393#issuecomment-2423777267 addressed.
I didn't bother implementing 4 because there seemed to be multiple possible solutions to it, the way I originally attempted it was quite hacky and caused breaking changes.
Breaking changes:
Now, valid flags like `"-x c++"` will be treated as `"-x" "c++"` and thus behave incorrectly. I found this to be a non-issue as Zig currently doesn't accept those flags, and I believe `"-xc++"` is a valid alternative. I don't know enough C to know if there are other possibly useful flags that often come with spaces between.
> build.zig: Fix various issues around `-Dconfig`

- src/platforms/rcore_web.c
Ref: #4394
This `MaximizeWindow()` implementation matches the desktop behavior (which is changing the window/canvas area without applying any scale), handles `RestoreWindow()` and integrates with the `WindowSizeCallback` (to seamlessly update the viewport, render, fbo and screen values). The PR can be tested with:
```
if (IsKeyPressed(KEY_ONE)) { MaximizeWindow(); }
if (IsKeyPressed(KEY_TWO)) { RestoreWindow(); }
DrawText("test", 20, 20, 20, BLACK);
EndDrawing();
}
CloseWindow();
return 0;
}
```
> [rcore] [web] Adds `MaximizeWindow()` and `RestoreWindow()` implementation for `PLATFORM_WEB`

- src/rtextures.c
This PR enables ImageDraw() to work with all formats that are *not* compressed and *don't* have an alpha channel. This specifically allows loading cubemaps again, which before did not work for any layouts except `CUBEMAP_LAYOUT_LINE_VERTICAL`, possibly since 589d606000a61aaf9d7f14089a83a2bb30c3e714, because the function attempts to restructure cubemap images into a vertical line.
> [rtextures] ImageDraw(): Don't try to blend images without alpha

- examples/models/models_gpu_skinning.c
Brought up by another user and then confirmed by Jeff, this call to `UpdateModelAnimationBoneMatrices` is not needed as it's performed in the loop before any rendering and can be removed
> [examples] removed extra update command

- src/platforms/rcore_web.c
Complementary to #4397. This PR can be tested with:
```
if (IsKeyPressed(KEY_ONE)) SetWindowState(FLAG_WINDOW_MAXIMIZED);
if (IsKeyPressed(KEY_TWO)) ClearWindowState(FLAG_WINDOW_MAXIMIZED);
if (IsKeyPressed(KEY_Q)) MaximizeWindow();
if (IsKeyPressed(KEY_W)) RestoreWindow();
DrawText("test", 20, 20, 20, BLACK);
EndDrawing();
}
CloseWindow();
return 0;
}
```
> [rcore] [web] Updates `SetWindowState()` and `ClearWindowState()` to handle `FLAG_WINDOW_MAXIMIZED` for `PLATFORM_WEB`

- src/platforms/rcore_web.c
Sorry, there was an oversight on my part when commiting #4402.
If the user `SetWindowState(FLAG_WINDOW_MAXIMIZED)` then `MaximizeWindow()`, the `platform.unmaximizedWidth/Height` will be overridden and `ClearWindowState(FLAG_WINDOW_MAXIMIZED)` or `RestoreWindow()` won't be able to restore the canvas ("window") to the unmaximized size. This can be fixed with additional flag checks.
The fix can be tested with:
```
// Press 1, 2, 3 or 1, 2, 4:
if (IsKeyPressed(KEY_ONE)) SetWindowState(FLAG_WINDOW_MAXIMIZED);
if (IsKeyPressed(KEY_TWO)) …
```
> [rcore] [web] Fix an oversight on `MaximizeWindow()` for `PLATFORM_WEB`

- src/platforms/rcore_web.c
This implementation matches the desktop behavior: the whole canvas ("window") gets the opacity effect. It can be tested with:
```
if (IsKeyPressed(KEY_ONE)) SetWindowOpacity(0.0f);
if (IsKeyPressed(KEY_TWO)) SetWindowOpacity(0.5f);
if (IsKeyPressed(KEY_THREE)) SetWindowOpacity(1.0f);
DrawText("test", 20, 20, 20, RED);
EndDrawing();
}
CloseWindow();
return 0;
}
```
> [rcore] [web] Adds `SetWindowOpacity()` implementation for `PLATFORM_WEB`

- src/rlgl.h
Hi!
The the function loading for this was kinda broken before, with an impossible condition (unless you were using ANGLE). This fixes that and includes the GL_NV versions of the extensions, that are supported by all modern NVIDIA GPUs when running on Desktop using its GLES mode (that is a better alternative to ANGLE on systems that support it).
I opted by only marking the support flag if GL_XXX_instanced_arrays is present, but still loading the function pointers if only GL_XXX_draw_instanced is, just in case the user isn't using the vertex attribute functionality and for some reason the GPU only supports one of the extensions (although I can't find instanced of that being a thing, if one is supported, both seems to be). If that's not OK, let me know the proper wanted behavior, so I can …
> [rlgl] Updated instanced rendering support loading

- src/raymath.h
This PR extends the last one for C++ operators in raymath and adds matrix operators.
> [Raymath] Add matrix operators to raymath for C++

- src/config.h
- src/platforms/rcore_android.c
- src/platforms/rcore_desktop_glfw.c
- src/platforms/rcore_desktop_sdl.c
- src/platforms/rcore_drm.c
- src/platforms/rcore_web.c
- src/raylib.h
Updated `SetGamepadVibration()` to handle duration (in ms) on `PLATFORM_DESKTOP_SDL`. Also renamed the `left/rightMotor` parameters to `low/high` as it's more commonly referenced ([ref](https://wiki.libsdl.org/SDL2/SDL_GameControllerRumble)). Since a new parameter was added, **this is a breaking change.**
The PR can be tested with:
```
if (IsGamepadButtonPressed(0, GAMEPAD_BUTTON_RIGHT_FACE_UP)) SetGamepadVibration(0, 1.0f, 1.0f, 300);
if (IsGamepadButtonPressed(0, GAMEPAD_BUTTON_RIGHT_FACE_RIGHT)) SetGamepadVibration(0, 0.0f, 1.0f, 300);
if (IsGamepadButtonPressed(0, GAMEPAD_BUTTON_RIGHT_FACE_LEFT)) SetGamepadVibration(0, 1.0f, 0.0f, 300);
if (IsGamepadButtonPressed(0, …
```
> [rcore] Adds implementation to `SetGamepadVibration()` on `PLATFORM_WEB` and updates it on `PLATFORM_DESKTOP_SDL` to handle duration

- build.zig
This is an updated list of Linux dependencies that Raylib should require according to Nixpkgs. I think it's likely to be accurate but it does warrant testing. In particular, I would like to know whether the fact that `libdrm` and `libgbm` depends on `pkg-config` is a NixOS-quirk. It could also just be that NixOS is more/less faithful to upstream than other distros. In practice, what should matter is obviously the convention of major distros. I'm only touching the Zig build system as that's what I know best.
`flake.nix` used to test dependencies:
```nix
{
inputs.flake-utils.url = "github:numtide/flake-utils";
outputs = {
self,
nixpkgs,
flake-utils,
}:
flake-utils.lib.eachDefaultSystem (
system: let
pkgs = nixpkgs.legacyPackages.${system};
in {
#devShells.default = pkgs.stdenv.mkDerivation …
```
> build.zig: Better specify Linux dependencies

- src/platforms/rcore_web.c
So it doesn't depend on macro'd JS functions. Changes can be tested with:
```
DrawText("Resize the browser window manually", 20, 20, 20, BLACK);
DrawText(TextFormat("canvas size: %i x %i", GetScreenWidth(), GetScreenHeight()), 20, 40, 20, BLACK);
EndDrawing();
}
CloseWindow();
return 0;
}
```
> [rcore] [web] Simplify `EmscriptenResizeCallback()`

- examples/core/core_input_gamepad.c
Relaxes the detection criteira so any compatible gamepad can get detected/displayed on the example. Currently it's too restrictive to those three specific strings, which leaves lots of compatible gamepads ([ref](https://github.com/mdqinc/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt)) appearing as if they were not supported.
Examples of compatible gamepads that appear unsupported on the example: [1](https://github.com/mdqinc/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt#L108), [2](https://github.com/mdqinc/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt#L128), [3](https://github.com/mdqinc/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt#L184), [4](https://github.com/mdqinc/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt#L242), …
> [examples] Update `core_input_gamepad` example

- src/raylib.h
- src/rcore.c
All credits to @dmg46664 for finding this issue (#4405, [ref](https://github.com/raysan5/raylib/issues/4405#issuecomment-2429195055)) and pointing the solution. Great catch!
Summary: At the moment a mininum value of `0.1f` is being applied on all gamepad axis at all times on all platforms. Since the deadzone depends on each specific gamepad, it's indeed something that should be exposed to the end-user (e.g.: the player playing the game) be able to adjust to his case at runtime. This PR adds deadzone to `CORE.Input.Gamepad` and exposes `SetGamepadDeadzone()` to set that value. It also allows the dev-user to zero it and handle the deadzone himself.
<details>
<summary>This PR can be tested with:</summary>
```
InitWindow(400, 300, "test"); …
```
> [rcore] Fix #4405

- examples/core/core_input_gamepad.c
Ref: https://github.com/raysan5/raylib/pull/4420#issuecomment-2430475332, https://github.com/raysan5/raylib/pull/4420#issuecomment-2430479617.
Kept the handling plain and simple to make it very easy to grasp. Also used the previous default value of `0.1f` so it feels exactly like before.
> [examples] Add deadzone handling to `core_input_gamepad` example

- examples/core/core_input_gamepad.c
Gamepads detected as "generic" now look like this on the `core_input_gamepad` example:
<details>
<summary>To test this PR, spoof the aliases like this:</summary>
``` diff
diff --git a/examples/core/core_input_gamepad.c b/examples/core/core_input_gamepad.c
index 538e1c38..e5af88f2 100644
--- a/examples/core/core_input_gamepad.c
+++ b/examples/core/core_input_gamepad.c
@@ -20,9 +20,9 @@
// NOTE: Gamepad name ID depends on drivers and OS
-#define XBOX_ALIAS_1 "xbox"
-#define XBOX_ALIAS_2 "x-box"
-#define PS_ALIAS     "playstation"
+#define XBOX_ALIAS_1 "aaa"
+#define XBOX_ALIAS_2 "bbb"
+#define PS_ALIAS     "ccc"
//------------------------------------------------------------------------------------
```
</details>
> [examples] Add drawing for generic gamepad on `core_input_gamepad` example

- parser/output/raylib_api.json
- parser/output/raylib_api.lua
- parser/output/raylib_api.txt
- parser/output/raylib_api.xml
- src/raylib.h
- src/rtextures.c
The panorama cube map option was not implemented, so this PR removes it from the enumeration in raylib.h so that users do not get confused and try to use it.
I left a todo in the code for some aspiring developer to finish.
> [RTEXTURES] Remove the panorama cubemap layout option

- src/rshapes.c
Reviews `DrawRectangleLine()` so that the +1 offset is replaced with a +0.5 offset divided by the camera zoom (actually m0 from `rlGetMatrixModelview()`. m5 does have the zoom also but I am unsure if anything could throw either of those off in a 2D context). This also fixes an issue where the rectangle is drawn incorrectly if rendered at tiny sizes with a big enough zoom value.
Examples (from issue #3973's example snippet, modified for PR example):
<details><summary>modified 3973 example snippet</summary>
<p>
```c
#include "rlgl.h"
#include <string.h>
#include <stdbool.h>
void matrixToString(Matrix *m, char *str) {
sprintf(str,
"%.02f, %.02f, %.02f, %.02f\n"
"%.02f, %.02f, %.02f, %.02f\n"
"%.02f, %.02f, %.02f, %.02f\n"
"%.02f, %.02f, %.02f, %.02f\n" …
```
> [rshapes] Review `DrawRectangleLines()` pixel offset

- examples/shaders/resources/shaders/glsl330/base.fs
This PR has the base fragment shader for the examples use the vertex color in addition to the tint color. This provides a better example of what the default shader is doing.
I also added some more comments to the finalColor computation to explain what is happening.
If having the base shader ignore vertex color is intended in order to keep the shader simple, please reject this PR.
> [Shaders] Have the base fragment shader use the vertex color

- CMakeOptions.txt
This is to align with the behavior of #4369, see #4371 for rationale on disabling Wayland by default.
> [build] CMake: Don't build for wayland by default

- examples/Makefile
[eb04154](https://github.com/raysan5/raylib/commit/eb04154c98616f0355b0035945a58fa7b56d59e2) changed `emmake make` to `mingw32-make` for `PLATFORM_WEB`. However, `mingw32-make` isn't always present (e.g.: Linux hosts), which leads to these:
```
~/raylib-master/examples$ make PLATFORM=PLATFORM_WEB core/core_basic_window
find . -type f -executable -delete
rm -fv *.o
Cleaning done
mingw32-make -f Makefile.Web core/core_basic_window
make: mingw32-make: No such file or directory
make: *** [Makefile:660: core/core_basic_window] Error 127
```
Since `emmake` is usually provided by Emscripten's `emsdk`, this PR checks if `emmake` is present. If it is, uses it. If not, falls back to `mingw32-make`.
> [build] [web] Fix examples `Makefile` for `PLATFORM_WEB`

- examples/models/models_skybox.c
- src/rlgl.h
- src/rtextures.c
Load all mipmaps for cubemaps to the GPU and enable the proper filters for them. This is especially important for image based lighting (IBL), where for different roughness levels, different pre-filtered environment maps are stored in mipmaps. Calculating these filters is rather expensive, so it is often done offline and the pre-filtered cubemaps are shipped with the game.
The implementation did require some reworking; notably `rlLoadTextureCubemap` gains a new `mipmapCount` parameter, and `ImageMipmaps` no longer regenerates already existing mipmaps.
I structured the PR to be able to just be rebased onto master if you want all the different changes to reflect in the tree.
> [rtextures/rlgl] Load mipmaps for cubemaps

- examples/Makefile
Package one break ; removed /usr/pkg flags, it is used by only NetBSD anyway.
> Fix OpenGL

- src/rtextures.c
`LoadTextureCubemap()`, takes `image` as a copy, not a reference.`ImageMipmaps()` re-allocates the `data` pointer of an image, making the old pointer invalid. This means that calls to `LoadTextureCubemap()` would almost always render the image unusable, resulting in a use-after-free bug, e.g. when unloading the image.
My apologies, fixup for #4429
> [rtextures] LoadTextureCubemap(): Copy image before generating mipmaps, to avoid dangling re-allocated pointers

- src/rtext.c
MeasureTextEx used to output negative X for empty strings with non-zero spacing, for example
```
int main()
{
InitWindow(400, 600, "Raylib window");
printf("%f \n", MeasureTextEx(GetFontDefault(), "", 10.0f, 0).x); // 0
printf("%f \n", MeasureTextEx(GetFontDefault(), "", 10.0f, 1).x); // -1
printf("%f \n", MeasureTextEx(GetFontDefault(), "", 10.0f, 2).x); // -2
printf("%f \n", MeasureTextEx(GetFontDefault(), "", 10.0f, 15).x); // -15
CloseWindow();
}
```
> Fix negative X output value in MeasureTextEx

- src/platforms/rcore_desktop_glfw.c
There is an error with the forward declaration of the winMM functions when building on MSVC. Inconsistent DLL linkage.
This is not a critical warning, so this PR disables it.
This PR also removes the timeBeginPeriod declaration as it is no longer needed.
> [rcore][GLFW] Fix warning on windows in MSVC

- src/platforms/rcore_web.c
Reverts #4451 for `PLATFORM_WEB`.
The window size is properly set by `WindowSizeCallback` ([ref](https://github.com/raysan5/raylib/blob/3bad05aa7bd319eaaae937928b396b46f4886e3e/src/platforms/rcore_web.c#L1394)) after updating the viewport, render and fbo.
<details>
<summary>Test case:</summary>
```
if (IsKeyPressed(KEY_ONE)) SetWindowSize(400, 200);
DrawText(TextFormat("window size %i x %i", GetScreenWidth(), GetScreenHeight()), 20, 20, 20, BLACK);
EndDrawing();
}
CloseWindow();
return 0;
}
```
> [rcore] [web] Fix `SetWindowSize()` for `PLATFORM_WEB`

- src/rmodels.c
When creating a new sphere mesh with high number of slices/rings the top and bottom parts of the generated sphere are removed. This happens because the triangles in those parts, due to high resolution, end up being very small and are removed as part of the 'par_shapes' library's optimization. Adding par_shapes_set_epsilon_degenerate_sphere(0.0); before generating the sphere mesh sets the threshold for removal of small triangles is removed and the sphere is returned to raylib correctly.
> Update rmodels.c - 'fix' for GenMeshSphere artifact

- src/raymath.h
For transform matrices with certain ranges of rotation angles and scaling factors, `MatrixDecompose()` would give incorrect answers.
I narrowed down the issue to where the scaling factors are removed from the cloned transform, before the rotation is extracted: the scale factors needed to be taken into account for extra matrix members.
The models_loading_gltf example still works correctly after this fix.
Further tests and discussion here: https://github.com/raysan5/raylib/issues/4454
> [raymath] Fix for issue 4454, `MatrixDecompose()` gave incorrect output for certain scale and rotations

- src/rtextures.c
The gradient generated with GenImageGradientLinear would have unexpected artifacts when the direction parameter would resolve to an angle having cosine and sine of different signs (it also contains a division by something which can approach zero with specific angles).
This is a bit of a blunt attempt at a solution, given that it's my first for this kind of work, feedback would be much appreciated ^^.
I've left a long winded comment explaining some of the rationale, but I couldn't manage to make it clearer than it got.
Here is a comparison of a minimal example with a rotating gradient:
https://github.com/user-attachments/assets/ba92ef1c-77c0-4ae5-9478-11725674d58f
<details>
<summary>Example code:</summary>
```c
int main(int argc, char **argv)
{
InitWindow(1000, 500, "Window");
double angle …
```
> [rtextures] fix bad behaviour of GenImageGradientLinear with certain angle values.

- src/rtextures.c
This PR fixes some double to float casting warnings in rTextures.
> [rTextures] Fix Casting Warnings

- build.zig
- build.zig.zon
- Add xcode_frameworks when cross compiling for mac (ref: https://github.com/hexops/mach/blob/main/build.zig)
- Add emsdk when cross compiling for wasm (ref: https://github.com/floooh/sokol-zig/blob/master/build.zig)
> Improve cross-compilation with zig builds

- build.zig
- addRaylib just duplicates what adding raylib as dependency already does
so it do not needs to exist
- move raygui build to standard build process when flag is enabled. this
works correctly when using raylib as dependency and having raygui as
dependency as well. problem with previous approach was that raygui was in
options but it was doing nothing because you had to also use addRaygui for
it to be effective
For how the dependency should be included normally in other projects using zig builds, its as simple as this (on top of including raylib in build.zig.zon)
```zig
const target = b.standardTargetOptions(.{});
const optimize = b.standardOptimizeOption(.{});
// This is the whole thing
const raylib_dep = b.dependency("raylib", .{ .target = target, .optimize = optimize, .shared = true }); …
```
> [build][Zig] Remove `addRaylib` and fix `raygui` builds when using raylib as dep

- src/rmodels.c
The lower Y cap of the cylinder in DrawCylinder has a small mistake and does not draw properly.
this PR fixes it up to render correctly.
> [rModels] Fix bad triangles in DrawCylinder

- src/platforms/rcore_desktop_glfw.c
This PR fixes a typecast warning in the GLFW clipboard functions (raylib image can't read a 64 bit size).
> [rCore_GLFW] Fix a typecast warning in glfw clipboard access

- build.zig
- Removed raygui option from build.zig since it is not working as intended
- Re add addRaygui function
Function addRaygui is not the idiomatic way of including dependencies in zig, but currently using the raygui flag would give the following error. This would happen because the build system is looking for the raygui dependancy in from raylibs own [build.zig.zon](https://github.com/raysan5/raylib/blob/master/build.zig.zon) file.
```
thread 27788 panic: no dependency named 'raygui' in '/home/kimi/.cache/zig/p/1220eb09ded36376449dc82f259286d0ad17440081117e36bb41604504a0c0ac19c3/build.zig.zon'. All packages used in build.zig must be declared in this file
```
Having the addRaygui function saves the user from adding non intuitive code into their own build.zig file.
The following is required for …
> [BUILD][ZIG]: remove raygui from build options and re add addRaygui as a function

- examples/Makefile.Web
<details>
<summary>Error logs:</summary>
<br>
```
~/raylib-master/src$ make PLATFORM=PLATFORM_WEB
[...]
~/raylib-master/src$ cd ../examples/
```
```
~/raylib-master/examples$ make PLATFORM=PLATFORM_WEB core
[...]
core/core_basic_window_web.c:18:10: fatal error: 'raylib.h' file not found
18 | #include "raylib.h"
|          ^~~~~~~~~~
1 error generated.
[...]
core/core_input_virtual_controls.c:18:10: fatal error: 'raylib.h' file not found
18 | #include "raylib.h"
|          ^~~~~~~~~~
1 error generated.
[...]
```
```
~/raylib-master/examples$ make PLATFORM=PLATFORM_WEB textures
[...]
textures/textures_image_channel.c:18:10: fatal error: 'raylib.h' file not found
18 | #include <raylib.h>
|          ^~~~~~~~~~
1 error generated.
[...]
```
```
~/raylib-master/examples$ make …
```
> [build] [web] Fix (missing) examples compilation for `PLATFORM_WEB`

- src/rmodels.c
The nextShapeEnd integer is a pointer in the OBJ data structures. The faceVertIndex is a vertex index counter for the mesh we are about to create. Both integers are not compatible, which causes the code to finish the meshes too early, thus writing the OBJ data incompletely into the target meshes.
It wasn't noticed because for the last mesh, it process all remaining data, causing the last mesh to contain all remaining triangles.
This would have been noticed if the OBJ meshes used different textures for each mesh.
> Fixing an OBJ loader bug that fragmented the loaded meshes

- BINDINGS.md
[raylib-cpp](https://github.com/RobLoach/raylib-cpp) has been updated to use the new raylib 5.5 functions. This is a great release! Thanks so much.
> BINDINGS: raylib-cpp supports raylib 5.5

- examples/core/core_3d_camera_first_person.c
Changed line 118 from, "// For advance camera controls, it's reecommended to compute camera movement manually", to, "// For advanced camera controls, it's recommended to compute camera movement manually".
> Fixed grammar mistakes in core_3d_camera_first_person.c

- BINDINGS.md
According to https://github.com/electronstudio/raylib-python-cffi
> Update BINDINGS.md: raylib-python-cffi is on v5.0

- BINDINGS.md
As the title says, raylib beef has been updated to 5.5 https://github.com/Starpelly/raylib-beef
And this pr changes the bindings.md file to reflect that
> Update BINDINGS.md for raylib-beef

- BINDINGS.md
The [Fortran bindings](https://github.com/interkosmos/fortran-raylib) have been updated to raylib 5.5.
> Update BINDINGS.md: fortran-raylib is on v5.5

- build.zig
Cross compiling to windows when adding Raygui would error due to how zig handles the C \#include macro.
Added explicit include path for raylib.h for the raylib dependency when adding raygui.
- Build and executable tested only on my local machine.
- Only tested with argument  -Dtarget=x86_64-windows
> [build][Zig] Fix `raygui` inclusion in windows cross compilation

- src/platforms/rcore_web.c
Ref: [doc](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio), #4525. The PR can be tested with:
```
const Vector2 scale = GetWindowScaleDPI();
DrawText(TextFormat("scale %fx%f", scale.x, scale.y), 20, 20, 20, BLACK);
EndDrawing();
}
CloseWindow();
return 0;
}
```
> [rcore] [web] Add implementation to `GetWindowScaleDPI()` for `PLATFORM_WEB`

- build.zig
Like already discussed here https://github.com/raysan5/raylib/pull/4358#issuecomment-2488242077 I made it possible to change the platform over the zig build.
I also saw that it wasn't possible to change if raudio, rmodels, and so on is enabled or not, I also made a fix for that, and It's now customizable over the zig build.
It would be nice if someone who already did some changes to the zig build could look into this PR.
> fixed platform change for zig build file

- src/raymath.h
some functions overloaded the wrong operator or multiplied instead of dividing
> [raymath] fix C++ operator overloads

- CMakeLists.txt
This PR fixes two issues regarding CMakeLists.txt:
1. Compatibility with future versions of CMake: Compatibility with CMake version < 3.10 will be removed from a future version of CMake. Calls to [cmake_minimum_required(VERSION)](https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html#command:cmake_minimum_required) that do not specify at least 3.10 as their policy version will produce a **deprecation warning** in CMake 3.31 and above.
2. **Build failure** with CMake < 3.12: Building raylib with the previously specified minimum CMake version of 3.5 **fails** because [cmake/ParseConfigHeader.cmake](https://github.com/raysan5/raylib/blob/c53dd8a9310ad34f730ea853478dc77c8caff23d/cmake/ParseConfigHeader.cmake#L12) uses `list(TRANSFORM...` which was …
> [build] CMake: Set minimum CMake version to 3.12

- projects/Notepad++/raylib_npp_parser/raylib_to_parse.h
- src/raylib.h
Further fixing this issue: [#4019](https://github.com/raysan5/raylib/issues/4019)
(Because implementation [#4161](https://github.com/raysan5/raylib/pull/4161) lacked a prototype)
See [my lengthier comment over there](https://github.com/raysan5/raylib/issues/4019#issuecomment-2503846566).
> GetKeyName prototype

- src/raudio.c
This PR fixes a heap buffer overflow in raudio that can be triggered by a WAV file with a very large frame count. This is the result of two separate issues. The first is an integer overflow in the call to malloc since the unsigned integer can be overflowed when multiplied by the maximum number of channels (256). The second is using the 64-bit value for frame count even though it is cast to an unsigned int when allocating the buffer.
To fix this, I cast the frame count to a size_t in the malloc call, and I used 32-bit value for the number of frames to be written to the buffer. I recognize that issues like these aren't critical since the assets are almost always trusted, but it is nice to fix in case anyone wants to incorporate user-generated content into their game.
> [raudio] Fixed buffer overflow when loading WAV files

- CONTRIBUTING.md
- FAQ.md
Fixed two small misprints.
1. Before: ‘You can check other issues to see how is being done!‘
After: ‘You can check other issues to see how it's being done!
2. Before: ‘I would say "simplicity" and "enjoyment" at a really low level of coding but actually is up to the user to discover it, to try it and to see if it fits their needs.’
After: ‘I would say "simplicity" and "enjoyment" at a really low level of coding but actually it is up to the user to discover it, to try it and to see if it fits their needs.’
(I suspect these errors are tied to how Spanish can work with implicit pronouns, by the way. ;))
> Update CONTRIBUTING.md + FAQ.md: small misprints

- src/raymath.h
Clarified that the angle is signed and that positive angles appear visually clockwise. I am coming from Unity and their [Vector2.Angle](https://docs.unity3d.com/ScriptReference/Vector2.Angle.html) is unsigned so this confused me for some time. This might help others too.
> Update documentation for Vector2Angle

- src/rmodels.c
This fixes a null pointer dereference when loading a texture from a GLB file. The fix is just to check if the buffer_view is NULL before checking if the data pointer is NULL.
> [rmodels] Fix null pointer dereference in LoadImageFromCgltfImage

- src/rmodels.c
This fixes a crash that can happen when null is passed to LoadImageFromCgltfImage. There is a case where the argument is null in LoadGLTF. A possible fix is to check if the it is null in LoadImageFromCgltfImage.
> [rmodels] Fix crash when NULL is passed to LoadImageFromCgltfImage

- BINDINGS.md
Hey,
raylib-go now supports raylib 5.5.
Sources:
https://github.com/gen2brain/raylib-go/pull/472
https://github.com/gen2brain/raylib-go/releases/tag/raylib%2Fv5.5.0
> Update BINDINGS.md: raylib-go is now v5.5.0

- BINDINGS.md
As per this PR: https://github.com/TSnake41/raylib-lua/commit/1b6c3185857364d5b662fabb92ec19858879d644
raylib-lua appears to support raylib 5.0.
> [documentation] updated raylib-lua version

- BINDINGS.md
Went through the repos for the bindings and updated some of them. Repos that have not been updated in a while may have remained outdated.
I would like to point out that both raylib-lua and rayboo are 404, but I did not know if it was ok to remove them
> [documentation] Updating keybindings versions

- src/rmodels.c
This is the last I've found so far :)
I was able to get it to crash here when loading a file:
> [rmodels] Fixed null pointer dereference in LoadGLTF

- examples/shaders/resources/shaders/glsl330/lighting_instancing.vs
- examples/shaders/shaders_mesh_instancing.c
- src/config.h
- src/raylib.h
- src/rcore.c
- src/rlgl.h
- src/rmodels.c
Add a dedicated instanceTransform shader location index to avoid unwanted re-assigning of vertex attribute buffers when drawing a mesh sequentially with **DrawMeshInstanced** using multiple different shaders
#4538
> [rlgl][rmodels] Add instranceTransform shader location index #4538

- src/raylib.h
I was going to add negative support for these methods, however, after investigation, I've found that it is actually already supported.
[rtext.c:1444](https://github.com/raysan5/raylib/blob/1f704be4e4aba6b25e56bde3c30cc136b6e94049/src/rtext.c#L1444)
> [rtext] Removed inaccurate comment about negatives not being supported with TextToFloat and TextToInt Methods

- src/platforms/rcore_desktop_sdl.c
Fixes `RestoreWindow()` ([ref](https://github.com/raysan5/raylib/blob/79facde3535af1f35942eec38f02f2851de618ab/src/platforms/rcore_desktop_sdl.c#L513)) for `PLATFORM_DESKTOP_SDL` that was using the incorrect call.
Fixes manually minimizing, maximizing and restoring the window not setting the correct `FLAG_WINDOW_MAXIMIZED` and `FLAG_WINDOW_MINIMIZED` respectively on `PLATFORM_DESKTOP_SDL`, and `IsWindowMinimized()` ([ref](https://github.com/raysan5/raylib/blob/79facde3535af1f35942eec38f02f2851de618ab/src/rcore.c#L767-L770)) and `IsWindowMaximized()` ([ref](https://github.com/raysan5/raylib/blob/79facde3535af1f35942eec38f02f2851de618ab/src/rcore.c#L773-L776)) that were INOP on `PLATFORM_DESKTOP_SDL` because the platform was missing event handling for `SDL_WINDOWEVENT_MINIMIZED`, …
> [rcore] [SDL2] Fix maximizing, minimizing and restoring windows

- src/platforms/rcore_desktop_rgfw.c
- src/platforms/rcore_template.c
The implementation of the function `SetGamepadVibration` was missing.
> add SetGamepadVibration to rgfw and template platform

- src/platforms/rcore_desktop_sdl.c
Fixes show, hide, focus and unfocus window/flags states on `PLATFORM_DESKTOP_SDL`, and `IsWindowHidden()` ([ref](https://github.com/raysan5/raylib/blob/79facde3535af1f35942eec38f02f2851de618ab/src/rcore.c#L761-L764)) and `IsWindowFocused()` ([ref](https://github.com/raysan5/raylib/blob/79facde3535af1f35942eec38f02f2851de618ab/src/rcore.c#L779-L782)) that were INOP on `PLATFORM_DESKTOP_SDL` because the platform was missing event handling for `SDL_WINDOWEVENT_HIDDEN`, `SDL_WINDOWEVENT_SHOWN`, `SDL_WINDOWEVENT_FOCUS_GAINED` and `SDL_WINDOWEVENT_FOCUS_LOST` ([ref](https://github.com/raysan5/raylib/blob/bdfbd6e8cc77b755d6552f90028ba8262d79ab92/src/platforms/rcore_desktop_sdl.c#L1499-L1502)).
This PR was tested with `SDL2.30.10` on `Linux Mint 22.0`. `SDL3` wasn't tested but should work since …
> [rcore] [SDL2] Fix show, hide, focus and unfocus window/flags states

- src/rmodels.c
- Updating bones only once instead for each `mesh`.
- Updating only one `model.meshes[].boneMatrices` and then using deep copy for other meshes instead of calculating for each bone in each mesh.
- Tried to keep asserts and condition at their places.
**Other points:**
- Makes it a clean base/template/reference for other/new bone updation functions. Because if using this as template or modifying it, then some calculations done in one mesh can affect bones in other mesh in next iteration(doubles the effect in for next mesh) If some new variable used in loops is declared outside loop.
- This new template is helpful for me to create new functions to update bones of model for animation system I'm working on.
> [rmodels] Optimized `UpdateModelAnimationBones()` function

- src/platforms/rcore_android.c
- src/platforms/rcore_desktop_glfw.c
- src/platforms/rcore_desktop_rgfw.c
- src/platforms/rcore_drm.c
- src/platforms/rcore_template.c
From `GamepadSetVibration` to `SetGamepadVibration`, to match the function name.
> [rcore] Fix `SetGamepadVibration()` `TRACELOG` message

- src/rlgl.h
if the user supplies less mips than would be generated normally the texture rendering will break. 
for example quake1&2 and halflife have 4 pre-generated mips included with the data, viewing those textures without this fix would result in visual errors.
> setting MAX_LEVEL based on actual mipcount input

- BINDINGS.md
Raylib-cs now supports raylib 5.5.
Source: https://github.com/chrisdill/raylib-cs/pull/279
> Update BINDINGS.md: Raylib-cs now supports 5.5

- src/rtext.c
Alpha was broken for rtext's default font on Big Endian
Before
After
> [rtext] Fix default font alpha on Big Endian systems

- src/rmodels.c
As requested here: https://github.com/raysan5/raylib/issues/4581#issuecomment-2560162214
I fixed the function by transforming the normals using only the rotational part of the transformation matrix, obtained via its inverse transpose.
I also simplified the inversion of the quaternion `inRotation`, which was being calculated twice within the same scope.
**Edit**: the examples `models_animation`, `models_bone_socket`, and `models_loading_gltf` were successfully (re)tested.
> [rmodels] Fix normal transform in `UpdateModelAnimationBones`

- BINDINGS.md
Added a Ruby binding known as raylib-ruby on 4.5. (https://github.com/wilsonsilva/raylib-ruby)
> Updated BINDINGS.md for Ruby

- src/platforms/rcore_desktop_glfw.c
- src/platforms/rcore_desktop_sdl.c
See https://github.com/raysan5/raylib/pull/4598#issuecomment-2554483960.
> [rcore] [SDL2] Add implementation for `FLAG_WINDOW_ALWAYS_RUN`

- src/platforms/rcore_web.c
Currently the web platform uses `glfwSetWindowFocusCallback` which seems to do nothing regarding the game canvas' focus. This PR adds emscripten focus/blur callbacks targeting the canvas.
Sample project [focus.zip](https://github.com/user-attachments/files/18254710/focus.zip)
```c
#include <emscripten/emscripten.h>
void gameupdate(void) {
ClearBackground(WHITE);
if (IsWindowFocused()) {
DrawText("Focused", 10, 10, 50, BLACK);
} else {
DrawText("Unfocused", 10, 10, 50, BLACK);
}
EndDrawing();
}
InitWindow(400, 400, "focus events");
emscripten_set_main_loop(gameupdate, 0, 1);
CloseWindow();
return 0;
}
```
https://github.com/user-attachments/assets/ceec3e5a-d787-49bb-b749-1fbde211691f
> Fix `IsWindowFocused()` on web.

- projects/VS2022/raylib/raylib.vcxproj
- projects/VS2022/raylib/raylib.vcxproj.filters
This PR adds the platform files to the MSVC project so that they show up for editing (and searching), but do not get built since they are handled via a #include.
This just lets MSVC find the files so that features like search and replace and refactoring tools will work on the files. It changes no functionality.
> [Build] Add platform files to MSVC project for editing

- build.zig
- examples/build.zig
defineCMacro is removed, this is my solution to get raylib to build with zig 0.14.0+2540
> [build][Zig] Reviewed compatibility with latest zig master branch (v0.14.0)

- src/platforms/rcore_desktop_glfw.c
- src/platforms/rcore_desktop_sdl.c
Changes:
1. Fixes `EnableEventWaiting()` and `DisableEventWaiting()` ([ref](https://github.com/raysan5/raylib/blob/7ecc47d12e5f4c322af3d16615a08ba9bc47c4c2/src/rcore.c#L843-L853)) that were inop on `SDL`;
2. Adds a `GetFrameTime()` reset for `CORE.Window.eventWaiting` on `SDL` and `GLFW`;
3. Simplifies/optimizes/unifies `FLAG_WINDOW_ALWAYS_RUN` and `CORE.Window.eventWaiting` handling for `SDL` and `GLFW`.
Tested on `Linux Mint 22.0` with `GLFW` and `SDL2.30.10`, but should work on `SDL3` as well.
<details>
<summary>Test case:</summary>
<br>
```
if (IsKeyPressed(KEY_ONE)) { EnableEventWaiting();  TraceLog(LOG_INFO, "[1] EVENT WAITING ON" ); }
if (IsKeyPressed(KEY_TWO)) { …
```
> [rcore] [GLFW] [SDL2] Updates `CORE.Window.eventWaiting` and `FLAG_WINDOW_ALWAYS_RUN` handling

- examples/models/resources/shaders/glsl330/skinning.vs
The GPU skinning example only transformed the vertex data in the shader, it did not show how to also transform the normal data. Even though the normals are not used by the fragment shader, I feel it is important to have an example of how to transform the normals by the skin transforms for people that do want to eventually use lighting on GPU skinned meshes.
This PR transforms the normal and passes it to the fragment shader.
> [Examples] Add support for normal transformation to the GPU skinning example

- src/rmodels.c
Add calls to UnloadFileData() before return in cases of invalid IQM file.
> Fix leaks in LoadIQM() and LoadModelAnimationsIQM()

- src/rlgl.h
> [rlgl.h] Fixed typo in top comment

- src/platforms/rcore_web.c
Issue:
1. Player touches position ```{ 10, 10 }``` on the screen.
- CORE.Input.Touch.pointCount = 1
- Vector = ```[{10,10}]```
2. Player touches position ```{ 100, 100 }``` on the screen with another finger.
- CORE.Input.Touch.pointCount = 2
- Vector = ```[{ 10, 10 } , { 100, 100 }]```
3. Player release first finger from position ```{ 10, 10  }```.
- CORE.Input.Touch.pointCount = 1
- Vector = ```[{ 10, 10 } , { 100, 100 }]```
4. When the game try to access the position 0 it gets the wrong values as the Vector is not in order.
Solution:
1. Identify the index touch that was changed: ```if (touchEvent->touches[i].isChanged)```.
2. Move all touch values available one position up.
3. Reduce ```CORE.Input.Touch.pointCount```.
> [rcore_web]: Fix Touch pointCount reduction

- src/rshapes.c
I propose here a fix for `DrawRectangleRoundedLinesEx` as discussed in this issue: https://github.com/raysan5/raylib/issues/4601.
The method used to calculate the points corresponds to this in pseudocode:
```c
vec2 tl = coord + 0.5
vec2 br = coord + size - 0.5
```
I was only able to test it on the following configurations:
- **NVIDIA GTX 980**  
- Driver: 550.120  
- System: Linux Mint 21.3
- **NVIDIA Quadro NVS 160M**  
- Driver: 340.108  
- System: Linux Mint 21.3
It would be nice to be able to test it on AMD and Intel hardware.
___
The same approach can also be applied to `DrawRectangleLines`.
However, as demonstrated in the issue linked above, this function applies an offset using `zoomFactor`, which causes other alignment issues and leads to incorrect rendering.
To obtain correct …
> [rshapes] Fix pixel offset issue with line drawing

- src/rshapes.c
As requested here (https://github.com/raysan5/raylib/pull/4666#issuecomment-2578790857), here is the fix for `DrawRectangleLines`.
And good news! This fix also handles scale transformations!
There was initially a small error in applying the offsets, which has been corrected.
But most importantly, strangely, the function `rlGetMatrixModelview()` seems to only return the first matrix of the transformation stack, which could be considered just the view matrix if we want to put it that way...
However, by calling `rlGetMatrixTransform()`, we seem to get the actual 'modelView' matrix, which corresponds to all the accumulated transformation matrices on the stack.
Here’s a little example:
```c
BeginDrawing();  // rlLoadIdentity();
rlPushMatrix();
rlScalef(2, 5, 1);
Matrix mv = …
```
> [rshapes] Fix pixel offset issue with `DrawRectangleLines`

- build.zig.zon
When building on Mac via zig, the xcode-frameworks dependency is out of date and therefore fails to build.
This PR updates that dependency to the latest version, which builds correctly.
It should only affect macs. I have only been able to test it on an M1 mac, but I do not think there is any architecture difference in this regard.
> Update xcode-frameworks dependency for latest zig

- src/rshapes.c
As discussed in #4673 this removes the fallback to `DrawRectangle()` if the width or height is < 1.
Rounded rectangles with a size < 1 can already be drawn without issues if the check is removed and this behavior is desirable in cases where rounded rectangles are placed in between fractional world coordinates.
> [rshapes] Allow `DrawRectangleRounded()` to draw rectangles with a size < 1

- BINDINGS.md
The bindings from @EmmaTheMartian were moved to official status, so the link is updated.  The name was normalized to be consistent with other 'vendored' names in other languages.
> Update BINDINGS.md for official V language binding change

- examples/core/core_input_mouse.c
- src/platforms/rcore_web.c
This change is replacing the hardcoded "#canvas" element references in rcore_web to allow using canvas elements that use different names (which is necessary when using multiple canvas elements on one page).
Also adding a cursor hiding example to test this functionality in browser.
> Using canvas id provided by Module for event binding

- BINDINGS.md
Bumped Raylib.nelua to version 5.5.
> Bump BINDINGS.md version number for Raylib.nelua

- src/rtextures.c
Define STBIR_NO_SIMD when `__TINYC__` is defined so stb_image_resize2 will not include *mmintrin headers which are not supported by all compilers.
There are similar checks for `__TINYC__` already elsewhere in raylib and they are also mostly there to disable SIMD headers.
Additionally, move similar check for stb_image, to be a little bit deeper. Before it was defining STBI_NO_SIMD without including stb_image itself. It was also clashing with note, causing said note to make no sense.
Fixes: https://github.com/raysan5/raylib/discussions/2994
Reference: https://github.com/nothings/stb/issues/1738
> fix(rtextures): TCC not being able to compile due to: 'emmintrin.h' not found

- examples/README.md
- examples/core/core_basic_window_web.c
- examples/core/core_input_gestures_web.c
- examples/core/core_input_virtual_controls.c
- examples/core/core_random_sequence.c
- examples/models/models_bone_socket.c
- examples/models/models_gpu_skinning.c
- examples/models/models_point_rendering.c
- examples/models/models_tesseract_view.c
- examples/others/easings_testbed.c
- examples/others/embedded_files_loading.c
- examples/others/raylib_opengl_interop.c
- examples/others/raymath_vector_angle.c
- examples/others/rlgl_compute_shader.c
- examples/others/rlgl_standalone.c
- examples/shaders/shaders_basic_lighting.c
- examples/shaders/shaders_basic_pbr.c
- examples/shaders/shaders_shadowmap.c
- examples/shaders/shaders_vertex_displacement.c
- examples/textures/textures_image_channel.c
- examples/textures/textures_image_kernel.c
- examples/textures/textures_image_rotate.c
- examples/textures/textures_polygon.c
- README.md:
- Updated miss-matched stars count (from examples source files)
- Updated miss-matched created version info (assumed true from examples source files)
- Updated miss-matched last-updated version info (taken the larger value from README.md vs. examples source files)
- Updated miss-matched author (assumed true from the contributor from commit history of raylib)
- Added entries from examples source files not present in the examples list in README.md
- Addressed renamed GitHub user account (codifies -> chriscamacho) and other miss-matched name renames
- Removed duplicate example entry (core_window_should_close)
- examples/\*/\*.c:
- Added difficulty/complexity rating from missing source files (thank Ray for providing the rating)
- Inconsistent Copyright author
- Addressed renamed …
> [examples] Update examples list and more inconsistencies

- src/platforms/rcore_web.c
conversation from https://github.com/raysan5/raylib/issues/4712
There are 2 types of web-builds
1) Using `asyncify` -- the additional `emscripten_sleep(16)` is removed, EndDrawing still pauses properly
2) Using `set_main_loop` -- the additional `emscripten_sleep(16)` is removed, EndDrawing still adds an additional pause from the browser (i think should be handled in a different PR)
> [rcore_web] removed hardcoded sleep

- src/Makefile
[see linked issue for more context]
When asking Makefile to create SHARED library for WEB
```
~/raylib/src $ make TARGET_PLATFORM=PLATFORM_WEB RAYLIB_LIBTYPE=SHARED
```
it would instead silently create STATIC library thus not fulfilling the request as expected
This commit adds an error in this case and stops further execution which fixes this issue.
This is not consistent with Cmake, because Cmake throws the warning and does not stop, but Cmake can easily recover from this case and people probably does not even notice it. However, Makefile is something that you have to handle yourself and you have to recover from any issues so having an error and aborting with exit code 1 is more expected. Otherwise people may spend a lot of time debugging Makefile in order to understand what's even going …
> [build] Makefile: throw an error when trying to build SHARED library

- src/rtextures.c
_Another two patches for loading cubemaps with mipmaps. Hopefully the last ones 😅_
Two fixes in one PR for loading cubemaps with mipmaps:
1. Previously we were always generating mipmaps if we could. This makes sense for cubemaps with _some_ mipmaps, but not all possible. If we didn't do it there, that cubemap would be incomplete when filtering with `GL_LINEAR_MIPMAP_LINEAR`/`RL_TEXTURE_FILTER_MIP_LINEAR` or `GL_NEAREST_MIPMAP_LINEAR`/`RL_TEXTURE_FILTER_NEAREST_MIP_LINEAR`, because those require all possible mipmaps to be available[^1]. For cubemaps with no mipmaps (just the base mipmap level), there is no need to generate any mipmaps (or use VRAM to store them), because the user wouldn't expect there to be any mipmaps in the first place. Thus, only build cubemap mipmaps when necessary.
2. …
> [rtexture] Cubemap mipmap loading improvements

- src/platforms/rcore_desktop_sdl.c
Fixes #4722 (both the gamepad connect/disconnect issue and the gamepad button handling).
<details><summary>Explanation of the issue:</summary>
<br>
The SDL2 [doc mentions](https://wiki.libsdl.org/SDL2/SDL_JoyDeviceEvent) `Sint32 which;       /**< The joystick device index for the ADDED event, instance id for the REMOVED event */`, and that's what's happening here. During `SDL_JOYDEVICEADDED` `event.jdevice.which` will hold the `device_index`. But during `SDL_JOYDEVICEREMOVED` `event.jdevice.which` holds the `instance_id`, which are different things.
The problem was that raylib is using the `device_index` to fill/order the `platform.gamepad[]` array. However, it should track the `instance_id` instead (on a different var) to known which gamepad is which.
</details>
This PR can be tested …
> [rcore] [SDL2] Fix gamepad event handling by adding joystick instance id tracking

- src/rtextures.c
Attempts to fix #4728 using @Not-Nik suggestion (https://github.com/raysan5/raylib/issues/4728#issuecomment-2614469470) of using an `union`.
<details><summary>This change was tested with the following test on Linux Mint 22.0:</summary><br>
Both versions were tested side by side to confirm they would return the same results:
``` c
// NOTE: Compile this with -02.
// Snippet from 'rtextures.c' ------------------------------------------
// Convert half-float (stored as unsigned short) to float
// REF: https://stackoverflow.com/questions/1659440/32-bit-to-16-bit-floating-point-conversion/60047308#60047308
static float aHalfToFloat(unsigned short x)
{
float result = 0.0f;
const unsigned int e = (x & 0x7C00) >> 10; // Exponent
const unsigned int m = (x & 0x03FF) << 13; // …
```
> [rtextures] Fix `HalfToFloat()` and `FloatToHalf()` dereferencing issues with an union

- src/Makefile
Currently, a warning about _GNU_SOURCE being redefined is emitted when compiling rglfw.c
```c
In file included from rglfw.c:99:
external/glfw/src/posix_poll.c:27:9: warning: "_GNU_SOURCE" redefined
27 | #define _GNU_SOURCE
|         ^~~~~~~~~~~
<command-line>: note: this is the location of the previous definition
```
This can be avoided by not defining _GNU_SOURCE on the command line for this file.
Defining feature test macros in source code is not really good practice so this should probably reviewed in glfw itself, at least to maybe check
#ifdef _GNU_SOURCE first. But for now this change will suffice.
Fixes #4725
> [build] [Makefile]: Undefine _GNU_SOURCE for rglfw.c

- src/platforms/rcore_desktop_glfw.c
Currently GetGamepadButtonPressed() cannot return `GAMEPAD_BUTTON_LEFT_TRIGGER_2` or `GAMEPAD_BUTTON_RIGHT_TRIGGER_2` when using GLFW for input because GLFW treats them as analog values. When their analog value exceeds 0.1, Raylib sets the binary button state to 1 but doesn't update `lastButtonPressed`. This is probably an oversight, so I've fixed that in this PR.
> [platforms/glfw] fix: GetGamepadButtonPressed() can return analog trigger button values

- src/rtextures.c
Fixes: https://github.com/raysan5/raylib/issues/4737
I tested the changes with a small program: https://gist.github.com/henrikglass/1c6a0b35703836a60bd3c44b88f9e7eb
> [rtextures] Add missing increments of k in `LoadImageDataNormalized()`

- CMakeOptions.txt
This PR improves the CMake web build by setting the `PLATFORM` to `Web` by default when configuring builds using `emcmake cmake`.
This solution is the same as 9821725c6bafeaf4153ab8604e692dfe13cbff09 wanted to achieve, but for it to work the value must be set before `enum_option(PLATFORM ...)` is called, that's why it didn't work before.
My only doubt is if it's best to just set the default value like I did, or if it makes sense to force PLATFORM to Web and only call `enum_option(PLATFORM ...)` in the `else()` branch, since Emscripten cannot build raylib with any other value of PLATFORM set.
> [build][cmake] Set PLATFORM to Web by default when configuring web builds with emcmake

- src/rmodels.c
Create separate textures for roughness and metallic values when loading GLTF/GLB files. No one interjected, so I just did the implementation of my proposal.
This doesn't break any examples, because the only GLTF+PBR example we have, loads its own texture files manually. I did test this with my own setup, where this creates the same behaviour as if doing the separation in an image editing tool before running, and then loading the textures, after loading the image.
For more info see #4715
> [rmodels] Separate GLTF roughness and metallic channels on load

- parser/output/raylib_api.json
- parser/output/raylib_api.lua
- parser/output/raylib_api.txt
- parser/output/raylib_api.xml
- projects/Notepad++/raylib_npp_parser/raylib_npp.xml
- projects/Notepad++/raylib_npp_parser/raylib_to_parse.h
- src/raylib.h
Thank you for your nice library.
I stumbled over the usage of audio processors. Initially I processed a mono-audio file and was surprised to receive stereo data. After analyzing the code I realized that it always provides two channels as float (see #4743). 
I added additional documentation. Could you have a critical look and help to clarify the usage?
Thank you
> doc: audio stream processor, number of channels

- src/rcore.c
this fixes issue addressed at #4758, but preserving functionality. 
in short, module `rcore` cannot be compiled independently from module `rtext` since it uses the function `TextFindIndex()`, implemented at `rtext`.
> [rcore] fix: use `strstr()` instead of `TextFindIndex()` to decouple module from `rtext`

- src/rmodels.c
This PR updates the default normal and tangent values used when a mesh lacks corresponding buffers.  
- **Default normal:** Changed from `(1, 1, 1)` to **`(0, 0, 1)`** to ensure a properly normalized default normal, aligned with the standard convention of pointing out of the surface.  
- **Default tangent:** Changed from `(0, 0, 0, 0)` to **`(1, 0, 0, 1)`** to provide a valid and reliable fallback for constructing the bitangent in shaders.  
- Avoids potential problems when calculating the bitangent from a tangent that has a zero value.
- You can achieve **optional normal mapping** without requiring extra checks/shaders or conditional branches in shaders.
> [rmodels] Improve default normal and tangent values (UploadMesh)

- src/platforms/rcore_android.c
Implementation for the missing functions:
- `GetWindowScaleDPI()`
- `GetMonitorPhysicalWidth()`
- `GetMonitorPhysicalHeight()`
Only a small issue with `GetMonitorPhysicalWidth` and `GetMonitorPhysicalHeight` on some devices, where the value seems to be underestimated.
I tested it on a Samsung Galaxy with satisfactory results, but on a Xiaomi device (Redmi A9), the result was underestimated by about ~0.5 inches...
So I add a note about it.
This PR follows a request on raymob: https://github.com/Bigfoot71/raymob/issues/35
> [rcore_android] Implementation for `GetWindowScaleDPI` and monitor physical dimensions

- src/rshapes.c
Fix typo: "betweeen" → "between"
> Fix typo in rshapes.c

- src/raylib.h
args for ImageResizeNN were missing a space in the arguments after a comma, i just added one.
> [raylib.h] Added space after comma

- src/platforms/rcore_desktop_glfw.c
Raylib allows for providing custom allocators via macros. GLFW supports this too, but via function pointers. Let's make sure that GLFW uses those Raylib macros, by wrapping them in function calls and setting them up inside of InitPlatform(). This is possible because of glfwInitAllocator() and GLFWallocator. (see linked issue for more context)
I hope that code notes speak for itself but let me know what do you think, and if this is the correct approach or not.
Tested on x86_64 Linux with GNU Make and Cmake, with GCC and TCC, by compiling and running some examples.
Reference: https://www.glfw.org/docs/latest/intro_guide.html#init_allocator
Fixes: https://github.com/raysan5/raylib/issues/4776
Relates-to: https://github.com/raysan5/raylib/issues/4751
> [rcore_desktop_glfw.c] fix: make sure that GLFW uses RL_*ALLOC macros

- src/raudio.c
In the case of a failure within miniaudio on the function: `ma_convert_frames`, the dynamic memory allocated for the `data` variable will leak on the early return.
> [raudio] Fixed memory leak on early-return of WaveFormat func

- src/platforms/rcore_web.c
This PR adds emscripten visibility callbacks targeting the window. The game window is hidden when changing browser tabs or when the browser window is hidden.
Sample project: [hidden.zip](https://github.com/user-attachments/files/18930175/hidden.zip)
https://github.com/user-attachments/assets/d2c47cef-5fe0-4910-9135-68db853606e7
> Support `IsWindowHidden()` on web.

- src/rcore.c
Under windows I kept getting the linkage warnings
```
rcore.c(161): warning C4028: formal parameter 1 different from declaration
rcore.c(161): warning C4028: formal parameter 2 different from declaration
rcore.c(162): warning C4028: formal parameter 1 different from declaration
rcore.c(162): warning C4028: formal parameter 2 different from declaration
rcore.c(163): warning C4028: formal parameter 3 different from declaration
rcore.c(163): warning C4028: formal parameter 5 different from declaration
rcore.c(163): warning C4028: formal parameter 7 different from declaration
rcore.c(504): warning C4273: 'Sleep': inconsistent dll linkage
C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um\synchapi.h(684): note: see previous definition of 'Sleep'
```
because the windows functions …
> [rcore] fix linkage warnings under windows

- examples/textures/textures_polygon.c
- src/rlgl.h
`rlBegin` resets texture to default when drawing mode switches. This PR makes `rlBegin` preserve texture. Since many routines expect texture to be default if not explicitly specified, `rlEnd` now resets texture to default.
Fixes https://github.com/raysan5/raylib/issues/4347
> [rlgl] Preserve texture on mode switching

- cmake/raylib-config.cmake
Default target when building raylib itself is STATIC, but projects that use raylib was SHARED.
Changed raylib-config.cmake to consider STATIC as the default linkage.
Related to #4797
> [cmake] Use STATIC lib ON by default

- src/rcore.c
Check the result of InitPlatform(), if it isn't 0, report the Error and return. This prevent crashes and allows for gracefully aborting or recovering by checking IsWindowReady().
I decided to use `LOG_ERROR` here, because this is a fatal error in most cases, and it will cause a crash when ignored. However, I'm not so sure about `SYSTEM` prefix. There was no good choice for it. It must be very generic because InitPlatform() can fail in multiple cases.
Tested on native x86_64 Linux, and on x86_64 MacOS 13.6.9 running in VM. With GLFW in both cases.
Partially-fixes: https://github.com/raysan5/raylib/issues/4801
> [rcore] fix crash in InitWindow, due to unchecked result of InitPlatform

- src/external/stb_truetype.h
The logic for handling composite glyph scaling doesn't match the truetype specs, hence the results are different when a glyph in a ttf file defines composite glyh scales. I couldn't really find a ttf font with a glyph that has this exact issue, but the specs allows both uniform and non-uniform scaling for composite glyphs.
Part of the spec i am referring to
Synthetic tests (intentionally add scale to glyph component, spec allows it)
Left is FontForger, Right is raylib
With this fix applied
> [rtext] Fix `stb_truetype` composite glyph scaling logic

- src/platforms/rcore_android.c
- src/platforms/rcore_desktop_glfw.c
- src/platforms/rcore_desktop_rgfw.c
- src/platforms/rcore_desktop_sdl.c
- src/platforms/rcore_drm.c
- src/platforms/rcore_template.c
- src/platforms/rcore_web.c
Hello, my editor was pulling the function description from the raylib source and the comment for GetCurrentMonitor was not accurate which was confusing. This is just a small fix to replace the comment with what is in raylib.h.
> Fix GetCurrentMonitor comments.

- build.zig.zon
zig 0.14 updated the hash format.  Using the old hash forces a refetch on each zig build.  See https://github.com/ziglang/zig/issues/23051 for explanation.
> build.zig.zon: update hashes

- examples/shapes/shapes_splines_drawing.c
Move some if statements to surround for loops instead of being inside them, and add additional conditions for ensuring selection is inactive before looking for a point to focus.
Related to #4828
> [examples] Reorganize some conditions to fix overlap bugs

- src/external/RGFW.h
- src/platforms/rcore_desktop_rgfw.c
- ensure functions that use `platform.window` check `platform.window` is valid first 
- ensure fullscreen toggling is working properly 
- ensure raylib responds to `RGFW_quit` properly 
- update RGFW
- handle `RGFW_windowMaximized`, `RGFW_windowMinimized` and `RGFW_windowRestored` events
- properly handle raylib's `FLAG_WINDOW_UNFOCUSED` flag with `RGFW_windowFocusOnShow `
- remove out-of-date code
> [rcore][RGFW] bug fixes

- src/external/sinfl.h
under TCC sinfl_bsr returned no value.
> [rcore] sinfl_bsr fix for TCC

- src/external/jar_xm.h
I added an #undef DEBUG before the DEBUG(...) macro definition in jar_xm.h to prevent redefinition warnings and potential conflicts. This macro is commonly defined by external build systems for debug configurations, so undefining it here avoids collisions without disrupting other code.  
I also looked and jar_xm.h seems to only be included in raudio.c as an implementation detail, so I don't believe this should affect anything else(and if anything does include jar_xm.h directly, it was almost certainly getting redefined anyway)
This should help clean up some pesky warnings in debug builds so people can turn on -Werror to enforce clean builds, even if they define DEBUG elsewhere or pass -DDEBUG as a compiler option.
> Guard against DEBUG Redefinition

- src/rcore.c
In some cases, specific user configurations may allow for file/directory paths that exceed the set path limit. In such cases the current implementation of `ScanDirectoryFiles` would cause a buffer overflow.
This change makes sure that the path string does not exceed the buffer size, failing gracefully with the following warning.
```
WARNING: FILEIO: Path longer than 4096 characters ([very long path]...)
WARNING: FILEIO: Read files count do not match capacity allocated
```
> [rcore] Use snprintf to prevent buffer overflow in path construction

- examples/core/core_2d_camera.c
Fixes warning: narrowing conversion caused by trying to convert int to unsigned char
>  Converting int to char

- src/platforms/rcore_desktop_glfw.c
- src/platforms/rcore_desktop_rgfw.c
- src/platforms/rcore_desktop_sdl.c
This PR fixes the issue reported in #4834
When we get a resize event from the platform, we are just setting the screen size to the raw data returned by the event.
But if the user enabled the HIGHDPI flag on startup, we scaled the render and window size by the DPI scale. This means that on startup you get one set of sizes for the window, but after a resize, you swap from emulated unscaled values up to scaled values, and GetScreenSize no longer matches the viewport size.
This PR unscales the screen size on resize for the 3 desktop platforms so that the screen size stays in the same 'unscaled' space as the viewport.
> [rcore] Correctly handle window size on resize in auto-scaled HIGHDPI environment

- src/rshapes.c
This change adds early return to circle sector drawing functions `DrawCircleSector` and `DrawCircleSectorLines`
when startAngle equals endAngle, matching the existing behavior in `DrawRing` and 
`DrawRingLines` functions.
Benefits:
- Prevents unnecessary calculations when there's nothing to draw
- Avoids potential division by zero when angles are equal and segments=0
- Makes behavior consistent with the ring drawing functions
I've tested these changes on a Mac (no access to a Windows machine at the moment) and they don't break the build.
(In particular, `shapes_draw_circle_sector` example works the same way as before).
Suggestion - perhaps comparing the difference to `EPSILON` defined in `raylib.h` is a better approach for all this functions.
> Add early return when angles are equal in DrawCircleSector and DrawCircleSectorLine functions.

- src/rcore.c
I find it quite confusing that `InitWindow()` logs CWD during initialization, but the actual `ChangeDirectory()` does not do this upon successfully changing directory. This patch adds one line with `TRACELOG()` for said condition. It uses the same message as the one from InitWindow. Tested on Linux by building and running some examples with Cmake.
> [rcore] fix: TRACELOG upon successfully changing directory

- parser/output/raylib_api.json
- parser/output/raylib_api.lua
- parser/output/raylib_api.txt
- parser/output/raylib_api.xml
- projects/Notepad++/raylib_npp_parser/raylib_npp.xml
- projects/Notepad++/raylib_npp_parser/raylib_to_parse.h
- src/platforms/rcore_android.c
- src/platforms/rcore_desktop_glfw.c
- src/platforms/rcore_desktop_rgfw.c
- src/platforms/rcore_desktop_sdl.c
- src/platforms/rcore_drm.c
- src/platforms/rcore_template.c
- src/platforms/rcore_web.c
- src/raylib.h
Restore window currently says it sets the window state to:
"not minimized/maximized"
However, if a window is maximized and then minimized, it's typical that it would restore back to being maximized, which is what seems to happen from my testing. I've reworded the description to better reflect this behavior.
> Improve description of RestoreWindow

- examples/core/core_window_flags.c
I think this line was accidently commented out in this commit:
3d1ae3500c731aa37d8f887cd165db480c4890eb
The FPS limit is needed to get the desired wait time for the "hide window" test, which uses the frame counter to hide the window for 3 seconds. On my machine without this limit it runs at over 1000 FPS and it appears like the hide window state is broken.
I also added some text that tells the user that it only hides the window for 3 seconds so they're not surprised when the window automatically reappears.
> Uncomment SetTargetFPS in core_window_flags

- examples/core/core_window_flags.c
The core_window_flags example automatically restores the window from being minimized after 3 seconds. However, it only resets the frameCounter if the window is minimized through the app from inputting KEY_N.  This means if you miminize the window by other means (like pressing the minimize button) then the example will immediately restore the window because the frame counter wasn't reset. I've fixed this by setting the frameCounter back to 0 once it's expired. I also added a note in the UI that the example automatically restores the window so it's not a surprise.
> Prevent immediate window restore from minimize in core_window_flags

- examples/core/core_window_flags.c
Adds a toggle for borderless windowed mode to the core_window_flags example with the `[B]` key.
> core_window_flags example: add borderless windowed toggle

- build.zig
Added an Android target to the zig build script, mostly adapting existing work from the c Makefile.
This allows a user to easily build with only Android-supported libraries.
Library paths are automatically inferred as much as possible. Unfortunately, that also means a lot of ugly runtime string concatenation lol.
Tested on Linux and Windows. 
Also: my first PR!
> Add Android Target to build.zig

- build.zig
Fixes an issue (that I created, sorry) with the generated `android-libc.txt` file when using raylib as a dependency in another zig project. Tested on Linux and Windows.
> small build.zig fix

- src/platforms/rcore_desktop_sdl.c
I believe it makes sense to only do this when there are no known touch points. I am not even sure if this should be done at all.
See https://github.com/raysan5/raylib/issues/4872 for more information on the bug this attempts to fix.
> [rcore][SDL2] First touch position is overwritten with mouse pos

- build.zig
Formats `build.zig` with `zig fmt build.zig`.  It was formatted before but fell out with the recent changes to add android.
> build.zig: run zig fmt

- BINDINGS.md
This PR updates `BINDINGS.md` to reflect that [racket-raylib](https://docs.racket-lang.org/raylib/index.html) now binds to Raylib 5.5.
> Update `racket-raylib` version in BINDING.md

- src/rcore.c
If you take a screenshot on a high DPI display and are using the native resolution (you do not set WINDOW_FLAG_HIGHDPI), then you will not get a good screenshot as it will be scaled incorrectly.
This PR Only scale the screenshot by the DPI scale if we are doing automatic High DPI scaling, otherwise the native resolution is correct.
Fixes #4882
A mac user should test this change, it may need to be stubbed out for APPLE platforms due to the way the mac handles it's high DPI stuff and it's buggy GL drivers.
> [RCORE] Fix issue with screenshots on HIGHDPI displays 

- src/raudio.c
The audio stream subbuffer size was computed based on the device sample rate, but not the device sample size and channels.
this PR uses that data to compute the buffer size so we get a better default that is not too small on devices with more than 8 bits per sample.
> [RAUDIO] Better computation of the default audio stream buffer size

- projects/VS2022/examples/models_loading_gltf.vcxproj
The gltf example had a duplicate res file in it's project and would not build, this PR removes the extra file from the build so there is not a duplicate icon resource.
> [Examples] Remove duplicate resource file

- examples/text/text_draw_3d.c
Fixed multiple problems mentioned in #4901 , now the _DrawText3D()_, _MeasureTextWave3D(_), _DrawTextWave3D()_ won't be affected by the base size of the font, which will show same effect as directly invoke DrawText() in 3D drawing. 
This could be the **expected effect** of the 'text_draw_3d.c' as the creator of the example mentioned that they suppose _MeasureTextEx()_ could work but didn't:
```
// Measure a text in 3D. For some reason `MeasureTextEx()` just doesn't seem to work so i had to use this instead.
```
As the unexpected scale is removed now _MeasureTextEx()_ can normally function in program so I replaced _MeasureText3D()_ with it.
Also, the "\~\~" markdown as command in wave text used to be counted for space and calculate character number in line in typer, which is now fixed by …
> [example] Closes #4901, Fix Problems in 'text_draw_3d.c'

- build.zig
build.zig doesn't support the examples for the emscripten OS but it does support the raylib library. However, the examples panic if emscripten is configured which prevents it from building the library. I've replaced this panic with a fail step to fix this.
> build.zig: fix building raylib for emscripten

- CMakeLists.txt
When building `raylib` with other libraries using CMake's `FetchContent`, the `uninstall` target might clash between these libraries. User might encounter error similar to the following (the other library here is [Eigen](https://gitlab.com/libeigen/eigen))
```
CMake Error at build/_deps/eigen3-src/CMakeLists.txt:648 (add_custom_target):
add_custom_target cannot create target "uninstall" because another target
with the same name already exists.  The existing target is a custom target
created in source directory "/build/_deps/raylib-src".  See documentation for 
policy CMP0002 for more details.
```
The solution to this is fairly straight-forward: only add the custom target if we are building `raylib` by itself. We can achieve this by using `PROJECT_IS_TOP_LEVEL` built-in variable introduced …
> Only create uninstall target when raylib is top level

- CMakeLists.txt
- CMakeOptions.txt
- projects/CMake/CMakeLists.txt
- src/CMakeLists.txt
Byproduct of #4913
Since the current version of CMake in `raylib` is 3.25, we can replace the custom `RAYLIB_IS_MAIN` with `PROJECT_IS_TOP_LEVEL` (available since 3.21).
> cmake: replace custom variable with built-in one

- src/raudio.c
Pausing the active track, then stopping it and playing it again results in the playback restarting from the beginning, while GetMusicTimePlayed incorrectly returns the previous playback time.
> [raudio] fix: GetMusicTimePlayed returns incorrect time after restarting a paused track

- examples/audio/audio_sound_positioning.c
Changes line 111 from `Vector3 right = Vector3Normalize(Vector3CrossProduct(forward, listener.up));` to `Vector3 right = Vector3Normalize(Vector3CrossProduct(listener.up, forward));` which will correctly output positional audio via stereo.
Fixes #4904
> [examples] PR for #4904, calculate 'right' Vector3 to correctly perform audio positioning.

- src/rtext.c
A few issues were found with how the default font is loaded if it is used before InitWindow, with the Image API. This PR resolves them.
- Don't try to use the texture size when building up the source rects for the default font, it may not be loaded.
- Don't try to reload the default font if it's glyphs have already been loaded, this would leak memory on every call to ImageDrawText as it would reload and reallocate the buffers every time.
- If the font glyhps are loaded but the texture was not, just upload the atlas texture and return early, so we don't again leak memory.
> [rText] Fix issues with default font being used before InitWindow in the image API.

- src/rcore.c
This PR adds a null check for `files.paths` before calling `free()` in `UnloadDirectoryFiles`
While at it, I fixed an inconsistency in `ScanDirectoryFilesRecursively` by making `path` static, just like in `ScanDirectoryFiles`
Previously, both functions called `memset(path, 0, size)`, but only `ScanDirectoryFiles` had `path` declared as `static`
In the recursive version, `path` was reallocated on the stack and zero-initialized twice on each call
This change aligns the recursive version with the apparent original intent
___
Review of my previous PR: https://github.com/raysan5/raylib/pull/4921
> [rcore] Some adjustments for `FilePathList`

- src/rmodels.c
Currently when drawing meshes with GL 1.1 only the static vertex and normal buffers are used, this means that CPU animation can't work with GL 1.1.
This PR uses the animated vertex and normal buffers if they exist just like GL 2.2+ does, supporting animated models in GL1.1.
It's not going to be fast since it's all done CPU side, but that should be up to the user, not raylib.
> [rmodels] support CPU animation in OpenGL 1.1

- src/rlgl.h
I've noticed the default near and far clipping planes were recently changed, and I'd like to suggest a fix
The current range `[0.001, 10000.0]` feels excessive and hard to justify
The near plane is too close, which can cause depth buffer precision issues and visual artifacts, while a far value of `10000.0` seems unnecessarily high for a default here
If the intent was to increase the far plane, a more reasonable default would be `[0.05, 4000.0]`, offering a better balance between depth precision and visible range
For special cases, `rlSetClipPlanes` already exists to override these defaults anyway
___
Here is a visual example using shadow mapping, where the scene depth (from the camera's point of view) was projected with a near/far range of `[0.001, 10000.0]`: …
> [rlgl] Proposed fix for default near/far clipping range

- src/rmodels.c
DrawCube has normals, DrawSphere doesn't. So I added it to DrawSphere.
Note that DrawCylinder, DrawCapsule, DrawTriangle3D and DrawCircle3D still doesn't have normals. But drawing a sphere is common for testing lighting, so I thought it would be nice. It's cheap to do for a sphere since the non-scaled vertex position is also the vertex normal. It may not be as cheap for those other drawing functions.
> Add normals to DrawSphereEx

- src/rtext.c
The default font is unloaded, but its fields are never set to null. This will cause problems if the window is opened again and something tries to reinitialize the default font. This PR resets the fields back to null on unload.
> [rtext] Properly clean up the default font on unload

- parser/output/raylib_api.json
- parser/output/raylib_api.lua
- parser/output/raylib_api.txt
- parser/output/raylib_api.xml
- src/raylib.h
The SaveFileTextCallback does not take it's second argument as a const char*, this is not the same as the argument the caller passes in in SaveFileText function, this generates a warning in gcc.
```utils.c
../external/raylib-master/src/utils.c: In function 'SaveFileText':
../external/raylib-master/src/utils.c:416:43: warning: passing argument 2 of 'saveFileText' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
416 |             return saveFileText(fileName, text);
|                                           ^~~~
../external/raylib-master/src/utils.c:416:43: note: expected 'char *' but argument is of type 'const char *'
```
This PR changes the callback signature to match. This should not change binary compatibility since const is not used at runtime. The …
> [utils] fix const warning with SaveFileText callback

- src/rmodels.c
I propose a nearly complete review of `GenMeshTangents`, which had several issues
Here is the list of changes:
- Support for indexed meshes (`mesh->indices`)
- Correct accumulation of tangents/bitangents per vertex
- Improved handling of degenerate cases (invalid UVs, null tangents -> fallback to orthogonal)
- More robust orthogonalization (Gram-Schmidt with fallback in case of collinearity)
- Bonus, some comments
The function was tested with R3D, here is a quick example "before / after" with IBL:
> [rmodels] Fix and improve `GenMeshTangents`

- examples/shaders/shaders_basic_pbr.c
When I was playing around with basic pbr example i noticed that chnging metallness and roughness values at these lines:
car.materials[0].maps[MATERIAL_MAP_METALNESS].value = 0.0f;
car.materials[0].maps[MATERIAL_MAP_ROUGHNESS].value = 0.0f;
did nothing so I decided to fix this. Now changing these values has an effect on the final image.
> [examples] Basic pbr example fix

- src/rmodels.c
* `DrawMesh` incorrectly references `animNormalss` instead of `animNormals`, preventing an OpenGL 1.1 build.
> Fix typo in mesh animNormals

- src/platforms/rcore_android.c
raylib treats both touch and hover events as same in android platform. This causes problem with android devices with pen or stylus support.
IsMouseButtonPressed() and IsMouseButtonDown() are triggered just for hovering above the screen with stylus. And IsMouseButtonReleased() is not triggered. meaning, the mouse is always down. Because, raylib not check AMOTION_EVENT_ACTION_HOVER_EXIT to release the input.
So this PR adds code to ignore the Hovering Input completely.
The Code is Tested in my samsung A13 phone. It does not have pen or stylus support. But i used [Genymobile/scrcpy](https://github.com/Genymobile/scrcpy) to emulate hovering input.
The hovering is ignored successfully and in my phone it works perfectly without any side effects to other inputs.
I already tested another version …
> [rcore] Fixed bug in hovering and input for android

- src/rcore.c
Nothing more than the removal of an unused variable from ``rcore.c``.
> Remove unused variable

- src/platforms/rcore_desktop_rgfw.c
there is a mistake in rcore_desktop_rgfw line 992
currently it looks like this:
```c
if ((CORE.Window.eventWaiting) || (IsWindowState(FLAG_WINDOW_MINIMIZED) && !IsWindowState(FLAG_WINDOW_ALWAYS_RUN)))
{
RGFW_window_eventWait(platform.window, 0); // Wait for input events: keyboard/mouse/window events (callbacks) -> Update keys state
CORE.Time.previous = GetTime();
}
```
with `RGFW_window_eventWait` set to 0 timeout. this makes `EnableEventWaiting();` not work, since the timeout is always 0. setting it to -1 makes it work correctly.
> Change `RGFW_window_eventWait` timeout to -1 to fix `EnableEventWaiting`

- build.zig
This fixes build issues when building raygui on Linux systems without wayland, that are missing the `wayland-scanner` program. More details on the issue can be found at Not-Nik/raylib-zig#243.
A different solution to this problem could be requiring `raylib_dep` to be passed into `addRaygui` directly, but I don't see any semantic difference, as the dependency functions should reuse previously created `std.Build.Dependency` instances.
> Allow passing options to raygui in build.zig

- src/rcore.c
Fixes a regression since 5.5, where `ScanDirectoryFilesRecursively` no longer does the "recursively" part due to `path` being `static`.
The issue was once already fixed in https://github.com/raysan5/raylib/commit/5530a3ceb88962066affa5db8e13b00b64444b37 but recently made it back it in.
> [rcore] Fix ScanDirectoryFilesRecursively

- src/config.h
Fixes a typo in config.h, from "Selecte" to "Selected", same expression as the comment on line 223.
> Fix typo on config.h

- examples/shaders/resources/shaders/glsl100/pbr.vs
- examples/shaders/resources/shaders/glsl120/pbr.vs
- examples/shaders/resources/shaders/glsl330/pbr.vs
The shaders are currently using a vec3 for vertexTangent despite Raylib uploading vec4's to them. I also multiplied the biNormal by the w component as this example loads .glb files which use the w component for the tangent basis sign.
> [example] Fix pbr example shaders to use vec4 for vertexTangent

- src/rmodels.c
The [GLTF spec](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#meshes) defines TANGENT for meshes as a vec4. The code is loading this correctly but when transforming the tangents it's using an offset of 3 floats instead of 4.
> [rmodels] Fixing offset for processing tangents for GLTF/GLB loading

- build.zig
This PR is to allow: `zig build -Dtarget=wasm32-emscripten textures_sprite_anim`
Changes:
* if `target.result.os.tag == .emscripten` Steps are create as: 
* `exe_lib` - new
* `raylib` - reused
*  ^ dependOn
* `emcc_command` - new
* ^ dependOn
* `run_step` - new create by method `emscriptenRunStep`
* Add `const module_resources = b.pathJoin(&.{ module_subpath, "resources@resources" });` to be able to map resources folder for the examples.
* Add `run_step.addArg("--no_browser");` to run without running a browser so the user can point to the example manually.
* Skipping `rlgl_standalone` and `raylib_opengl_interop` examples for now.
Result:
Now you can compile examples like:
* `zig build -Dtarget=wasm32-emscripten examples` - it compiles all examples (except `rlgl_standalone` and …
> [zig] Add run examples using zig and emscripten for web

- src/raudio.c
Save some resource when no music playing by stopping the UpdateMusicStream to process without music.
> [raudio] Prevent UpdateMusicStream to run without music playing

- examples/core/core_custom_frame_control.c
In the online example and when compiling locally, the inputs aren't being registered. While testing, I found that on the web, the input event poll only works when called after the inputs checks.
So I just added:
```
#ifndef PLATFORM_WEB
PollInputEvents(); 
#endif
// ... inputs checks
```
and 
```
// ... inputs checks
#ifdef PLATFORM_WEB 
PollInputEvents(); 
#endif
```
I don't know the root cause, I just made it work on web properly.
> [example][web] Fix core_custom_frame_control.c to properly register inputs on web platform

- src/platforms/rcore_web.c
There are times when we want to use keys that are otherwise used for browser functions.
F1 -> opens a help tab (in Chromium based browsers, see #4951)
F5 -> refresh the page
There are many more key/key combinations that trigger browser actions. This PR seeks prevent the default browser actions by consuming all keyboard events. This leaves us free to use any keyboard cominations as we would in any other environment.
This PR fixes issue #4951
> [rcore][web] Add `EmscriptenKeyboardCallback()` to consume key events

- src/rmodels.c
When loading OBJ files that have no normals in the file, the loader crashes. It does not crash for web builds, but I guess this is due to WASM not crashing for such memory access errors.
> [rmodels] Fixing OBJ loading crash when there are no normals present

- .github/workflows/linux.yml
- Add ubuntu-24.04-arm runner for native ARM64 compilation
- Support building both static and shared libraries for ARM64
- Maintain backwards compatibility with existing x86/x64 builds
- Addresses issue #5051 for ARM64 pre-compiled binaries
Expected output: raylib-X.X-linux_arm64.tar.gz in releases
> [build] Add ARM64 support to Linux builds

- src/rcore.c
This PR makes the GetRender size functions return the size of the active render target, if a render texture is active then the size of that texture will be returned. This gives users a consistent way to get the current target frame buffer size without having to know the current target. This makes creating reusable libraries much easier.
> [CORE} Make GetRenderWidth/Height return the FBO size if one is active

- src/external/jar_mod.h
Fixed a buffer overflow warning in `jar_mod.h` where 1084 bytes were being copied into a 20-byte buffer, causing a `-Wstringop-overflow` compiler warning.
The `memcopy` call on line 1133 was incorrectly targeting `&(modctx->song.title)` (a 20-byte field) instead of the entire module structure when loading MOD file data:
Changed the destination address to point to the beginning of the entire song structure instead of just the title field.
The module structure has a total size of 1085 bytes:
`title[20]` = 20 bytes
`samples[31]` = 930 bytes (31 × 30 bytes each)
`length` = 1 byte
`protracker` = 1 byte
`patterntable[128]` = 128 bytes
`signature[4]` = 4 bytes
`speed` = 1 byte
1. Compiles without buffer overflow warnings
2. Preserves existing functionality for MOD file loading
3. No changes to …
> fix: buffer overflow in jar_mod.h memcopy

- tools/rexm/rexm.c
This change is to block `./remx rename core_ test_`.
Ignore this PR if it was intended to be able to rename all file categories.
> [remx] Add check for category on new name

- BINDINGS.md
The raylib-zig repository moved to its own organisation and already runs on a 5.6-dev version :)
> Update raylib-zig in BINDINGS.md

- src/platforms/rcore_desktop_glfw.c
This may not be the correct approach, however this appears to work. The idea is that before modifying `CORE.Window.flags` when first creating the window we keep a copy of the flags in order to call `SetWindowState` after initialization has completed, which should behave as if `MaximizeWindow` or `MinimizeWindow`, or conceptually any other flag modifying function were called after `InitWindow`.
This pull request only performs this for the windows platform, modify as needed in the switch statement at the end for others.
> [rcore] Support window flags with initialization issues

- src/platforms/rcore_web.c
Suggestion is to `glfwSetWindowSize` when triggered `EmscriptenResizeCallback`.
Tested on example `core_window_letterbox`
Issue:
Result:
> [rcore][web] Work around to fix mouse positioning on scaled window

- src/raudio.c
The sound alias would copy the volume from the source sound, this made the new sound be in a different state than it would be if it was loaded as a copy.
This PR forces sound alias to the same state as a new sound for consistency.
> [raudio] Initialize sound alias properties as if it was a new sound

- build.zig
This is necessary to allow for using the function in dependent `build.zig`s.
> Add pub to compileRaylib

- build.zig
- build.zig.zon
For a long time, I didn't like how Zig builds for the web.
The main problem was that there wasn't any helper method and that the build system emsdk was cloned twice—once for the Raylib dependency and once on the user side.
With the helper methods, it will be cloned only once and use the same folder for the operation.
Here is an example of how the build step can look now on the user side:
```zig
const std = @import("std");
const rl = @import("raylib");
pub fn build(b: *std.Build) !void {
const target = b.standardTargetOptions(.{});
const optimize = b.standardOptimizeOption(.{});
const raylib_dep = b.dependency("raylib", .{
.target = target,
.optimize = optimize,
});
const raylib_artifact = raylib_dep.artifact("raylib");
const exe_mod = b.createModule(.{
.root_source_file = …
```
> [build.zig]: a concrete approach to build for web with zig-build

- src/platforms/rcore_desktop_sdl.c
SDL3 joystick ID does not start from 0. In my case, my controllers were 4 and 5. First find the ID, then add to the platform/CORE.
> [rcore] Reviewed SDL3 gamepad detection

- src/platforms/rcore_desktop_glfw.c
Currently, scaling doesn't work correctly on macOS (see #5185).  This commit
works around this issue by disabling SCALE_FRAMEBUFFER on macOS when
`FLAG_WINDOW_HIGHDPI` is unset.
0. Buy a Mac and set up developer tools
1. `git clone git@github.com:vegerot/snek.git --recurse-submodules`
2. `zig build play`
3. Play around for a minute and have fun 🙂 
Everything should be working
4. `git switch -d HEAD~1`
5. `git submodule update --init`
6. `zig build play`
Expected: everything should work
Actual: Incorrect scaling
> fix(rcore): correctly scale content on macOS

- projects/CMake/CMakeLists.txt
- projects/CMake/README.md
- projects/CMake/core_basic_window.c
For some reason, #5181 deleted it.
This project is intended to be a simple template to set up a project consuming raylib with CMake.
This PR restores it exactly how it was before it was deleted.
> Restore projects/CMake/CMakeLists.txt

- src/rtextures.c
The screenshot code is always applying the DPI scale to the image, even if the framebuffer was not created with that scale, thus if you have a DPI scale but are NOT doing DPI auto scaling and using the window at it's native resolution, the image will be too big.
The screenshot code should never use ScreenSize, it should use RenderSize, so that it gets the size of the framebuffer that it's saving. There should not be any need for High DPI logic here since this is just saving an existing framebuffer that has a fixed size.
This PR makes the change so that screenshots work in both modes on all platforms since it's just using the same size that the framebuffer was created with.
> [rTextures] Use the render size not the screen size for screenshots

- src/rlgl.h
This PR is to fix the rlSetTexture as when you have different textures it will not override the mode that is default to GL_QUAD.
The fix is to check if the drawCounter has more then 1 and copy the previous mode to the new Draw.
No Need to change the order of rlSetTexture and rlBegin for it to work.
Removed vertexCount and textureId set from rlBegin as it is already set for every draw.
```
RLGL.currentBatch->draws[RLGL.currentBatch->drawCounter - 1].vertexCount = 0;
RLGL.currentBatch->draws[RLGL.currentBatch->drawCounter - 1].textureId = RLGL.State.defaultTextureId;
```
Initializer: https://github.com/maiconpintoabreu/raylib/blob/8d1add31d92da6f8704426f5bcb6c307e4e9cd85/src/rlgl.h#L2848
https://github.com/maiconpintoabreu/raylib/blob/8d1add31d92da6f8704426f5bcb6c307e4e9cd85/src/rlgl.h#L3124 …
> [rlgl] Fix Not default Draw Mode breaking when changing texture

- src/rmodels.c
I'm only looking at GLTF at the moment, but possible that the IQM logic would also appreciate a similar change given that it uses the same `BuildPoseFromParentJoints`.
Meanwhile, consider the following helper functions below (and exposing them with `RLAPI`)
I think these would be useful tools for animators to be able to use. I am currently using these for machine learning for animation on my personal fork.
Just let me know where you'd like me to put them (and their header declarations) if you agree :)
```
// Compose Model Space Transform
Transform ComposeTransform(Transform transform, Transform parentTransform)
{
transform.rotation = QuaternionMultiply(parentTransform.rotation, transform.rotation);
transform.scale = Vector3Multiply(transform.scale, parentTransform.scale); …
```
> [rmodels] GLTF Anim Correctly Inherits World Transform

- src/rtextures.c
We have detected some issues with old console platforms when initialization for Image structure is not done in Image structure definition order.
Using defined order fix the issue.
> [rtextures] fix align order initialization in Image

- examples/shapes/shapes_bouncing_ball.c
Adds a new example based on the classic bouncing ball, modified to include gravity and floor damping. 
Added for: #5209
Tested on Desktop (Linux).
> [examples] Update `shapes_bouncing_ball` with gravity

- examples/core/core_input_mouse.c
I noticed while porting the example to Odin that the boolean check of whether the mouse is visible is actually the opposite of what it should be.
> [examples] Corrected typo in core_input_mouse

- examples/core/core_3d_camera_free.c
Hello! I noticed core_3d_camera_free uses a char in place of the constants that it is supposed to be using. I don't see this repeated in other examples, so I think it would be better to replace it with the constant to prevent future confusion.
> [examples] REVIEW: `core_3d_camera_free` uses `IsKeyPressed()` incorrectly

- tools/rexm/Makefile
- tools/rexm/rexm.c
Fixed a windows only backslash in
rexm's makefile causing build errors on macOS and linux
Added unix paths to rexm for better compatibility
> FIXED: rexm's makefile and default paths

- src/platforms/rcore_desktop_glfw.c
This PR is to fix the issue when removing a Monitor while getting information about it.
The issue was confirmed on Linux and Windows.
Renamed `vidmode` to `mode` to match with methods like `GetMonitorHeight` and `GetMonitorWidth`.
> [rcore] Check if mode is valid on `GetMonitorRefreshRate` to avoid Segfault when removing Monitor
